force-app/main/default/objects/BLN_IntegrationLogger__c/BLN_IntegrationLogger__c.object-meta.xml
<CustomObject>
    <label>Integration Logger</label>
    <nameField>
        <displayFormat>IL-{00000000}</displayFormat>
        <label>Integration Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logger</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_APICallInSeconds__c.field-meta.xml
<CustomField>
    <fullName>BLN_APICallInSeconds__c</fullName>
    <description>FOUK-252 -&gt; Store the Duration between Request was sent and Response was received</description>
    <label>API Call (In Seconds)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_CorrelationId__c.field-meta.xml
<CustomField>
    <fullName>BLN_CorrelationId__c</fullName>
    <description>FOUK-252 -&gt; Unique Identifier created to be sent in Header to other system</description>
    <label>Correlation Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_RequestBody__c.field-meta.xml
<CustomField>
    <fullName>BLN_RequestBody__c</fullName>
    <description>FOUK-252 -&gt; Store The Requested Body To Sent The End Point</description>
    <label>Request Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_RequestEndPoint__c.field-meta.xml
<CustomField>
    <fullName>BLN_RequestEndPoint__c</fullName>
    <description>FOUK-252 -&gt; Store The End Point Url</description>
    <label>Request End Point</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_RequestHeaders__c.field-meta.xml
<CustomField>
    <fullName>BLN_RequestHeaders__c</fullName>
    <description>FOUK-252 -&gt; Store The Request Header Of  API</description>
    <label>Request Headers</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_RequestIssuedBy__c.field-meta.xml
<CustomField>
    <fullName>BLN_RequestIssuedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>FOUK-252 -&gt; Store User who initiated the request.</description>
    <label>Request Issued By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>IntegrationLogger</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_RequestMethod__c.field-meta.xml
<CustomField>
    <fullName>BLN_RequestMethod__c</fullName>
    <description>FOUK-252 -&gt; Store The Method Type</description>
    <label>Request Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_RequestSent__c.field-meta.xml
<CustomField>
    <fullName>BLN_RequestSent__c</fullName>
    <description>FOUK-252 -&gt; Store Date and Time when Request was sent</description>
    <label>Request Sent</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_ResponseBody__c.field-meta.xml
<CustomField>
    <fullName>BLN_ResponseBody__c</fullName>
    <description>FOUK-252 -&gt; Store  Response Body sent to target system.</description>
    <label>Response Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_ResponseHeaders__c.field-meta.xml
<CustomField>
    <fullName>BLN_ResponseHeaders__c</fullName>
    <description>FOUK-252 -&gt; Store The Response Header</description>
    <label>Response Headers</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_ResponseReceived__c.field-meta.xml
<CustomField>
    <fullName>BLN_ResponseReceived__c</fullName>
    <description>FOUK-252 -&gt; Store The Date and Time when Response was recieved</description>
    <label>Response Received</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_ResponseStatus__c.field-meta.xml
<CustomField>
    <fullName>BLN_ResponseStatus__c</fullName>
    <description>FOUK-252 -&gt; Store The Response Status</description>
    <label>Response Status</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_ResponseStatusCode__c.field-meta.xml
<CustomField>
    <fullName>BLN_ResponseStatusCode__c</fullName>
    <description>FOUK-252 -&gt; Store The Response Status Code</description>
    <label>Response Status Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_TargetSystem__c.field-meta.xml
<CustomField>
    <fullName>BLN_TargetSystem__c</fullName>
    <description>FOUK-252 -&gt; Store Which Target System To Used The Data</description>
    <label>Target System</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Vehicle__c/BLN_Vehicle__c.object-meta.xml
<CustomObject>
    <description>FOUK-495 This object is created for storing the Vehicles.</description>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{00000000}</displayFormat>
        <label>Vehicle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_Vehicle__c/fields/BLN_MakeOfVehicle__c.field-meta.xml
<CustomField>
    <fullName>BLN_MakeOfVehicle__c</fullName>
    <description>FOUK-116--&gt; This field is created for make of vehicle details.</description>
    <label>Make Of Vehicle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Vehicle__c/fields/BLN_ModelOfVehicle__c.field-meta.xml
<CustomField>
    <fullName>BLN_ModelOfVehicle__c</fullName>
    <description>FOUK-116--&gt; This field is created for model of vehicle .</description>
    <label>Model Of Vehicle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Vehicle__c/fields/BLN_VehicleRegNumber__c.field-meta.xml
<CustomField>
    <fullName>BLN_VehicleRegNumber__c</fullName>
    <description>Fouk-109 To store vehicle registeration number.</description>
    <label>Vehicle Registration Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Vehicle__c/fields/BLN_VIN__c.field-meta.xml
<CustomField>
    <fullName>BLN_VIN__c</fullName>
    <description>FOUK-495 This field is used to store vehicle identification number</description>
    <label>VIN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BLN_SendBoschJobCardBatch.cls
/**@description : This batch class handles the data sent to Mulesoft-Bosch
*  @author: PwC India
*  @Story: FOUK-5582
*  @CreatedDate: 13/03/2024
*/
public class BLN_SendBoschJobCardBatch implements Database.Batchable<sObject>,  Database.AllowsCallouts, Schedulable{
    public static Integer expiresIn;
    public Database.QueryLocator start(Database.BatchableContext bc) {
        string statusScheduled = System.label.BLN_ScheduledStatus;
        string statusDispatched = System.label.BLN_DispatchedStatus;
        string statusOpen = 'None';
        
        Datetime dateBegins = System.now();
        Time endTime = Time.newInstance(23, 59, 59, 0);
        DateTime dateEnds = DateTime.newInstance(system.today(), endTime);
        Boolean isBoschJobCardSent = False;

        String query = 'Select Id, BLN_WorkOrderLineItem__c, BLN_Vehicle__c, BLN_Vehicle__r.BLN_VehicleRegNumber__c , BLN_Vehicle__r.BLN_MakeOfVehicle__c, BLN_Vehicle__r.BLN_ModelOfVehicle__c, BLN_Vehicle__r.BLN_VIN__c, AccountId, Account.FirstName, Account.LastName, BLN_IsBoschJobCardSent__c from ServiceAppointment where (((Status = :statusOpen or Status = :statusScheduled or Status = :statusDispatched) and ArrivalWindowStartTime >= :dateBegins and ArrivalWindowStartTime <= :dateEnds) or ((Status = :statusScheduled or Status = :statusDispatched) and SchedStartTime >= :dateBegins and SchedStartTime <= :dateEnds)) and BLN_IsBoschJobCardSent__c = :IsBoschJobCardSent and ServiceTerritory.BLN_ConsiderforR1__c = false';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<ServiceAppointment> records){
        DateTime expiresIn;
        String oktaToken;
        Cache.OrgPartition orgPart = Cache.Org.getPartition('local.OKTAIdP');
        expiresIn = (DateTime)orgPart.get('OKTATokenExpirationDateTime');
        oktaToken = (String)orgPart.get('OKTAAccessToken');

        if(expiresIn == null || oktaToken == '' || expiresIn <= Datetime.now() || Test.isRunningTest()){
            setOktaAccessToken();
            expiresIn = (DateTime)orgPart.get('OKTATokenExpirationDateTime');
            oktaToken = (String)orgPart.get('OKTAAccessToken');
        }
        if(oktaToken != '' && expiresIn > Datetime.now()){
            System.enqueueJob(new BLN_SendBoschJobCard(records, oktaToken, false));
        }
    }

    public void finish(Database.BatchableContext bc){
        try{
            AsyncApexJob job = new AsyncApexJob();
            job = [SELECT Id, JobType, ApexClassId, Status, NumberOfErrors, MethodName, CompletedDate FROM AsyncApexJob WHERE Id =: bc.getJobId()];
        } catch (Exception e) {
            BLN_ExceptionLogger.captureException(e);
        }
    }

    public void execute(SchedulableContext ctx) {
        integer batchSize = 200;
        BLN_SendBoschJobCardBatch p = new BLN_SendBoschJobCardBatch();
        database.executeBatch(p,batchSize);
    }

    public static void setOktaAccessToken(){
        List<Exception> exceptionList = new List<Exception>();
        try {
            Http http = new Http();
            HttpRequest req = new HttpRequest();
            HttpResponse res = new HttpResponse();
            req.setMethod('POST');
            req.setEndpoint('callout:OKTAIntegration');
            req.setBody(System.label.BLN_OktaIntegrationBody);
            DateTime t1 = System.Now();
            res = http.send(req);
            DateTime t2 = System.Now();
            
            Decimal decSec2 = t2.getTime();
            Decimal decSec1 = t1.getTime();
            Decimal miliDiff = decsec2 - decsec1;
            Decimal secDiff = miliDiff/1000;
            Decimal rounded = secDiff.setScale(3);
            String secondsGap = String.valueOf(rounded);
            
            Map<String, Object> results = (Map<String, Object>)JSON.deserializeUntyped(res.getBody());
            String accessToken;
            Datetime expireTime;
            
            if((res.getstatusCode() == 200 || res.getstatusCode() == 201) && res.getbody() != null){
                accessToken = (String)results.get('access_token');
                expiresIn = (Integer)results.get('expires_in');
                Integer sec = expiresIn - 60;            
                DateTime now = DateTime.now();
                expireTime = now.addSeconds(sec);
            }
            
            String auth = 'Bearer ' + accessToken;
            String instanceUrl = System.label.BLN_CurrentOrgInitials;
            Cache.OrgPartition orgPart = Cache.Org.getPartition('local.OKTAIdP');
            if(String.isNotBlank(accessToken)){
                orgPart.put('OKTAAccessToken', accessToken);
                orgPart.put('OKTATokenExpirationDateTime', expireTime);
            }
            
            if((res.getstatusCode() == 200 || res.getstatusCode() == 201) && res.getbody() != null){
                // Store Integration Logger Record
                String correlationId = BLN_SendBoschJobCard.randomCodeGenerator();
                List<BLN_IntegrationLogger__c> intLogList = new List<BLN_IntegrationLogger__c>();
                BLN_IntegrationLogger__c integrat = new BLN_IntegrationLogger__c();
                integrat.BLN_APICallInSeconds__c = secondsGap;
                integrat.BLN_CorrelationId__c = correlationId;
                integrat.BLN_RequestBody__c = req.getBody();
                integrat.BLN_RequestEndPoint__c = req.getEndpoint();
                integrat.BLN_RequestHeaders__c = '';
                integrat.BLN_RequestIssuedBy__c = UserInfo.getUserId();
                integrat.BLN_RequestMethod__c = req.getMethod();
                integrat.BLN_RequestSent__c = System.today();
                integrat.BLN_ResponseBody__c = res.getBody();
                integrat.BLN_ResponseHeaders__c = BLN_SendBoschJobCard.resHeaders(res);
                integrat.BLN_ResponseReceived__c = System.today();
                integrat.BLN_ResponseStatus__c = res.getStatus();
                integrat.BLN_ResponseStatusCode__c = ''+res.getStatusCode();
                integrat.BLN_TargetSystem__c = System.label.BLN_TargetSystemOkta;
                intLogList.add(integrat);
                
                BLN_IntegrationLogger.logRequest(intLogList);
            }
        }
        catch (Exception ex) {
            // Store Exception Logger Record
            BLN_ExceptionLogger.captureException(ex);
        }
    }
}