force-app/main/default/objects/BLN_IntegrationLogger__c/BLN_IntegrationLogger__c.object-meta.xml
<CustomObject>
    <label>Integration Logger</label>
    <nameField>
        <displayFormat>IL-{00000000}</displayFormat>
        <label>Integration Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logger</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_APICallInSeconds__c.field-meta.xml
<CustomField>
    <fullName>BLN_APICallInSeconds__c</fullName>
    <description>FOUK-252 -&gt; Store the Duration between Request was sent and Response was received</description>
    <label>API Call (In Seconds)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_RecordId__c.field-meta.xml
<CustomField>
    <fullName>BLN_RecordId__c</fullName>
    <description>FOUK-252 -&gt; Store The Record Id Created By API</description>
    <label>Reference Id</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_RequestBody__c.field-meta.xml
<CustomField>
    <fullName>BLN_RequestBody__c</fullName>
    <description>FOUK-252 -&gt; Store The Requested Body To Sent The End Point</description>
    <label>Request Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_RequestEndPoint__c.field-meta.xml
<CustomField>
    <fullName>BLN_RequestEndPoint__c</fullName>
    <description>FOUK-252 -&gt; Store The End Point Url</description>
    <label>Request End Point</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_RequestHeaders__c.field-meta.xml
<CustomField>
    <fullName>BLN_RequestHeaders__c</fullName>
    <description>FOUK-252 -&gt; Store The Request Header Of  API</description>
    <label>Request Headers</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_RequestIssuedBy__c.field-meta.xml
<CustomField>
    <fullName>BLN_RequestIssuedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>FOUK-252 -&gt; Store User who initiated the request.</description>
    <label>Request Issued By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>IntegrationLogger</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_RequestMethod__c.field-meta.xml
<CustomField>
    <fullName>BLN_RequestMethod__c</fullName>
    <description>FOUK-252 -&gt; Store The Method Type</description>
    <label>Request Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_RequestSent__c.field-meta.xml
<CustomField>
    <fullName>BLN_RequestSent__c</fullName>
    <description>FOUK-252 -&gt; Store Date and Time when Request was sent</description>
    <label>Request Sent</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_ResponseBody__c.field-meta.xml
<CustomField>
    <fullName>BLN_ResponseBody__c</fullName>
    <description>FOUK-252 -&gt; Store  Response Body sent to target system.</description>
    <label>Response Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_ResponseHeaders__c.field-meta.xml
<CustomField>
    <fullName>BLN_ResponseHeaders__c</fullName>
    <description>FOUK-252 -&gt; Store The Response Header</description>
    <label>Response Headers</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_ResponseReceived__c.field-meta.xml
<CustomField>
    <fullName>BLN_ResponseReceived__c</fullName>
    <description>FOUK-252 -&gt; Store The Date and Time when Response was recieved</description>
    <label>Response Received</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_ResponseStatus__c.field-meta.xml
<CustomField>
    <fullName>BLN_ResponseStatus__c</fullName>
    <description>FOUK-252 -&gt; Store The Response Status</description>
    <label>Response Status</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_ResponseStatusCode__c.field-meta.xml
<CustomField>
    <fullName>BLN_ResponseStatusCode__c</fullName>
    <description>FOUK-252 -&gt; Store The Response Status Code</description>
    <label>Response Status Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_TargetSystem__c.field-meta.xml
<CustomField>
    <fullName>BLN_TargetSystem__c</fullName>
    <description>FOUK-252 -&gt; Store Which Target System To Used The Data</description>
    <label>Target System</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BLN_IntegrationLoggerHandler.cls
/* @description - Creates IntegrationLogger records. Used after making API callouts.
 * @Story - FOUK-5189
 * @author - Animesh Biswas
 * @Created Date - 21/02/2024
*/ 
public without sharing class BLN_IntegrationLoggerHandler {

     /*@description : logCalloutDetails method used to create integrationLogger records.
      @Return : method returns database.SaveResult*/
    public static Database.SaveResult logCalloutDetails (Id recordId, String targetSystem, DateTime reqTime,DateTime resTime, HttpRequest request,HttpResponse response) {
        BLN_IntegrationLogger__c loggerRecord = new BLN_IntegrationLogger__c();
                
        //assignment of request details
        loggerRecord.BLN_RequestBody__c = request.getBody();
        loggerRecord.BLN_RequestEndPoint__c = request.getEndpoint();
        loggerRecord.BLN_RequestIssuedBy__c = UserInfo.getUserId();
        loggerRecord.BLN_RequestMethod__c = request.getMethod();
        loggerRecord.BLN_RequestSent__c = reqTime;
        
        //assigment of response details
        loggerRecord.BLN_ResponseBody__c = response.getBody();
        for(String keyVal : response.getHeaderkeys()){loggerRecord.BLN_ResponseHeaders__c += response.getHeader(keyVal)+'\n';}
        loggerRecord.BLN_ResponseReceived__c = resTime;
        loggerRecord.BLN_ResponseStatusCode__c = String.valueOf(response.getStatusCode());
        loggerRecord.BLN_ResponseStatus__c = response.getStatus();
        
        //assignment of other details
        loggerRecord.BLN_APICallInSeconds__c = String.valueOf(resTime.getTime() - reqTime.getTime()) ;
        loggerRecord.BLN_RecordId__c = recordId;
        loggerRecord.BLN_TargetSystem__c = targetSystem;
        
        return Database.insert(loggerRecord,false);
    }

    public static Database.SaveResult logCalloutDetailsRest(String recordId, String targetSystem, Datetime reqTime, Datetime resTime, RestRequest request, RestResponse response, String method) {
        BLN_IntegrationLogger__c loggerRecord = new BLN_IntegrationLogger__c();
        loggerRecord.BLN_RequestBody__c = request.requestBody?.toString();
        loggerRecord.BLN_RequestEndPoint__c = request.requestURI;
        loggerRecord.BLN_RequestIssuedBy__c = UserInfo.getUserId();
        loggerRecord.BLN_RequestMethod__c = method;
        loggerRecord.BLN_RequestSent__c = reqTime;
        loggerRecord.BLN_RequestHeaders__c = request.headers?.toString();
        
        loggerRecord.BLN_ResponseBody__c = response.responseBody?.toString();
        loggerRecord.BLN_ResponseHeaders__c = response.headers?.toString();
        loggerRecord.BLN_ResponseReceived__c = resTime;
        loggerRecord.BLN_ResponseStatus__c = response.statusCode?.toString();
        loggerRecord.BLN_ResponseStatusCode__c = response.statusCode?.toString();
        
        loggerRecord.BLN_APICallInSeconds__c = String.valueOf(resTime.getTime() - reqTime.getTime());
        loggerRecord.BLN_RecordId__c = recordId;
        loggerRecord.BLN_TargetSystem__c = targetSystem;
        return Database.insert(loggerRecord, false);
    }
}