force-app/main/default/objects/BLN_IntegrationLogger__c/BLN_IntegrationLogger__c.object-meta.xml
<CustomObject>
    <label>Integration Logger</label>
    <nameField>
        <displayFormat>IL-{00000000}</displayFormat>
        <label>Integration Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logger</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_RecordId__c.field-meta.xml
<CustomField>
    <fullName>BLN_RecordId__c</fullName>
    <description>FOUK-252 -&gt; Store The Record Id Created By API</description>
    <label>Reference Id</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_RequestBody__c.field-meta.xml
<CustomField>
    <fullName>BLN_RequestBody__c</fullName>
    <description>FOUK-252 -&gt; Store The Requested Body To Sent The End Point</description>
    <label>Request Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_RequestEndPoint__c.field-meta.xml
<CustomField>
    <fullName>BLN_RequestEndPoint__c</fullName>
    <description>FOUK-252 -&gt; Store The End Point Url</description>
    <label>Request End Point</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_RequestIssuedBy__c.field-meta.xml
<CustomField>
    <fullName>BLN_RequestIssuedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>FOUK-252 -&gt; Store User who initiated the request.</description>
    <label>Request Issued By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>IntegrationLogger</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_RequestMethod__c.field-meta.xml
<CustomField>
    <fullName>BLN_RequestMethod__c</fullName>
    <description>FOUK-252 -&gt; Store The Method Type</description>
    <label>Request Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_RequestSent__c.field-meta.xml
<CustomField>
    <fullName>BLN_RequestSent__c</fullName>
    <description>FOUK-252 -&gt; Store Date and Time when Request was sent</description>
    <label>Request Sent</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_ResponseBody__c.field-meta.xml
<CustomField>
    <fullName>BLN_ResponseBody__c</fullName>
    <description>FOUK-252 -&gt; Store  Response Body sent to target system.</description>
    <label>Response Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_ResponseReceived__c.field-meta.xml
<CustomField>
    <fullName>BLN_ResponseReceived__c</fullName>
    <description>FOUK-252 -&gt; Store The Date and Time when Response was recieved</description>
    <label>Response Received</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_ResponseStatus__c.field-meta.xml
<CustomField>
    <fullName>BLN_ResponseStatus__c</fullName>
    <description>FOUK-252 -&gt; Store The Response Status</description>
    <label>Response Status</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_ResponseStatusCode__c.field-meta.xml
<CustomField>
    <fullName>BLN_ResponseStatusCode__c</fullName>
    <description>FOUK-252 -&gt; Store The Response Status Code</description>
    <label>Response Status Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_TargetSystem__c.field-meta.xml
<CustomField>
    <fullName>BLN_TargetSystem__c</fullName>
    <description>FOUK-252 -&gt; Store Which Target System To Used The Data</description>
    <label>Target System</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/BLN_Payment__c.object-meta.xml
<CustomObject>
    <description>FOUK-4686: This object is created to store Payment information.</description>
    <label>Payments &amp; Refunds</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments &amp; Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_Case__c.field-meta.xml
<CustomField>
    <fullName>BLN_Case__c</fullName>
    <description>FOUK-4686: This field is created to store case value.</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_challengereference__c.field-meta.xml
<CustomField>
    <fullName>BLN_challengereference__c</fullName>
    <label>Challengereference</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_PaymentAmountTaken__c.field-meta.xml
<CustomField>
    <fullName>BLN_PaymentAmountTaken__c</fullName>
    <description>FOUK-4686: This field is created to store Payment amount taken value.</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_PaymentId__c.field-meta.xml
<CustomField>
    <fullName>BLN_PaymentId__c</fullName>
    <description>FOUK-4686: This field is created to store Payment Id value.</description>
    <label>Token Number</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_WorldPay_Token__c.field-meta.xml
<CustomField>
    <fullName>BLN_WorldPay_Token__c</fullName>
    <description>FOUK-6343 - Created to store the token received from worldpay for a customer card</description>
    <label>WorldPay Token</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BLN_WorldPayVerification.cls
/** @description : This class is used for payment verification
*   @author: Sourabh Bhattacharjee
*   @Story: FOUK-10605
*   @Created Date: 06/06/2024
*/
public with sharing class BLN_WorldPayVerification {
    public static Map<String,String> performCallout(String paymentid){
        BLN_Payment__c.SObjectType.getDescribe(SObjectDescribeOptions.DEFERRED).isAccessible();
        BLN_Payment__c newpayment = [SELECT Id, BLN_challengereference__c,BLN_WorldPay_Token__c,BLN_Case__c,BLN_PaymentAmountTaken__c,BLN_PaymentId__c FROM BLN_Payment__c WHERE id =:paymentid LIMIT 1];
        Map<String,String> returnmap = new Map<String,String>();
        returnmap.put('method', 'verification');
        // Define the request body
         Map<String, Object> requestBody = new Map<String, Object>{
            'transactionReference' => 'Portal_'+paymentid,
            'merchant' => new Map<String, Object>{
                'entity' => 'default'
            },
            'challenge' => new Map<String, Object>{
                'reference' => newpayment.BLN_challengereference__c
            }   
        };
       
        // Convert request body to JSON string
        String requestBodyJson = JSON.serialize(requestBody);
       //System.debug('BODY 22-->'+requestBodyJson);
        // Make HTTP callout
        HttpRequest request = new HttpRequest();
        request.setEndpoint('callout:WorldPayCredential/verifications/customers/3ds/verification');
        request.setMethod('POST');
        //request.setHeader('Content-Type', 'application/json');
        request.setBody(requestBodyJson);
        
        Map<String,string> headers = new Map<String,String>();
        headers.put('Authorization','Basic ZjljZ2V4MTJqMmhvaDJ4MDowODBlOWo0bzBxbjZ5emVkaWVvcW8wamYwa2ZicHk5YTdyZ3BlNWJqdTZqdWkwY3huZHFnYmtxd3JsbjljdDdi');
        headers.put('Content-Type','application/vnd.worldpay.verifications.customers-v3.hal+json');
        headers.put('Accept','application/vnd.worldpay.verifications.customers-v3.hal+json');
        
        for (String key : headers.keySet()) {
            request.setHeader(key, headers.get(key));
        }
 
        // Send the request
        Http http = new Http();
        HttpResponse response = http.send(request);
        Map<String, Object> jsonMap = (Map<String, Object>)JSON.deserializeUntyped(response.getBody());
        System.debug('JSONMAP 44-->'+JSON.serializePretty(jsonMap));
        String outcome = (String)jsonMap.get('outcome');
        /*List<BLN_IntegrationLogger__c> intLogList = new List<BLN_IntegrationLogger__c>();
                BLN_IntegrationLogger__c integrat = new BLN_IntegrationLogger__c();
                integrat.BLN_RecordId__c=paymentid;
                integrat.BLN_RequestBody__c = request.getBody();
                integrat.BLN_RequestEndPoint__c = request.getEndpoint();
                integrat.BLN_RequestIssuedBy__c = UserInfo.getUserId();
                integrat.BLN_RequestMethod__c = request.getMethod();
                integrat.BLN_RequestSent__c = System.today();
                integrat.BLN_ResponseBody__c = response.getBody();
                integrat.BLN_ResponseReceived__c = System.today();
                integrat.BLN_ResponseStatus__c = response.getStatus();
                integrat.BLN_ResponseStatusCode__c = ''+response.getStatusCode();
                integrat.BLN_TargetSystem__c = System.label.BLN_TargetSystemMulesoft;
                intLogList.add(integrat);
                BLN_IntegrationLogger.logRequest(intLogList);*/
        if(outcome == 'authenticated'){
            // System.debug(newpayment.BLN_PaymentAmountTaken__c+'Param passd fr authpay verification-->'+newpayment.BLN_WorldPay_Token__c+'-'+newpayment.BLN_PaymentId__c);
            returnmap = BLN_PaymentWorldPayController.authorizeAPayment(paymentid,newpayment.BLN_WorldPay_Token__c,newPayment.BLN_PaymentAmountTaken__c*100,newPayment.BLN_PaymentId__c);
           // System.debug('returnmap in verification-->'+returnmap);
              if(returnmap.get('code')!= null && returnmap.get('code')=='201'){
                returnmap.put('code', '201');
                returnmap.put('caseid', newpayment.BLN_Case__c);
                returnmap.put('outcome',outcome);
                 //System.debug('LINE 66-->'+returnmap);
                return returnmap;
            }
        }
        else{
            returnmap.put('code', String.valueOf(response.getStatusCode()));
            returnmap.put('caseid', newpayment.BLN_Case__c);
            returnmap.put('outcome',outcome);
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Payment could not be completed at this moment, please try later'));
           // System.debug('LINE 75-->'+returnmap);
            return returnmap;    
        }
        return null;
    }
}