force-app/main/default/objects/BLN_IntegrationLogger__c/BLN_IntegrationLogger__c.object-meta.xml
<CustomObject>
    <label>Integration Logger</label>
    <nameField>
        <displayFormat>IL-{00000000}</displayFormat>
        <label>Integration Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logger</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_RecordId__c.field-meta.xml
<CustomField>
    <fullName>BLN_RecordId__c</fullName>
    <description>FOUK-252 -&gt; Store The Record Id Created By API</description>
    <label>Reference Id</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_RequestBody__c.field-meta.xml
<CustomField>
    <fullName>BLN_RequestBody__c</fullName>
    <description>FOUK-252 -&gt; Store The Requested Body To Sent The End Point</description>
    <label>Request Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_RequestEndPoint__c.field-meta.xml
<CustomField>
    <fullName>BLN_RequestEndPoint__c</fullName>
    <description>FOUK-252 -&gt; Store The End Point Url</description>
    <label>Request End Point</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_RequestIssuedBy__c.field-meta.xml
<CustomField>
    <fullName>BLN_RequestIssuedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>FOUK-252 -&gt; Store User who initiated the request.</description>
    <label>Request Issued By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>IntegrationLogger</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_RequestMethod__c.field-meta.xml
<CustomField>
    <fullName>BLN_RequestMethod__c</fullName>
    <description>FOUK-252 -&gt; Store The Method Type</description>
    <label>Request Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_RequestSent__c.field-meta.xml
<CustomField>
    <fullName>BLN_RequestSent__c</fullName>
    <description>FOUK-252 -&gt; Store Date and Time when Request was sent</description>
    <label>Request Sent</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_ResponseBody__c.field-meta.xml
<CustomField>
    <fullName>BLN_ResponseBody__c</fullName>
    <description>FOUK-252 -&gt; Store  Response Body sent to target system.</description>
    <label>Response Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_ResponseReceived__c.field-meta.xml
<CustomField>
    <fullName>BLN_ResponseReceived__c</fullName>
    <description>FOUK-252 -&gt; Store The Date and Time when Response was recieved</description>
    <label>Response Received</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_ResponseStatus__c.field-meta.xml
<CustomField>
    <fullName>BLN_ResponseStatus__c</fullName>
    <description>FOUK-252 -&gt; Store The Response Status</description>
    <label>Response Status</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_ResponseStatusCode__c.field-meta.xml
<CustomField>
    <fullName>BLN_ResponseStatusCode__c</fullName>
    <description>FOUK-252 -&gt; Store The Response Status Code</description>
    <label>Response Status Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_TargetSystem__c.field-meta.xml
<CustomField>
    <fullName>BLN_TargetSystem__c</fullName>
    <description>FOUK-252 -&gt; Store Which Target System To Used The Data</description>
    <label>Target System</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/BLN_Payment__c.object-meta.xml
<CustomObject>
    <description>FOUK-4686: This object is created to store Payment information.</description>
    <label>Payments &amp; Refunds</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments &amp; Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_challengereference__c.field-meta.xml
<CustomField>
    <fullName>BLN_challengereference__c</fullName>
    <label>Challengereference</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BLN_AuthenticationRequest.cls
/** @description : This class is used for 3DS callout
*   @author: Sourabh Bhattacharjee
*   @Story: FOUK-10605
*   @Created Date: 06/06/2024
*/
public without sharing class BLN_AuthenticationRequest {
    public static Map<String,String> performCallout(String paymentId,Decimal amount,String token,String said,String pref) {
        // Define the endpoint URL
       // System.debug(paymentId+'PARAM 6--'+amount+token+said+pref);
       // String endpoint = 'https://try.access.worldpay.com/verifications/customers/3ds/authentication';
        Map<String,String> returnmap = new Map<String,String>();
        returnmap.put('method', 'authentication');
        // Define the request body
         Map<String, Object> requestBody = new Map<String, Object>{
            'transactionReference' => 'Portal_'+paymentid,
            'merchant' => new Map<String, Object>{ 
                'entity' => 'default'
            },
            'instruction' => new Map<String, Object>{
                'paymentInstrument' => new Map<String, Object>{
                    'type' => 'card/tokenized',
                    'href' => token
                },
                'value' => new Map<String, Object>{
                    'currency' => 'GBP',
                    'amount' => amount
                }
            },
            'deviceData' => new Map<String, Object>{
                'acceptHeader' => 'text/html',
                'userAgentHeader' => 'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0)'
            },
            'challenge' => new Map<String, Object>{
                'windowSize' => '600x400',
                'preference' => pref,
                //'preference' => 'noPreference',
                'returnUrl' => Site.getBaseUrl()+'/apex/BLN_Worldpay_final?challenge=complete&paymentid='+paymentId +'&said='+said
            } 
        };
       
        // Convert request body to JSON string
        String requestBodyJson = JSON.serialize(requestBody);
        // Make HTTP callout
        HttpRequest request = new HttpRequest();
        request.setEndpoint('callout:WorldPayCredential/verifications/customers/3ds/authentication');
        request.setMethod('POST');
        //request.setHeader('Content-Type', 'application/json');
        request.setBody(requestBodyJson);
        
        Map<String,string> headers = new Map<String,String>();
        headers.put('Authorization','Basic ZjljZ2V4MTJqMmhvaDJ4MDowODBlOWo0bzBxbjZ5emVkaWVvcW8wamYwa2ZicHk5YTdyZ3BlNWJqdTZqdWkwY3huZHFnYmtxd3JsbjljdDdi');
        headers.put('Content-Type','application/vnd.worldpay.verifications.customers-v3.hal+json');
        headers.put('Accept','application/vnd.worldpay.verifications.customers-v3.hal+json');
        
        for (String key : headers.keySet()) {
            request.setHeader(key, headers.get(key));
        }
        // Send the request
        Http http = new Http();
        HttpResponse response = http.send(request);
        Map<String, Object> jsonMap = (Map<String, Object>)JSON.deserializeUntyped(response.getBody());
        String outcome = (String)jsonMap.get('outcome');
        Map<String, Object> challengemap = (Map<String, Object>)jsonMap.get('challenge');
        String challengereference = (String)challengemap.get('reference');
        String url = (String)challengemap.get('url');
        String jwt = (String)challengemap.get('jwt');
        String payload = (String)challengemap.get('payload');
        BLN_IntegrationLogger__c.SObjectType.getDescribe(SObjectDescribeOptions.DEFERRED).isAccessible();
        List<BLN_IntegrationLogger__c> intLogList = new List<BLN_IntegrationLogger__c>();
                BLN_IntegrationLogger__c integrat = new BLN_IntegrationLogger__c();
                integrat.BLN_RequestBody__c = request.getBody();
                integrat.BLN_RequestEndPoint__c = request.getEndpoint();
                integrat.BLN_RequestIssuedBy__c = UserInfo.getUserId();
                integrat.BLN_RequestMethod__c = request.getMethod();
                integrat.BLN_RequestSent__c = System.today();
                integrat.BLN_ResponseBody__c = response.getBody();
                integrat.BLN_ResponseReceived__c = System.today();
                integrat.BLN_ResponseStatus__c = response.getStatus();
                integrat.BLN_ResponseStatusCode__c = ''+response.getStatusCode();
                integrat.BLN_TargetSystem__c = System.label.BLN_TargetSystemMulesoft;
        		integrat.BLN_RecordId__c=paymentId;
                intLogList.add(integrat);
                BLN_IntegrationLogger.logRequest(intLogList);
        // Check the response
        if (response.getStatusCode() == 200) {
            // Successful callout
           // String responseBody = response.getBody();
            returnmap.put('outcome', outcome);
            returnmap.put('challengereference', challengereference);
            returnmap.put('url', url);
            returnmap.put('jwt', jwt);
            returnmap.put('payload', payload);
            if(outcome =='Authenticated'){
                returnmap = BLN_PaymentWorldPayController.authorizeAPayment(paymentid,token,amount,'');
                return returnmap;
            }
            if(outcome == 'Challenged'){
                returnmap.put('challengereference', challengereference);
                returnmap.put('url', url);
                returnmap.put('jwt', jwt);
                returnmap.put('payload', payload);
                BLN_Payment__c pay = new BLN_Payment__c(Id = paymentId);
                pay.BLN_challengereference__c = challengereference;
                BLN_Payment__c.SObjectType.getDescribe(SObjectDescribeOptions.DEFERRED).isUpdateable();
                update pay;
            }
        } else {
            // Error handling
          //  String responseBody = response.getBody();
            returnmap.put('outcome', outcome);
            /*returnmap.put('challengereference', challengereference);
            returnmap.put('url', url);
            returnmap.put('jwt', jwt);
            returnmap.put('payload', payload);*/
        }
        return returnmap;
    }
}