force-app/main/default/objects/BLN_ExceptionLogger__c/BLN_ExceptionLogger__c.object-meta.xml
<CustomObject>
    <description>This is used to store exception logs.</description>
    <label>Exception Logger</label>
    <nameField>
        <displayFormat>EL-{00000000}</displayFormat>
        <label>Exception Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logger</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_ExceptionLogger__c/fields/BLN_CurrentUser__c.field-meta.xml
<CustomField>
    <fullName>BLN_CurrentUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>FOUK-2048--&gt; Need to create this field to populate this field of record with field values carried from Flow Exception Logger platform event:</description>
    <label>Current User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ExceptionLogger</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BLN_ExceptionLogger__c/fields/BLN_EntityName__c.field-meta.xml
<CustomField>
    <fullName>BLN_EntityName__c</fullName>
    <description>FOUK-2048--&gt; Need to create this field to populate this field of record with field values carried from Flow Exception Logger platform event:</description>
    <label>Entity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ExceptionLogger__c/fields/BLN_ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>BLN_ErrorMessage__c</fullName>
    <description>FOUK-252 -&gt; Store The Exception Error Message</description>
    <label>Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BLN_ExceptionLogger__c/fields/BLN_ExceptionType__c.field-meta.xml
<CustomField>
    <fullName>BLN_ExceptionType__c</fullName>
    <description>FOUK-252 -&gt; Store The Exception Type</description>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ExceptionLogger__c/fields/BLN_LineNumber__c.field-meta.xml
<CustomField>
    <fullName>BLN_LineNumber__c</fullName>
    <description>FOUK-252 -&gt; Store The ExceptionLine Number</description>
    <label>Line Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ExceptionLogger__c/fields/BLN_MethodStep__c.field-meta.xml
<CustomField>
    <fullName>BLN_MethodStep__c</fullName>
    <description>FOUK-252 -&gt; Store The Mehtod</description>
    <label>Method/Step</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ExceptionLogger__c/fields/BLN_RecordIdIdentifier__c.field-meta.xml
<CustomField>
    <fullName>BLN_RecordIdIdentifier__c</fullName>
    <description>FOUK--2048--&gt; Store the Record ID</description>
    <label>RecordId/Identifier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ExceptionLogger__c/fields/BLN_StackTrace__c.field-meta.xml
<CustomField>
    <fullName>BLN_StackTrace__c</fullName>
    <description>FOUK-252 -&gt; Store The Stack Trace of Exception</description>
    <label>Stack Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/BLN_ExceptionLogger.cls
/** @description : This apex class used to store Exceptoin from Apex class
*   @author:Rahul Jain (PwC IN)
*   @CreatedDate: 24.07.2023
*   @Story: FOUK-252
*/
public without sharing class BLN_ExceptionLogger {

       /*****************************************
MethodName : saveExceptions
Description : This is used to save exception
Input Parameter : (List<ExceptionLoggerWrapper>)
Output Parameter : void
CreatedDate: 11/08/2023
CreatedBy : Pwc-India
Change log :
****************************************/

    
    public static void saveExceptions (List<ExceptionLoggerWrapper> exceptionWrappers) {
        
        List<BLN_ExceptionLogger__c> exceptionLogs = new List<BLN_ExceptionLogger__c>();
        
        for(ExceptionLoggerWrapper exceptionWrap : exceptionWrappers){
            
            exceptionLogs.add(exceptionWrap.exceptionLog);
        }
        if(Schema.sObjectType.BLN_ExceptionLogger__c.isCreateable()){
            insert exceptionLogs;
        }
    }
  
    
    /*****************************************
MethodName : captureException
Description : This is used to capture exception
Input Parameter : (Exception)
Output Parameter : void
CreatedDate: 11/08/2023
CreatedBy : Pwc-India
Change log :
****************************************/
    public static void captureException( Exception ex){
        
        List<ExceptionLoggerWrapper> lstwrapper = new List<ExceptionLoggerWrapper>();
        Integer count = 1;
        
        if(ex.getTypeName() == 'System.DmlException'){
            
            count = ex.getNumDml();
        }
        
        for (Integer i = 0; i < count; i++) { 
            
            ExceptionLoggerWrapper objwrapper = new ExceptionLoggerWrapper( ex, i);
            lstwrapper.add(objwrapper);
        }
        
        saveExceptions(lstwrapper);
    }
    

    public static List<BLN_ExceptionLogger__c> logException(List<Exception> execepLogList, String failedRecordId){
        return logException(execepLogList, true, failedRecordId);
    }

    public static List<BLN_ExceptionLogger__c> logException(List<Exception> execepLogList, Id processedRecord, Boolean insertLogs, String failedRecordId){
        List<BLN_ExceptionLogger__c> exceptionLoggs = logException(execepLogList, false, failedRecordId);
        for (BLN_ExceptionLogger__c exceptionLog : exceptionLoggs) {
            exceptionLog.BLN_RecordIdIdentifier__c = processedRecord;
        }
        return exceptionLoggs;
    }

    public static List<BLN_ExceptionLogger__c> logException(List<Exception> execepLogList, Boolean insertLogs, String failedRecordId){
        List<BLN_ExceptionLogger__c> loggerListException  = new  List<BLN_ExceptionLogger__c>();

        for(Exception excepLoggerObj : execepLogList){
            BLN_ExceptionLogger__c objExcepLogger = New BLN_ExceptionLogger__c();
            if(excepLoggerObj instanceof DmlException){
                DmlException dmlException = (DmlException)excepLoggerObj;
                String recordId = excepLoggerObj.getDmlId(0);
                objExcepLogger.BLN_RecordIdIdentifier__c = recordId;
            } else {
                objExcepLogger.BLN_RecordIdIdentifier__c = failedRecordId != null ? failedRecordId : '';
            }
            String stackTrace = excepLoggerObj.getStackTraceString();
            String apexClassName = stackTrace.substringAfter('.').substringBefore('.');
            String classMethodName = stackTrace.substringBefore(':').substringAfter(apexClassName).substringAfter('.');
            objExcepLogger.BLN_EntityName__c = apexClassName;
            objExcepLogger.BLN_ExceptionType__c = excepLoggerObj.getTypeName();
            objExcepLogger.BLN_LineNumber__c = string.valueof(excepLoggerObj.getLineNumber());
            objExcepLogger.BLN_ErrorMessage__c = excepLoggerObj.getMessage();
            objExcepLogger.BLN_MethodStep__c = classMethodName;
            objExcepLogger.BLN_StackTrace__c = stackTrace;

            loggerListException.add(objExcepLogger);
        }

        if (insertLogs) {
            if(Schema.sObjectType.BLN_ExceptionLogger__c.isCreateable()){
                insert loggerListException;
            }
        }

        return loggerListException;
    }
    
    public static void logExceptionRequest(List<Exception> execepLogList, String request, String failedRecordId){
        List<BLN_ExceptionLogger__c> loggerListException  = new  List<BLN_ExceptionLogger__c>();
        
        for(Exception excepLoggerObj : execepLogList){
            BLN_ExceptionLogger__c objExcepLogger = New BLN_ExceptionLogger__c();
            if(excepLoggerObj instanceof DmlException){
                DmlException dmlException = (DmlException)excepLoggerObj;
                String recordId = excepLoggerObj.getDmlId(0);
                objExcepLogger.BLN_RecordIdIdentifier__c = recordId;
            } else {
                objExcepLogger.BLN_RecordIdIdentifier__c = failedRecordId != null ? failedRecordId : '';
            }
            String stackTrace = excepLoggerObj.getStackTraceString();
            String apexClassName = stackTrace.substringAfter('.').substringBefore('.');
            String classMethodName = stackTrace.substringBefore(':').substringAfter(apexClassName).substringAfter('.');
            objExcepLogger.BLN_EntityName__c = apexClassName;
            objExcepLogger.BLN_ExceptionType__c = excepLoggerObj.getTypeName();
            objExcepLogger.BLN_LineNumber__c = string.valueof(excepLoggerObj.getLineNumber());
            objExcepLogger.BLN_ErrorMessage__c = excepLoggerObj.getMessage();
            objExcepLogger.BLN_MethodStep__c = classMethodName;
            objExcepLogger.BLN_StackTrace__c = stackTrace+ '\n\n'+ request;
            
            loggerListException.add(objExcepLogger); 
        }
        if(Schema.sObjectType.BLN_ExceptionLogger__c.isCreateable()){
            insert loggerListException;
        }
    }
    
    /*****************************************
  Description : This is a wrapper class
  ****************************************/ 
  
  public class ExceptionLoggerWrapper {
        
    BLN_ExceptionLogger__c exceptionLog = new BLN_ExceptionLogger__c();
        
        public ExceptionLoggerWrapper(Exception ex, Integer i){
            
            String stackTrace = ex.getStackTraceString().subStringBefore('\n');
            String apexClassName = stackTrace.substringAfter('.').substringBefore('.');
            String classMethodName = stackTrace.substringBefore(':').substringAfter(apexClassName).substringAfter('.');
            exceptionLog.BLN_EntityName__c      = apexClassName;
            exceptionLog.BLN_MethodStep__c      = classMethodName;
            exceptionLog.BLN_ErrorMessage__c    = ex.getMessage();
            exceptionLog.BLN_LineNumber__c      = string.valueof(ex.getLineNumber());
            exceptionLog.BLN_StackTrace__c      = ex.getStackTraceString();
            exceptionLog.BLN_ExceptionType__c   = ex.getTypeName();
            exceptionLog.BLN_CurrentUser__c     = UserInfo.getUserId();
            if(ex.getTypeName() == 'System.DmlException'){
                exceptionLog.BLN_RecordIdIdentifier__c = ex.getDmlId(i);
            }
        }
    }
}