force-app/main/default/objects/LAD_Return_Item__c/LAD_Return_Item__c.object-meta.xml
<CustomObject>
    <description>This Object stores all the Return Items info when an order is returned</description>
    <label>Return Item</label>
    <nameField>
        <displayFormat>RI-{0000000}</displayFormat>
        <label>Return Order Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Return Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LAD_Return_Item__c/fields/LAD_CreditNote__c.field-meta.xml
<CustomField>
    <fullName>LAD_CreditNote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A lookup field to Financial document object</description>
    <label>Credit Note</label>
    <referenceTo>LAD_Financial_Document__c</referenceTo>
    <relationshipLabel>Return Items</relationshipLabel>
    <relationshipName>Return_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LAD_Return_Item__c/fields/LAD_Return_Order__c.field-meta.xml
<CustomField>
    <fullName>LAD_Return_Order__c</fullName>
    <description>This is a master-detail to Return Order Object</description>
    <label>Return Order</label>
    <referenceTo>LAD_Return__c</referenceTo>
    <relationshipLabel>Return Items</relationshipLabel>
    <relationshipName>Return_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LAD_Return_Item__c/fields/LAD_Status__c.field-meta.xml
<CustomField>
    <fullName>LAD_Status__c</fullName>
    <description>This Field is used to store Status of the Returned Item</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Return Submitted</fullName>
                <default>true</default>
                <label>Return Submitted</label>
            </value>
            <value>
                <fullName>Awaiting Inspection</fullName>
            </value>
            <value>
                <fullName>Return Accepted</fullName>
            </value>
            <value>
                <fullName>Return Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LAD_ScheduleFinancialDocumentCreation.cls
/* description:     This apex class is used to schedule LAD_InvoiceCreationBatch batch class for creation of Invoices and 
                    schedule the LAD_CreditNoteCreationBatch for creation of Credit Notes.
   author:          (binayak.debnath@pwc.com (IN))
   Story:           FOUK-10522; FOUK-10582
*/
public class LAD_ScheduleFinancialDocumentCreation implements Schedulable{
    //creat schedule
    public void execute(SchedulableContext context){
        if(([SELECT OrderSummaryId FROM OrderItemSummary WHERE LAD_Status__c = 'Shipped' AND LAD_Invoice__c = null LIMIT 1]).size() != 0){
            Database.executeBatch(new LAD_InvoiceCreationBatch(), 200);
        }

        if(([SELECT LAD_Return_Order__c FROM LAD_Return_Item__c WHERE LAD_Status__c = 'Return Accepted' AND LAD_CreditNote__c = null LIMIT 1]).size() != 0){
            Database.executeBatch(new LAD_CreditNoteCreationBatch(), 200);
        }
    }
}