force-app/main/default/objects/LAD_Financial_Document__c/LAD_Financial_Document__c.object-meta.xml
<CustomObject>
    <description>Implementation of the Financial documents for Laddaw B2B platform. FOUK-10357</description>
    <label>Financial Document</label>
    <nameField>
        <displayFormat>FIN-{0000000}</displayFormat>
        <label>Financial Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LAD_Financial_Document__c/fields/LAD_Account__c.field-meta.xml
<CustomField>
    <fullName>LAD_Account__c</fullName>
    <description>Master-Detail relationship with Account Object. FOUK-10357</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Documents</relationshipLabel>
    <relationshipName>Financial_Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LAD_Financial_Document__c/fields/LAD_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>LAD_Due_Date__c</fullName>
    <description>To store the Due date of Financial Document. FOUK-10357</description>
    <label>Due Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/LAD_Financial_Document__c/fields/LAD_Order_Summary__c.field-meta.xml
<CustomField>
    <fullName>LAD_Order_Summary__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup Relation with the Order Summary object. FOUK-10357</description>
    <label>Order Summary</label>
    <referenceTo>OrderSummary</referenceTo>
    <relationshipLabel>Financial Documents</relationshipLabel>
    <relationshipName>Financial_Documents</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LAD_Financial_Document__c/fields/LAD_Remaining_Amount__c.field-meta.xml
<CustomField>
    <fullName>LAD_Remaining_Amount__c</fullName>
    <description>To store the Remaining Amount. FOUK-10357</description>
    <label>Remaining Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/LAD_Financial_Document__c/fields/LAD_Return_Order__c.field-meta.xml
<CustomField>
    <fullName>LAD_Return_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>FOUK-10472: Created to store reference to Return records for Credit Notes</description>
    <label>Return Order</label>
    <referenceTo>LAD_Return__c</referenceTo>
    <relationshipLabel>Financial Documents</relationshipLabel>
    <relationshipName>Financial_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LAD_Financial_Document__c/fields/LAD_Status__c.field-meta.xml
<CustomField>
    <fullName>LAD_Status__c</fullName>
    <description>To store the multiple value of Status. FOUK-10357</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LAD_Financial_Document__c/fields/LAD_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>LAD_Total_Amount__c</fullName>
    <description>To store the Total amount Price. FOUK-10357</description>
    <label>Total Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/LAD_Financial_Document__c/fields/LAD_Type__c.field-meta.xml
<CustomField>
    <fullName>LAD_Type__c</fullName>
    <description>To show the type of Financial Document. FOUK-10357</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Credit Note</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LAD_Return__c/LAD_Return__c.object-meta.xml
<CustomObject>
    <description>This Object Stores all the info of the Returned Order</description>
    <label>Return</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Return Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Returns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LAD_Return__c/fields/LAD_Account__c.field-meta.xml
<CustomField>
    <fullName>LAD_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stores Account Info</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Returns</relationshipLabel>
    <relationshipName>Returns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LAD_Return__c/fields/LAD_Original_Order_Summary__c.field-meta.xml
<CustomField>
    <fullName>LAD_Original_Order_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the original order summary</description>
    <label>Original Order Summary</label>
    <referenceTo>OrderSummary</referenceTo>
    <relationshipLabel>Returns</relationshipLabel>
    <relationshipName>Returns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LAD_Return__c/fields/LAD_Status__c.field-meta.xml
<CustomField>
    <fullName>LAD_Status__c</fullName>
    <description>This Fields is used to store Status of the Returned Order</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Return Submitted</fullName>
                <default>true</default>
                <label>Return Submitted</label>
            </value>
            <value>
                <fullName>Awaiting Inspection</fullName>
            </value>
            <value>
                <fullName>Return Accepted</fullName>
            </value>
            <value>
                <fullName>Return Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LAD_Return_Item__c/LAD_Return_Item__c.object-meta.xml
<CustomObject>
    <description>This Object stores all the Return Items info when an order is returned</description>
    <label>Return Item</label>
    <nameField>
        <displayFormat>RI-{0000000}</displayFormat>
        <label>Return Order Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Return Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LAD_Return_Item__c/fields/LAD_CreditNote__c.field-meta.xml
<CustomField>
    <fullName>LAD_CreditNote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A lookup field to Financial document object</description>
    <label>Credit Note</label>
    <referenceTo>LAD_Financial_Document__c</referenceTo>
    <relationshipLabel>Return Items</relationshipLabel>
    <relationshipName>Return_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LAD_Return_Item__c/fields/LAD_Original_Order_Summary_Product__c.field-meta.xml
<CustomField>
    <fullName>LAD_Original_Order_Summary_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the original order product summary</description>
    <label>Original Order Summary Product</label>
    <referenceTo>OrderItemSummary</referenceTo>
    <relationshipLabel>Return Items</relationshipLabel>
    <relationshipName>Return_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LAD_Return_Item__c/fields/LAD_Return_Order__c.field-meta.xml
<CustomField>
    <fullName>LAD_Return_Order__c</fullName>
    <description>This is a master-detail to Return Order Object</description>
    <label>Return Order</label>
    <referenceTo>LAD_Return__c</referenceTo>
    <relationshipLabel>Return Items</relationshipLabel>
    <relationshipName>Return_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LAD_Return_Item__c/fields/LAD_Status__c.field-meta.xml
<CustomField>
    <fullName>LAD_Status__c</fullName>
    <description>This Field is used to store Status of the Returned Item</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Return Submitted</fullName>
                <default>true</default>
                <label>Return Submitted</label>
            </value>
            <value>
                <fullName>Awaiting Inspection</fullName>
            </value>
            <value>
                <fullName>Return Accepted</fullName>
            </value>
            <value>
                <fullName>Return Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LAD_CreditNoteCreationBatch.cls
/* description :   This apex class is used to create Credit Notes for Return Accepted Return Items grouped by Return records
   author:         (binayak.debnath@pwc.com (IN))
   Story:          FOUK-10582
*/

public class LAD_CreditNoteCreationBatch implements Database.Batchable<SObject>, Database.Stateful{

    // Start method to define the query to retrieve records
    public Database.QueryLocator start(Database.BatchableContext BC) {
        // Create a set of Return Ids for all Return Items with Status 'Return Accepted' and Credit Note at null
        Set<String> returnIds = new Set<String>();
        for(LAD_Return_Item__c item: [SELECT LAD_Return_Order__c FROM LAD_Return_Item__c WHERE LAD_Status__c = 'Return Accepted' AND LAD_CreditNote__c = null]){
            returnIds.add(item.LAD_Return_Order__c);
        }

        //Query String for all records grouped by Order Summary
        String query =  'SELECT Id, ' + 
                                'LAD_Account__c	, ' +
                                'LAD_Account__r.BLN_PaymentTerms__c, ' + 
                                'CurrencyIsoCode, ' +
                                'LAD_Original_Order_Summary__c, ' +
                                '(SELECT Id, ' + 
                                    'Name, ' + 
                                    'LAD_CreditNote__c, ' + 
                                    'LAD_Status__c, ' + 
                                    'LAD_Original_Order_Summary_Product__r.AdjustedLineAmtWithTax, ' + 
                                    'LAD_Return_Order__c ' + 
                                'FROM Return_Items__r ' + 
                                'WHERE LAD_Status__c = \'Return Accepted\' AND LAD_CreditNote__c = null) ' + 
                        'FROM LAD_Return__c ' + 
                        'WHERE Id IN :returnIds';
        System.debug(query);   
        return Database.getQueryLocator(query);
    }

    // Execute method to process each batch of records
    public void execute(Database.BatchableContext BC, List<LAD_Return__c> returns) {
        try {
            Map<String, LAD_Financial_Document__c> returnIdCreditNoteMap = new Map<String, LAD_Financial_Document__c>();
            List<LAD_Financial_Document__c> insertCreditNoteList = new List<LAD_Financial_Document__c>();
            List<LAD_Return_Item__c> updateReturnItemList = new List<LAD_Return_Item__c>();
            for(LAD_Return__c ret : returns){
                LAD_Financial_Document__c fin = new LAD_Financial_Document__c();
                fin.LAD_Type__c = 'Credit Note';
                fin.LAD_Account__c = ret.LAD_Account__c;
                fin.LAD_Order_Summary__c = ret.LAD_Original_Order_Summary__c;
                fin.LAD_Return_Order__c = ret.Id;
                fin.CurrencyIsoCode = ret.CurrencyIsoCode;
                fin.LAD_Status__c = 'Open';
                fin.LAD_Total_Amount__c = 0;

                for(LAD_Return_Item__c item : ret.Return_Items__r){
                    fin.LAD_Total_Amount__c -= item.LAD_Original_Order_Summary_Product__r.AdjustedLineAmtWithTax;
                }

                Date today = Date.today();
                Date firstOf30Month = today.toStartOfMonth().addMonths(1);
                Date firstOf60Month = firstOf30Month.addMonths(1);
                system.debug(ret.LAD_Account__r.BLN_PaymentTerms__c);

                if(ret.LAD_Account__r.BLN_PaymentTerms__c == '30 END OF MONTH') {
                    fin.LAD_Due_Date__c = Date.daysInMonth(firstOf30Month.year(), firstOf30Month.month()) >= 30 ? firstOf30Month.addDays(29) : firstOf30Month.addDays(Date.daysInMonth(firstOf30Month.year(), firstOf30Month.month()) - 1);
                }
                else if(ret.LAD_Account__r.BLN_PaymentTerms__c == '60 END OF MONTH') {
                    fin.LAD_Due_Date__c = Date.daysInMonth(firstOf60Month.year(), firstOf60Month.month()) >= 30 ? firstOf60Month.addDays(29) : firstOf60Month.addDays(Date.daysInMonth(firstOf60Month.year(), firstOf60Month.month()) - 1);
                }
                else if(ret.LAD_Account__r.BLN_PaymentTerms__c == '5 END OF MONTH') {
                    fin.LAD_Due_Date__c = firstOf30Month.addDays(4);
                }

                fin.LAD_Remaining_Amount__c = fin.LAD_Total_Amount__c;
                returnIdCreditNoteMap.put(ret.Id, fin);
                insertCreditNoteList.add(fin);
            }

            if(insertCreditNoteList.size() > 0){
                insert insertCreditNoteList;
            }

            for(LAD_Return__c ret : returns){
                for(LAD_Return_Item__c item : ret.Return_Items__r){
                    item.LAD_CreditNote__c = returnIdCreditNoteMap.get(ret.Id).Id;
                }
                updateReturnItemList.addAll(ret.Return_Items__r);
            }

            update updateReturnItemList;
        } catch (Exception e) {
            // Handle any exceptions
            BLN_ExceptionLogger.captureException(e);
            System.debug('Exception: ' + e.getMessage());
        }
    }

    // Finish method
    public void finish(Database.BatchableContext BC) {
        // Any final processing or logging can be done here
        System.debug('Batch process finished.');
    }
}