force-app/main/default/objects/BLN_Initiative__c/BLN_Initiative__c.object-meta.xml
<CustomObject>
    <description>FOUK-4789</description>
    <label>Initiative</label>
    <nameField>
        <label>Intiative Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Initiatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_Initiative__c/fields/BLN_AccountPlanName__c.field-meta.xml
<CustomField>
    <fullName>BLN_AccountPlanName__c</fullName>
    <description>FOUK-4770. Created for related list</description>
    <label>Account Plan Name</label>
    <referenceTo>BLN_AccountPlan__c</referenceTo>
    <relationshipLabel>Initiatives</relationshipLabel>
    <relationshipName>Initiatives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BLN_Initiative__c/fields/BLN_EndDate__c.field-meta.xml
<CustomField>
    <fullName>BLN_EndDate__c</fullName>
    <description>This is a date field indicated the end date (FOUK-4772)</description>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BLN_Initiative__c/fields/BLN_StartDate__c.field-meta.xml
<CustomField>
    <fullName>BLN_StartDate__c</fullName>
    <description>This is a date field indicated the start date (FOUK-4772)</description>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BLN_Initiative__c/fields/BLN_Status__c.field-meta.xml
<CustomField>
    <fullName>BLN_Status__c</fullName>
    <description>FOUK-4775. To get Status of the Initiative.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BLN_TimeLineController.cls
public with sharing class BLN_TimeLineController {
    @AuraEnabled
    public static List<BLN_WrapperStore.InitiativeWrapper> getInitiatives(String recId) {
        List<BLN_WrapperStore.InitiativeWrapper> intWrapList = new List<BLN_WrapperStore.InitiativeWrapper>();
        
        for(BLN_Initiative__c initiative : [SELECT Id, Name, BLN_Status__c, BLN_EndDate__c, BLN_StartDate__c 
                                            FROM BLN_Initiative__c 
                                            WHERE BLN_AccountPlanName__c = :recId WITH SECURITY_ENFORCED]) {
            String className;
            
            switch on initiative.BLN_Status__c {
                when 'In Progress' {
                    className = 'blue';
                    if(initiative.BLN_EndDate__c < System.today()) {
                        className = 'red';
                    }
                }
                when 'Completed' {
                    className = 'green';
                }
                when 'Aborted' {
                    className = 'red';
                }
                when else {
                    if(initiative.BLN_EndDate__c < System.today()) {
                        className = 'red';
                    } else {
                        className = 'yellow';
                    }
                }
            }
             
            intWrapList.add(new BLN_WrapperStore.InitiativeWrapper(String.valueOf(initiative.Id), initiative.Name, String.valueOf(initiative.BLN_StartDate__c), String.valueOf(initiative.BLN_EndDate__c), className));
        }
        
        return intWrapList;
    }
}