force-app/main/default/objects/BLN_ProductIdentifier__mdt/BLN_ProductIdentifier__mdt.object-meta.xml
<CustomObject>
    <label>Product Identifier</label>
    <pluralLabel>BLN_ProductIdentifiers</pluralLabel>
</CustomObject>

force-app/main/default/objects/BLN_ProductIdentifier__mdt/fields/BLN_CategoryCode__c.field-meta.xml
<CustomField>
    <fullName>BLN_CategoryCode__c</fullName>
    <label>Category Code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ProductIdentifier__mdt/fields/BLN_MatchingCriteria__c.field-meta.xml
<CustomField>
    <fullName>BLN_MatchingCriteria__c</fullName>
    <label>Matching Criteria</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Exact</fullName>
                <default>true</default>
                <label>Exact</label>
            </value>
            <value>
                <fullName>Partial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_ProductIdentifier__mdt/fields/BLN_Type__c.field-meta.xml
<CustomField>
    <fullName>BLN_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CHARGES</fullName>
                <default>true</default>
                <label>CHARGES</label>
            </value>
            <value>
                <fullName>WINDSCREEN</fullName>
            </value>
            <value>
                <fullName>BODY GLASS</fullName>
            </value>
            <value>
                <fullName>PRIME</fullName>
            </value>
            <value>
                <fullName>VAPS</fullName>
            </value>
            <value>
                <fullName>REPAIR</fullName>
            </value>
            <value>
                <fullName>HIDE ON UI</fullName>
            </value>
            <value>
                <fullName>EXCLUDE FOR APPOINTMENT</fullName>
            </value>
            <value>
                <fullName>STATIC</fullName>
            </value>
            <value>
                <fullName>DYNAMIC</fullName>
            </value>
            <value>
                <fullName>STATIC &amp; DYNAMIC</fullName>
            </value>
            <value>
                <fullName>SPECIALIST CALIBRATION REQUIRED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BLN_ProductIdentifierUtilityTest.cls
@isTest
public class BLN_ProductIdentifierUtilityTest {
@isTest
    static void getProductIndentifyTest(){           
        Set<String> productCodes = new Set<String>();
        String data = [SELECT BLN_CategoryCode__c, BLN_MatchingCriteria__c, BLN_Type__c FROM BLN_ProductIdentifier__mdt LIMIT 1].BLN_CategoryCode__c;
      
        productCodes.add(data);
        Test.startTest();
        BLN_ProductIdentifierUtility.getProductIndentify(System.Label.BLN_PRIME);
       
        Test.stopTest(); 
        System.assertNotEquals(data, null,'test');
    }
@isTest
    static void getAppointmentExcludedProductCodesTest(){
        Test.startTest();
        BLN_ProductIdentifierUtility.getAppointmentExcludedProductCodes();
       BLN_ProductIdentifierUtility.getRepairProduct();
        Test.stopTest(); 
        
    }
}