force-app/main/default/objects/BLN_AccountGroupRule__c/BLN_AccountGroupRule__c.object-meta.xml
<CustomObject>
    <label>Account Group Rule</label>
    <nameField>
        <label>Account Group Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Group Rules</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_AccountGroupRule__c/fields/BLN_ClientType__c.field-meta.xml
<CustomField>
    <fullName>BLN_ClientType__c</fullName>
    <label>Client Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ClientTypes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_AccountGroupRule__c/fields/BLN_CorporateType__c.field-meta.xml
<CustomField>
    <fullName>BLN_CorporateType__c</fullName>
    <description>FOUK-5765</description>
    <label>Corporate Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ClientTypes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/BLN_AccountRuleParameter__c.object-meta.xml
<CustomObject>
    <description>FOUK-1904</description>
    <label>Account Rule Parameter</label>
    <nameField>
        <displayFormat>ARP-{000000}</displayFormat>
        <label>Account Rule Parameter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Rule Parameters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_AccountRuleGroup__c.field-meta.xml
<CustomField>
    <fullName>BLN_AccountRuleGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Rule Group</label>
    <referenceTo>BLN_AccountGroupRule__c</referenceTo>
    <relationshipLabel>Account Rule Parameters</relationshipLabel>
    <relationshipName>Account_Rule_Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_Contract__c.field-meta.xml
<CustomField>
    <fullName>BLN_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>FOUK-6522 Optional relationship to Contract which defines this Account Rule Parameter.</description>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Account Rule Parameters</relationshipLabel>
    <relationshipName>Account_Rule_Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_InheritanceBehaviour__c.field-meta.xml
<CustomField>
    <fullName>BLN_InheritanceBehaviour__c</fullName>
    <label>Inheritance Behaviour</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lowest Level</fullName>
            </value>
            <value>
                <fullName>Sum</fullName>
            </value>
            <value>
                <fullName>Sum with Lowest Level Precedence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_InLineWithStandardSLA__c.field-meta.xml
<CustomField>
    <fullName>BLN_InLineWithStandardSLA__c</fullName>
    <defaultValue>false</defaultValue>
    <description>FOUK-6522 Field for checking if ARP is in line to Standard SLA</description>
    <label>In Line with Standard SLA?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_SLAApproved__c.field-meta.xml
<CustomField>
    <fullName>BLN_SLAApproved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>FOUK-6522 Field to check if SLA approved or not</description>
    <label>SLA Approved?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_SLAType__c.field-meta.xml
<CustomField>
    <fullName>BLN_SLAType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>FOUK-6522 Lookup field for SLA record types to SLA Definition custom object</description>
    <label>SLA Type</label>
    <referenceTo>BLN_SLADefinition__c</referenceTo>
    <relationshipLabel>Account Rule Parameters</relationshipLabel>
    <relationshipName>Account_Rule_Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_SplitBill__c.field-meta.xml
<CustomField>
    <fullName>BLN_SplitBill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Split Bill</label>
    <referenceTo>BLN_AccountRuleParameter__c</referenceTo>
    <relationshipLabel>Product Excesses</relationshipLabel>
    <relationshipName>Account_Rule_Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_ThresholdValue__c.field-meta.xml
<CustomField>
    <fullName>BLN_ThresholdValue__c</fullName>
    <description>FOUK-6522 Field on Account Rule Parameter to hold threshold value</description>
    <label>Threshold Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BLN_ARPInheritanceBehaviour__mdt/BLN_ARPInheritanceBehaviour__mdt.object-meta.xml
<CustomObject>
    <label>ARP Inheritance Behaviour</label>
    <pluralLabel>ARP Inheritance Behaviours</pluralLabel>
</CustomObject>

force-app/main/default/objects/BLN_ARPInheritanceBehaviour__mdt/fields/BLN_ARPRecordTypeName__c.field-meta.xml
<CustomField>
    <fullName>BLN_ARPRecordTypeName__c</fullName>
    <label>ARP RecordType Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ARPInheritanceBehaviour__mdt/fields/BLN_InheritanceBehaviour__c.field-meta.xml
<CustomField>
    <fullName>BLN_InheritanceBehaviour__c</fullName>
    <label>Inheritance Behaviour</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lowest Level</fullName>
                <default>true</default>
                <label>Lowest Level</label>
            </value>
            <value>
                <fullName>Sum</fullName>
            </value>
            <value>
                <fullName>Sum with Lowest Level Precedence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_SLADefinition__c/BLN_SLADefinition__c.object-meta.xml
<CustomObject>
    <description>FOUK-6522 New custom object to log all the Service Level Agreement (SLAs) agreed with clients at contract with associated Account   Legal Entity or Grouping level</description>
    <label>SLA Definition</label>
    <nameField>
        <label>SLA Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SLAs Definition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_SLADefinition__c/fields/BLN_ThresholdOperator__c.field-meta.xml
<CustomField>
    <fullName>BLN_ThresholdOperator__c</fullName>
    <label>Threshold Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Greater Than (&gt;)</fullName>
            </value>
            <value>
                <fullName>Lesser Than (&lt;)</fullName>
            </value>
            <value>
                <fullName>Equal (=)</fullName>
            </value>
            <value>
                <fullName>Greater Than or Equal (&gt;=)</fullName>
            </value>
            <value>
                <fullName>Lesser Than or Equal (&lt;=)</fullName>
            </value>
            <value>
                <fullName>blank</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/ClientTypes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Insurance</fullName>
        <label>Insurer</label>
    </customValue>
    <customValue>
        <fullName>Fleet National</fullName>
    </customValue>
    <customValue>
        <fullName>Fleet Local</fullName>
    </customValue>
    <customValue>
        <fullName>Lease</fullName>
    </customValue>
    <customValue>
        <fullName>Rental</fullName>
    </customValue>
    <customValue>
        <fullName>Trade/Commercial</fullName>
    </customValue>
    <customValue>
        <fullName>Wholesale</fullName>
    </customValue>
    <customValue>
        <fullName>Agent/Broker</fullName>
    </customValue>
    <customValue>
        <fullName>Intercompany</fullName>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <customValue>
        <fullName>Intermediary</fullName>
    </customValue>
    <customValue>
        <fullName>Fleet</fullName>
        <isActive>false</isActive>
        <label>Fleet</label>
    </customValue>
    <customValue>
        <fullName>Trade Client</fullName>
        <isActive>false</isActive>
        <label>Trade Client</label>
    </customValue>
    <masterLabel>Client Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BLN_AccountRuleParameterTriggerHandler.cls
/*****************************************
*ClassName : BLN_AccountRuleParameterTriggerHandler
*@description : FOUK-6076 fill Inheritance Behaviour from custom metadata
*CreatedDate: 11-03-2024
*CreatedBy : PwC-India
****************************************/
public with sharing class BLN_AccountRuleParameterTriggerHandler {
    public static void beforeInsert(List<BLN_AccountRuleParameter__c> arpList) {
        List<BLN_AccountRuleParameter__c> slAarpList = new List<BLN_AccountRuleParameter__c>();
        String arpRecordTypeIdSla = Schema.SObjectType.BLN_AccountRuleParameter__c.getRecordTypeInfosByName().get('SLA').getRecordTypeId();
        for(BLN_AccountRuleParameter__c arp : arpList) {
            if(arp.RecordTypeId == arpRecordTypeIdSla){
                slAarpList.add(arp);
            }
        }
        if(slAarpList != null && slAarpList.size() > 0){
            Set<Id> arpRecordTypeIdSet = new Set<Id>();
            Map<Id, String> arpRecordTypeMap = new Map<Id, String>();
            Map<String, String> arpIbMap = new Map<String, String>();
            
            // for(BLN_AccountRuleParameter__c arp : arpList) {
            for(BLN_AccountRuleParameter__c arp : slAarpList) {
                arpRecordTypeIdSet.add(arp.RecordTypeId);
            }
            
            for(RecordType rt : [SELECT Name FROM RecordType WHERE Id IN: arpRecordTypeIdSet WITH SECURITY_ENFORCED]) {
                arpRecordTypeMap.put(rt.Id, rt.Name);
            }
            
            for(BLN_ARPInheritanceBehaviour__mdt arpIbMtd : [SELECT Id, BLN_ARPRecordTypeName__c, BLN_InheritanceBehaviour__c 
                                                            FROM BLN_ARPInheritanceBehaviour__mdt 
                                                            WHERE BLN_ARPRecordTypeName__c IN: arpRecordTypeMap.values() WITH SECURITY_ENFORCED]) {
                                                                arpIbMap.put(arpIbMtd.BLN_ARPRecordTypeName__c, arpIbMtd.BLN_InheritanceBehaviour__c);
                                                            }
            
            for(BLN_AccountRuleParameter__c arp : arpList) {
                arp.BLN_InheritanceBehaviour__c = arpIbMap.get(arpRecordTypeMap.get(arp.RecordTypeId));
            }
            matchStandardSla(slAarpList, arpRecordTypeMap);
        }
    }
    
    public static void matchStandardSla(List<BLN_AccountRuleParameter__c> arpList, Map<Id, String> arpRecordTypeMap) {
        List<BLN_AccountRuleParameter__c> slaArpList = new List<BLN_AccountRuleParameter__c>();
        Set<Id> contractIdSet = new Set<Id>();
        Map<Id, String> contractClientTypeMap = new Map<Id, String>();
        
        for(BLN_AccountRuleParameter__c arp : arpList) {
            if(arpRecordTypeMap.get(arp.RecordTypeId) == BLN_AppConstants.RECORD_TYPE_SLA) {
                slaArpList.add(arp);
                contractIdSet.add(arp.BLN_Contract__c);
            }
        }
        
        for(Contract contractRec : [SELECT Id, Account.BLN_ClientType__c FROM Contract 
                                    WHERE Id IN: contractIdSet WITH SECURITY_ENFORCED]) {
                                        contractClientTypeMap.put(contractRec.Id, contractRec.Account.BLN_ClientType__c);
                                    }
                
        Map<String, List<BLN_AccountRuleParameter__c>> accRuleGrpMap = new Map<String, List<BLN_AccountRuleParameter__c>>();
        
        for(BLN_AccountGroupRule__c accRuleGrp : [SELECT Id, BLN_CorporateType__c, (SELECT Id, BLN_ThresholdValue__c, BLN_SLAType__c, BLN_SLAType__r.BLN_ThresholdOperator__c FROM Account_Rule_Parameters__r WHERE RecordType.Name =: BLN_AppConstants.RECORD_TYPE_SLA) 
                                                  FROM BLN_AccountGroupRule__c 
                                                  WHERE RecordType.Name =: BLN_AppConstants.RECORD_TYPE_CORPORATE_LEVEL 
                                                  AND BLN_CorporateType__c in: contractClientTypeMap.values() WITH SECURITY_ENFORCED ]) {
            if(accRuleGrpMap.get(accRuleGrp.BLN_CorporateType__c) == null) {
                accRuleGrpMap.put(accRuleGrp.BLN_CorporateType__c, new List<BLN_AccountRuleParameter__c>());
            }
                                                      List<BLN_AccountRuleParameter__c> tempArp = accRuleGrpMap.get(accRuleGrp.BLN_CorporateType__c);
                                                      tempArp.addAll(accRuleGrp.Account_Rule_Parameters__r);
            accRuleGrpMap.put(accRuleGrp.BLN_CorporateType__c, tempArp);
        }
        
        
        for(BLN_AccountRuleParameter__c arp : slaArpList) {
            if(arp.BLN_Contract__c != NULL && accRuleGrpMap.containsKey(contractClientTypeMap.get(arp.BLN_Contract__c))) {  
                String accountClientType = contractClientTypeMap.get(arp.BLN_Contract__c);
                for (BLN_AccountRuleParameter__c stndrdArp : accRuleGrpMap.get(accountClientType)) {
                    if(stndrdArp.BLN_SLAType__c == arp.BLN_SLAType__c) {
                        Boolean flag = false;
                        if(arp.BLN_ThresholdValue__c != null && stndrdArp.BLN_ThresholdValue__c != null) {
                            switch on stndrdArp.BLN_SLAType__r.BLN_ThresholdOperator__c {
                                when 'Greater Than (>)' {
                                    if(arp.BLN_ThresholdValue__c > stndrdArp.BLN_ThresholdValue__c) {
                                        flag = true;
                                    }
                                }
                                when 'Lesser Than (<)' {
                                    if(arp.BLN_ThresholdValue__c < stndrdArp.BLN_ThresholdValue__c) {
                                        flag = true;
                                    }
                                }
                                when 'Equal (=)' {
                                    if(arp.BLN_ThresholdValue__c == stndrdArp.BLN_ThresholdValue__c) {
                                        flag = true;
                                    }
                                }
                                when 'Greater Than or Equal (>=)' {
                                    if(arp.BLN_ThresholdValue__c >= stndrdArp.BLN_ThresholdValue__c) {
                                        flag = true;
                                    }
                                }
                                when 'Lesser Than or Equal (<=)' {
                                    if(arp.BLN_ThresholdValue__c <= stndrdArp.BLN_ThresholdValue__c) {
                                        flag = true;
                                    }
                                }
                            }
                        }
                        
                        if(flag == true) {
                            arp.BLN_SLAApproved__c = true;
                            arp.BLN_InLineWithStandardSLA__c = true;
                        } else {
                            arp.BLN_SLAApproved__c = false;
                            arp.BLN_InLineWithStandardSLA__c = false;
                        }
                    }
                }
            }    
        }
    }  
}