force-app/main/default/objects/BLN_AccountGroupRule__c/BLN_AccountGroupRule__c.object-meta.xml
<CustomObject>
    <label>Account Group Rule</label>
    <nameField>
        <label>Account Group Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Group Rules</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_AccountGroupRule__c/fields/BLN_ActiveFrom__c.field-meta.xml
<CustomField>
    <fullName>BLN_ActiveFrom__c</fullName>
    <description>FOUK-5765</description>
    <label>Active From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BLN_AccountGroupRule__c/fields/BLN_ActiveTo__c.field-meta.xml
<CustomField>
    <fullName>BLN_ActiveTo__c</fullName>
    <description>FOUK-5765</description>
    <label>Active To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BLN_AccountGroupRule__c/fields/BLN_ClientType__c.field-meta.xml
<CustomField>
    <fullName>BLN_ClientType__c</fullName>
    <label>Client Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ClientTypes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_AccountGroupRule__c/fields/BLN_CorporateType__c.field-meta.xml
<CustomField>
    <fullName>BLN_CorporateType__c</fullName>
    <description>FOUK-5765</description>
    <label>Corporate Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ClientTypes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/BLN_AccountRuleParameter__c.object-meta.xml
<CustomObject>
    <description>FOUK-1904</description>
    <label>Account Rule Parameter</label>
    <nameField>
        <displayFormat>ARP-{000000}</displayFormat>
        <label>Account Rule Parameter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Rule Parameters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_Account__c.field-meta.xml
<CustomField>
    <fullName>BLN_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Mandatory relationship to the Account to which Account rule parameter applies to.(FOUK-1904)</description>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Rule Parameters</relationshipLabel>
    <relationshipName>BLN_AccountRuleParameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_AccountRuleGroup__c.field-meta.xml
<CustomField>
    <fullName>BLN_AccountRuleGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Rule Group</label>
    <referenceTo>BLN_AccountGroupRule__c</referenceTo>
    <relationshipLabel>Account Rule Parameters</relationshipLabel>
    <relationshipName>Account_Rule_Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_ActiveFrom__c.field-meta.xml
<CustomField>
    <fullName>BLN_ActiveFrom__c</fullName>
    <description>Specifies validity date for Account Rule Parameter. This date will be set when Account Rule Parameter will be agreed. If data is not set - ARP is considered not activated. (FOUK-1904)</description>
    <label>Active From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_ActiveTo__c.field-meta.xml
<CustomField>
    <fullName>BLN_ActiveTo__c</fullName>
    <description>Specifies validity date for Account Rule Parameter. This date will be set when Account Rule Parameter will be agreed. If data is not set - ARP is considered not activated. (FOUK-1904)</description>
    <label>Active To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_Contract__c.field-meta.xml
<CustomField>
    <fullName>BLN_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>FOUK-6522 Optional relationship to Contract which defines this Account Rule Parameter.</description>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Account Rule Parameters</relationshipLabel>
    <relationshipName>Account_Rule_Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_InheritanceBehaviour__c.field-meta.xml
<CustomField>
    <fullName>BLN_InheritanceBehaviour__c</fullName>
    <label>Inheritance Behaviour</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lowest Level</fullName>
            </value>
            <value>
                <fullName>Sum</fullName>
            </value>
            <value>
                <fullName>Sum with Lowest Level Precedence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_InLineWithStandardSLA__c.field-meta.xml
<CustomField>
    <fullName>BLN_InLineWithStandardSLA__c</fullName>
    <defaultValue>false</defaultValue>
    <description>FOUK-6522 Field for checking if ARP is in line to Standard SLA</description>
    <label>In Line with Standard SLA?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_ProductCategory__c.field-meta.xml
<CustomField>
    <fullName>BLN_ProductCategory__c</fullName>
    <label>Product Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_SLAApproved__c.field-meta.xml
<CustomField>
    <fullName>BLN_SLAApproved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>FOUK-6522 Field to check if SLA approved or not</description>
    <label>SLA Approved?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_SLAType__c.field-meta.xml
<CustomField>
    <fullName>BLN_SLAType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>FOUK-6522 Lookup field for SLA record types to SLA Definition custom object</description>
    <label>SLA Type</label>
    <referenceTo>BLN_SLADefinition__c</referenceTo>
    <relationshipLabel>Account Rule Parameters</relationshipLabel>
    <relationshipName>Account_Rule_Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_ThresholdValue__c.field-meta.xml
<CustomField>
    <fullName>BLN_ThresholdValue__c</fullName>
    <description>FOUK-6522 Field on Account Rule Parameter to hold threshold value</description>
    <label>Threshold Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BLN_SLADefinition__c/BLN_SLADefinition__c.object-meta.xml
<CustomObject>
    <description>FOUK-6522 New custom object to log all the Service Level Agreement (SLAs) agreed with clients at contract with associated Account   Legal Entity or Grouping level</description>
    <label>SLA Definition</label>
    <nameField>
        <label>SLA Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SLAs Definition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_SLADefinition__c/fields/BLN_ThresholdOperator__c.field-meta.xml
<CustomField>
    <fullName>BLN_ThresholdOperator__c</fullName>
    <label>Threshold Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Greater Than (&gt;)</fullName>
            </value>
            <value>
                <fullName>Lesser Than (&lt;)</fullName>
            </value>
            <value>
                <fullName>Equal (=)</fullName>
            </value>
            <value>
                <fullName>Greater Than or Equal (&gt;=)</fullName>
            </value>
            <value>
                <fullName>Lesser Than or Equal (&lt;=)</fullName>
            </value>
            <value>
                <fullName>blank</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/ClientTypes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Insurance</fullName>
        <label>Insurer</label>
    </customValue>
    <customValue>
        <fullName>Fleet National</fullName>
    </customValue>
    <customValue>
        <fullName>Fleet Local</fullName>
    </customValue>
    <customValue>
        <fullName>Lease</fullName>
    </customValue>
    <customValue>
        <fullName>Rental</fullName>
    </customValue>
    <customValue>
        <fullName>Trade/Commercial</fullName>
    </customValue>
    <customValue>
        <fullName>Wholesale</fullName>
    </customValue>
    <customValue>
        <fullName>Agent/Broker</fullName>
    </customValue>
    <customValue>
        <fullName>Intercompany</fullName>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <customValue>
        <fullName>Intermediary</fullName>
    </customValue>
    <customValue>
        <fullName>Fleet</fullName>
        <isActive>false</isActive>
        <label>Fleet</label>
    </customValue>
    <customValue>
        <fullName>Trade Client</fullName>
        <isActive>false</isActive>
        <label>Trade Client</label>
    </customValue>
    <masterLabel>Client Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BLN_AccountRuleParameterHandlerTest.cls
/*****************************************
 *ClassName : BLN_AccountRuleParameterHandlerTest
 *@description : FOUK-6076 BLN_AccountRuleParameterHandlerTest Class used for testing BLN_AccountRuleParameterHandlerTest.
 *CreatedDate: 11-03-2024
 *CreatedBy : PwC-India
 ****************************************/
@IsTest
private class BLN_AccountRuleParameterHandlerTest {
    
    /**
     * @description: Test method for creating TestData using TestData Factory
     */
    @TestSetup
    static void createData() {
        Account acc = new Account(Name = 'Test Account', BLn_ClientType__c = 'Insurance');
        insert acc;
        
        Contract contrct = new Contract(AccountId = acc.Id);
        insert contrct;
        
        String agrRecordTypeId = Schema.SObjectType.BLN_AccountGroupRule__c.getRecordTypeInfosByName().get('Corporate Level').getRecordTypeId();
        BLN_AccountGroupRule__c agrRecord = new BLN_AccountGroupRule__c(BLN_ActiveFrom__c = Date.Today() - 1, BLN_ActiveTo__c = Date.Today(), 
                                                                  BLN_CorporateType__c = 'Insurance', Name = 'TestAccountRuleGroup',
                                                                  RecordTypeId = agrRecordTypeId);
        
        insert agrRecord;
        
        
        List<BLN_SLADefinition__c> slaDefinitionList = new List<BLN_SLADefinition__c>();
        slaDefinitionList.add(new BLN_SLADefinition__c(Name = 'test sla1 definition', BLN_ThresholdOperator__c = 'Greater Than (>)'));
        slaDefinitionList.add(new BLN_SLADefinition__c(Name = 'test sla2 definition', BLN_ThresholdOperator__c = 'Lesser Than (<)'));
        slaDefinitionList.add(new BLN_SLADefinition__c(Name = 'test sla3 definition', BLN_ThresholdOperator__c = 'Equal (=)'));
        slaDefinitionList.add(new BLN_SLADefinition__c(Name = 'test sla4 definition', BLN_ThresholdOperator__c = 'Greater Than or Equal (>=)'));
        slaDefinitionList.add(new BLN_SLADefinition__c(Name = 'test sla5 definition', BLN_ThresholdOperator__c = 'Lesser Than or Equal (<=)'));
        slaDefinitionList.add(new BLN_SLADefinition__c(Name = 'test sla6 definition', BLN_ThresholdOperator__c = 'Equal (=)'));
        insert slaDefinitionList;
        
        String arpRecordTypeId = Schema.SObjectType.BLN_AccountRuleParameter__c.getRecordTypeInfosByName().get('SLA').getRecordTypeId();
        BLN_AccountRuleParameter__c testArp1 = BLN_TestDataFactory.createAccountRuleParameter(acc.Id, arpRecordTypeId, Date.today(), Date.today());
        BLN_AccountRuleParameter__c testArp2 = BLN_TestDataFactory.createAccountRuleParameter(acc.Id, arpRecordTypeId, Date.today(), Date.today());
        BLN_AccountRuleParameter__c testArp3 = BLN_TestDataFactory.createAccountRuleParameter(acc.Id, arpRecordTypeId, Date.today(), Date.today());
        BLN_AccountRuleParameter__c testArp4 = BLN_TestDataFactory.createAccountRuleParameter(acc.Id, arpRecordTypeId, Date.today(), Date.today());
        BLN_AccountRuleParameter__c testArp5 = BLN_TestDataFactory.createAccountRuleParameter(acc.Id, arpRecordTypeId, Date.today(), Date.today());
        BLN_AccountRuleParameter__c testArp6 = BLN_TestDataFactory.createAccountRuleParameter(acc.Id, arpRecordTypeId, Date.today(), Date.today());
        
        testArp1.BLN_AccountRuleGroup__c = agrRecord.Id;
        testArp1.BLN_SLAType__c = slaDefinitionList[0].Id;
        testArp1.BLN_ThresholdValue__c = 40;
        testArp1.BLN_Contract__c = contrct.Id;
        
        testArp2.BLN_AccountRuleGroup__c = agrRecord.Id;
        testArp2.BLN_SLAType__c = slaDefinitionList[1].Id;
        testArp2.BLN_ThresholdValue__c = 40;
        testArp2.BLN_Contract__c = contrct.Id;

        
        testArp3.BLN_AccountRuleGroup__c = agrRecord.Id;
        testArp3.BLN_SLAType__c = slaDefinitionList[2].Id;
        testArp3.BLN_ThresholdValue__c = 40;
        testArp3.BLN_Contract__c = contrct.Id;

        
        testArp4.BLN_AccountRuleGroup__c = agrRecord.Id;
        testArp4.BLN_SLAType__c = slaDefinitionList[3].Id;
        testArp4.BLN_ThresholdValue__c = 40;
        testArp4.BLN_Contract__c = contrct.Id;

        
        testArp5.BLN_AccountRuleGroup__c = agrRecord.Id;
        testArp5.BLN_SLAType__c = slaDefinitionList[4].Id;
        testArp5.BLN_ThresholdValue__c = 40;
        testArp5.BLN_Contract__c = contrct.Id;

        
        testArp6.BLN_AccountRuleGroup__c = agrRecord.Id;
        testArp6.BLN_SLAType__c = slaDefinitionList[5].Id;
        testArp6.BLN_ThresholdValue__c = 40;
        testArp6.BLN_Contract__c = contrct.Id;

        
        List<BLN_AccountRuleParameter__c> arpList = new List<BLN_AccountRuleParameter__c>();
		arpList.add(testArp1); 
        arpList.add(testArp2); 
        arpList.add(testArp3); 
        arpList.add(testArp4); 
        arpList.add(testArp5); 
        arpList.add(testArp6);
        insert arpList;
    }
    
    /**
     * @description: Test method for testing auto populating Inheritance Behaviour
     */    
	@IsTest
    static void autoPopulateInheritanceBehaviourTest() {
        String arpRecordTypeId = Schema.SObjectType.BLN_AccountRuleParameter__c.getRecordTypeInfosByName().get('Authorization Limit').getRecordTypeId();
        
        Account acc = [SELECT Id FROM Account LIMIT 1];
        BLN_AccountRuleParameter__c arp = new BLN_AccountRuleParameter__c(BLN_Account__c = acc.Id, RecordTypeId = arpRecordTypeId, BLN_ProductCategory__c = 'test Product');
        
        Test.startTest(); // Begin test context, where the batch can run once
        insert arp;
        Test.stopTest(); // End test context, which processes any asynchronous behavior like batch jobs
        
        arp = [SELECT BLN_InheritanceBehaviour__c FROM BLN_AccountRuleParameter__c WHERE Id =: arp.Id LIMIT 1];  
       // System.assertEquals(arp.BLN_InheritanceBehaviour__c, 'Lowest Level', 'Inheritance Behaviour should be Lowest Level as per metadata');
    }

    
    /**
     * @description: Test method for matching standard SLA (Greater Than scenario)
     */    
    @IsTest
    static void matchStandardSlaTestGreaterThan() {
        String arpRecordTypeId = Schema.SObjectType.BLN_AccountRuleParameter__c.getRecordTypeInfosByName().get('SLA').getRecordTypeId();
        Id contractId = [SELECt Id FROM Contract LIMIT 1].Id;
        Id accId = [SELECT Id FROM Account LIMIT 1].Id;
        
        BLN_SLADefinition__c slaDefinition = [SELECT Id FROM BLN_SLADefinition__c WHERE Name = 'test sla1 definition' LIMIT 1];
        
        BLN_AccountRuleParameter__c arp = new BLN_AccountRuleParameter__c(BLN_Account__c = accId, RecordTypeId = arpRecordTypeId, BLN_ProductCategory__c = 'test Product', BLN_Contract__c = contractId);
        arp.BLN_SLAType__c = slaDefinition.id;
        arp.BLN_ThresholdValue__c = 50;
        insert arp;
        
        arp = [SELECT BLN_SLAApproved__c, BLN_InLineWithStandardSLA__c FROM BLN_AccountRuleParameter__c WHERE Id =: arp.Id LIMIT 1];
        
     //   System.assertEquals(arp.BLN_InLineWithStandardSLA__c, true, 'In line with standard SLA sould be true');
     //   System.assertEquals(arp.BLN_SLAApproved__c, true, 'SLA approved sould be true');
    }
    
    /**
     * @description: Test method for matching standard SLA (Less Than scenario)
     */    
    @IsTest
    static void matchStandardSlaTestLessThan() {
        String arpRecordTypeId = Schema.SObjectType.BLN_AccountRuleParameter__c.getRecordTypeInfosByName().get('SLA').getRecordTypeId();
        Id contractId = [SELECt Id FROM Contract LIMIT 1].Id;
        Id accId = [SELECT Id FROM Account LIMIT 1].Id;
        
        BLN_SLADefinition__c slaDefinition = [SELECT Id FROM BLN_SLADefinition__c WHERE Name = 'test sla2 definition' LIMIT 1];
        
        BLN_AccountRuleParameter__c arp = new BLN_AccountRuleParameter__c(BLN_Account__c = accId, RecordTypeId = arpRecordTypeId, BLN_ProductCategory__c = 'test Product', BLN_Contract__c = contractId);
        arp.BLN_SLAType__c = slaDefinition.id;
        arp.BLN_ThresholdValue__c = 30;
        insert arp;
        
        arp = [SELECT BLN_SLAApproved__c, BLN_InLineWithStandardSLA__c FROM BLN_AccountRuleParameter__c WHERE Id =: arp.Id LIMIT 1];
        
      //  System.assertEquals(arp.BLN_InLineWithStandardSLA__c, true, 'In line with standard SLA sould be true');
      //  System.assertEquals(arp.BLN_SLAApproved__c, true, 'SLA approved sould be true');
    }
    
    /**
     * @description: Test method for matching standard SLA (Equal scenario)
     */
    @IsTest
    static void matchStandardSlaTestEqual() {
        String arpRecordTypeId = Schema.SObjectType.BLN_AccountRuleParameter__c.getRecordTypeInfosByName().get('SLA').getRecordTypeId();
        Id contractId = [SELECt Id FROM Contract LIMIT 1].Id;
        Id accId = [SELECT Id FROM Account LIMIT 1].Id;
        
        BLN_SLADefinition__c slaDefinition = [SELECT Id FROM BLN_SLADefinition__c WHERE Name = 'test sla3 definition' LIMIT 1];
        
        BLN_AccountRuleParameter__c arp = new BLN_AccountRuleParameter__c(BLN_Account__c = accId, RecordTypeId = arpRecordTypeId, BLN_ProductCategory__c = 'test Product', BLN_Contract__c = contractId);
        arp.BLN_SLAType__c = slaDefinition.id;
        arp.BLN_ThresholdValue__c = 40;
        insert arp;
        
        arp = [SELECT BLN_SLAApproved__c, BLN_InLineWithStandardSLA__c FROM BLN_AccountRuleParameter__c WHERE Id =: arp.Id LIMIT 1];
     
      //  System.assertEquals(arp.BLN_InLineWithStandardSLA__c, true, 'In line with standard SLA sould be true');
       // System.assertEquals(arp.BLN_SLAApproved__c, true, 'SLA approved sould be true');
    }
    
    /**
     * @description: Test method for matching standard SLA (Greater Than or Equal scenario)
     */    
    @IsTest
    static void matchStandardSlaTestGreaterThanEqual() {
        String arpRecordTypeId = Schema.SObjectType.BLN_AccountRuleParameter__c.getRecordTypeInfosByName().get('SLA').getRecordTypeId();
        Id contractId = [SELECt Id FROM Contract LIMIT 1].Id;
        Id accId = [SELECT Id FROM Account LIMIT 1].Id;
        
        BLN_SLADefinition__c slaDefinition = [SELECT Id FROM BLN_SLADefinition__c WHERE Name = 'test sla4 definition' LIMIT 1];
        
        BLN_AccountRuleParameter__c arp = new BLN_AccountRuleParameter__c(BLN_Account__c = accId, RecordTypeId = arpRecordTypeId, BLN_ProductCategory__c = 'test Product', BLN_Contract__c = contractId);
        arp.BLN_SLAType__c = slaDefinition.id;
        arp.BLN_ThresholdValue__c = 40;
        insert arp;
        
        arp = [SELECT BLN_SLAApproved__c, BLN_InLineWithStandardSLA__c FROM BLN_AccountRuleParameter__c WHERE Id =: arp.Id LIMIT 1];
        
      //  System.assertEquals(arp.BLN_InLineWithStandardSLA__c, true, 'In line with standard SLA sould be true');
      //  System.assertEquals(arp.BLN_SLAApproved__c, true, 'SLA approved sould be true');
    }
    
    /**
     * @description: Test method for matching standard SLA (Less Than or Equal scenario)
     */    
    @IsTest
    static void matchStandardSlaTestLessThanEqual() {
        String arpRecordTypeId = Schema.SObjectType.BLN_AccountRuleParameter__c.getRecordTypeInfosByName().get('SLA').getRecordTypeId();
        Id contractId = [SELECt Id FROM Contract LIMIT 1].Id;
        Id accId = [SELECT Id FROM Account LIMIT 1].Id;
        
        BLN_SLADefinition__c slaDefinition = [SELECT Id FROM BLN_SLADefinition__c WHERE Name = 'test sla5 definition' LIMIT 1];
        
        BLN_AccountRuleParameter__c arp = new BLN_AccountRuleParameter__c(BLN_Account__c = accId, RecordTypeId = arpRecordTypeId, BLN_ProductCategory__c = 'test Product', BLN_Contract__c = contractId);
        arp.BLN_SLAType__c = slaDefinition.id;
        arp.BLN_ThresholdValue__c = 30;
        insert arp;
        
        arp = [SELECT BLN_SLAApproved__c, BLN_InLineWithStandardSLA__c FROM BLN_AccountRuleParameter__c WHERE Id =: arp.Id LIMIT 1];
        
      //  System.assertEquals(arp.BLN_InLineWithStandardSLA__c, true, 'In line with standard SLA sould be true');
      //  System.assertEquals(arp.BLN_SLAApproved__c, true, 'SLA approved sould be true');
    }
    
    /**
     * @description: Test method for matching standard SLA (Blank scenario)
     */    
    @IsTest
    static void matchStandardSlaTestBlank() {
        String arpRecordTypeId = Schema.SObjectType.BLN_AccountRuleParameter__c.getRecordTypeInfosByName().get('SLA').getRecordTypeId();
        Id contractId = [SELECt Id FROM Contract LIMIT 1].Id;
        Id accId = [SELECT Id FROM Account LIMIT 1].Id;
        
        BLN_SLADefinition__c slaDefinition = [SELECT Id FROM BLN_SLADefinition__c WHERE Name = 'test sla6 definition' LIMIT 1];
        
        BLN_AccountRuleParameter__c arp = new BLN_AccountRuleParameter__c(BLN_Account__c = accId, RecordTypeId = arpRecordTypeId, BLN_ProductCategory__c = 'test Product', BLN_Contract__c = contractId);
        arp.BLN_SLAType__c = slaDefinition.id;
        arp.BLN_ThresholdValue__c = 30;
        insert arp;
        
        arp = [SELECT BLN_SLAApproved__c, BLN_InLineWithStandardSLA__c FROM BLN_AccountRuleParameter__c WHERE Id =: arp.Id LIMIT 1];
        
       // System.assertEquals(arp.BLN_InLineWithStandardSLA__c, false, 'In line with standard SLA sould be true');
        //System.assertEquals(arp.BLN_SLAApproved__c, false, 'SLA approved sould be true');
    }
}