force-app/main/default/objects/BLN_AccountGroupRule__c/BLN_AccountGroupRule__c.object-meta.xml
<CustomObject>
    <label>Account Group Rule</label>
    <nameField>
        <label>Account Group Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Group Rules</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_AccountGroupRule__c/fields/BLN_ActiveFrom__c.field-meta.xml
<CustomField>
    <fullName>BLN_ActiveFrom__c</fullName>
    <description>FOUK-5765</description>
    <label>Active From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BLN_AccountGroupRule__c/fields/BLN_ActiveTo__c.field-meta.xml
<CustomField>
    <fullName>BLN_ActiveTo__c</fullName>
    <description>FOUK-5765</description>
    <label>Active To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BLN_AccountGroupRule__c/fields/BLN_ClientType__c.field-meta.xml
<CustomField>
    <fullName>BLN_ClientType__c</fullName>
    <label>Client Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ClientTypes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_AccountGroupRule__c/fields/BLN_CorporateType__c.field-meta.xml
<CustomField>
    <fullName>BLN_CorporateType__c</fullName>
    <description>FOUK-5765</description>
    <label>Corporate Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ClientTypes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_AccountGroupRule__c/fields/BLN_IsActive__c.field-meta.xml
<CustomField>
    <fullName>BLN_IsActive__c</fullName>
    <description>FOUK-5765</description>
    <formula>AND(
    TODAY() &lt;=  BLN_ActiveTo__c ,
    TODAY() &gt;=  BLN_ActiveFrom__c 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/BLN_AccountRuleParameter__c.object-meta.xml
<CustomObject>
    <description>FOUK-1904</description>
    <label>Account Rule Parameter</label>
    <nameField>
        <displayFormat>ARP-{000000}</displayFormat>
        <label>Account Rule Parameter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Rule Parameters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_Account__c.field-meta.xml
<CustomField>
    <fullName>BLN_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Mandatory relationship to the Account to which Account rule parameter applies to.(FOUK-1904)</description>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Rule Parameters</relationshipLabel>
    <relationshipName>BLN_AccountRuleParameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_AccountRuleGroup__c.field-meta.xml
<CustomField>
    <fullName>BLN_AccountRuleGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Rule Group</label>
    <referenceTo>BLN_AccountGroupRule__c</referenceTo>
    <relationshipLabel>Account Rule Parameters</relationshipLabel>
    <relationshipName>Account_Rule_Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_ActiveFrom__c.field-meta.xml
<CustomField>
    <fullName>BLN_ActiveFrom__c</fullName>
    <description>Specifies validity date for Account Rule Parameter. This date will be set when Account Rule Parameter will be agreed. If data is not set - ARP is considered not activated. (FOUK-1904)</description>
    <label>Active From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_ActiveTo__c.field-meta.xml
<CustomField>
    <fullName>BLN_ActiveTo__c</fullName>
    <description>Specifies validity date for Account Rule Parameter. This date will be set when Account Rule Parameter will be agreed. If data is not set - ARP is considered not activated. (FOUK-1904)</description>
    <label>Active To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_InheritanceBehaviour__c.field-meta.xml
<CustomField>
    <fullName>BLN_InheritanceBehaviour__c</fullName>
    <label>Inheritance Behaviour</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lowest Level</fullName>
            </value>
            <value>
                <fullName>Sum</fullName>
            </value>
            <value>
                <fullName>Sum with Lowest Level Precedence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_IsActive__c.field-meta.xml
<CustomField>
    <fullName>BLN_IsActive__c</fullName>
    <description>- checkbox=True when (Today is &lt;=Active To) and (Today&gt;=Active From). 
- checkbox=True when Active To &amp; Active From = null

Calculated field - not to be mapped into MDM</description>
    <formula>OR (
  AND (
    TODAY() &gt;= BLN_ActiveFrom__c,
    TODAY() &lt;= BLN_ActiveTo__c
  ),
  AND (
     ISBLANK(BLN_ActiveFrom__c),
     ISBLANK(BLN_ActiveTo__c) 
  ),
  AND (
   
    TODAY() &gt;= BLN_ActiveFrom__c, 
    ISBLANK(BLN_ActiveTo__c)
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_ParameterUsageInstruction__c.field-meta.xml
<CustomField>
    <fullName>BLN_ParameterUsageInstruction__c</fullName>
    <description>Description field for storing additional instructions to be added by Sales Team member when configuring Account Rule Parameter. This instructions can be used by CSR or other actor when applying the rule. Example: In OE rule additional contractual terms and conditions needs to be set (for example around vehicle age, if this is leased vehicle etc). (FOUK-1904)</description>
    <label>Parameter Usage Instruction</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BLN_ARPInheritanceBehaviour__mdt/BLN_ARPInheritanceBehaviour__mdt.object-meta.xml
<CustomObject>
    <label>ARP Inheritance Behaviour</label>
    <pluralLabel>ARP Inheritance Behaviours</pluralLabel>
</CustomObject>

force-app/main/default/objects/BLN_ARPInheritanceBehaviour__mdt/fields/BLN_ARPRecordTypeName__c.field-meta.xml
<CustomField>
    <fullName>BLN_ARPRecordTypeName__c</fullName>
    <label>ARP RecordType Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ARPInheritanceBehaviour__mdt/fields/BLN_FieldList__c.field-meta.xml
<CustomField>
    <fullName>BLN_FieldList__c</fullName>
    <description>Add Fields API Names, separated by comma(,)</description>
    <label>Field List</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BLN_ARPInheritanceBehaviour__mdt/fields/BLN_InheritanceBehaviour__c.field-meta.xml
<CustomField>
    <fullName>BLN_InheritanceBehaviour__c</fullName>
    <label>Inheritance Behaviour</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lowest Level</fullName>
                <default>true</default>
                <label>Lowest Level</label>
            </value>
            <value>
                <fullName>Sum</fullName>
            </value>
            <value>
                <fullName>Sum with Lowest Level Precedence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/ClientTypes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Insurance</fullName>
        <label>Insurer</label>
    </customValue>
    <customValue>
        <fullName>Fleet National</fullName>
    </customValue>
    <customValue>
        <fullName>Fleet Local</fullName>
    </customValue>
    <customValue>
        <fullName>Lease</fullName>
    </customValue>
    <customValue>
        <fullName>Rental</fullName>
    </customValue>
    <customValue>
        <fullName>Trade/Commercial</fullName>
    </customValue>
    <customValue>
        <fullName>Wholesale</fullName>
    </customValue>
    <customValue>
        <fullName>Agent/Broker</fullName>
    </customValue>
    <customValue>
        <fullName>Intercompany</fullName>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <customValue>
        <fullName>Intermediary</fullName>
    </customValue>
    <customValue>
        <fullName>Fleet</fullName>
        <isActive>false</isActive>
        <label>Fleet</label>
    </customValue>
    <customValue>
        <fullName>Trade Client</fullName>
        <isActive>false</isActive>
        <label>Trade Client</label>
    </customValue>
    <masterLabel>Client Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BLN_AccountRuleParameterUtil.cls
/*****************************************
*ClassName : BLN_AccountRuleParameterUtil
*@description : FOUK-5297 retrieve Account Rules Parameters within CRM
*CreatedDate: 19-01-2023
*CreatedBy : PwC-India
****************************************/
public with sharing class BLN_AccountRuleParameterUtil{
    /*MethodName : getAccountRuleParameters
	*@description: Retrieves Account Rule Parameters based on Account ID, Account Rule Parameter Record Type, and Date of the job.
    *@param :  Parameters:
     *     - accountId (Id): The ID of the Account.
     *     - arpRecordType (String): The RecordType.Name of the Account Rule Parameter.
     *     - jobDate (Date): The Date of the job.
    *@return List<BLN_AccountRuleParameter__c>
    ****************************************/
    @AuraEnabled //Made this method @AuraEnabled as a part of FOUK-3801
    
    public static List<BLN_AccountRuleParameter__c> getAccountRuleParameters(String arpRecordType, Id accountId, Date jobDate) {
        List<Id> allHierachyAccountList = new List<Id>();
        String fieldToQuery = 'Id, BLN_Account__c, BLN_IsActive__c, BLN_ActiveFrom__c, BLN_ActiveTo__c, BLN_ParameterUsageInstruction__c, RecordType.Name';
        List<BLN_AccountRuleParameter__c> accountRuleParameters = new List<BLN_AccountRuleParameter__c>();
        
        try {
            if(String.isEmpty(accountId)) {
               throw new BLN_CustomException(BLN_AppConstants.ACCOUNT_ID_MISSING);
           }
            
            BLN_ARPInheritanceBehaviour__mdt arpIbMtd = [SELECT Id, MasterLabel, BLN_InheritanceBehaviour__c, BLN_FieldList__c 
                                                          FROM BLN_ARPInheritanceBehaviour__mdt 
                                                          WHERE BLN_ARPRecordTypeName__c =: arpRecordType WITH SECURITY_ENFORCED];
            fieldToQuery += arpIbMtd.BLN_FieldList__c != null ? ', ' + arpIbMtd.BLN_FieldList__c : '';
            
            Account acc = [SELECT Id, ParentId, Parent.ParentId, BLN_Level__c, BLN_ClientType__c, Parent.BLN_Level__c, Parent.Parent.BLN_Level__c, Parent.BLN_ClientType__c
                           FROM Account
                           WHERE Id =: accountId
                           AND BLN_Status__c !=: BLN_AppConstants.STATUS_CLOSED
                           AND (RecordType.Name =: BLN_AppConstants.RECORD_TYPE_B2B OR RecordType.Name =: BLN_AppConstants.RECORD_TYPE_REFERRAL) WITH SECURITY_ENFORCED];
            
            //if (acc == null) {
                //throw new BLN_CustomException(BLN_AppConstants.ACCOUNT_BRANCH_UNAVAILABLE);
            //}
            
            String clientType = (acc.BLN_Level__c == BLN_AppConstants.SITE_ACCOUNT) ? acc.Parent.BLN_ClientType__c : acc.BLN_ClientType__c;

            List<BLN_AccountGroupRule__c> accRuleGrp = [SELECT Id FROM BLN_AccountGroupRule__c 
                                                            WHERE RecordType.Name =: BLN_AppConstants.RECORD_TYPE_CORPORATE_LEVEL 
                                                            AND BLN_CorporateType__c =: clientType WITH SECURITY_ENFORCED];
            
            if(arpIbMtd.BLN_InheritanceBehaviour__c == BLN_AppConstants.INHERITANCE_BEHAVIOUR_SUM || arpIbMtd.BLN_InheritanceBehaviour__c == BLN_AppConstants.INHERITANCE_BEHAVIOUR_SUM_LOWEST_LEVEL) {
                allHierachyAccountList.add(acc.Id);
                
                if(acc.ParentId != null) {
                    allHierachyAccountList.add(acc.ParentId);
                }
                
                if(acc.ParentId != null && acc.Parent.ParentId != null) {
                    allHierachyAccountList.add(acc.Parent.ParentId);
                }
                
                accountRuleParameters = queryAccountRuleParam(fieldToQuery, allHierachyAccountList, accRuleGrp, arpRecordType, jobDate);
                
            } else if(arpIbMtd.BLN_InheritanceBehaviour__c == BLN_AppConstants.INHERITANCE_BEHAVIOUR_LOWEST_LEVEL) {
                accountRuleParameters = queryAccountRuleParam(fieldToQuery, new List<Id> { accountId }, null, arpRecordType, jobDate);
                
                if(accountRuleParameters.IsEmpty() && acc.ParentId != null) {
                    accountRuleParameters = queryAccountRuleParam(fieldToQuery, new List<Id> { acc.ParentId }, null, arpRecordType, jobDate);
                }
                
                if(accountRuleParameters.IsEmpty() && acc.ParentId != null && acc.Parent.ParentId != null) {
                    accountRuleParameters = queryAccountRuleParam(fieldToQuery, new List<Id> { acc.Parent.ParentId }, null, arpRecordType, jobDate);
                }
                
                if(accountRuleParameters.IsEmpty()) {
                    accountRuleParameters = queryAccountRuleParam(fieldToQuery, null, accRuleGrp, arpRecordType, jobDate);
                }
            }
            
            // if (accountRuleParameters.isEmpty()) {
            //     // Handle scenario where no ARPs are found for the defined input args
            //     throw new BLN_CustomException(System.Label.Error_Message_No_ARP);
            // }
            
        } catch (Exception e) {
            BLN_ExceptionLogger.captureException(e);
        }
        system.debug('accountRuleParameters'+accountRuleParameters);
        return accountRuleParameters.size() > 0 ? accountRuleParameters : null;
    }
    
    public static List<BLN_AccountRuleParameter__c> queryAccountRuleParam(String fieldToQuery, List<id> allHierachyAccountList, List<BLN_AccountGroupRule__c> accRuleGrp, String arpRecordType, Date jobDate) {
        Integer recordLimit = 0;
      
        // String whereClause = 'RecordType.Name =: arpRecordType AND BLN_ActiveFrom__c <=: jobDate AND BLN_ActiveTo__c >=: jobDate';
        String whereClause = 'RecordType.Name =: arpRecordType AND BLN_ActiveFrom__c <=: jobDate AND BLN_IsActive__c = true';
        
        if(allHierachyAccountList != null && accRuleGrp != null) {
            whereClause += ' AND (BLN_Account__c IN: allHierachyAccountList OR BLN_AccountRuleGroup__c IN: accRuleGrp)';
        } else if(allHierachyAccountList != null) {
            whereClause += ' AND BLN_Account__c IN: allHierachyAccountList';
        } else {
            whereClause += ' AND BLN_AccountRuleGroup__c IN: accRuleGrp';
        }

        String query = makeDynamicQuery(fieldToQuery, 'BLN_AccountRuleParameter__c', whereClause, recordLimit);
        return System.Database.query(query);
    }
    
    public static String makeDynamicQuery(String fieldsToQuery, String objectAPIName, String whereClause, Integer recordLimit) {
        String query = 'SELECT ' + fieldsToQuery + ' FROM ' + objectAPIName;
        query += whereClause != null ? ' WHERE ' + whereClause : '';
        query += recordLimit > 0 ? ' LIMIT ' + recordLimit : '';
        query += ' WITH SECURITY_ENFORCED';
        
        return query;
    }
    
    // Custom exception class
    public class BLN_CustomException extends Exception {}
}