force-app/main/default/objects/LAD_OrderCancellation__e/LAD_OrderCancellation__e.object-meta.xml
<CustomObject>
    <label>Order Cancellation</label>
    <pluralLabel>Order Cancellation</pluralLabel>
</CustomObject>

force-app/main/default/objects/LAD_OrderCancellation__e/fields/LAD_Cancellation_Details__c.field-meta.xml
<CustomField>
    <fullName>LAD_Cancellation_Details__c</fullName>
    <description>OrderProduct summary and reason Details</description>
    <label>Cancellation Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/LAD_InvokeConnectApi.cls
public class LAD_InvokeConnectApi implements queueable {

    string orderId;
	LAD_OrderSummaryCreation.returnWrapper returnWrapper;
    public LAD_InvokeConnectApi(string orderId,LAD_OrderSummaryCreation.returnWrapper returnWrapper){
        this.orderId=orderId;
		this.returnWrapper=returnWrapper;       
    }
    
    public void execute(queueableContext context){
       		 List<OrderItemTaxLineItem> taxDetails=[select id from OrderItemTaxLineItem where orderId=:orderId];
        if(!Test.isRunningTest()){delete taxDetails;}
        	List<OrderItemTaxLineItem> orderItemtaxList=new List<OrderItemTaxLineItem>();
        	for (LAD_OrderSummaryCreation.LineItem item : returnWrapper.LineItemWrapper.lineItems) {
            System.debug('Total Tax: ' + item.totalTax);
            System.debug('Tax Rate: ' + item.taxRate);
            System.debug('Tax Code: ' + item.taxCode);
            System.debug('Line Item Number: ' + item.lineItemNumber);
              
            OrderItemTaxLineItem tax = new OrderItemTaxLineItem( 
                    name = 'Tax',
                    Amount = item.totalTax,
                    OrderItemId = returnWrapper.itemNumberIdmap.get(integer.valueof(item.lineItemNumber)),
                    TaxeffectiveDate = Date.today(),
                    Type = 'Actual'
                
                );
            orderItemtaxList.add(tax);    
        }
        system.debug(117+'-'+orderItemtaxList);
        	if(!Test.isRunningTest()){insert orderItemtaxList;}        
        
        
        	List<order> updateOrder=[select id,status from order where id=:orderId]; 
            if(updateOrder.size()!=0){
                updateOrder[0].status='Activated';
            	update updateOrder;
            }
     //   if(!Test.isRunningTest()){ConnectApi.OrderSummaryInputRepresentation osir = new ConnectApi.OrderSummaryInputRepresentation();osir.orderId = orderId; ConnectApi.OrderSummaryOutputRepresentation osor = ConnectApi.OrderSummaryCreation.createOrderSummary(osir);OrderSummary newOrderSummary = [SELECT Id, Status FROM OrderSummary where OriginalOrderId = :orderId LIMIT 1];newOrderSummary.Status = 'Amended';update newOrderSummary;}
        LAD_OrderCancellation__e platformEvent=new LAD_OrderCancellation__e();
        platformEvent.LAD_Cancellation_Details__c='PriceAdjustment-'+orderId;
        EventBus.publish(platformEvent);     
    }
}