force-app/main/default/objects/BLN_ResourceAbsenceTypeMapping__mdt/BLN_ResourceAbsenceTypeMapping__mdt.object-meta.xml
<CustomObject>
    <label>Resource Absence Type Mapping</label>
    <pluralLabel>Resource Absence Type Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/BLN_ResourceAbsenceTypeMapping__mdt/fields/BLN_KronosReason__c.field-meta.xml
<CustomField>
    <fullName>BLN_KronosReason__c</fullName>
    <description>Paycodes incoming from Kronos</description>
    <label>Kronos Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ResourceAbsenceTypeMapping__mdt/fields/BLN_SFReason__c.field-meta.xml
<CustomField>
    <fullName>BLN_SFReason__c</fullName>
    <description>Salesforce absence reason</description>
    <label>SF Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BLN_ResourceAbsenceTriggerHelper.cls
/**
 * Created by gciesielsk001 on 28.03.2024.
 */

public with sharing class BLN_ResourceAbsenceTriggerHelper {

    public static void mapResourceAbsence(List<ResourceAbsence> lstResourceAbsences) {

        List<ResourceAbsence> rAbsencesToMap = new List<ResourceAbsence>();

        for (ResourceAbsence rAbsence : lstResourceAbsences) {
            if (rAbsence.BLN_ItemID__c != null) {
                rAbsencesToMap.add(rAbsence);
            }
        }

        if (!rAbsencesToMap.isEmpty()) {
            Map<String, String> mapOfAbsenceTypes = new Map<String, String>();
            List<BLN_ResourceAbsenceTypeMapping__mdt> absenceTypes = [
                    SELECT
                            Id,
                            BLN_KronosReason__c,
                            BLN_SFReason__c
                    FROM
                            BLN_ResourceAbsenceTypeMapping__mdt
                    WITH SECURITY_ENFORCED
            ];

            for (BLN_ResourceAbsenceTypeMapping__mdt aType : absenceTypes) {
                mapOfAbsenceTypes.put(aType.BLN_KronosReason__c, aType.BLN_SFReason__c);
            }

            for (ResourceAbsence rAbsence : rAbsencesToMap) {
                if (mapOfAbsenceTypes.containsKey(rAbsence.Type)) {
                    rAbsence.Type = mapOfAbsenceTypes.get(rAbsence.Type);
                }
            }
        }
    }
}