force-app/main/default/objects/BLN_RecalibrationJobCard__c/BLN_RecalibrationJobCard__c.object-meta.xml
<CustomObject>
    <description>FOUK-3892</description>
    <label>Recalibration Job Card</label>
    <nameField>
        <displayFormat>RJC-{00000}</displayFormat>
        <label>Recalibration Job Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recalibration Job Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_RecalibrationJobCard__c/fields/BLN_Product__c.field-meta.xml
<CustomField>
    <fullName>BLN_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>FOUK-3892</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Recalibration Job Cards</relationshipLabel>
    <relationshipName>BLN_RecalibrationJobCards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BLN_RecalibrationJobCard__c/fields/BLN_SortOrder__c.field-meta.xml
<CustomField>
    <fullName>BLN_SortOrder__c</fullName>
    <description>FOUK-3892</description>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BLN_RecalibrationJobCard__c/fields/BLN_TaskName__c.field-meta.xml
<CustomField>
    <fullName>BLN_TaskName__c</fullName>
    <description>FOUK-3892</description>
    <label>Task Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Vehicle__c/BLN_Vehicle__c.object-meta.xml
<CustomObject>
    <description>FOUK-495 This object is created for storing the Vehicles.</description>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{00000000}</displayFormat>
        <label>Vehicle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_Vehicle__c/fields/BLN_MakeOfVehicle__c.field-meta.xml
<CustomField>
    <fullName>BLN_MakeOfVehicle__c</fullName>
    <description>FOUK-116--&gt; This field is created for make of vehicle details.</description>
    <label>Make Of Vehicle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Vehicle__c/fields/BLN_ModelOfVehicle__c.field-meta.xml
<CustomField>
    <fullName>BLN_ModelOfVehicle__c</fullName>
    <description>FOUK-116--&gt; This field is created for model of vehicle .</description>
    <label>Model Of Vehicle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Vehicle__c/fields/BLN_VehicleRegNumber__c.field-meta.xml
<CustomField>
    <fullName>BLN_VehicleRegNumber__c</fullName>
    <description>Fouk-109 To store vehicle registeration number.</description>
    <label>Vehicle Registration Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Vehicle__c/fields/BLN_VIN__c.field-meta.xml
<CustomField>
    <fullName>BLN_VIN__c</fullName>
    <description>FOUK-495 This field is used to store vehicle identification number</description>
    <label>VIN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BLN_SendBoschJobCardBatchTest.cls
/**@description : This is the Apex Test class for the Apex Classes BLN_SendBoschJobCardBatch And BLN_SendBoschJobCard
*  @author: PwC India
*  @Story: FOUK-5582
*  @CreatedDate: 13/03/2024
*/
@isTest
public class BLN_SendBoschJobCardBatchTest {
    
    /**
* @description Sets up test data for the test methods
*/
    @TestSetup
    static void setupTestData() {
        
        WorkType workType = BLN_TestDataFactory.createWorkType('Replacement', 1.0, true, true);
        WorkOrder workOrder = BLN_TestDataFactory.createWorkOrder(false);
        workOrder.status = 'Completed';
        insert workOrder;
        
        WorkOrderLineItem wOLI = new WorkOrderLineItem();
        wOLI.WorkTypeId = worktype.Id;
        wOLI.WorkOrderId = workOrder.id;
        wOLI.status = 'Completed';
        wOLI.BLN_IsStockCheckInCompleted__c = false;
        insert wOLI;  
        
        ServiceAppointment servApp = BLN_TestDataFactory.createServiceAppntmnt('Replacement', True);
        servApp.BLN_WorkOrderLineItem__c = wOLI.Id;
        servApp.WorkTypeId = workType.Id;
        servApp.BLN_WorkOrderNumber__c = workOrder.Id;
        servApp.ArrivalWindowStartTime = System.now().addhours(1);
        update servApp;
        
        Product2 prod1 = BLN_TestDataFactory.createTestProduct();
        insert prod1;
        
        ProductRequired prRq = new ProductRequired();
        prRq.Product2Id = prod1.Id;
        prRq.BLN_ProductRequiredTitle__c = 'Test PR';
        prRq.BLN_WorkOrder__c = servApp.BLN_WorkOrderNumber__c;
        prRq.BLN_WOLI__c = servApp.BLN_WorkOrderLineItem__c;
        prRq.ParentRecordId = servApp.BLN_WorkOrderLineItem__c;
        insert prRq;        
        
        BLN_RecalibrationJobCard__c recal1 = new BLN_RecalibrationJobCard__c();
        BLN_RecalibrationJobCard__c recal2 = new BLN_RecalibrationJobCard__c();
        
        recal1.BLN_SortOrder__c = 1;
        recal2.BLN_SortOrder__c = 2;
        recal1.BLN_TaskName__c = 'Task1';
        recal2.BLN_TaskName__c = 'Task2';
        recal1.BLN_Product__c = prod1.Id;
        recal2.BLN_Product__c = prod1.Id;
        insert recal1;
        insert recal2;        
        
    }
    
    /*
    *@description: This method is used to test execute method.
    *return : void
    */
    @isTest
    static void testCallout() {     
        
        ServiceAppointment saRecord = new ServiceAppointment();
        
        List<ServiceAppointment> serviceAppointList = new List<ServiceAppointment>();
        serviceAppointList.add(saRecord);
        List<ServiceAppointment> sAList2 = [Select Id, BLN_WorkOrderLineItem__c, BLN_Vehicle__c, BLN_Vehicle__r.BLN_VehicleRegNumber__c , BLN_Vehicle__r.BLN_MakeOfVehicle__c, BLN_Vehicle__r.BLN_ModelOfVehicle__c, BLN_Vehicle__r.BLN_VIN__c, AccountId, Account.FirstName, Account.LastName, BLN_IsBoschJobCardSent__c from ServiceAppointment];
        Id sAId = [Select Id from ServiceAppointment limit 1].id;
        List<Id> sAList = new List<Id>();
        sAList.add(sAId);
        // Set up mock HTTP callout
        Test.setMock(HttpCalloutMock.class, new BLN_MockHttpResponseHTTPCallOutToOkta());
        Test.startTest();
        BLN_SendBoschJobCard.sendBoschJobCardFromFlow(sAList);
        System.enqueueJob(new BLN_SendBoschJobCard(sAList2, null, true));
        Test.stopTest();
        System.assertEquals(1, serviceAppointList.size(), 'Appointment Should be only 1');
    }

    /*
    *@description: This method is used to test execute method.
    *return : void
    */
    @isTest
    static void testBatchexcution() {     
        // Set up mock HTTP callout
        Test.setMock(HttpCalloutMock.class, new BLN_MockHttpResponseHTTPCallOutToOkta());
        Test.startTest();
            integer batchSize = 200;
            BLN_SendBoschJobCardBatch p = new BLN_SendBoschJobCardBatch();
            Id batch = Database.executeBatch(p,batchSize);
        Test.stopTest();
        AsyncApexJob job = [SELECT Status FROM AsyncApexJob Where ID = :batch];
        System.assertNotEquals(job, null, 'Test');
    }
}