force-app/main/default/objects/BLN_AppointmentShorteningConfiguration__mdt/BLN_AppointmentShorteningConfiguration__mdt.object-meta.xml
<CustomObject>
    <description>This holds configuration for Appointment Shortening for different Business Units</description>
    <label>AppointmentShorteningConfiguration</label>
    <pluralLabel>AppointmentShorteningConfigurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/BLN_AppointmentShorteningConfiguration__mdt/fields/BLN_Active__c.field-meta.xml
<CustomField>
    <fullName>BLN_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>FOUK-777</description>
    <inlineHelpText>Activate this configuration</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BLN_AppointmentShorteningConfiguration__mdt/fields/BLN_AllowVirtualTech__c.field-meta.xml
<CustomField>
    <fullName>BLN_AllowVirtualTech__c</fullName>
    <defaultValue>false</defaultValue>
    <description>FOUK-777To include Virtual Technicians or not</description>
    <inlineHelpText>To include Virtual Technicians or not</inlineHelpText>
    <label>Allow Virtual Technicians</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BLN_AppointmentShorteningConfiguration__mdt/fields/BLN_ArrivalStartTimeAdjustmentInMinutes__c.field-meta.xml
<CustomField>
    <fullName>BLN_ArrivalStartTimeAdjustmentInMinutes__c</fullName>
    <description>FOUK-777Time to be subtracted from Arrival Window Start in minutes</description>
    <inlineHelpText>Time to be subtracted from Arrival Start in minuteseg if Arr Start is 10:30and Time off is 30 mins, so new Arr Start will be 10:00</inlineHelpText>
    <label>Arrival Start Time Adjustment (In Minute</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BLN_AppointmentShorteningConfiguration__mdt/fields/BLN_HorizonInHours__c.field-meta.xml
<CustomField>
    <fullName>BLN_HorizonInHours__c</fullName>
    <description>FOUK-777
Horizon in hours</description>
    <inlineHelpText>Next upcomming appointments time frame
e.g 48 hrs means all upcomming appointments in next 48hrs</inlineHelpText>
    <label>Horizon in Hours</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BLN_AppointmentShorteningConfiguration__mdt/fields/BLN_MaxPlnDurationInMins__c.field-meta.xml
<CustomField>
    <fullName>BLN_MaxPlnDurationInMins__c</fullName>
    <description>FOUK-777
Max allowed Planned Duration</description>
    <label>Max Planned Duration  in Minutes</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BLN_AppointmentShorteningConfiguration__mdt/fields/BLN_MaxSchDurationInMins__c.field-meta.xml
<CustomField>
    <fullName>BLN_MaxSchDurationInMins__c</fullName>
    <description>FOUK-777
Max allowed Scheduled Duration</description>
    <label>Max Scheduled Duration in Minutes</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BLN_AppointmentShorteningConfiguration__mdt/fields/BLN_RoundedDurationInMinutes__c.field-meta.xml
<CustomField>
    <fullName>BLN_RoundedDurationInMinutes__c</fullName>
    <description>FOUK-777
Round Down time in minutes</description>
    <inlineHelpText>Round to nearest time in multiples of given number. e.g if time is 1:34, should be round down to 1:30</inlineHelpText>
    <label>Rounded Duration (In Minutes)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BLN_AppointmentShorteningConfiguration__mdt/fields/BLN_ShorteningWindowInMinutes__c.field-meta.xml
<CustomField>
    <fullName>BLN_ShorteningWindowInMinutes__c</fullName>
    <description>FOUK-777Time to be added to Due Date</description>
    <inlineHelpText>Time to be added to Due Dateeg Due Date is 15:00 and Time added is 180, so new Due Date is 18:00</inlineHelpText>
    <label>Shortening Window</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BLN_AppointmentShorteningServiceBatch.cls
/**@description : This batch class handle the service appointments to be dispatched to their assigned technician.
*  @author: Shubbh ArorA
*  @Story: FOUK-777
*  @CreatedDate: 07/03/2024
*/

public class BLN_AppointmentShorteningServiceBatch implements Database.Batchable<sObject>, Schedulable{
    public static DateTime currentDateTime = System.now();
    public static DateTime currentDateTimeWithHorizon;
    public static Integer durationInMinutes;
    public static Integer fslDurationInMinutes;
    Set<String> excludedWorkTypes = new Set<String>{System.label.BLN_Assist, System.label.BLN_StockCollect};
    
    public Database.QueryLocator start(Database.BatchableContext batchableContext){
        String query = queryFormation();
        if(query != System.label.BLN_InactiveMetadata){
            return Database.getQueryLocator(query);
        }
        else{
             return null;
        }
    }

    public void execute(Database.BatchableContext batchableContext, List<ServiceAppointment> saList){
        DateTime newArrivalStart;
        DateTime newArrivalEnd;
        DateTime newDueDate;
        Integer arrivalStartTimeFromMetadata;
        Integer roundedDurationFromMetadata;
        Integer shortningWindowFromMetadata;
        List<ServiceAppointment> updatedSAList = new List<ServiceAppointment>();

        BLN_AppointmentShorteningConfiguration__mdt appShortningConfigMetadata = new BLN_AppointmentShorteningConfiguration__mdt();
        appShortningConfigMetadata = BLN_HandlerWebservice.getServAppShortningConfigMetadata();
        if(saList.size() > 0 && saList != null){
            for(ServiceAppointment eachServApp: saList){				
                arrivalStartTimeFromMetadata = appShortningConfigMetadata.BLN_ArrivalStartTimeAdjustmentInMinutes__c != null ? Integer.valueOf(appShortningConfigMetadata.BLN_ArrivalStartTimeAdjustmentInMinutes__c) : 0;
                roundedDurationFromMetadata = appShortningConfigMetadata.BLN_RoundedDurationInMinutes__c != null ? Integer.valueOf(appShortningConfigMetadata.BLN_RoundedDurationInMinutes__c) : 0;
                shortningWindowFromMetadata = appShortningConfigMetadata.BLN_ShorteningWindowInMinutes__c != null ? Integer.valueOf(appShortningConfigMetadata.BLN_ShorteningWindowInMinutes__c) : 0;
                    
                newArrivalStart = eachServApp.SchedStartTime.addMinutes(-arrivalStartTimeFromMetadata);
                newArrivalStart = roundOffTime(newArrivalStart, roundedDurationFromMetadata);

                newArrivalStart = newArrivalStart < eachServApp.ArrivalWindowStartTime ? eachServApp.ArrivalWindowStartTime : newArrivalStart;

                newDueDate = newArrivalStart.addMinutes(shortningWindowFromMetadata);

                newDueDate = newDueDate > eachServApp.DueDate ? eachServApp.DueDate : newDueDate;

                newArrivalEnd = newDueDate.addMinutes(-Integer.valueOf(eachServApp.DurationInMinutes));

                eachServApp.ArrivalWindowStartTime = newArrivalStart;
                eachServApp.DueDate = newDueDate;
                eachServApp.ArrivalWindowEndTime = newArrivalEnd;

                eachServApp.BLN_IsAppointementShortened__c = True;
                eachServApp.BLN_AppointmentShorteningDateTime__c = System.now();

                updatedSAList.add(eachServApp);
            }
        }
        if(updatedSAList.size() > 0 && Schema.sObjectType.ServiceAppointment.isUpdateable()){
            DATABASE.update(updatedSAList, FALSE);
        }
    }

    public void finish(Database.BatchableContext batchableContext){
        try{
            AsyncApexJob job = new AsyncApexJob();
            job = [SELECT Id, JobType, ApexClassId, Status, NumberOfErrors, MethodName, CompletedDate FROM AsyncApexJob WHERE Id =: BatchableContext.getJobId()];
        } catch (Exception e) {
            BLN_ExceptionLogger.captureException(e);
        }
    }

    public void execute(SchedulableContext ctx) {
        integer batchSize = 200;
        BLN_AppointmentShorteningServiceBatch appShortningBatch = new BLN_AppointmentShorteningServiceBatch();
        database.executeBatch(appShortningBatch, batchSize);
    }

    public static String queryFormation(){
        String virtualTech;
        Boolean virtualTechFlag;
        Integer horizon;

        BLN_AppointmentShorteningConfiguration__mdt appShortningConfigMetadata = getAppShortningMetadata();
        durationInMinutes = appShortningConfigMetadata.BLN_MaxPlnDurationInMins__c != null ? Integer.valueOf(appShortningConfigMetadata.BLN_MaxPlnDurationInMins__c) : 0;
        fslDurationInMinutes = appShortningConfigMetadata.BLN_MaxSchDurationInMins__c != null ? Integer.valueOf(appShortningConfigMetadata.BLN_MaxSchDurationInMins__c) : 0;

        if(appShortningConfigMetadata.BLN_Active__c == True){
            virtualTechFlag = appShortningConfigMetadata.BLN_AllowVirtualTech__c;
            horizon = appShortningConfigMetadata.BLN_HorizonInHours__c != null ? Integer.valueOf(appShortningConfigMetadata.BLN_HorizonInHours__c) : 0;
            currentDateTimeWithHorizon = currentDateTime.addHours(horizon);
            if(virtualTechFlag == False){
                virtualTech = ' AND BLN_AssignedServiceResource__r.BLN_Type__c != \'' + System.label.BLN_VirtualTech + '\' ';
            }
            else{
                virtualTech = ' ';
            }
            String query = 'SELECT Id, ArrivalWindowStartTime, ArrivalWindowEndTime, SchedStartTime, SchedEndTime, DueDate, DurationInMinutes, FSL__Duration_In_Minutes__c FROM ServiceAppointment WHERE (Status = \'Dispatched\' OR Status = \'Scheduled\') ' + 
            'AND BLN_IsForcedAppointment__c = False AND BLN_IsAppointementShortened__c = False AND ServiceTerritory.BLN_EnableAppointmentShortening__c = True' + virtualTech + 'AND SchedStartTime >=: currentDateTime AND SchedStartTime <=: currentDateTimeWithHorizon ' +
            'AND DurationInMinutes <=: durationInMinutes AND FSL__Duration_In_Minutes__c <=: fslDurationInMinutes AND WorkType.Name NOT IN : excludedWorkTypes ' + 
            'WITH SECURITY_ENFORCED';
            return query;
        }
        else{
            return System.label.BLN_InactiveMetadata;
        }
    }

    public static BLN_AppointmentShorteningConfiguration__mdt getAppShortningMetadata(){
        BLN_AppointmentShorteningConfiguration__mdt appShortningConfigMetadata = new BLN_AppointmentShorteningConfiguration__mdt();
        appShortningConfigMetadata = BLN_HandlerWebservice.getServAppShortningConfigMetadata();
        return appShortningConfigMetadata;
    }
    
    public static DateTime roundOffTime(DateTime arrivalWindowStartTime, Integer roundDownTime){
        Integer rOff = roundDownTime;
        Time timeValue = arrivalWindowStartTime.time();
        Integer remainder = Math.mod((timeValue.hour() * 60 + timeValue.minute()), rOff);
        Integer roundedMinutes = ((timeValue.hour() * 60 + timeValue.minute()) - remainder);
        if(remainder >= rOff / 2){
            roundedMinutes += rOff;
        }
        Integer roundedHours = roundedMinutes / 60;
        roundedMinutes -= roundedHours*60;
        Time roundedTime = Time.newInstance(roundedHours, roundedMinutes, 0, 0);
        DateTime roundedDateTime = DateTime.newInstance(arrivalWindowStartTime.dateGmt(), roundedTime);
        return roundedDateTime;
    }

}