force-app/main/default/objects/BLN_TriggerSetting__mdt/BLN_TriggerSetting__mdt.object-meta.xml
<CustomObject>
    <description>Trigger Metadata used for all triggers</description>
    <label>Trigger Setting</label>
    <pluralLabel>Trigger Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/BLN_TriggerSetting__mdt/fields/BLN_Active__c.field-meta.xml
<CustomField>
    <fullName>BLN_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BLN_TriggerSetting__mdt/fields/BLN_AfterDelete__c.field-meta.xml
<CustomField>
    <fullName>BLN_AfterDelete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BLN_TriggerSetting__mdt/fields/BLN_AfterInsert__c.field-meta.xml
<CustomField>
    <fullName>BLN_AfterInsert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BLN_TriggerSetting__mdt/fields/BLN_AfterUndelete__c.field-meta.xml
<CustomField>
    <fullName>BLN_AfterUndelete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Undelete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BLN_TriggerSetting__mdt/fields/BLN_AfterUpdate__c.field-meta.xml
<CustomField>
    <fullName>BLN_AfterUpdate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BLN_TriggerSetting__mdt/fields/BLN_BeforeDelete__c.field-meta.xml
<CustomField>
    <fullName>BLN_BeforeDelete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Before Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BLN_TriggerSetting__mdt/fields/BLN_BeforeInsert__c.field-meta.xml
<CustomField>
    <fullName>BLN_BeforeInsert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Before Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BLN_TriggerSetting__mdt/fields/BLN_BeforeUpdate__c.field-meta.xml
<CustomField>
    <fullName>BLN_BeforeUpdate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Before Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BLN_TriggerSetting__mdt/fields/BLN_Object__c.field-meta.xml
<CustomField>
    <fullName>BLN_Object__c</fullName>
    <label>Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BLN_TriggerDispatcher.cls
/** @description : Trigger Dispatcher
*   @author: Rahul Jain(PwC IN)
*    @CreatedDate: 21/06/2024
*/
public with sharing class BLN_TriggerDispatcher {
   public static void dispatch(BLN_TriggerInterface handler, System.TriggerOperation triggerEvent, String objName) {
       if (handler.stopDispatch()) {
           return;
       }
       BLN_TriggerSetting__mdt tsMdt = getTriggerSetting(objName);
       if (tsMdt != null && tsMdt.BLN_Active__c) {
           handleTriggerEvent(handler, triggerEvent, tsMdt);
       }
   }
   private static BLN_TriggerSetting__mdt getTriggerSetting(String objName) {
       List<BLN_TriggerSetting__mdt> mdtList = [
           SELECT BLN_Active__c, BLN_BeforeUpdate__c,BLN_AfterInsert__c,BLN_AfterUpdate__c,BLN_BeforeInsert__c, BLN_BeforeDelete__c, BLN_AfterDelete__c,BLN_AfterUndelete__c
           FROM BLN_TriggerSetting__mdt
           WHERE BLN_Object__c = :objName WITH SECURITY_ENFORCED
       ];
       if (!mdtList.isEmpty()) {
           return mdtList[0];
       }
       return null;
   } 
   private static void handleTriggerEvent(BLN_TriggerInterface handler, System.TriggerOperation triggerEvent, BLN_TriggerSetting__mdt tsMdt) {
       switch on triggerEvent {

            when BEFORE_INSERT { 
                If (tsMdt.BLN_BeforeInsert__c){handler.beforeInsert(Trigger.New);}
            }
            //5167
            when AFTER_INSERT {
                If (tsMdt.BLN_AfterInsert__c){ 
                    handler.afterInsert(Trigger.New,Trigger.newMap);
                }
            }
        
           when BEFORE_UPDATE {
               if (tsMdt.BLN_BeforeUpdate__c) {
                   handler.beforeUpdate(Trigger.New, Trigger.OldMap);
               }
           }

            when AFTER_UPDATE {
                If (tsMdt.BLN_AfterUpdate__c){
                    handler.afterUpdate(Trigger.New,Trigger.oldMap);
                }
            }

            when BEFORE_DELETE {
                If (tsMdt.BLN_BeforeDelete__c){
                    handler.beforeDelete(Trigger.old,Trigger.oldMap);
                }
            }
            when AFTER_DELETE {
                    If (tsMdt.BLN_AfterDelete__c){ 
                        handler.afterDelete(Trigger.old,Trigger.oldMap);
                    }
            }
            when AFTER_UNDELETE {                        
                    If (tsMdt.BLN_AfterUndelete__c){
                        handler.afterUnDelete(Trigger.new,trigger.newMap);
                    }
 }
           // when AFTER_INSERT { ... }
           // when BEFORE_DELETE { ... }
           // when AFTER_DELETE { ... }
       }
   }
}