force-app/main/default/objects/LAD_MDC_Preference__c/LAD_MDC_Preference__c.object-meta.xml
<CustomObject>
    <description>Transactional / Setup Object
- Will be used to store the MDC selected for given Product, in order to
reflect it later on Cart Item
- Introduction of this Object will allow to leverage OOTBfunctionalitiesof
B2B Commerce
- Recordsof this object will be created automatically, won&apos;t have any
impact on External or Internal Users experience
- After journey is finalized - the records will be automatically removed
from the system, as they&apos;ll be no longer needed</description>
    <label>MDC Preference</label>
    <nameField>
        <displayFormat>MDC-{0000}</displayFormat>
        <label>MDC Pre Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MDC Preference</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LAD_MDC_Preference__c/fields/LAD_Account__c.field-meta.xml
<CustomField>
    <fullName>LAD_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>MDC Preference</relationshipLabel>
    <relationshipName>MDC_Preference_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LAD_MDC_Preference__c/fields/LAD_Associated_Location__c.field-meta.xml
<CustomField>
    <fullName>LAD_Associated_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated Location</label>
    <referenceTo>AssociatedLocation</referenceTo>
    <relationshipLabel>MDC Preference</relationshipLabel>
    <relationshipName>MDC_Preference_AssociatedLocation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LAD_MDC_Preference__c/fields/LAD_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>LAD_Delivery_Date__c</fullName>
    <label>Delivery Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LAD_MDC_Preference__c/fields/LAD_Product__c.field-meta.xml
<CustomField>
    <fullName>LAD_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>MDC Preference</relationshipLabel>
    <relationshipName>MDC_Preference_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LAD_MDC_Preference__c/fields/LAD_User__c.field-meta.xml
<CustomField>
    <fullName>LAD_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MDC_Preference</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LAD_FetchTaxDetailsTest.cls
/**
* @description       : Test Class for LAD_FetchTaxDetails
* @author            : Prajjawal Tiwari
* @group             : B2B Commerce - Belron
* @last modified on  : 06-11-2024
* @last modified by  : Prajjawal Tiwari
**/

@isTest
private class LAD_FetchTaxDetailsTest {

    @TestSetup
    static void makeData(){
        Account testAccount = new Account(Name = 'ABC Corp'); // add more fields based on your org validation 
        insert testAccount;
        Contact testContact = New Contact(LastName = 'Test', AccountID = testAccount.id);
        insert testContact;
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Customer Community Login User' LIMIT 1];
        user testUser = New User(UserName = 'test_' + math.random() + '@test.com',
                                 FirstName = 'Test-First',
                                 LastName = 'Test-Last',
                                 Alias = 'test',
                                 email = 'test' + math.random() + '@test.com',
                                 CommunityNickName = string.valueOf(math.random()).substring(0,6),
                                 ProfileID = p.id,
                                 ContactId = testContact.Id,
                                 TimeZoneSidKey = 'America/New_York', 
                                 LocaleSidKey = 'en_US', 
                                 EmailEncodingKey = 'UTF-8', 
                                 LanguageLocaleKey = 'en_US');
        insert testUser; 
        
        Schema.location loc= new Schema.location();
        loc.Name = 'test';
        loc.LocationType = 'WAREHOUSE';
        loc.BLN_GUID__c = 'L31_UK';
        insert loc;
        
        
        AssociatedLocation testAssociatedLocation = new AssociatedLocation(LocationId = loc.id,
                                                                           LAD_Location_Type__c = 'Primary',
                                                                           ParentRecordId = testAccount.Id);
        insert testAssociatedLocation;
        
        Product2 testProduct = new Product2(Name = 'Test Product');
        insert testProduct;
        
        WebStore testStore = new WebStore(Name = 'test Store',
                                          OptionsAutoFacetingEnabled = true,
                                          OptionsCartToOrderAutoCustomFieldMapping = true,	
                                          OptionsCommerceEinsteinActivitiesTracked = true,	                                             
                                          OptionsCommerceEinsteinDeployed = true,	
                                          OptionsGuestBrowsingEnabled = true,	                                             
                                          OptionsSkipAdditionalEntitlementCheckForSearch = true);
        insert testStore;
        WebCart testCart = new WebCart (Name = 'TestCart', WebStoreId = testStore.id, AccountId = testAccount.id);
        insert testCart;
        
        OrderDeliveryMethod testDelMethod = new OrderDeliveryMethod(name = 'TestMethod', isActive = true);
        insert testDelMethod;
        
        CartDeliveryGroup testGroup = new CartDeliveryGroup(Name = 'TestGroup', CartId = testCart.id, DeliveryMethodId = testDelMethod.Id);
        insert testGroup;
        
        String deliveryDate = Date.today().addDays(7).format();
        LAD_MDC_Preference__c mdcPreference = new LAD_MDC_Preference__c();
        mdcPreference.LAD_Account__c = testAccount.Id;
        mdcPreference.LAD_Delivery_Date__c = deliveryDate;
        mdcPreference.LAD_Associated_Location__c = testAssociatedLocation.Id;
        
        
        mdcPreference.LAD_Product__c = testProduct.id;
        
        
        mdcPreference.LAD_User__c = testUser.id;
        
        insert mdcPreference;
        CartItem testItem = new CartItem(Name = 'TestItem', 
                                         Product2id = testProduct.id,
                                         Quantity = 10,
                                         CartDeliveryGroupId = testGroup.id, 
                                         CartId = testCart.id,
                                        TotalPriceAfterAllAdjustments=100);
        insert testItem;
         Set<Id> idSet = new Set<Id>();
        idSet.add(testItem.id);
        Test.setMock(HttpCalloutMock.class, new LAD_FetchTaxDetailsMock());
        Test.startTest();
        LAD_FetchTaxDetails.getTaxInfo(idSet);
                  
		List<CartTax> exitingTax=[select id from carttax];
        system.assertequals(0,exitingTax.size());
        Test.stopTest();


    }

    @isTest
    static void getTaxInfoTest() {
        Id itemId = [SELECT Id FROM CartItem WHERE Name = 'TestItem' LIMIT 1].Id;
        List<LAD_FetchTaxDetails.LineItem> wrapperList=new List<LAD_FetchTaxDetails.LineItem>();
                LAD_FetchTaxDetails.LineItem wrapperitem=new  LAD_FetchTaxDetails.LineItem();
				wrapperitem.totaltax=10;
        wrapperList.add(wrapperitem);
       LAD_FetchTaxDetails.LineItemWrapper wrapper=new  LAD_FetchTaxDetails.LineItemWrapper();
       wrapper.lineItems=wrapperList;
    }
    
    
    @isTest
    static void returnBearerTokensTest(){
         Test.setMock(HttpCalloutMock.class, new LAD_FetchTaxDetailsMockOcta());
        Test.startTest();
        LAD_FetchTaxDetails.returnBearerTokens();
                  

        Test.stopTest();
    }
}