force-app/main/default/objects/LAD_MDC_Preference__c/LAD_MDC_Preference__c.object-meta.xml
<CustomObject>
    <description>Transactional / Setup Object
- Will be used to store the MDC selected for given Product, in order to
reflect it later on Cart Item
- Introduction of this Object will allow to leverage OOTBfunctionalitiesof
B2B Commerce
- Recordsof this object will be created automatically, won&apos;t have any
impact on External or Internal Users experience
- After journey is finalized - the records will be automatically removed
from the system, as they&apos;ll be no longer needed</description>
    <label>MDC Preference</label>
    <nameField>
        <displayFormat>MDC-{0000}</displayFormat>
        <label>MDC Pre Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MDC Preference</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LAD_MDC_Preference__c/fields/LAD_Cartitem__c.field-meta.xml
<CustomField>
    <fullName>LAD_Cartitem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CartItem</label>
    <referenceTo>CartItem</referenceTo>
    <relationshipLabel>MDC Preference</relationshipLabel>
    <relationshipName>MDC_Preference</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LAD_webCartTriggerHandler.cls
public with sharing class LAD_webCartTriggerHandler {
    public static Boolean isFirstTime = true;

    public static void clearMDCPreferenceRecords(List<WebCart> webCarts) {
        system.debug('isfirstime>>'+isFirstTime);
        List<Id> cartIds = new List<Id>();
        for(WebCart c: webCarts){
             cartIds.add(c.Id);
        }
        system.debug('cart Ids updated>>>'+cartIds);
        
        List<WebCart> c = [SELECT Id, Status, (SELECT Id, Product2Id FROM CartItems) FROM WebCart WHERE Id IN :cartIds];
        system.debug('cart>>'+c);
        List<CartItem> ci = new List<CartItem>();
        List<Id> ciIds = new List<Id>();
        List<LAD_MDC_Preference__c> clearMDCList = new List<LAD_MDC_Preference__c>();

        try{
            for(WebCart i:c){
                if(i.Status=='Closed' || i.Status=='PendingClosed' || i.Status == 'PendingDelete'){
                    ci.addAll(i.CartItems);
                }
            }
            system.debug('cart items>>'+ci);

            if(ci.size()>0){
                for(CartItem i:ci){
                    ciIds.add(i.Id);
                }
            
                clearMDCList = [SELECT Id FROM LAD_MDC_Preference__c WHERE LAD_Cartitem__c in :ciIds];
                system.debug('clearMDCList>>'+clearMDCList);
                Database.DeleteResult[] result = Database.delete(clearMDCList);
                system.debug('deletion status>>>'+result);

            }

        }catch (Exception e) {
            // Handling the exceptions and log an error message
            BLN_ExceptionLogger.captureException(e);
        }
    }
}