force-app/main/default/objects/BLN_VehicleType__c/BLN_VehicleType__c.object-meta.xml
<CustomObject>
    <description>FOUK-1176 This object is used to store vehicle type information.</description>
    <label>Vehicle Type</label>
    <nameField>
        <displayFormat>VT-{00000000}</displayFormat>
        <label>Vehicle Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_VehicleType__c/fields/BLN_BodyType__c.field-meta.xml
<CustomField>
    <fullName>BLN_BodyType__c</fullName>
    <description>FOUK-1176 This field is used to store body type of the vehicle type</description>
    <label>Body Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_VehicleType__c/fields/BLN_Make__c.field-meta.xml
<CustomField>
    <fullName>BLN_Make__c</fullName>
    <description>FOUK-1167 This field is used to store make of the vehicle type.</description>
    <label>Make</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_VehicleType__c/fields/BLN_Model__c.field-meta.xml
<CustomField>
    <fullName>BLN_Model__c</fullName>
    <description>FOUK-1176 This field is used to store model of the vehicle type.</description>
    <label>Model</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_VehicleType__c/fields/BLN_MVRIS__c.field-meta.xml
<CustomField>
    <fullName>BLN_MVRIS__c</fullName>
    <description>FOUK-1176 This field is used to store MVRIS of the vehicle type.</description>
    <label>MVRIS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_VehicleType__c/fields/BLN_Year__c.field-meta.xml
<CustomField>
    <fullName>BLN_Year__c</fullName>
    <description>FOUK-1176 This field is used to store year the vehicle type was registered.</description>
    <label>Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LAD_FetchVehicleType.cls
/** @description :  LAD_FetchVehicleType
*/
public with sharing class LAD_FetchVehicleType {
    //fetchByChars method
    @AuraEnabled
    public static List<VehicleWrapper> fetchByChars(){
        try {
            List<BLN_VehicleType__c> vehTypes = [SELECT Id, Name, BLN_BodyType__c, BLN_Make__c, BLN_Model__c, BLN_Year__c, BLN_MVRIS__c FROM BLN_VehicleType__c WITH SECURITY_ENFORCED];
            List<VehicleWrapper> wrapperList = new List<VehicleWrapper>(); 
            for(BLN_VehicleType__c veh : vehTypes){
                VehicleWrapper wrap = new VehicleWrapper();
                wrap.mvris = veh.BLN_MVRIS__c;
                wrap.make = veh.BLN_Make__c;
                wrap.model = veh.BLN_Model__c;
                wrap.body = veh.BLN_BodyType__c;
                wrap.year = veh.BLN_Year__c;

                wrapperList.add(wrap);
            }

            return wrapperList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

     //Wrapper Class for Vehicle Type
     public class VehicleWrapper{
         //mvris
        @auraenabled public String mvris {get;set;}
         //make
        @auraenabled public String make {get;set;}
         //model
        @auraenabled public String model {get;set;}
         //body
        @auraenabled public String body {get;set;}
         //year
        @auraenabled public Double year {get;set;}
    }
}