force-app/main/default/objects/BLN_AssistedPmtAttr__mdt/BLN_AssistedPmtAttr__mdt.object-meta.xml
<CustomObject>
    <description>FOUK-4767 This is used for payment attributes.</description>
    <label>Assisted Payment Attributes</label>
    <pluralLabel>Assisted Payment Attributes</pluralLabel>
</CustomObject>

force-app/main/default/objects/BLN_AssistedPmtAttr__mdt/fields/BLN_AccountId__c.field-meta.xml
<CustomField>
    <fullName>BLN_AccountId__c</fullName>
    <description>FOUK-4676</description>
    <label>AccountId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_AssistedPmtAttr__mdt/fields/BLN_Amount__c.field-meta.xml
<CustomField>
    <fullName>BLN_Amount__c</fullName>
    <description>FOUK-4767</description>
    <label>Amount</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_AssistedPmtAttr__mdt/fields/BLN_BaseURL__c.field-meta.xml
<CustomField>
    <fullName>BLN_BaseURL__c</fullName>
    <description>FOUK-4767</description>
    <label>BaseURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_AssistedPmtAttr__mdt/fields/BLN_ClientId__c.field-meta.xml
<CustomField>
    <fullName>BLN_ClientId__c</fullName>
    <description>FOUK-4767</description>
    <label>ClientId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_AssistedPmtAttr__mdt/fields/BLN_ClientRef__c.field-meta.xml
<CustomField>
    <fullName>BLN_ClientRef__c</fullName>
    <description>FOUK-4767</description>
    <label>ClientReference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_AssistedPmtAttr__mdt/fields/BLN_Currency__c.field-meta.xml
<CustomField>
    <fullName>BLN_Currency__c</fullName>
    <description>FOUK-4767</description>
    <label>Currency</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_AssistedPmtAttr__mdt/fields/BLN_Digest__c.field-meta.xml
<CustomField>
    <fullName>BLN_Digest__c</fullName>
    <description>FOUK-4767</description>
    <label>Digest</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_AssistedPmtAttr__mdt/fields/BLN_GatewayId__c.field-meta.xml
<CustomField>
    <fullName>BLN_GatewayId__c</fullName>
    <description>FOUK-4767</description>
    <label>GatewayId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_AssistedPmtAttr__mdt/fields/BLN_JobNo__c.field-meta.xml
<CustomField>
    <fullName>BLN_JobNo__c</fullName>
    <description>FOUK-4767</description>
    <label>RemedyJobNo</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_AssistedPmtAttr__mdt/fields/BLN_LicenseCode__c.field-meta.xml
<CustomField>
    <fullName>BLN_LicenseCode__c</fullName>
    <description>FOUK-4767</description>
    <label>LicenseCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_AssistedPmtAttr__mdt/fields/BLN_MchntRef__c.field-meta.xml
<CustomField>
    <fullName>BLN_MchntRef__c</fullName>
    <description>FOUK-4767</description>
    <label>MerchantReference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_AssistedPmtAttr__mdt/fields/BLN_PostFwdURL__c.field-meta.xml
<CustomField>
    <fullName>BLN_PostFwdURL__c</fullName>
    <description>FOUK-4767</description>
    <label>PostForwardURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_AssistedPmtAttr__mdt/fields/BLN_Principle__c.field-meta.xml
<CustomField>
    <fullName>BLN_Principle__c</fullName>
    <description>FOUK-4676</description>
    <label>Principle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_AssistedPmtAttr__mdt/fields/BLN_ResponseType__c.field-meta.xml
<CustomField>
    <fullName>BLN_ResponseType__c</fullName>
    <description>FOUK-4767</description>
    <label>ResponseType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_AssistedPmtAttr__mdt/fields/BLN_ResponseURL__c.field-meta.xml
<CustomField>
    <fullName>BLN_ResponseURL__c</fullName>
    <description>FOUK-4767</description>
    <label>ResponseURL</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_AssistedPmtAttr__mdt/fields/BLN_ReturnBin__c.field-meta.xml
<CustomField>
    <fullName>BLN_ReturnBin__c</fullName>
    <description>FOUK-9428</description>
    <label>Return Bin</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_AssistedPmtAttr__mdt/fields/BLN_SalesDetails__c.field-meta.xml
<CustomField>
    <fullName>BLN_SalesDetails__c</fullName>
    <description>FOUK-9428</description>
    <label>Sales Details</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_AssistedPmtAttr__mdt/fields/BLN_SemafoneCode__c.field-meta.xml
<CustomField>
    <fullName>BLN_SemafoneCode__c</fullName>
    <description>FOUK-4767</description>
    <label>SemafoneCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_AssistedPmtAttr__mdt/fields/BLN_TenantId__c.field-meta.xml
<CustomField>
    <fullName>BLN_TenantId__c</fullName>
    <description>FOUK-4767</description>
    <label>TenantId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_AssistedPmtAttr__mdt/fields/BLN_Tokenize__c.field-meta.xml
<CustomField>
    <fullName>BLN_Tokenize__c</fullName>
    <description>FOUK-4767</description>
    <label>Tokenize</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_AssistedPmtAttr__mdt/fields/BLN_TxnRef__c.field-meta.xml
<CustomField>
    <fullName>BLN_TxnRef__c</fullName>
    <description>FOUK-4767</description>
    <label>TransactionReference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_AssistedPmtAttr__mdt/fields/BLN_TxnType__c.field-meta.xml
<CustomField>
    <fullName>BLN_TxnType__c</fullName>
    <description>FOUK-4767</description>
    <label>TransactionType</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/BLN_Payment__c.object-meta.xml
<CustomObject>
    <description>FOUK-4686: This object is created to store Payment information.</description>
    <label>Payments &amp; Refunds</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments &amp; Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_Case__c.field-meta.xml
<CustomField>
    <fullName>BLN_Case__c</fullName>
    <description>FOUK-4686: This field is created to store case value.</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_CR__c.field-meta.xml
<CustomField>
    <fullName>BLN_CR__c</fullName>
    <description>FOUK-3977 This is used in BLN_SCUtility class.</description>
    <externalId>true</externalId>
    <label>CR</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_Currency__c.field-meta.xml
<CustomField>
    <fullName>BLN_Currency__c</fullName>
    <defaultValue>&apos;GBP&apos;</defaultValue>
    <description>FOUK-5663, FOUK-5744 Fixed value for UK</description>
    <label>Currency</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_PaymentAmountTaken__c.field-meta.xml
<CustomField>
    <fullName>BLN_PaymentAmountTaken__c</fullName>
    <description>FOUK-4686: This field is created to store Payment amount taken value.</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/BLN_AssistedPaymentsController.cls
/** @description : This controller class is used in Assisted Payment.
*   @Story : FOUK-4767
*   @author: PwC-India
*   @CreatedDate: 18-04-2024
*/
public with sharing class BLN_AssistedPaymentsController {
    
    
    @auraenabled
    public static string generatedHexDigestkey(string paymentId){
        String hexStr = '';
        String digestkey = '';
        Blob sha256v ;
        String uRL = '';
        AsstPaymentWrapper aPW = new AsstPaymentWrapper();
        BLN_AssistedPmtAttr__mdt asstPayList = new BLN_AssistedPmtAttr__mdt();
        list<AsstPaymentWrapper> asstWrpList = new list<AsstPaymentWrapper>();
        
        BLN_Payment__c payments = [Select BLN_PaymentAmountTaken__c, BLN_CR__c, BLN_Case__r.CaseNumber from BLN_Payment__c where Id =: paymentId with security_enforced];
        hexStr = system.label.BLN_ClientReferenceAstPmt + payments.BLN_CR__c + system.label.BLN_DigestAstPmt;
        
        sha256v = Crypto.generateDigest(system.label.BLN_hexCode, Blob.valueOf(hexStr)); 
        
        digestkey = EncodingUtil.convertToHex(sha256v);
        asstPayList = BLN_AssistedPmtAttr__mdt.getAll().values();
        
        uRL = asstPayList.BLN_BaseURL__c+asstPayList.BLN_ClientRef__c+asstPayList.BLN_SemafoneCode__c+asstPayList.BLN_GatewayId__c+asstPayList.BLN_TenantId__c+asstPayList.BLN_ClientId__c+asstPayList.BLN_AccountId__c+asstPayList.BLN_Principle__c+asstPayList.BLN_LicenseCode__c+asstPayList.BLN_ResponseType__c+asstPayList.BLN_txnType__c+asstPayList.BLN_ResponseURL__c+asstPayList.BLN_Amount__c+string.valueOf(payments.BLN_PaymentAmountTaken__c)+asstPayList.BLN_Currency__c+asstPayList.BLN_ReturnBin__c+asstPayList.BLN_JobNo__c+string.valueOf(payments.BLN_Case__r.CaseNumber)+asstPayList.BLN_SalesDetails__c+payments.BLN_CR__c+asstPayList.BLN_PostFwdURL__c+asstPayList.BLN_Digest__c+digestkey;
        
        aPW.responseType = asstPayList.BLN_ResponseType__c;
        aPW.merchantRef = asstPayList.BLN_MchntRef__c;
        aPW.principle = asstPayList.BLN_Principle__c;
        aPW.curency = asstPayList.BLN_Currency__c;
        aPW.licenseCode = asstPayList.BLN_LicenseCode__c;
        aPW.txnType = asstPayList.BLN_txnType__c;
        aPW.accountId = asstPayList.BLN_AccountId__c;
        aPW.tokenize = asstPayList.BLN_Tokenize__c;
        aPW.amount = asstPayList.BLN_Amount__c  + string.valueOf(payments.BLN_PaymentAmountTaken__c);
        aPW.gatewayId = asstPayList.BLN_GatewayId__c;
        aPW.digest = asstPayList.BLN_Digest__c + digestkey;
        aPW.postFwdURL = asstPayList.BLN_PostFwdURL__c;
    //    aPW.txnRef = asstPayList.BLN_TxnRef__c;
        aPW.clientId = asstPayList.BLN_ClientId__c;
        aPW.tenantId = asstPayList.BLN_TenantId__c;
        aPW.semafoneCode = asstPayList.BLN_SemafoneCode__c;
        aPW.jobNo = asstPayList.BLN_JobNo__c;
        aPW.clientRef = asstPayList.BLN_ClientRef__c;
        aPW.baseURL = asstPayList.BLN_BaseURL__c;
        aPW.responseURL = asstPayList.BLN_ResponseURL__c;
        asstWrpList.add(aPW);
        
        return uRL;
        
    }
    
    public class AsstPaymentWrapper{
        private string responseType; 
        private string merchantRef;
        private string principle;
        private string curency;
        private string licenseCode;
        private string txnType;
        private string accountId;
        private string tokenize;
        private string amount;
        private string gatewayId;
        private string digest;
        private string postFwdURL;
        private string clientId;
        private string tenantId;
        private string semafoneCode;
        private string jobNo;
        private string clientRef;
        private string baseURL;
        private string responseURL;
        
    }
    
}