force-app/main/default/objects/BLN_ExternalFileLinks__c/BLN_ExternalFileLinks__c.object-meta.xml
<CustomObject>
    <description>FOUK-5770 This custom object will hold records to keep mapping between the ParentId eg WOLIId and AWS DocumentId</description>
    <label>External File Links</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>ExtFileLink</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External File Links</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_DocumentId__c.field-meta.xml
<CustomField>
    <fullName>BLN_DocumentId__c</fullName>
    <description>FOUK-7055 This field is to hold the AWS Id returned by Mule-AWS</description>
    <label>Document Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_FileCreationDate__c.field-meta.xml
<CustomField>
    <fullName>BLN_FileCreationDate__c</fullName>
    <description>FOUK-7055 This field is to hold DateTime of when document Id was created</description>
    <label>File Creation Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_FileName__c.field-meta.xml
<CustomField>
    <fullName>BLN_FileName__c</fullName>
    <description>FOUK-7055 This field is to hold original file name</description>
    <label>File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_FileType__c.field-meta.xml
<CustomField>
    <fullName>BLN_FileType__c</fullName>
    <description>FOUK-7055 This field is to hold File Type</description>
    <label>File Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JPG</fullName>
            </value>
            <value>
                <fullName>PNG</fullName>
            </value>
            <value>
                <fullName>PDF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_ParentId__c.field-meta.xml
<CustomField>
    <fullName>BLN_ParentId__c</fullName>
    <description>FOUK-7055 This field is to hold Parent Id</description>
    <externalId>true</externalId>
    <label>Parent Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_ParentObjectName__c.field-meta.xml
<CustomField>
    <fullName>BLN_ParentObjectName__c</fullName>
    <description>FOUK-7055 This field is to hold name of Parent Object</description>
    <label>Parent Object Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_S3BucketLink__c.field-meta.xml
<CustomField>
    <fullName>BLN_S3BucketLink__c</fullName>
    <description>FOUK-7055 This field is to hold Amazon AWS S3 Bucket Link</description>
    <label>S3 Bucket Link</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/BLN_UploadPhotoToServiceCertaintyTest.cls
@isTest
public class BLN_UploadPhotoToServiceCertaintyTest {
    @testSetup
    static void setupTestData(){
        WorkOrderLineItem woli = BLN_TestDataFactory.createWOLI();
        String woliId = woli.Id;
        List<BLN_ExternalFileLinks__c> extfileList = BLN_TestDataFactory.createExternalFileLink();
        extfileList[0].BLN_ParentId__c = woliId;
    }

    @isTest
    public static void uploadPhotosToServiceCertaintyTest(){
        List<BLN_ExternalFileLinks__c> extfileList = [Select Id, Name,BLN_FileName__c,BLN_FileType__c,BLN_ParentObjectName__c,BLN_DocumentId__c,BLN_FileCreationDate__c,BLN_S3BucketLink__c,BLN_ParentId__c from BLN_ExternalFileLinks__c];
        Test.setMock(HttpCalloutMock.class, new MockResponseGenerator());
        Test.startTest();
        BLN_UploadPhotoToServiceCertaintyCallout.uploadPhotosToServiceCertainty(extfileList);
        Test.stopTest();
        System.assertEquals(extfileList.size() > 0, true,'Atleast one record should be there');
    }
    
    
    public class MockResponseGenerator implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse response = new HttpResponse();
            response.setBody('{"token_type":"Bearer","expires_in":3600,"access_token":"MockAccessToken123","scope":"read"}');
                response.setStatusCode(200);
                return response; 
        }
    }
}