force-app/main/default/objects/BLN_ExternalFileLinks__c/BLN_ExternalFileLinks__c.object-meta.xml
<CustomObject>
    <description>FOUK-5770 This custom object will hold records to keep mapping between the ParentId eg WOLIId and AWS DocumentId</description>
    <label>External File Links</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>ExtFileLink</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External File Links</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_Category__c.field-meta.xml
<CustomField>
    <fullName>BLN_Category__c</fullName>
    <description>Categorization of the File Uploaded</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Inspection</fullName>
            </value>
            <value>
                <fullName>Additional Inspection</fullName>
            </value>
            <value>
                <fullName>Post-Inspection</fullName>
            </value>
            <value>
                <fullName>Recalibration</fullName>
            </value>
            <value>
                <fullName>Failed Appointment Photos</fullName>
            </value>
            <value>
                <fullName>Corrective Action Report</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_DocumentId__c.field-meta.xml
<CustomField>
    <fullName>BLN_DocumentId__c</fullName>
    <description>FOUK-7055 This field is to hold the AWS Id returned by Mule-AWS</description>
    <label>Document Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_FileCreationDate__c.field-meta.xml
<CustomField>
    <fullName>BLN_FileCreationDate__c</fullName>
    <description>FOUK-7055 This field is to hold DateTime of when document Id was created</description>
    <label>File Creation Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_FileType__c.field-meta.xml
<CustomField>
    <fullName>BLN_FileType__c</fullName>
    <description>FOUK-7055 This field is to hold File Type</description>
    <label>File Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JPG</fullName>
            </value>
            <value>
                <fullName>PNG</fullName>
            </value>
            <value>
                <fullName>PDF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_ParentId__c.field-meta.xml
<CustomField>
    <fullName>BLN_ParentId__c</fullName>
    <description>FOUK-7055 This field is to hold Parent Id</description>
    <externalId>true</externalId>
    <label>Parent Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_ParentObjectName__c.field-meta.xml
<CustomField>
    <fullName>BLN_ParentObjectName__c</fullName>
    <description>FOUK-7055 This field is to hold name of Parent Object</description>
    <label>Parent Object Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BLN_SendDocsForPrintBatchTest.cls
/**@description : This is the Apex Test Class for BLN_SendDocsForPrintBatch
*  @author: PwC India
*  @Story: FOUK-5770 (Create Bulk Customer Service Report File for Printing and Posting)
*  @CreatedDate: 29/04/2024
*/
@isTest
public class BLN_SendDocsForPrintBatchTest {
    public static String accessToken = '00D7a00000057BE!AR0AQL3GDzbly30diuDf7bL3MhSCjAcmRPrrKcG1hdWZpO8JU2yUytrpaiXfkQ50vab4vSOygl8.b9NIwnSCsCZHQk_xt18n';
    /*Description : It is used for test data for below methods*/
    @testSetup
    static void setup(){
        Id userid = UserInfo.getUserId();
        
        // Assert that the user ID is not null
        System.assertNotEquals(null, userid, 'User ID should not be null');
        
        WorkType workType = BLN_TestDataFactory.createWorkType('Replacement', 1.0, true, true);
        
        Case caseObj =  BLN_TestDataFactory.createCase('BLN_JobRequest','Job Request','New');
        insert caseObj;
        
        WorkOrder workOrder = BLN_TestDataFactory.createWorkOrder(false);
        workOrder.status = 'completed';
        workOrder.CaseId = caseObj.Id;
        insert workOrder;
        
        WorkOrderLineItem wOLI = new WorkOrderLineItem();
        wOLI.WorkTypeId = worktype.Id;
        wOLI.WorkOrderId = workOrder.id;
        wOLI.status = 'Completed';
        wOLI.BLN_IsStockCheckInCompleted__c = false;
        insert wOLI;        
        
        wOLI.Status = 'Completed';
        wOLI.BLN_PrintStatus__c = 'Ready For Print';
        wOLI.BLN_FinalSummaryReportDeliveryMethod__c = 'Post';
        update wOLI;

        ServiceAppointment servApp = BLN_TestDataFactory.createServiceAppntmnt('Replacement', True);
        servApp.BLN_WorkOrderLineItem__c = wOLI.Id;
        servApp.WorkTypeId = workType.Id;
        servApp.BLN_WorkOrderNumber__c = workOrder.Id;
        servApp.ArrivalWindowStartTime = System.now().addhours(1);
        update servApp;
        
    }
    /*Description : This method is used for checking Send Docs for print batch*/
    @isTest
    static void testMethod1() {
        List<WorkOrderLineItem> woliList = [SELECT Id FROM WorkOrderLineItem LIMIT 1];
        BLN_ExternalFileLinks__c link = new BLN_ExternalFileLinks__c();
        link.BLN_ParentId__c = woliList[0].Id;
        link.BLN_DocumentId__c = 'AWS-001';
        link.BLN_ParentObjectName__c = 'WorkOrderLineItem';
        link.BLN_FileType__c = 'PDF';
        link.BLN_FileCreationDate__c = System.now().addMinutes(-5);
        link.BLN_Category__c = 'Post-Inspection';
        insert link;
        Test.setMock(HttpCalloutMock.class, new BLN_MockHttpResponseHTTPCallOutToOkta());
        Test.startTest();
        BLN_SendDocsForPrintBatch job = new BLN_SendDocsForPrintBatch();
        String cronExpr = '0 0 2 * * ? *';
        System.schedule('BLN_SendDocsForPrintBatch', cronExpr, job);
        job.execute(null);
        Test.stopTest();
        System.assertEquals(1, woliList.size(), 'Appointment Should be only 1');
    }
     /*Description : This method is used for checking Send Docs for print batch based on WorkOrderLineItem */
    @isTest
    static void testMethod2() {
        List<WorkOrderLineItem> woliList = [SELECT Id FROM WorkOrderLineItem LIMIT 1];
        Test.setMock(HttpCalloutMock.class, new BLN_MockHttpResponseHTTPCallOutToOkta());
        Test.startTest();
        BLN_SendDocsForPrintBatch job = new BLN_SendDocsForPrintBatch();
        String cronExpr = '0 0 2 * * ? *';
        System.schedule('BLN_SendDocsForPrintBatch', cronExpr, job);
        job.execute(null);
        Test.stopTest();
        System.assertEquals(1, woliList.size(), 'Appointment Should be only 1');
    }
}