force-app/main/default/objects/BLN_ExternalFileLinks__c/BLN_ExternalFileLinks__c.object-meta.xml
<CustomObject>
    <description>FOUK-5770 This custom object will hold records to keep mapping between the ParentId eg WOLIId and AWS DocumentId</description>
    <label>External File Links</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>ExtFileLink</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External File Links</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_DocumentId__c.field-meta.xml
<CustomField>
    <fullName>BLN_DocumentId__c</fullName>
    <description>FOUK-7055 This field is to hold the AWS Id returned by Mule-AWS</description>
    <label>Document Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_FileName__c.field-meta.xml
<CustomField>
    <fullName>BLN_FileName__c</fullName>
    <description>FOUK-7055 This field is to hold original file name</description>
    <label>File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_ParentId__c.field-meta.xml
<CustomField>
    <fullName>BLN_ParentId__c</fullName>
    <description>FOUK-7055 This field is to hold Parent Id</description>
    <externalId>true</externalId>
    <label>Parent Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_ParentObjectName__c.field-meta.xml
<CustomField>
    <fullName>BLN_ParentObjectName__c</fullName>
    <description>FOUK-7055 This field is to hold name of Parent Object</description>
    <label>Parent Object Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/BLN_IntegrationLogger__c.object-meta.xml
<CustomObject>
    <label>Integration Logger</label>
    <nameField>
        <displayFormat>IL-{00000000}</displayFormat>
        <label>Integration Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logger</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_APICallInSeconds__c.field-meta.xml
<CustomField>
    <fullName>BLN_APICallInSeconds__c</fullName>
    <description>FOUK-252 -&gt; Store the Duration between Request was sent and Response was received</description>
    <label>API Call (In Seconds)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_RequestBody__c.field-meta.xml
<CustomField>
    <fullName>BLN_RequestBody__c</fullName>
    <description>FOUK-252 -&gt; Store The Requested Body To Sent The End Point</description>
    <label>Request Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_RequestEndPoint__c.field-meta.xml
<CustomField>
    <fullName>BLN_RequestEndPoint__c</fullName>
    <description>FOUK-252 -&gt; Store The End Point Url</description>
    <label>Request End Point</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_RequestHeaders__c.field-meta.xml
<CustomField>
    <fullName>BLN_RequestHeaders__c</fullName>
    <description>FOUK-252 -&gt; Store The Request Header Of  API</description>
    <label>Request Headers</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_RequestIssuedBy__c.field-meta.xml
<CustomField>
    <fullName>BLN_RequestIssuedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>FOUK-252 -&gt; Store User who initiated the request.</description>
    <label>Request Issued By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>IntegrationLogger</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_RequestMethod__c.field-meta.xml
<CustomField>
    <fullName>BLN_RequestMethod__c</fullName>
    <description>FOUK-252 -&gt; Store The Method Type</description>
    <label>Request Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_RequestSent__c.field-meta.xml
<CustomField>
    <fullName>BLN_RequestSent__c</fullName>
    <description>FOUK-252 -&gt; Store Date and Time when Request was sent</description>
    <label>Request Sent</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_ResponseBody__c.field-meta.xml
<CustomField>
    <fullName>BLN_ResponseBody__c</fullName>
    <description>FOUK-252 -&gt; Store  Response Body sent to target system.</description>
    <label>Response Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_ResponseHeaders__c.field-meta.xml
<CustomField>
    <fullName>BLN_ResponseHeaders__c</fullName>
    <description>FOUK-252 -&gt; Store The Response Header</description>
    <label>Response Headers</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_ResponseReceived__c.field-meta.xml
<CustomField>
    <fullName>BLN_ResponseReceived__c</fullName>
    <description>FOUK-252 -&gt; Store The Date and Time when Response was recieved</description>
    <label>Response Received</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_ResponseStatus__c.field-meta.xml
<CustomField>
    <fullName>BLN_ResponseStatus__c</fullName>
    <description>FOUK-252 -&gt; Store The Response Status</description>
    <label>Response Status</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_ResponseStatusCode__c.field-meta.xml
<CustomField>
    <fullName>BLN_ResponseStatusCode__c</fullName>
    <description>FOUK-252 -&gt; Store The Response Status Code</description>
    <label>Response Status Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_IntegrationLogger__c/fields/BLN_TargetSystem__c.field-meta.xml
<CustomField>
    <fullName>BLN_TargetSystem__c</fullName>
    <description>FOUK-252 -&gt; Store Which Target System To Used The Data</description>
    <label>Target System</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ServiceCertaintyImageTags__mdt/BLN_ServiceCertaintyImageTags__mdt.object-meta.xml
<CustomObject>
    <description>Created as a part of FOUK-6910. This metadata will be used to story the image tags for those images which we needs to send to service certainty.</description>
    <label>Service Certainty Image Tag</label>
    <pluralLabel>Service Certainty Image Tags</pluralLabel>
</CustomObject>

force-app/main/default/classes/BLN_UploadPhotoToServiceCertaintyCallout.cls
public with sharing class BLN_UploadPhotoToServiceCertaintyCallout{
    
    @InvocableMethod(label='Send Image To Service Certainty' callout=true)
    public static void uploadPhotosToServiceCertainty(List<BLN_ExternalFileLinks__c> extFileList){
        List<BLN_ExternalFileLinks__c> eligibleRecords = new List<BLN_ExternalFileLinks__c>();
        Set<String> imageNameToSendSet = new Set<String>();
        
        //Collect all tags from config to send particular images to Service Certainty
        List<BLN_ServiceCertaintyImageTags__mdt> imageNameToSend = [Select DeveloperName 
                                                                    From BLN_ServiceCertaintyImageTags__mdt WITH SECURITY_ENFORCED];
        
        for(BLN_ServiceCertaintyImageTags__mdt imageName : imageNameToSend){
            if(!imageNameToSendSet.contains(imageName.DeveloperName)){
                imageNameToSendSet.add(imageName.DeveloperName);
            }
        }
        //Filter out eligible file records
        for (BLN_ExternalFileLinks__c extFile : extFileList) {
            for(String imageNameoInclude : imageNameToSendSet){
               
                if (extFile.BLN_ParentObjectName__c != null 
                    	&& extFile.BLN_FileName__c !=null  
                    	&& extFile.BLN_FileName__c.contains(imageNameoInclude) 
                    	&& (extFile.BLN_ParentObjectName__c.equalsIgnoreCase('WorkOrderLineItem'))
                   		&& extFile.BLN_ParentId__c != null
                   ) {
                    eligibleRecords.add(extFile);
                }
            }
        }
        
        if (!eligibleRecords.isEmpty()) {
            Set<Id> woliIds = new Set<Id>();
            for (BLN_ExternalFileLinks__c extFileRec : eligibleRecords) {
                if(!woliIds.contains(extFileRec.BLN_ParentId__c)){
                	woliIds.add(extFileRec.BLN_ParentId__c);    
                }                
            }
            
            List<WorkOrderLineItem> wolis = [SELECT Id, WorkOrder.Case.BLN_AssignmentID__c, WorkOrder.Case.CaseNumber 
                                             FROM WorkOrderLineItem 
                                             WHERE Id IN :woliIds WITH SECURITY_ENFORCED];
            
            Map<Id, String> woliIdVsAssignmentId = new Map<Id, String>();
            Map<Id, String> woliIdVsCaseNumber = new Map<Id, String>();
            for (WorkOrderLineItem woLi : wolis) {
                woliIdVsAssignmentId.put(woLi.Id, woLi.WorkOrder.Case.BLN_AssignmentID__c);
                woliIdVsCaseNumber.put(woli.Id, woli.WorkOrder.Case.CaseNumber);
            } 
            
            List<ServiceCertanityWrapper> wrappersToSend = new List<ServiceCertanityWrapper>();
            for (BLN_ExternalFileLinks__c extFileRec : eligibleRecords) {
                if(woliIdVsAssignmentId.containsKey(extFileRec.BLN_ParentId__c) 
                   	&& woliIdVsAssignmentId.get(extFileRec.BLN_ParentId__c) != null
                  	&& woliIdVsCaseNumber.containskey(extFileRec.BLN_ParentId__c)
                   	&& woliIdVsCaseNumber.get(extFileRec.BLN_ParentId__c) != null
                  ){
					ServiceCertanityWrapper wrapper = new ServiceCertanityWrapper();
                    wrapper.entityName = '';
                    wrapper.entityID = woliIdVsAssignmentId.get(extFileRec.BLN_ParentId__c);
                    wrapper.eventType = 'Create';
                    wrapper.sourceSystem = 'Salesforce';
                    wrapper.timestamp = Datetime.now();
                    wrapper.initialisedSystem = 'Salesforce';
                    wrapper.data = new DataWrapper();
                    wrapper.data.current = new CurrentWrapper();
                    wrapper.data.current.caseId = woliIdVsCaseNumber.get(extFileRec.BLN_ParentId__c);
                    wrapper.data.current.assignmentId = woliIdVsAssignmentId.get(extFileRec.BLN_ParentId__c);
                    wrapper.data.current.documentId = extFileRec.BLN_DocumentId__c;
                    wrappersToSend.add(wrapper);
                }         

            }
            if(wrappersToSend.size() > 0){
                sendDataToMuleServiceCertainty(wrappersToSend);
            }

        }
    }
    
    public static void sendDataToMuleServiceCertainty(List<ServiceCertanityWrapper> wrappersToSend){
        String oktaToken = BLN_HTTPCallOutAccessToken.getAccessToken()?.accessToken;
        for(ServiceCertanityWrapper payload: wrappersToSend){
        	makeCallout(oktaToken, payload);    
        }
    }

    public static void makeCallout(String accessToken, ServiceCertanityWrapper payload){
        try{
            HttpResponse res;
            String auth = System.label.BLN_Bearer + ' ' + accessToken;
            String destination = System.label.BLN_ServiceCertaintyMulesoftDestination;
            String reqHeader;
            
            Http http = new Http();
            HttpRequest req = new HttpRequest();
            
            String correlationId = randomCodeGenerator();  
            req.setMethod('POST');
            req.setHeader('Authorization', auth);
            req.setHeader('Content-Type', 'application/json');
            req.setHeader('X-CORRELATION-ID', correlationId);
            req.setHeader('country-code', 'UK');
            req.setHeader('destination', destination);
            req.setHeader('destinationType', 'Topic');
            req.setHeader('legacyBroker', 'false');
            req.setHeader('businessGroup', 'Customer');
            
            reqHeader =	'Authorization: ' + auth +
                        ' Content-Type: application/json' +
                        ' X-CORRELATION-ID: ' + correlationId +
                        ' country-code: ' + 'UK' +
                        ' destination: '  + destination +
                        ' destinationType: Topic'+
                        'legacyBroker: false' +
                        'businessGroup: Customer';        
            String endPoint = System.label.BLN_MulesoftServiceCertaintyEndpoint;
            req.setEndpoint(endPoint);
            req.setTimeout(Integer.valueof(120000));
            req.setBody(JSON.serialize(payload));
            
            DateTime t1 = System.Now();
            res = http.send(req);
            DateTime t2 = System.Now();
            
            Decimal decSec2 = t2.getTime();
            Decimal decSec1 = t1.getTime();
            Decimal miliDiff = decsec2 - decsec1;
            Decimal secDiff = miliDiff/1000;
            Decimal rounded = secDiff.setScale(3);
            String secondsGap = String.valueOf(rounded);
            
            if ((res.getStatusCode() == 200 || res.getStatusCode() == 201) && res.getbody() != null) {
                // Store Integration Logger Record
                List<BLN_IntegrationLogger__c> intLogList = new List<BLN_IntegrationLogger__c>();
                BLN_IntegrationLogger__c integrat = new BLN_IntegrationLogger__c();
                integrat.BLN_APICallInSeconds__c = secondsGap;
                integrat.BLN_RequestBody__c = req.getBody();
                integrat.BLN_RequestEndPoint__c = req.getEndpoint();
                integrat.BLN_RequestHeaders__c = reqHeader;
                integrat.BLN_RequestIssuedBy__c = UserInfo.getUserId();
                integrat.BLN_RequestMethod__c = req.getMethod();
                integrat.BLN_RequestSent__c = System.today();
                integrat.BLN_ResponseBody__c = res.getBody();
                integrat.BLN_ResponseHeaders__c = resHeaders(res);
                integrat.BLN_ResponseReceived__c = System.today();
                integrat.BLN_ResponseStatus__c = res.getStatus();
                integrat.BLN_ResponseStatusCode__c = ''+res.getStatusCode();
                integrat.BLN_TargetSystem__c = System.label.BLN_TargetSystemMulesoft;
                intLogList.add(integrat);

                BLN_IntegrationLogger.logRequest(intLogList);
            }
        }
        catch(Exception ex){
            // Store Exception Logger Record
            BLN_ExceptionLogger.captureException(ex);
        }
        
    }
    
    public static string resHeaders(HttpResponse res){
        string[] headerkeys = res.getHeaderKeys();
        String headers;
        for(String header : headerkeys){
            headers = res.getHeader(header) + ',';
        }
        return headers;
    }
    
    public static String randomCodeGenerator() {
        Blob blobKey = Crypto.GenerateAESKey(128);
        String hexKey = EncodingUtil.ConvertTohex(blobKey);
        String uid = hexKey.SubString(0,8)
            			+ '-' 
            			+ hexKey.SubString(8,12) 
            			+ '-' 
            			+ hexKey.SubString(12,16) 
            			+ '-' 
            			+ hexKey.SubString(16,20) 
            			+ '-' 
            			+ hexKey.substring(20);
        return uid;
    }
    
    
    public class ServiceCertanityWrapper{
        public string entityName{get;set;}
        public string entityID{get;set;}
        public string eventType{get;set;}
        public string sourceSystem{get;set;}
        public Datetime timestamp{get;set;}
        public string initialisedSystem{get;set;}
        public DataWrapper data {get;set;}
    }

    public class DataWrapper{
        public CurrentWrapper current{get;set;}
    }
    public class CurrentWrapper{
        public string caseId{get;set;}
        public string assignmentId{get;set;}
        public string documentId{get;set;}
    }

}