force-app/main/default/objects/BLN_CalloutSettings__c/BLN_CalloutSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Callout Settings</label>
</CustomObject>

force-app/main/default/objects/BLN_CalloutSettings__c/fields/BLN_ExpiresTimeBuffer__c.field-meta.xml
<CustomField>
    <fullName>BLN_ExpiresTimeBuffer__c</fullName>
    <label>Expires Time Buffer</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_CalloutSettings__c/fields/BLN_IsEventPublished__c.field-meta.xml
<CustomField>
    <fullName>BLN_IsEventPublished__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Event Published</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BLN_OktaCallout__e/BLN_OktaCallout__e.object-meta.xml
<CustomObject>
    <label>OktaCallout</label>
    <pluralLabel>OktaCallout</pluralLabel>
</CustomObject>

force-app/main/default/objects/BLN_OktaCallout__e/fields/BLN_ServiceAppointmentId__c.field-meta.xml
<CustomField>
    <fullName>BLN_ServiceAppointmentId__c</fullName>
    <label>ServiceAppointmentId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BLN_OktaCalloutTriggerHelper.cls
/**
 * Created by gciesielsk001 on 28.03.2024.
 */

public with sharing class BLN_OktaCalloutTriggerHelper {

    public static void generateOktaToken(List<BLN_OktaCallout__e> newOktaCallouts) {
        Cache.OrgPartition orgPart = Cache.Org.getPartition('local.OKTAIdP');
        DateTime expiresIn = (DateTime) orgPart.get('OKTATokenExpirationDateTime');
        String oktaToken = (String) orgPart.get('OKTAAccessToken');
        BLN_CalloutSettings__c customSetting = BLN_CalloutSettings__c.getInstance();
        if ((expiresIn == null || oktaToken == null || expiresIn < Datetime.now().addSeconds(Integer.valueOf(customSetting.BLN_ExpiresTimeBuffer__c))) && !customSetting.BLN_IsEventPublished__c) {
            customSetting.BLN_IsEventPublished__c = true;
            BLN_GenerateOktaToken.generateOktaToken((Id) newOktaCallouts[0].BLN_ServiceAppointmentId__c);
        }
    }

}