force-app/main/default/objects/BLN_AccountPlan__c/BLN_AccountPlan__c.object-meta.xml
<CustomObject>
    <description>FOUK-4763</description>
    <label>Account Plan</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Account Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_AccountPlan__c/fields/BLN_AccountName__c.field-meta.xml
<CustomField>
    <fullName>BLN_AccountName__c</fullName>
    <description>FOUK-4763</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Plans</relationshipLabel>
    <relationshipName>Account_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BLN_AccountPlan__c/fields/BLN_Status__c.field-meta.xml
<CustomField>
    <fullName>BLN_Status__c</fullName>
    <description>FOUK-5335</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
            <value>
                <fullName>Aborted,</fullName>
                <isActive>false</isActive>
                <label>Aborted,</label>
            </value>
            <value>
                <fullName>Completed,</fullName>
                <isActive>false</isActive>
                <label>Completed,</label>
            </value>
            <value>
                <fullName>In Progress,</fullName>
                <isActive>false</isActive>
                <label>In Progress,</label>
            </value>
            <value>
                <fullName>Planned,</fullName>
                <isActive>false</isActive>
                <label>Planned,</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_Initiative__c/BLN_Initiative__c.object-meta.xml
<CustomObject>
    <description>FOUK-4789</description>
    <label>Initiative</label>
    <nameField>
        <label>Intiative Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Initiatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_Initiative__c/fields/BLN_AccountName__c.field-meta.xml
<CustomField>
    <fullName>BLN_AccountName__c</fullName>
    <description>FOUK-4790.This is the reference field of Account Name.</description>
    <formula>BLN_AccountPlanName__r.BLN_AccountName__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Initiative__c/fields/BLN_AccountPlan__c.field-meta.xml
<CustomField>
    <fullName>BLN_AccountPlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>FOUK-4790</description>
    <label>Account Plan</label>
    <referenceTo>BLN_AccountPlan__c</referenceTo>
    <relationshipLabel>Initiatives (Account Plan)</relationshipLabel>
    <relationshipName>Initiatives1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BLN_Initiative__c/fields/BLN_AccountPlanName__c.field-meta.xml
<CustomField>
    <fullName>BLN_AccountPlanName__c</fullName>
    <description>FOUK-4770. Created for related list</description>
    <label>Account Plan Name</label>
    <referenceTo>BLN_AccountPlan__c</referenceTo>
    <relationshipLabel>Initiatives</relationshipLabel>
    <relationshipName>Initiatives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BLN_Initiative__c/fields/BLN_ClientPriority__c.field-meta.xml
<CustomField>
    <fullName>BLN_ClientPriority__c</fullName>
    <description>FOUK-4774. Created for Client getting priority.</description>
    <label>Client Priority</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_Initiative__c/fields/BLN_EndDate__c.field-meta.xml
<CustomField>
    <fullName>BLN_EndDate__c</fullName>
    <description>This is a date field indicated the end date (FOUK-4772)</description>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BLN_Initiative__c/fields/BLN_StartDate__c.field-meta.xml
<CustomField>
    <fullName>BLN_StartDate__c</fullName>
    <description>This is a date field indicated the start date (FOUK-4772)</description>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BLN_Initiative__c/fields/BLN_Status__c.field-meta.xml
<CustomField>
    <fullName>BLN_Status__c</fullName>
    <description>FOUK-4775. To get Status of the Initiative.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BLN_TimeLineControllerTest.cls
@IsTest
private class BLN_TimeLineControllerTest {
    @TestSetup
    static void createData() {
        Account acc = new Account(Name = 'Account 1');
        insert acc;
        
    	BLN_AccountPlan__c acPlan = new BLN_AccountPlan__c(BLN_AccountName__c = acc.Id);
        insert acPlan;
        
        List<BLN_Initiative__c> initiativeList = new List<BLN_Initiative__c>();
        initiativeList.add(new BLN_Initiative__c(Name = 'Int 1', BLN_Status__c = 'In Progress', BLN_EndDate__c = System.today() + 1, BLN_StartDate__c = System.today(), BLN_AccountPlanName__c = acPlan.Id, BLN_ClientPriority__c = 'High'));
        initiativeList.add(new BLN_Initiative__c(Name = 'Int 2', BLN_Status__c = 'Completed', BLN_EndDate__c = System.today() + 1, BLN_StartDate__c = System.today(), BLN_AccountPlanName__c = acPlan.Id, BLN_ClientPriority__c = 'High'));
        initiativeList.add(new BLN_Initiative__c(Name = 'Int 3', BLN_Status__c = 'In Progress', BLN_EndDate__c = System.today() - 1, BLN_StartDate__c = System.today() - 2, BLN_AccountPlanName__c = acPlan.Id, BLN_ClientPriority__c = 'High'));
        initiativeList.add(new BLN_Initiative__c(Name = 'Int 4', BLN_Status__c = 'Planned', BLN_EndDate__c = System.today() - 1, BLN_StartDate__c = System.today() - 2, BLN_AccountPlanName__c = acPlan.Id, BLN_ClientPriority__c = 'High'));
        insert initiativeList;
    }
    
	@IsTest
    static void getInitiativesTest() {
        BLN_AccountPlan__c acPlan = [SELECT Id FROM BLN_AccountPlan__c LIMIT 1];
        
        Test.startTest();
        	List<BLN_WrapperStore.InitiativeWrapper> intWrapList = BLN_TimeLineController.getInitiatives(acPlan.Id);
        Test.stopTest();
        
        System.assertEquals(intWrapList.size(), 4, 'Wrapper should have 4 records');
    }
}