force-app/main/default/objects/BLN_Relationship__c/BLN_Relationship__c.object-meta.xml
<CustomObject>
    <description>FOUK-4871. This is the custom object name as Relationship</description>
    <label>Relationship</label>
    <nameField>
        <label>Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_Relationship__c/fields/BLN_Account__c.field-meta.xml
<CustomField>
    <fullName>BLN_Account__c</fullName>
    <description>FOUK-4871. This field is the reference of Master Details relationship with Account</description>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.BLN_Level__c</field>
            <operation>equals</operation>
            <value>Legal Entity Account</value>
        </filterItems>
        <filterItems>
            <field>Account.BLN_Level__c</field>
            <operation>equals</operation>
            <value>Country Grouping Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BLN_Relationship__c/fields/BLN_ContactAttitudeTowardsBelron__c.field-meta.xml
<CustomField>
    <fullName>BLN_ContactAttitudeTowardsBelron__c</fullName>
    <formula>TEXT(BLN_ContactName__r.BLN_AttitudetowardsAutoglass__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Attitude Towards Belron</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Relationship__c/fields/BLN_ContactDecisionPower__c.field-meta.xml
<CustomField>
    <fullName>BLN_ContactDecisionPower__c</fullName>
    <formula>TEXT( BLN_ContactName__r.BLN_DecisionPower__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Decision Power</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Relationship__c/fields/BLN_ContactName__c.field-meta.xml
<CustomField>
    <fullName>BLN_ContactName__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>FOUK-4870</description>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BLN_Relationship__c/fields/BLN_ContactPosition__c.field-meta.xml
<CustomField>
    <fullName>BLN_ContactPosition__c</fullName>
    <formula>BLN_ContactName__r.BLN_Position__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Position</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Relationship__c/fields/BLN_RelationshipHealth__c.field-meta.xml
<CustomField>
    <fullName>BLN_RelationshipHealth__c</fullName>
    <description>FOUK-4871. This field is the reference of Relationship Health</description>
    <label>Relationship Health</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Good</fullName>
            </value>
            <value>
                <fullName>Average</fullName>
            </value>
            <value>
                <fullName>Poor</fullName>
            </value>
            <value>
                <fullName>Desired Contact</fullName>
                <default>true</default>
                <label>Desired Contact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_Relationship__c/fields/BLN_RelationshipHealthIndicator__c.field-meta.xml
<CustomField>
    <fullName>BLN_RelationshipHealthIndicator__c</fullName>
    <description>FOUK-4871. This field is the reference of Relationship Health Indicator</description>
    <formula>IF(ISPICKVAL(BLN_RelationshipHealth__c,&quot;Good&quot;), IMAGE(&apos;/resource/BLN_Good&apos;,&apos;BLN_Good&apos;,30,30),

IF(ISPICKVAL(BLN_RelationshipHealth__c, &quot;Average&quot;),IMAGE(&apos;/resource/BLN_Average&apos;,&apos;BLN_Average&apos;,30,30),

IF (ISPICKVAL(BLN_RelationshipHealth__c, &quot;Desired Contact&quot;), IMAGE(&apos;/resource/BLN_DesiredContact&apos;,&apos;BLN_DesiredContact&apos;,30,30),

IF (ISPICKVAL(BLN_RelationshipHealth__c, &quot;Poor&quot;), IMAGE(&apos;/resource/BLN_Poor&apos;,&apos;BLN_Poor&apos;,30,30),


IMAGE(&quot; &quot;, &quot; &quot;)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Relationship Health Indicator</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Relationship__c/fields/BLN_UserName__c.field-meta.xml
<CustomField>
    <fullName>BLN_UserName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>FOUK-4871. This field is the reference of relationship with User</description>
    <label>User Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BLN_RelationshipMatrixController.cls
/*****************************************
*ClassName : BLN_RelationshipMatrixController
*@description : FOUK-2031 This controller class is used in Lightning web component .
*CreatedDate: 10-02-2024
*CreatedBy : PwC-India
****************************************/
public with sharing class BLN_RelationshipMatrixController {
    
    /*MethodName : getRelationships
*@description : This method is used to return the relationships.
*@return Map
*@param string
*Input Parameter : String
*CreatedDate: 10-02-2024
*CreatedBy : Pwc-India
*Change log :
****************************************/
    
    @AuraEnabled(Cacheable = true)
    public static Map<Id,List<BLN_Relationship__c>> getRelationships(String recordId) {
        Map<Id,List<BLN_Relationship__c>> relationshipMap = new Map<Id,List<BLN_Relationship__c>>();
        
        try {
            if(String.isNotBlank(recordId)){
                List<BLN_Relationship__c> relationshipList = [SELECT Id, BLN_UserName__r.Name, BLN_ContactName__c, BLN_ContactName__r.Name, 
                                                              BLN_RelationshipHealth__c, BLN_RelationshipHealthIndicator__c, 
                                                              BLN_ContactPosition__c, BLN_ContactDecisionPower__c, 
                                                              BLN_ContactAttitudeTowardsBelron__c 
                                                              FROM BLN_Relationship__c 
                                                              WHERE BLN_Account__c = :recordId WITH SECURITY_ENFORCED LIMIT 500000];
                
               
                    for (BLN_Relationship__c relationship : relationshipList) {
                        if (!relationshipMap.containsKey(relationship.BLN_ContactName__c)) {
                            relationshipMap.put(relationship.BLN_ContactName__c, new List<BLN_Relationship__c>());
                        }
                        relationshipMap.get(relationship.BLN_ContactName__c).add(relationship);
                    }
                
            }
        }
        catch (Exception e) {
            BLN_ExceptionLogger.captureException(e);
        }
        return relationshipMap;
    }
    
    /*MethodName : getRelationshipId
*@description : This method is used to return the relationship Id.
*@return string
*@param string
*Input Parameter : String
*CreatedDate: 10-02-2024
*CreatedBy : Pwc-India
*Change log :
****************************************/
    @AuraEnabled
    public static string getRelationshipId(string contactId, string userName){
        try {
            
            BLN_Relationship__c  relationship = [select Id,BLN_RelationshipHealth__c from BLN_Relationship__c where BLN_ContactName__c =:contactId and BLN_UserName__r.Name =: userName   WITH SECURITY_ENFORCED limit 1];
           
            return relationship.Id;
        }
        catch (Exception e) {
            BLN_ExceptionLogger.captureException(e);
            return null;
            
        }
    }
}