force-app/main/default/objects/BLN_Payment__c/BLN_Payment__c.object-meta.xml
<CustomObject>
    <description>FOUK-4686: This object is created to store Payment information.</description>
    <label>Payments &amp; Refunds</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments &amp; Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_Case__c.field-meta.xml
<CustomField>
    <fullName>BLN_Case__c</fullName>
    <description>FOUK-4686: This field is created to store case value.</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_challengereference__c.field-meta.xml
<CustomField>
    <fullName>BLN_challengereference__c</fullName>
    <label>Challengereference</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_InitiatedBy__c.field-meta.xml
<CustomField>
    <fullName>BLN_InitiatedBy__c</fullName>
    <description>FOUK-5664: This field is created to store Initiated By value on payment record.</description>
    <label>Initiated By</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_InitiatedDateTime__c.field-meta.xml
<CustomField>
    <fullName>BLN_InitiatedDateTime__c</fullName>
    <description>FOUK-5611 This is used in Refund record page</description>
    <label>Initiated Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_PaymentAmountTaken__c.field-meta.xml
<CustomField>
    <fullName>BLN_PaymentAmountTaken__c</fullName>
    <description>FOUK-4686: This field is created to store Payment amount taken value.</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_PaymentStatus__c.field-meta.xml
<CustomField>
    <fullName>BLN_PaymentStatus__c</fullName>
    <description>FOUK-4686: This field is created to store Payment status value.</description>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>DECLINE</fullName>
            </value>
            <value>
                <fullName>INITIATED</fullName>
            </value>
            <value>
                <fullName>CANCELLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_PaymentType__c.field-meta.xml
<CustomField>
    <fullName>BLN_PaymentType__c</fullName>
    <description>FOUK-4686: This field is created to store Payment type value.</description>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ECOMMERCE</fullName>
            </value>
            <value>
                <fullName>CHIP &amp; PIN</fullName>
            </value>
            <value>
                <fullName>ONLINE PAYMENT</fullName>
            </value>
            <value>
                <fullName>BRANCH BANKING</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_Status__c.field-meta.xml
<CustomField>
    <fullName>BLN_Status__c</fullName>
    <description>FOUK-4686: This field is created to store Status value.</description>
    <label>Status</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_WorldPay_Token__c.field-meta.xml
<CustomField>
    <fullName>BLN_WorldPay_Token__c</fullName>
    <description>FOUK-6343 - Created to store the token received from worldpay for a customer card</description>
    <label>WorldPay Token</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BLN_WorldPayFinalControllerTest.cls
@isTest
public with sharing class BLN_WorldPayFinalControllerTest {
    /*@isTest
    public static void testFinal() {
        // Create test data
        Case c = new Case();
        c.Status='New';
        c.Type = 'Job Request';
        insert c;
        BLN_Payment__c testPayment = new BLN_Payment__c(
            // Populate required fields here
            BLN_PaymentAmountTaken__c = 250,
            BLN_Case__c = c.Id,
            BLN_InitiatedBy__c = 'Portal',
            BLN_InitiatedDateTime__c = Datetime.now(),
            BLN_PaymentStatus__c = 'Initiated',
            BLN_Status__c = 'Initiated',
            BLN_PaymentType__c = 'Online Payment',
            BLN_WorldPay_Token__c = 'testtoken',
            BLN_challengereference__c = 'test'
        );
        insert testPayment;
        String pid = testPayment.Id;

        
        // Start test
        Test.startTest();

        // Set up mock callout response
        Test.setMock(HttpCalloutMock.class, new BLN_WorldPayVerificationMock());
        // Call the method to be tested
       Map<String,String> returnmap = BLN_WorldPayFinalController.verification('test1234',pid);

        // Stop test
        Test.stopTest();
        //System.assertEquals(null, returnmap, 'Success message');
    }

    public class BLN_WorldPayVerificationMock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            // Create a fake response
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"outcome": "authenticated"}');
            res.setStatusCode(200);
            return res;
        }
    }*/
   
        
    @isTest
    static void testVerification() {
        Case c = new Case();
        c.Status='New';
        c.Type = 'Job Request';
        c.BLN_SubType__c = 'Job Request';
        insert c;
    
        BLN_Payment__c payment = new BLN_Payment__c();
        payment.BLN_PaymentAmountTaken__c = 250;
        payment.BLN_InitiatedDateTime__c = System.Now();
        payment.BLN_PaymentStatus__c = 'Initiated';
        payment.BLN_Case__c = c.Id;
    
     insert payment;
   	Id paymentId = payment.Id;
        
        // Mock the callout response
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

        // Define test parameters
       
        /*BLN_Payment__c testPayment =BLN_TestDataFactory.createPayments();
        insert testPayment;
        String paymentid = testPayment.Id;*/
        
        String challengeUrl = 'https://testurl.com';
       
        
        // Verify the future method execution
        Test.startTest();
         Map<String, String> result = BLN_WorldPayFinalController.verification(challengeUrl, paymentId);
        system.debug('result'+result );
        Test.stopTest();
        System.assert(c.Id != null, 'Result should not be null');
        
        
        // Perform any necessary assertions
        // Note: Since @future methods run asynchronously, you may not be able to directly capture the return value in the test method.
    }
    
    // Mock class to simulate callout response
    private class MockHttpResponseGenerator implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"outcome": "authenticated"}');
            res.setStatusCode(200);
            return res;
        }
    }



}