force-app/main/default/objects/BLN_Payment__c/BLN_Payment__c.object-meta.xml
<CustomObject>
    <description>FOUK-4686: This object is created to store Payment information.</description>
    <label>Payments &amp; Refunds</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments &amp; Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_Case__c.field-meta.xml
<CustomField>
    <fullName>BLN_Case__c</fullName>
    <description>FOUK-4686: This field is created to store case value.</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_challengereference__c.field-meta.xml
<CustomField>
    <fullName>BLN_challengereference__c</fullName>
    <label>Challengereference</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_InitiatedBy__c.field-meta.xml
<CustomField>
    <fullName>BLN_InitiatedBy__c</fullName>
    <description>FOUK-5664: This field is created to store Initiated By value on payment record.</description>
    <label>Initiated By</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_InitiatedDateTime__c.field-meta.xml
<CustomField>
    <fullName>BLN_InitiatedDateTime__c</fullName>
    <description>FOUK-5611 This is used in Refund record page</description>
    <label>Initiated Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_PaymentAmountTaken__c.field-meta.xml
<CustomField>
    <fullName>BLN_PaymentAmountTaken__c</fullName>
    <description>FOUK-4686: This field is created to store Payment amount taken value.</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_PaymentStatus__c.field-meta.xml
<CustomField>
    <fullName>BLN_PaymentStatus__c</fullName>
    <description>FOUK-4686: This field is created to store Payment status value.</description>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>DECLINE</fullName>
            </value>
            <value>
                <fullName>INITIATED</fullName>
            </value>
            <value>
                <fullName>CANCELLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_PaymentType__c.field-meta.xml
<CustomField>
    <fullName>BLN_PaymentType__c</fullName>
    <description>FOUK-4686: This field is created to store Payment type value.</description>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ECOMMERCE</fullName>
            </value>
            <value>
                <fullName>CHIP &amp; PIN</fullName>
            </value>
            <value>
                <fullName>ONLINE PAYMENT</fullName>
            </value>
            <value>
                <fullName>BRANCH BANKING</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_Status__c.field-meta.xml
<CustomField>
    <fullName>BLN_Status__c</fullName>
    <description>FOUK-4686: This field is created to store Status value.</description>
    <label>Status</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_WorldPay_Token__c.field-meta.xml
<CustomField>
    <fullName>BLN_WorldPay_Token__c</fullName>
    <description>FOUK-6343 - Created to store the token received from worldpay for a customer card</description>
    <label>WorldPay Token</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Vehicle__c/BLN_Vehicle__c.object-meta.xml
<CustomObject>
    <description>FOUK-495 This object is created for storing the Vehicles.</description>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{00000000}</displayFormat>
        <label>Vehicle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/BLN_AssistedPaymentsControllerTest.cls
/** 
 * @description : This test class is used for BLN_AssistedPaymentsController.
 * @Story : FOUK-4767
 * @Author: PwC-India
 * @Last Modified By: Subhamita Dutta
 * @Date: 06-06-2024
 */
@IsTest
public class BLN_AssistedPaymentsControllerTest {

    @TestSetup
    public static void setupTestData() {
        // Create and insert Contact
        Contact con = BLN_TestDataFactory.getContact('test');
        insert con;
        
        // Create and insert Vehicle
        BLN_Vehicle__c veh = BLN_TestDataFactory.getVehicle();
        insert veh;
        
        // Create and insert Case
        Case cases = BLN_TestDataFactory.getCase('Job Request', 'New');
        cases.ContactId = con.Id;
        cases.BLN_Vehicle__c = veh.Id; 
        insert cases;
        
        // Create and insert Payment
        BLN_Payment__c pays = BLN_TestDataFactory.createPayments( );
        pays.BLN_PaymentAmountTaken__c = 250;
    pays.BLN_Case__c = cases.Id;
    pays.BLN_InitiatedBy__c = 'Portal';
    pays.BLN_InitiatedDateTime__c = Datetime.now();
    pays.BLN_PaymentStatus__c = 'Initiated';
    pays.BLN_Status__c = 'Initiated';
    pays.BLN_PaymentType__c = 'Online Payment';
    pays.BLN_WorldPay_Token__c = 'testtoken';
    pays.BLN_challengereference__c = 'test';
    insert pays;
    }

    @IsTest
    public static void testGeneratedHexDigestKey() {
        // Retrieve the inserted payment record
        List<BLN_Payment__c> pays = [SELECT Id, BLN_PaymentAmountTaken__c FROM BLN_Payment__c LIMIT 1];
        
        if (!pays.isEmpty()){
        
        Test.startTest();
        // Call the method under test
            BLN_AssistedPaymentsController.generatedHexDigestkey(pays[0].Id);
        Test.stopTest();
        
        // Refresh the payment record to get the updated values
        pays = [SELECT Id, BLN_PaymentAmountTaken__c FROM BLN_Payment__c WHERE Id = :pays[0].Id LIMIT 1];
        
        // Assert that the payment amount is still correct
        System.assertnotEquals(200, pays[0].BLN_PaymentAmountTaken__c, 'The payment amount should match the expected value');
        }}

    @IsTest
    public static void testGeneratedHexDigestKeyWithInvalidId() {
        Test.startTest();
        try {
            // Call the method with an invalid payment Id
            BLN_AssistedPaymentsController.generatedHexDigestkey(null);
            System.assert(false, 'An exception should have been thrown for a null Id');
        } catch (Exception e) {
            // Assert that an exception is thrown
            System.assert(true, 'An exception was expected and thrown');
        }
        Test.stopTest();
    }
}