force-app/main/default/objects/BLN_Payment__c/BLN_Payment__c.object-meta.xml
<CustomObject>
    <description>FOUK-4686: This object is created to store Payment information.</description>
    <label>Payments &amp; Refunds</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments &amp; Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_Case__c.field-meta.xml
<CustomField>
    <fullName>BLN_Case__c</fullName>
    <description>FOUK-4686: This field is created to store case value.</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_PmtReferenceId__c.field-meta.xml
<CustomField>
    <fullName>BLN_PmtReferenceId__c</fullName>
    <description>FOUK-9426 To Store Value of Payment Reference</description>
    <label>Payment Reference</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LAD_Financial_Document__c/LAD_Financial_Document__c.object-meta.xml
<CustomObject>
    <description>Implementation of the Financial documents for Laddaw B2B platform. FOUK-10357</description>
    <label>Financial Document</label>
    <nameField>
        <displayFormat>FIN-{0000000}</displayFormat>
        <label>Financial Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LAD_Financial_Document__c/fields/LAD_Account__c.field-meta.xml
<CustomField>
    <fullName>LAD_Account__c</fullName>
    <description>Master-Detail relationship with Account Object. FOUK-10357</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Documents</relationshipLabel>
    <relationshipName>Financial_Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LAD_Financial_Document__c/fields/LAD_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>LAD_Due_Date__c</fullName>
    <description>To store the Due date of Financial Document. FOUK-10357</description>
    <label>Due Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/LAD_Financial_Document__c/fields/LAD_Order_Summary__c.field-meta.xml
<CustomField>
    <fullName>LAD_Order_Summary__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup Relation with the Order Summary object. FOUK-10357</description>
    <label>Order Summary</label>
    <referenceTo>OrderSummary</referenceTo>
    <relationshipLabel>Financial Documents</relationshipLabel>
    <relationshipName>Financial_Documents</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LAD_Financial_Document__c/fields/LAD_Remaining_Amount__c.field-meta.xml
<CustomField>
    <fullName>LAD_Remaining_Amount__c</fullName>
    <description>To store the Remaining Amount. FOUK-10357</description>
    <label>Remaining Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/LAD_Financial_Document__c/fields/LAD_Return_Order__c.field-meta.xml
<CustomField>
    <fullName>LAD_Return_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>FOUK-10472: Created to store reference to Return records for Credit Notes</description>
    <label>Return Order</label>
    <referenceTo>LAD_Return__c</referenceTo>
    <relationshipLabel>Financial Documents</relationshipLabel>
    <relationshipName>Financial_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LAD_Financial_Document__c/fields/LAD_Status__c.field-meta.xml
<CustomField>
    <fullName>LAD_Status__c</fullName>
    <description>To store the multiple value of Status. FOUK-10357</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LAD_Financial_Document__c/fields/LAD_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>LAD_Total_Amount__c</fullName>
    <description>To store the Total amount Price. FOUK-10357</description>
    <label>Total Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/LAD_Financial_Document__c/fields/LAD_Type__c.field-meta.xml
<CustomField>
    <fullName>LAD_Type__c</fullName>
    <description>To show the type of Financial Document. FOUK-10357</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Credit Note</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LAD_Financial_Document_Payment__c/LAD_Financial_Document_Payment__c.object-meta.xml
<CustomObject>
    <description>Junction Object for LAD_Financial_Document__c And BLN_Payment__c. FOUK-10357</description>
    <label>Financial Document Payment</label>
    <nameField>
        <label>Financial Document Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Document Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LAD_Financial_Document_Payment__c/fields/LAD_Financial_Document__c.field-meta.xml
<CustomField>
    <fullName>LAD_Financial_Document__c</fullName>
    <description>Master-Detail relationship with LAD_Financial_Document__c obj. FOUK-10357</description>
    <label>Financial Document</label>
    <referenceTo>LAD_Financial_Document__c</referenceTo>
    <relationshipLabel>Financial Document Payments</relationshipLabel>
    <relationshipName>Financial_Document_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LAD_Financial_Document_Payment__c/fields/LAD_Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>LAD_Paid_Amount__c</fullName>
    <description>Currency field to store the value of Amount, Paid.  FOUK-10357</description>
    <label>Paid Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/LAD_Financial_Document_Payment__c/fields/LAD_Payment__c.field-meta.xml
<CustomField>
    <fullName>LAD_Payment__c</fullName>
    <description>Master-Detail relationship with BLN_Payment__c object.  FOUK-10357</description>
    <label>Payment</label>
    <referenceTo>BLN_Payment__c</referenceTo>
    <relationshipLabel>Financial Document Payments</relationshipLabel>
    <relationshipName>Financial_Document_Payments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LAD_Return__c/LAD_Return__c.object-meta.xml
<CustomObject>
    <description>This Object Stores all the info of the Returned Order</description>
    <label>Return</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Return Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Returns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LAD_Return__c/fields/LAD_Account__c.field-meta.xml
<CustomField>
    <fullName>LAD_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stores Account Info</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Returns</relationshipLabel>
    <relationshipName>Returns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LAD_Return__c/fields/LAD_Original_Order_Summary__c.field-meta.xml
<CustomField>
    <fullName>LAD_Original_Order_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the original order summary</description>
    <label>Original Order Summary</label>
    <referenceTo>OrderSummary</referenceTo>
    <relationshipLabel>Returns</relationshipLabel>
    <relationshipName>Returns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LAD_Return__c/fields/LAD_Status__c.field-meta.xml
<CustomField>
    <fullName>LAD_Status__c</fullName>
    <description>This Fields is used to store Status of the Returned Order</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Return Submitted</fullName>
                <default>true</default>
                <label>Return Submitted</label>
            </value>
            <value>
                <fullName>Awaiting Inspection</fullName>
            </value>
            <value>
                <fullName>Return Accepted</fullName>
            </value>
            <value>
                <fullName>Return Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LAD_Return_Item__c/LAD_Return_Item__c.object-meta.xml
<CustomObject>
    <description>This Object stores all the Return Items info when an order is returned</description>
    <label>Return Item</label>
    <nameField>
        <displayFormat>RI-{0000000}</displayFormat>
        <label>Return Order Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Return Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LAD_Return_Item__c/fields/LAD_CreditNote__c.field-meta.xml
<CustomField>
    <fullName>LAD_CreditNote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A lookup field to Financial document object</description>
    <label>Credit Note</label>
    <referenceTo>LAD_Financial_Document__c</referenceTo>
    <relationshipLabel>Return Items</relationshipLabel>
    <relationshipName>Return_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LAD_Return_Item__c/fields/LAD_Original_Order_Summary_Product__c.field-meta.xml
<CustomField>
    <fullName>LAD_Original_Order_Summary_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the original order product summary</description>
    <label>Original Order Summary Product</label>
    <referenceTo>OrderItemSummary</referenceTo>
    <relationshipLabel>Return Items</relationshipLabel>
    <relationshipName>Return_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LAD_Return_Item__c/fields/LAD_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>LAD_Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This Fields is used to store Product Name from the Returned Order</description>
    <label>Product Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Return Items</relationshipLabel>
    <relationshipName>Return_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LAD_Return_Item__c/fields/LAD_Quantity_ordered__c.field-meta.xml
<CustomField>
    <fullName>LAD_Quantity_ordered__c</fullName>
    <description>This Fields is used to store Quantity Ordered of the returned order</description>
    <label>Quantity ordered</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LAD_Return_Item__c/fields/LAD_Quantity_returned__c.field-meta.xml
<CustomField>
    <fullName>LAD_Quantity_returned__c</fullName>
    <description>This Fields is used to store Quantity Returned of the Returned Order</description>
    <label>Quantity returned</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LAD_Return_Item__c/fields/LAD_Return_Order__c.field-meta.xml
<CustomField>
    <fullName>LAD_Return_Order__c</fullName>
    <description>This is a master-detail to Return Order Object</description>
    <label>Return Order</label>
    <referenceTo>LAD_Return__c</referenceTo>
    <relationshipLabel>Return Items</relationshipLabel>
    <relationshipName>Return_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LAD_Return_Item__c/fields/LAD_Sales_Code__c.field-meta.xml
<CustomField>
    <fullName>LAD_Sales_Code__c</fullName>
    <description>This Fields is used to store Sales Code of the Returned Order</description>
    <label>Sales Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LAD_Return_Item__c/fields/LAD_Status__c.field-meta.xml
<CustomField>
    <fullName>LAD_Status__c</fullName>
    <description>This Field is used to store Status of the Returned Item</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Return Submitted</fullName>
                <default>true</default>
                <label>Return Submitted</label>
            </value>
            <value>
                <fullName>Awaiting Inspection</fullName>
            </value>
            <value>
                <fullName>Return Accepted</fullName>
            </value>
            <value>
                <fullName>Return Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LAD_InvoiceHandlerTest.cls
/** @description :  Test Class for LAD_InvoiceHandler, LAD_ScheduleFinancialDocumentCreation, LAD_InvoiceCreationBatch and LAD_CreditNoteCreationBatch
*   @Story :        FOUK-8908; FOUK-10157; FOUK-8956; FOUK-10522; FOUK-10582
*   @author:        (binayak.debnath@pwc.com(IN)) (hrithas.sardar@pwc.com (IN))
*   @CreatedDate:   04-10-2024
*/
@isTest
public with sharing class LAD_InvoiceHandlerTest {
    /**@MethodName :    testFinDocCreation
    * @description :    This method is used to test LAD_ScheduleFinancialDocumentCreation, LAD_InvoiceCreationBatch and LAD_CreditNoteCreationBatch class.
    * @param:           
    * @return:          
    */
    //(SeeAllData = true) is essential for using ConnectApi methods. We need ConnectApi methods to create Order Summary records.
    @isTest(SeeAllData = true) 
    static void testFinDocCreation(){
        Account testAccount = new Account(Name = 'ABC Corp');
        testAccount.BLN_PaymentTerms__c = '5 END OF MONTH';
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('LAD_B2B_Commerce_Account').getRecordTypeId();
        testAccount.RecordTypeId = recordTypeId;
        insert testAccount;
        Contact testContact = New Contact(LastName = 'Test', AccountID = testAccount.id);
        insert testContact;
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Laddaw B2B Commerce External User' LIMIT 1];
        user testUser = New User(UserName = 'test_' + math.random() + '@test.com',
                                 FirstName = 'Test-First',
                                 LastName = 'Test-Last',
                                 Alias = 'test',
                                 email = 'test' + math.random() + '@test.com',
                                 CommunityNickName = string.valueOf(math.random()).substring(0,6),
                                 ProfileID = p.id,
                                 ContactId = testContact.Id,
                                 TimeZoneSidKey = 'America/New_York', 
                                 LocaleSidKey = 'en_US', 
                                 EmailEncodingKey = 'UTF-8', 
                                 LanguageLocaleKey = 'en_US');
        insert testUser; 
        
        Product2 testProduct1 = new Product2(Name = 'Test Product 1', ProductCode = 'Prod1');
        Product2 testProduct2 = new Product2(Name = 'Test Product 2', ProductCode = 'Prod2');
        Product2 testProduct3 = new Product2(Name = 'Test Product 3', ProductCode = 'Prod3');

        insert testProduct1;
        insert testProduct2;
        insert testProduct3;

        Product2 testProduct4 = new Product2(Name = 'Test Product 4');
        insert testProduct4;

        WebStore testStore = new WebStore(Name = 'test Store',
                                          OptionsAutoFacetingEnabled = true,
                                          OptionsCartToOrderAutoCustomFieldMapping = true,	
                                          OptionsCommerceEinsteinActivitiesTracked = true,	                                             
                                          OptionsCommerceEinsteinDeployed = true,	
                                          OptionsGuestBrowsingEnabled = true,	                                             
                                          OptionsSkipAdditionalEntitlementCheckForSearch = true);
        insert testStore;

        Id pricebookId = Test.getStandardPricebookId();
        Pricebook2 standardPricebook = new Pricebook2(
            Id = pricebookId,
            IsActive = true
        );
        update standardPricebook;

        Order testOrder = new Order();
        testOrder.SalesStoreId = testStore.Id;
        testOrder.AccountId = testAccount.id;
        testOrder.Status = 'Draft';
        //testOrder.PoNumber = activeCart.PoNumber;
        //testOrder.LAD_Created_by_Upload__c = activeCart.LAD_Created_by_Upload__c;
        testOrder.Pricebook2Id = standardPricebook.Id;
        testOrder.EffectiveDate = Date.today();
        testOrder.Description = 'Test';
        insert testOrder;
      
		OrderDeliveryMethod testDelMethod = new OrderDeliveryMethod(name = 'TestMethod', isActive = true);
        insert testDelMethod;

        OrderDeliveryGroup testOrdGroup = new OrderDeliveryGroup(   
                                                                    LAD_Name__c = 'Laddaw-Delivery-0001', 
                                                                    OrderId = testOrder.id, 
                                                                    OrderDeliveryMethodId = testDelMethod.Id, 
                                                                    DeliverToName = testUser.FirstName);
        insert testOrdGroup;

        List<Product2> productList = new List<Product2>{testProduct1, testProduct2, testProduct3};

        
        for(Integer i = 0; i < productList.size() ; i ++ ){
            /* PriceBookEntry testEntry = new PriceBookEntry(product2id = productList[i].id, pricebook2id = standardPricebook.Id, UnitPrice = 10);
            insert testEntry; */
            PriceBookEntry testEntry = [SELECT Id FROM PriceBookEntry WHERE pricebook2Id = :standardPriceBook.Id AND product2id = :productList[i].id LIMIT 1];
            OrderItem testOrdItem = new OrderItem(  product2id = productList[i].id,
                                                    Quantity = (i + 1) * 10,
                                                    OrderDeliveryGroupId = testOrdGroup.id, 
                                                    orderId = testOrder.id,
                                                    PriceBookEntryId = testEntry.Id,
                                                    unitprice = 0);
            insert testOrdItem; 
        }

        testOrder.OrderedDate = Date.today();
        testOrder.Status = 'Activated';

        update testOrder;

        ConnectApi.OrderSummaryInputRepresentation osir = new ConnectApi.OrderSummaryInputRepresentation();

        osir.orderId = testOrder.Id;
        osir.orderLifeCycleType='UNMANAGED';

        ConnectApi.OrderSummaryOutputRepresentation osor = ConnectApi.OrderSummaryCreation.createOrderSummary(osir);

        System.debug([SELECT OrderedDate FROM OrderSummary WHERE Id = :osor.orderSummaryId]);

        List<OrderItemSummary> itemList = [SELECT LAD_Status__c FROM OrderItemSummary WHERE OrderSummaryId = :osor.orderSummaryId];
        for(OrderItemSummary item : itemList){
            item.LAD_Status__c = 'Shipped';
        }

        update itemList;

        LAD_Return__c returnOrder1 = new LAD_Return__c(
            LAD_Account__c = testAccount.Id,
            LAD_Original_Order_Summary__c = osor.orderSummaryId
        );
        
        insert new List<LAD_Return__c>{ returnOrder1};

        LAD_Return_Item__c returnItem1 = new LAD_Return_Item__c(
            LAD_Sales_Code__c = 'SC001',
            LAD_Quantity_ordered__c = 5,
            LAD_Quantity_returned__c = 2,
            LAD_Product_Name__c = testProduct1.Id,
            LAD_Return_Order__c = returnOrder1.Id,
            LAD_Status__c = 'Return Accepted',
            LAD_Original_Order_Summary_Product__c = [SELECT Id FROM OrderItemSummary WHERE Product2Id = :testProduct1.Id LIMIT 1].Id
        );
        
        LAD_Return_Item__c returnItem2 = new LAD_Return_Item__c(
            LAD_Sales_Code__c = 'SC002',
            LAD_Quantity_ordered__c = 10,
            LAD_Quantity_returned__c = 5,
            LAD_Product_Name__c = testProduct2.Id,
            LAD_Return_Order__c = returnOrder1.Id,
            LAD_Status__c = 'Return Accepted',
            LAD_Original_Order_Summary_Product__c = [SELECT Id FROM OrderItemSummary WHERE Product2Id = :testProduct2.Id LIMIT 1].Id
        );
        
        insert new List<LAD_Return_Item__c>{ returnItem1, returnItem2 };

        String jobIdInvoice = System.schedule('test job', '0 0 * * * ?', new LAD_ScheduleFinancialDocumentCreation());


        Test.startTest();
        Test.stopTest();
    }

    /**@MethodName :    testFetchFinDoc
    * @description :    This method is used to test LAD_InvoiceHandler class.
    * @param:           
    * @return:          
    */

    //(SeeAllData = true) is essential for using ConnectApi methods. We need ConnectApi methods to create Order Summary records.
    @isTest(SeeAllData = true) 
    static void testFetchFinDoc(){
        Account testAccount = new Account(Name = 'ABC Corp');
        testAccount.BLN_PaymentTerms__c = '5 END OF MONTH';
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('LAD_B2B_Commerce_Account').getRecordTypeId();
        testAccount.RecordTypeId = recordTypeId;
        insert testAccount;
        Contact testContact = New Contact(LastName = 'Test', AccountID = testAccount.id);
        insert testContact;
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Laddaw B2B Commerce External User' LIMIT 1];
        user testUser = New User(UserName = 'test_' + math.random() + '@test.com',
                                 FirstName = 'Test-First',
                                 LastName = 'Test-Last',
                                 Alias = 'test',
                                 email = 'test' + math.random() + '@test.com',
                                 CommunityNickName = string.valueOf(math.random()).substring(0,6),
                                 ProfileID = p.id,
                                 ContactId = testContact.Id,
                                 TimeZoneSidKey = 'America/New_York', 
                                 LocaleSidKey = 'en_US', 
                                 EmailEncodingKey = 'UTF-8', 
                                 LanguageLocaleKey = 'en_US');
        insert testUser; 
        
        Product2 testProduct1 = new Product2(Name = 'Test Product 1', ProductCode = 'Prod1');
        Product2 testProduct2 = new Product2(Name = 'Test Product 2', ProductCode = 'Prod2');
        Product2 testProduct3 = new Product2(Name = 'Test Product 3', ProductCode = 'Prod3');

        insert testProduct1;
        insert testProduct2;
        insert testProduct3;

        Product2 testProduct4 = new Product2(Name = 'Test Product 4');
        insert testProduct4;

        WebStore testStore = new WebStore(Name = 'test Store',
                                          OptionsAutoFacetingEnabled = true,
                                          OptionsCartToOrderAutoCustomFieldMapping = true,	
                                          OptionsCommerceEinsteinActivitiesTracked = true,	                                             
                                          OptionsCommerceEinsteinDeployed = true,	
                                          OptionsGuestBrowsingEnabled = true,	                                             
                                          OptionsSkipAdditionalEntitlementCheckForSearch = true);
        insert testStore;

        Id pricebookId = Test.getStandardPricebookId();
        Pricebook2 standardPricebook = new Pricebook2(
            Id = pricebookId,
            IsActive = true
        );
        update standardPricebook;

        Order testOrder = new Order();
        testOrder.SalesStoreId = testStore.Id;
        testOrder.AccountId = testAccount.id;
        testOrder.Status = 'Draft';
        testOrder.PoNumber = '00ii20j020';
        //testOrder.LAD_Created_by_Upload__c = activeCart.LAD_Created_by_Upload__c;
        testOrder.Pricebook2Id = standardPricebook.Id;
        testOrder.EffectiveDate = Date.today();
        testOrder.Description = 'Test';
        insert testOrder;
      
		OrderDeliveryMethod testDelMethod = new OrderDeliveryMethod(name = 'TestMethod', isActive = true);
        insert testDelMethod;

        OrderDeliveryGroup testOrdGroup = new OrderDeliveryGroup(   
                                                                    LAD_Name__c = 'Laddaw-Delivery-0001', 
                                                                    OrderId = testOrder.id, 
                                                                    OrderDeliveryMethodId = testDelMethod.Id, 
                                                                    DeliverToName = testUser.FirstName);
        insert testOrdGroup;

        List<Product2> productList = new List<Product2>{testProduct1, testProduct2, testProduct3};

        
        for(Integer i = 0; i < productList.size() ; i ++ ){
            /* PriceBookEntry testEntry = new PriceBookEntry(product2id = productList[i].id, pricebook2id = standardPricebook.Id, UnitPrice = 10);
            insert testEntry; */
            PriceBookEntry testEntry = [SELECT Id FROM PriceBookEntry WHERE pricebook2Id = :standardPriceBook.Id AND product2id = :productList[i].id LIMIT 1];
            OrderItem testOrdItem = new OrderItem(  product2id = productList[i].id,
                                                    Quantity = (i + 1) * 10,
                                                    OrderDeliveryGroupId = testOrdGroup.id, 
                                                    orderId = testOrder.id,
                                                    PriceBookEntryId = testEntry.Id,
                                                    unitprice = 0,
                                                    LAD_PO_Number__c = '00000000' + String.valueOf(i + 1));
            insert testOrdItem; 
        }

        testOrder.OrderedDate = Date.today();
        testOrder.Status = 'Activated';

        update testOrder;

        ConnectApi.OrderSummaryInputRepresentation osir = new ConnectApi.OrderSummaryInputRepresentation();

        osir.orderId = testOrder.Id;
        osir.orderLifeCycleType='UNMANAGED';

        ConnectApi.OrderSummaryOutputRepresentation osor = ConnectApi.OrderSummaryCreation.createOrderSummary(osir);

        System.debug([SELECT OrderedDate FROM OrderSummary WHERE Id = :osor.orderSummaryId]);

        //Create Invoices and Payment records
        LAD_Financial_Document__c finDoc = new LAD_Financial_Document__c(LAD_Account__c = testAccount.Id, 
                                                                        LAD_Order_Summary__c = osor.orderSummaryId, 
                                                                        LAD_Type__c = 'Invoice',
                                                                        LAD_Total_Amount__c = 100,
                                                                        LAD_Remaining_Amount__c = 100,
                                                                        LAD_Status__c = 'Open',
                                                                        LAD_Due_Date__c = Date.today());
                                        
        insert finDoc;
        
        List<OrderItemSummary> itemList = [SELECT LAD_Status__c FROM OrderItemSummary WHERE OrderSummaryId = :osor.orderSummaryId];
        for(OrderItemSummary item : itemList){
            item.LAD_Status__c = 'Shipped';
            item.LAD_Invoice__c = finDoc.Id;
        }

        update itemList;

        Id jobReqId = SObjectType.Case.getRecordTypeInfosByDeveloperName().get('LAD_Laddaw_Case').getRecordTypeId();
        Case testCase = new Case(RecordTypeId = jobReqId, Status = 'New', AccountId = testAccount.Id, ContactId = testContact.Id);
        insert testCase;

        List<BLN_Payment__c> paymentList = new List<BLN_Payment__c>();
        for(Integer i = 0; i < 3; i++){
            BLN_Payment__c testPayment = new BLN_Payment__c(BLN_Case__c = testCase.Id, BLN_PmtReferenceId__c = 'Testioweuvqw' + String.valueOf(i));
            paymentList.add(testPayment);
        }
        
        insert paymentList;

        List<LAD_Financial_Document_Payment__c> finDocPayList = new List<LAD_Financial_Document_Payment__c>();
        for(Integer i = 0; i < paymentList.size(); i++){
            LAD_Financial_Document_Payment__c test = new LAD_Financial_Document_Payment__c( Name = 'Test' + i, 
                                                                                            LAD_Financial_Document__c = finDoc.Id, 
                                                                                            LAD_Payment__c = paymentList[i].Id,
                                                                                            LAD_Paid_Amount__c = 100);
            finDocPayList.add(test);
        }

        insert finDocPayList;

        //Create Credit Notes
        LAD_Return__c returnOrder1 = new LAD_Return__c(
            LAD_Account__c = testAccount.Id,
            LAD_Original_Order_Summary__c = osor.orderSummaryId
        );
        
        insert new List<LAD_Return__c>{ returnOrder1};

        LAD_Return_Item__c returnItem1 = new LAD_Return_Item__c(
            LAD_Sales_Code__c = 'SC001',
            LAD_Quantity_ordered__c = 5,
            LAD_Quantity_returned__c = 2,
            LAD_Product_Name__c = testProduct1.Id,
            LAD_Return_Order__c = returnOrder1.Id,
            LAD_Status__c = 'Return Accepted'
        );
        
        LAD_Return_Item__c returnItem2 = new LAD_Return_Item__c(
            LAD_Sales_Code__c = 'SC002',
            LAD_Quantity_ordered__c = 10,
            LAD_Quantity_returned__c = 5,
            LAD_Product_Name__c = testProduct2.Id,
            LAD_Return_Order__c = returnOrder1.Id,
            LAD_Status__c = 'Return Accepted'
        );
        
        insert new List<LAD_Return_Item__c>{ returnItem1, returnItem2 };

        LAD_Financial_Document__c creditDoc = new LAD_Financial_Document__c(   LAD_Account__c = testAccount.Id, 
                                                                            LAD_Return_Order__c = returnOrder1.Id, 
                                                                            LAD_Type__c = 'Credit Note',
                                                                            LAD_Total_Amount__c = -100,
                                                                            LAD_Remaining_Amount__c = -100,
                                                                            LAD_Status__c = 'Open',
                                                                            LAD_Due_Date__c = Date.today());

        insert creditDoc;

        returnItem1.LAD_CreditNote__c = creditDoc.Id;
        returnItem2.LAD_CreditNote__c = creditDoc.Id;
        update new List<LAD_Return_Item__c>{ returnItem1, returnItem2 };

        LAD_InvoiceHandler.FinancialDocInputWrapper wrap = new LAD_InvoiceHandler.FinancialDocInputWrapper();
        wrap.accountId = testAccount.Id;

        Test.startTest();
        List<LAD_InvoiceHandler.FinancialDocOutputWrapper> returnWrap = LAD_InvoiceHandler.fetchFinancialDocuments(wrap);
        Test.stopTest();

        System.Assert.areEqual(returnWrap.size(), 2);

        String orange = LAD_InvoiceHandler.invoiceBannerCheck(testAccount.Id);
        System.Assert.areEqual(orange, 'Orange');


        finDoc.LAD_Due_Date__c = Date.today().addDays(4);
        update finDoc;

        String blue = LAD_InvoiceHandler.invoiceBannerCheck(testAccount.Id);
        System.Assert.areEqual(blue, 'Blue');


        finDoc.LAD_Due_Date__c = Date.today().addDays(-3);
        update finDoc;

        String red = LAD_InvoiceHandler.invoiceBannerCheck(testAccount.Id);
        System.Assert.areEqual(red, 'Red');

/*         Date cutoffDate = Date.today().addYears(-3); 
        Test.setCreatedDate(finDoc.Id, cutoffDate); */
        LAD_InvoiceHandler.invokeDeleteFinancialDocumentBatch();

        LAD_InvoiceHandler.fetchVFBaseURL();
    }

    
}