force-app/main/default/objects/BLN_Payment__c/BLN_Payment__c.object-meta.xml
<CustomObject>
    <description>FOUK-4686: This object is created to store Payment information.</description>
    <label>Payments &amp; Refunds</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments &amp; Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_PmtReferenceId__c.field-meta.xml
<CustomField>
    <fullName>BLN_PmtReferenceId__c</fullName>
    <description>FOUK-9426 To Store Value of Payment Reference</description>
    <label>Payment Reference</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LAD_Financial_Document__c/LAD_Financial_Document__c.object-meta.xml
<CustomObject>
    <description>Implementation of the Financial documents for Laddaw B2B platform. FOUK-10357</description>
    <label>Financial Document</label>
    <nameField>
        <displayFormat>FIN-{0000000}</displayFormat>
        <label>Financial Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LAD_Financial_Document__c/fields/LAD_Account__c.field-meta.xml
<CustomField>
    <fullName>LAD_Account__c</fullName>
    <description>Master-Detail relationship with Account Object. FOUK-10357</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Documents</relationshipLabel>
    <relationshipName>Financial_Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LAD_Financial_Document__c/fields/LAD_Document_Number__c.field-meta.xml
<CustomField>
    <fullName>LAD_Document_Number__c</fullName>
    <description>FOUK-10357: To store the Document Number.</description>
    <displayFormat>2{0000000}</displayFormat>
    <externalId>true</externalId>
    <label>Document Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/LAD_Financial_Document__c/fields/LAD_Document_URL__c.field-meta.xml
<CustomField>
    <fullName>LAD_Document_URL__c</fullName>
    <description>To store the URL of the Document. FOUK-10357</description>
    <label>Document URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LAD_Financial_Document__c/fields/LAD_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>LAD_Due_Date__c</fullName>
    <description>To store the Due date of Financial Document. FOUK-10357</description>
    <label>Due Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/LAD_Financial_Document__c/fields/LAD_Order_Summary__c.field-meta.xml
<CustomField>
    <fullName>LAD_Order_Summary__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup Relation with the Order Summary object. FOUK-10357</description>
    <label>Order Summary</label>
    <referenceTo>OrderSummary</referenceTo>
    <relationshipLabel>Financial Documents</relationshipLabel>
    <relationshipName>Financial_Documents</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LAD_Financial_Document__c/fields/LAD_Remaining_Amount__c.field-meta.xml
<CustomField>
    <fullName>LAD_Remaining_Amount__c</fullName>
    <description>To store the Remaining Amount. FOUK-10357</description>
    <label>Remaining Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/LAD_Financial_Document__c/fields/LAD_Return_Order__c.field-meta.xml
<CustomField>
    <fullName>LAD_Return_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>FOUK-10472: Created to store reference to Return records for Credit Notes</description>
    <label>Return Order</label>
    <referenceTo>LAD_Return__c</referenceTo>
    <relationshipLabel>Financial Documents</relationshipLabel>
    <relationshipName>Financial_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LAD_Financial_Document__c/fields/LAD_Status__c.field-meta.xml
<CustomField>
    <fullName>LAD_Status__c</fullName>
    <description>To store the multiple value of Status. FOUK-10357</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LAD_Financial_Document__c/fields/LAD_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>LAD_Total_Amount__c</fullName>
    <description>To store the Total amount Price. FOUK-10357</description>
    <label>Total Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/LAD_Financial_Document__c/fields/LAD_Type__c.field-meta.xml
<CustomField>
    <fullName>LAD_Type__c</fullName>
    <description>To show the type of Financial Document. FOUK-10357</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Credit Note</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LAD_Financial_Document_Payment__c/LAD_Financial_Document_Payment__c.object-meta.xml
<CustomObject>
    <description>Junction Object for LAD_Financial_Document__c And BLN_Payment__c. FOUK-10357</description>
    <label>Financial Document Payment</label>
    <nameField>
        <label>Financial Document Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Document Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LAD_Financial_Document_Payment__c/fields/LAD_Financial_Document__c.field-meta.xml
<CustomField>
    <fullName>LAD_Financial_Document__c</fullName>
    <description>Master-Detail relationship with LAD_Financial_Document__c obj. FOUK-10357</description>
    <label>Financial Document</label>
    <referenceTo>LAD_Financial_Document__c</referenceTo>
    <relationshipLabel>Financial Document Payments</relationshipLabel>
    <relationshipName>Financial_Document_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LAD_Financial_Document_Payment__c/fields/LAD_Payment__c.field-meta.xml
<CustomField>
    <fullName>LAD_Payment__c</fullName>
    <description>Master-Detail relationship with BLN_Payment__c object.  FOUK-10357</description>
    <label>Payment</label>
    <referenceTo>BLN_Payment__c</referenceTo>
    <relationshipLabel>Financial Document Payments</relationshipLabel>
    <relationshipName>Financial_Document_Payments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LAD_Return__c/LAD_Return__c.object-meta.xml
<CustomObject>
    <description>This Object Stores all the info of the Returned Order</description>
    <label>Return</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Return Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Returns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LAD_Return__c/fields/LAD_Account__c.field-meta.xml
<CustomField>
    <fullName>LAD_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stores Account Info</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Returns</relationshipLabel>
    <relationshipName>Returns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LAD_Return__c/fields/LAD_Original_Order_Summary__c.field-meta.xml
<CustomField>
    <fullName>LAD_Original_Order_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the original order summary</description>
    <label>Original Order Summary</label>
    <referenceTo>OrderSummary</referenceTo>
    <relationshipLabel>Returns</relationshipLabel>
    <relationshipName>Returns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LAD_Return__c/fields/LAD_Status__c.field-meta.xml
<CustomField>
    <fullName>LAD_Status__c</fullName>
    <description>This Fields is used to store Status of the Returned Order</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Return Submitted</fullName>
                <default>true</default>
                <label>Return Submitted</label>
            </value>
            <value>
                <fullName>Awaiting Inspection</fullName>
            </value>
            <value>
                <fullName>Return Accepted</fullName>
            </value>
            <value>
                <fullName>Return Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LAD_Return_Item__c/LAD_Return_Item__c.object-meta.xml
<CustomObject>
    <description>This Object stores all the Return Items info when an order is returned</description>
    <label>Return Item</label>
    <nameField>
        <displayFormat>RI-{0000000}</displayFormat>
        <label>Return Order Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Return Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LAD_Return_Item__c/fields/LAD_CreditNote__c.field-meta.xml
<CustomField>
    <fullName>LAD_CreditNote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A lookup field to Financial document object</description>
    <label>Credit Note</label>
    <referenceTo>LAD_Financial_Document__c</referenceTo>
    <relationshipLabel>Return Items</relationshipLabel>
    <relationshipName>Return_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LAD_Return_Item__c/fields/LAD_Original_Order_Summary_Product__c.field-meta.xml
<CustomField>
    <fullName>LAD_Original_Order_Summary_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the original order product summary</description>
    <label>Original Order Summary Product</label>
    <referenceTo>OrderItemSummary</referenceTo>
    <relationshipLabel>Return Items</relationshipLabel>
    <relationshipName>Return_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LAD_Return_Item__c/fields/LAD_Return_Order__c.field-meta.xml
<CustomField>
    <fullName>LAD_Return_Order__c</fullName>
    <description>This is a master-detail to Return Order Object</description>
    <label>Return Order</label>
    <referenceTo>LAD_Return__c</referenceTo>
    <relationshipLabel>Return Items</relationshipLabel>
    <relationshipName>Return_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LAD_Return_Item__c/fields/LAD_Status__c.field-meta.xml
<CustomField>
    <fullName>LAD_Status__c</fullName>
    <description>This Field is used to store Status of the Returned Item</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Return Submitted</fullName>
                <default>true</default>
                <label>Return Submitted</label>
            </value>
            <value>
                <fullName>Awaiting Inspection</fullName>
            </value>
            <value>
                <fullName>Return Accepted</fullName>
            </value>
            <value>
                <fullName>Return Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LAD_InvoiceHandler.cls
/** @description :  This apex class is used to delete Financial Document records based on the time limit set by the user.
*   @Story :        FOUK-8908; FOUK-10157; FOUK-8956
*   @author:        (binayak.debnath@pwc.com(IN)) (hrithas.sardar@pwc.com (IN))
*   @CreatedDate:   23-09-2024
*/

public with sharing class LAD_InvoiceHandler {
    
    /**@MethodName :    fetchVFBaseURL
    * @description :    Returns base VF Page url for the org.
    * @param:           
    * @return:          String
    */
    @AuraEnabled 
    public static String fetchVFBaseURL(){
        return 'https://' + DomainCreator.getVisualforceHostname(null);
    }

    /**@MethodName :    invokeFinancialDocumentBatch
    * @description :    This method when invoked by a scheduled flow runs to delete Financial Document records based on the time limit set by the user.
    * @param:           
    * @return:          void
    * story:            FOUK-8956
    */
    @InvocableMethod
    public static void invokeDeleteFinancialDocumentBatch(){
        try {
            LAD_DeleteFinancialDocumentsBatch batch = new LAD_DeleteFinancialDocumentsBatch();
            Database.executeBatch(batch, 200);
        } catch (Exception e) {
            BLN_ExceptionLogger.captureException(e);
        }
    }

    /**@MethodName :    invoiceBannerCheck
    * @description :    This method is used to return the colour of the Payment Reminder Banner to be displayed based on Invoice data for the Account.
    * @param:           String accountId
    * @return:          string
    * story:            FOUK-10157
    */
    @AuraEnabled
    public static string invoiceBannerCheck(String accountId){
        try {
            String color;
            Date sevenDaysFromToday = Date.today().addDays(7);
            Date today = Date.today();
            List<LAD_Financial_Document__c> fin = new List<LAD_Financial_Document__c>();
            fin = [SELECT Id, LAD_Due_Date__c FROM LAD_Financial_Document__c WHERE LAD_Type__c = 'Invoice' AND LAD_Status__c = 'Open' AND LAD_Account__c = :accountId AND LAD_Due_Date__c <= :today LIMIT 1];
            if(fin.size() != 0){
                return fin[0].LAD_Due_Date__c == today ? 'Orange' : 'Red';
            }

            fin = [SELECT Id, LAD_Due_Date__c FROM LAD_Financial_Document__c WHERE LAD_Type__c = 'Invoice' AND LAD_Status__c = 'Open' AND LAD_Account__c = :accountId AND LAD_Due_Date__c <= :sevenDaysFromToday LIMIT 1];
            if(fin.size() != 0){
                return 'Blue';
            }
            return null;
    
        } catch (Exception e) {
            BLN_ExceptionLogger.captureException(e);
            return null;        
        }
    }


    public class FinancialDocInputWrapper{
        @AuraEnabled public String accountId{get; set;}
        @AuraEnabled public String issuedStartDate{get; set;}
        @AuraEnabled public String issuedEndDate{get; set;}
        @AuraEnabled public String dueStartDate{get; set;}
        @AuraEnabled public String dueEndDate{get; set;}
        @AuraEnabled public String searchMode{get; set;}
        @AuraEnabled public String documentNumber{get; set;}
        @AuraEnabled public String orderNumber{get; set;}

    }

    public class FinancialDocOutputWrapper{
        @AuraEnabled public String FinDocId;
        @AuraEnabled public String DocumentNumber;
        @AuraEnabled public String Type;
        @AuraEnabled public String CreatedDate;
        @AuraEnabled public String OrderNumber;
        @AuraEnabled public String OrderPONumber;
        @AuraEnabled public String PaymentId;
        @AuraEnabled public String TotalAmount;
        @AuraEnabled public String RemainingAmount;
        @AuraEnabled public String RemainingAmountValue;
        @AuraEnabled public String CurrencyIsoCode;
        @AuraEnabled public String DueDate;
        @AuraEnabled public String PaymentStatus;
        @AuraEnabled public String pdfURL;
        @AuraEnabled public Boolean disablePayNow;
        @AuraEnabled public Boolean disableDownloadPDF;
        @AuraEnabled public Boolean disableCheckbox;
        @AuraEnabled public Boolean disablePaymentTooltip;
        @AuraEnabled public Boolean disablePoTooltip;
        @AuraEnabled public String PaymentIdTooltip;
        @AuraEnabled public String OrderPoNumberToolTip;

    }

    /**@MethodName :    fetchFinancialDocuments
    * @description :    This method is used to return Financial Document data in a formatted manner to display in the Invoice Summary Page.
    * @param:           FinancialDocInputWrapper parameters
    * @return:          List<FinancialDocOutputWrapper>
    * story:            FOUK-8908
    */
    @AuraEnabled
    public static List<FinancialDocOutputWrapper> fetchFinancialDocuments(FinancialDocInputWrapper parameters){
        List<FinancialDocOutputWrapper> returnWrapper = new List<FinancialDocOutputWrapper>(); 
        Set<String> orderSummaryIdSet = new Set<String>();
        Set<String> returnIdSet = new Set<String>();
        Set<String> finDocIdSet = new Set<String>();
        Map<String, Set<String>> finDocIdPoNumbersMap = new Map<String, Set<String>>();
        try {
            string accountId = parameters.accountId;
            Date issuedStartDate = parameters.issuedStartDate != null ? Date.valueOf(parameters.issuedStartDate) : null;
            Date issuedEndDate = parameters.issuedEndDate != null  ? Date.valueOf(parameters.issuedEndDate).addDays(1) : null;
            Date dueStartDate = parameters.dueStartDate != null  ? Date.valueOf(parameters.dueStartDate) : null;
            Date dueEndDate = parameters.dueEndDate != null  ? Date.valueOf(parameters.dueEndDate).addDays(1) : null;
            String searchMode = parameters.searchMode;
            String documentNumber = parameters.documentNumber;
            String orderNumber = parameters.orderNumber;
            String issueFilter = issuedStartDate != null && issuedEndDate != null ? 'AND CreatedDate >=:issuedStartDate AND CreatedDate <=:issuedEndDate ' : '';
            String dueFilter = dueStartDate != null && dueEndDate != null ? 'AND LAD_Due_Date__c >=:dueStartDate AND LAD_Due_Date__c <=:dueEndDate ' : '';

            String query = 'SELECT  Id, ' +
                                    'LAD_Document_Number__c, ' +
                                    'LAD_Type__c, ' +
                                    'LAD_Status__c, ' +
                                    'CreatedDate, ' +
                                    'LAD_Order_Summary__c, ' +
                                    'LAD_Order_Summary__r.OrderNumber, ' +
                                    'LAD_Order_Summary__r.PoNumber, ' +
                                    'LAD_Return_Order__c, ' +
                                    'LAD_Return_Order__r.LAD_Original_Order_Summary__r.PoNumber, ' +
                                    'LAD_Return_Order__r.LAD_Original_Order_Summary__r.OrderNumber, ' +
                                    'CurrencyIsoCode, ' +
                                    'LAD_Total_Amount__c, ' +
                                    'LAD_Remaining_Amount__c, ' +
                                    'LAD_Due_Date__c, ' +
                                    'LAD_Document_URL__c, ' +
                                    'LAD_Account__c, ' +
                                    '(SELECT LAD_Payment__r.BLN_PmtReferenceId__c FROM Financial_Document_Payments__r) ' +
                            'FROM LAD_Financial_Document__c ' +
                            'WHERE LAD_Account__c = :accountId ' +
                            issueFilter + dueFilter +
                            'ORDER BY CreatedDate DESC LIMIT 500 ';
            List<LAD_Financial_Document__c> finDocList = Database.query(query);

            //Create Set of Order Summary Ids and Map of Order Summary Id to Summary PO for Invoices
            //Create Set of Return Ids for Credit Notes
            for(LAD_Financial_Document__c fin: finDocList){
                if(fin.LAD_Order_Summary__c != null && fin.LAD_Order_Summary__r.PoNumber != null){
                    finDocIdPoNumbersMap.put(fin.Id, new Set<String>{fin.LAD_Order_Summary__r.PoNumber});
                }
                else if(fin.LAD_Return_Order__c != null && fin.LAD_Return_Order__r.LAD_Original_Order_Summary__r.PoNumber != null){
                    finDocIdPoNumbersMap.put(fin.Id, new Set<String>{fin.LAD_Return_Order__r.LAD_Original_Order_Summary__r.PoNumber});
                }
                orderSummaryIdSet.add(fin.LAD_Order_Summary__c);
                returnIdSet.add(fin.LAD_Return_Order__c);
                finDocIdSet.add(fin.Id);
            }

            //Fetch all Order Item Summaries for Order Summaries and add to Map
            for(OrderItemSummary itemSum : [SELECT Id, LAD_PO_Number__c, OrderSummaryId, LAD_Invoice__c FROM OrderItemSummary WHERE OrderSummaryId IN :orderSummaryIdSet AND LAD_Invoice__c IN :finDocIdSet]){
                if(finDocIdPoNumbersMap.keySet().contains(itemSum.LAD_Invoice__c) && itemSum.LAD_PO_Number__c != null){
                    finDocIdPoNumbersMap.get(itemSum.LAD_Invoice__c).add(itemSum.LAD_PO_Number__c);
                }else if(itemSum.LAD_PO_Number__c != null){
                    finDocIdPoNumbersMap.put(itemSum.LAD_Invoice__c, new Set<String>{itemSum.LAD_PO_Number__c});
                }
            }

            for(LAD_Return_Item__c retItem : [  SELECT  LAD_CreditNote__c, LAD_Original_Order_Summary_Product__r.LAD_PO_Number__c
                                                FROM LAD_Return_Item__c
                                                WHERE LAD_Return_Order__c IN :returnIdSet AND LAD_CreditNote__c IN :finDocIdSet]){
                if(finDocIdPoNumbersMap.keySet().contains(retItem.LAD_CreditNote__c) && retItem.LAD_Original_Order_Summary_Product__r.LAD_PO_Number__c != null){
                    finDocIdPoNumbersMap.get(retItem.LAD_CreditNote__c).add(retItem.LAD_Original_Order_Summary_Product__r.LAD_PO_Number__c);
                }else if(retItem.LAD_Original_Order_Summary_Product__r.LAD_PO_Number__c != null){
                    finDocIdPoNumbersMap.put(retItem.LAD_CreditNote__c, new Set<String>{retItem.LAD_Original_Order_Summary_Product__r.LAD_PO_Number__c});
                }                                            
            }

            system.debug(finDocIdPoNumbersMap);

            for(LAD_Financial_Document__c fin : finDocList){
                FinancialDocOutputWrapper finItem = new FinancialDocOutputWrapper();
                finItem.FinDocId = fin.Id;
                finItem.DocumentNumber = fin.LAD_Document_Number__c;
                finItem.Type = fin.LAD_Type__c;
                finItem.CreatedDate = String.valueOf(fin.CreatedDate).substring(0, 10); 
                finItem.OrderNumber = fin.LAD_Order_Summary__r.OrderNumber; //Handle for Credit Note
                //finItem.OrderPONumber = fin.LAD_Order_Summary__r.PoNumber;
                //finItem.PaymentId = fin.;
                finItem.TotalAmount = LAD_checkoutPageController.returnSymbol(fin.CurrencyIsoCode) + fin.LAD_Total_Amount__c;
                finItem.RemainingAmount = LAD_checkoutPageController.returnSymbol(fin.CurrencyIsoCode) + String.valueOf(fin.LAD_Remaining_Amount__c);
                finItem.RemainingAmountValue = String.valueOf(fin.LAD_Remaining_Amount__c);
                finItem.CurrencyIsoCode = fin.CurrencyIsoCode;
                finItem.DueDate = String.valueOf(fin.LAD_Due_Date__c).substring(0, 10);
                finItem.PaymentStatus = Date.today() > fin.LAD_Due_Date__c && fin.LAD_Status__c == 'Open' && fin.LAD_Type__c == 'Invoice' ? 'Overdue' : fin.LAD_Status__c;
                finItem.pdfURL = String.isBlank(fin.LAD_Document_URL__c) ? '' : fin.LAD_Document_URL__c;
                finItem.disablePayNow = fin.LAD_Status__c == 'Closed' ? true : false;
                finItem.disableDownloadPDF = String.isBlank(fin.LAD_Document_URL__c) ? true : false;
                finItem.disableCheckbox = fin.LAD_Status__c == 'Closed' ? true : false;
                finItem.disablePaymentTooltip = (fin.Financial_Document_Payments__r).size() > 1 ? false : true;
                finItem.disablePoTooltip = finDocIdPoNumbersMap.containsKey(fin.Id) && (finDocIdPoNumbersMap.get(fin.Id)).size() > 1 ? false : true;
                if(finDocIdPoNumbersMap.containsKey(fin.Id)){
                    List<String> orderSummaryItemPONumberList = new List<String>(finDocIdPoNumbersMap.get(fin.Id));
                    finItem.OrderPONumber = orderSummaryItemPONumberList[0];
                    finItem.OrderPoNumberToolTip = (String.valueOf(orderSummaryItemPONumberList)).replace('{', '').replace('}', '').replace('(', '').replace(')', '');
                }
                finItem.PaymentId = (fin.Financial_Document_Payments__r).size() > 0 ? fin.Financial_Document_Payments__r[0].LAD_Payment__r.BLN_PmtReferenceId__c : '';
                if(finItem.disablePaymentTooltip){
                    finItem.PaymentIdTooltip = finItem.PaymentId;
                }
                else{
                    Set<String> paymentIdSet = new Set<String>();
                    for(LAD_Financial_Document_Payment__c fdp : fin.Financial_Document_Payments__r){
                        paymentIdSet.add(fdp.LAD_Payment__r.BLN_PmtReferenceId__c);
                    }
                    paymentIdSet.remove(null);
                    finItem.PaymentIdTooltip = String.valueOf(paymentIdSet).replace('{', '').replace('}', '').replace('(', '').replace(')', '');
                }
                
                returnWrapper.add(finItem);
            }
            system.debug(returnWrapper);
            return returnWrapper;
        } catch (Exception e) {
            BLN_ExceptionLogger.captureException(e);
            return null;
        }
    }

}