force-app/main/default/objects/BLN_Payment__c/BLN_Payment__c.object-meta.xml
<CustomObject>
    <description>FOUK-4686: This object is created to store Payment information.</description>
    <label>Payments &amp; Refunds</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments &amp; Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_Case__c.field-meta.xml
<CustomField>
    <fullName>BLN_Case__c</fullName>
    <description>FOUK-4686: This field is created to store case value.</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_InitiatedBy__c.field-meta.xml
<CustomField>
    <fullName>BLN_InitiatedBy__c</fullName>
    <description>FOUK-5664: This field is created to store Initiated By value on payment record.</description>
    <label>Initiated By</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_LinkData__c.field-meta.xml
<CustomField>
    <fullName>BLN_LinkData__c</fullName>
    <description>FOUK-9249, stores the link data id from Worldpay</description>
    <label>Link Data</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_PaymentAmountTaken__c.field-meta.xml
<CustomField>
    <fullName>BLN_PaymentAmountTaken__c</fullName>
    <description>FOUK-4686: This field is created to store Payment amount taken value.</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_PaymentId__c.field-meta.xml
<CustomField>
    <fullName>BLN_PaymentId__c</fullName>
    <description>FOUK-4686: This field is created to store Payment Id value.</description>
    <label>Token Number</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>BLN_PaymentMethod__c</fullName>
    <description>FOUK-6982 This field used to store payment method.</description>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automated</fullName>
            </value>
            <value>
                <fullName>Assisted</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Technician</fullName>
            </value>
            <value>
                <fullName>Portal</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_PaymentType__c.field-meta.xml
<CustomField>
    <fullName>BLN_PaymentType__c</fullName>
    <description>FOUK-4686: This field is created to store Payment type value.</description>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ECOMMERCE</fullName>
            </value>
            <value>
                <fullName>CHIP &amp; PIN</fullName>
            </value>
            <value>
                <fullName>ONLINE PAYMENT</fullName>
            </value>
            <value>
                <fullName>BRANCH BANKING</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_PmtGatewayProvider__c.field-meta.xml
<CustomField>
    <fullName>BLN_PmtGatewayProvider__c</fullName>
    <description>FOUK-5663 and FOUK-5744 Capture the payment gateway provider, for automated and assisted payments, it is always Barclays. For any other payment channel, it is Worldpay</description>
    <label>Payment Gateway Provider</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Barclays</fullName>
            </value>
            <value>
                <fullName>WorldPay</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_Status__c.field-meta.xml
<CustomField>
    <fullName>BLN_Status__c</fullName>
    <description>FOUK-4686: This field is created to store Status value.</description>
    <label>Status</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/recordTypes/BLN_Payments.recordType-meta.xml
<RecordType>
    <fullName>BLN_Payments</fullName>
    <active>true</active>
    <description>FOUK_5667, This Record Type is created for storing Payment related information</description>
    <label>Payments</label>
</RecordType>

force-app/main/default/classes/BLN_DecodeWorldPayMobileResponse.cls
/** @description : BLN_DecodeWorldPayMobileResponse is used in bln_PaymentResponse LWC to create payment record.
*  	@autor: Gaurav Giradkar
* 	@Story: FOUK-1609
*	@Created Date: 22/07/2024
*/
public with sharing class BLN_DecodeWorldPayMobileResponse {
    @AuraEnabled
    public static Boolean decodeWorldPayResponse(String returnResp, String woliId){
        Map<String, String> keyValueMap = new Map<String, String>();
        //Getting Payment record Id
        Id paymentRT = SObjectType.BLN_Payment__c.getRecordTypeInfosByDeveloperName().get('BLN_Payments').getRecordTypeId();
        //Gtting WOLI Details
        WorkOrderLineItem woli = [Select Id,WorkOrder.CaseId From WorkOrderLineItem Where Id =: woliId WITH SECURITY_ENFORCED];

        Boolean returnString = false;
        String paymentAmount = '';
        String paymentStatus = '';
        String tokenNumber = '';
        String linkData = '';
        
        // URL decode the string
        String urlDecodedString = EncodingUtil.urlDecode(returnResp, 'UTF-8');
        Blob decodedBlob = EncodingUtil.base64Decode(urlDecodedString);
        // Base64 Decode to URL Decoded string
        String base64DecodedString = decodedBlob.toString();
        // Split the returnString into responseLines
        List<String> responseLines = base64DecodedString.split('\n');
        
        for (String line : responseLines) {
            List<String> parts = line.split('=');
            if (parts.size() == 2) {
                keyValueMap.put(parts[0], parts[1]);
            }
        }
        // Check conditions and assign values
        if (keyValueMap.containsKey('3')) {
            String value3 = keyValueMap.get('3');
            if (value3 == '1' || value3 == '2') {
                returnString = true;
                paymentStatus = 'SUCCESS';
            } else if(value3 == '4' || value3 == '5' || value3 == '19' || value3 == '27' || value3 == '28' ||
                      value3 == '29' || value3 == '36' || value3 == '37' || value3 == '42'){
                returnString = false;
                paymentStatus = 'DECLINE';
            }
        }
        if (keyValueMap.containsKey('18')) {
            paymentAmount = String.valueOf(keyValueMap.get('18'));
        }
        if (keyValueMap.containsKey('5')) {
            tokenNumber = keyValueMap.get('5');
        }
        
        if (keyValueMap.containsKey('98')) {
            linkData = keyValueMap.get('98');
        }
         
        String randomString = BLN_SCUtility.generateRandomAlphabetString();
        String originalString = tokenNumber;  
        String updatedTokenNumber = originalString.replace('XXXXXX', randomString);  
         

        //Creating payment record
        BLN_Payment__c paymentRec = new BLN_Payment__c();
        paymentRec.BLN_PaymentAmountTaken__c = Decimal.valueOf(paymentAmount);
        paymentRec.BLN_PaymentId__c = tokenNumber;
        paymentRec.BLN_Status__c = paymentStatus;
        paymentRec.BLN_LinkData__c = linkData;
        paymentRec.BLN_PaymentType__c = System.label.BLN_ChipAndPin;
        paymentRec.RecordTypeId = paymentRT;
        paymentRec.BLN_Case__c = woli.WorkOrder.CaseId;
        paymentRec.BLN_PmtGatewayProvider__c = System.label.BLN_Worldpay;
        paymentRec.BLN_InitiatedBy__c = UserInfo.getName();
        paymentRec.BLN_PaymentMethod__c = System.label.BLN_Technician;
        if(Schema.sObjectType.BLN_Payment__c.isCreateable()){
            insert paymentRec;
        }
        return returnString;
    }
}