force-app/main/default/objects/BLN_Payment__c/BLN_Payment__c.object-meta.xml
<CustomObject>
    <description>FOUK-4686: This object is created to store Payment information.</description>
    <label>Payments &amp; Refunds</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments &amp; Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_CardType__c.field-meta.xml
<CustomField>
    <fullName>BLN_CardType__c</fullName>
    <description>FOUK-5663, FOUK-5744 Determines the card type based on the first and last 6 digits of the card received in the payment gateway response. This info is needed to sync payments with EBS.</description>
    <label>Card Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_Case__c.field-meta.xml
<CustomField>
    <fullName>BLN_Case__c</fullName>
    <description>FOUK-4686: This field is created to store case value.</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_CR__c.field-meta.xml
<CustomField>
    <fullName>BLN_CR__c</fullName>
    <description>FOUK-3977 This is used in BLN_SCUtility class.</description>
    <externalId>true</externalId>
    <label>CR</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_First6DigitsofCard__c.field-meta.xml
<CustomField>
    <fullName>BLN_First6DigitsofCard__c</fullName>
    <description>FOUK-3977 This is used to store  Last 6 digits of the card used for payment.</description>
    <formula>VALUE(LEFT( BLN_PaymentId__c , 6))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>First 6 Digits of Card Used</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_Last4DigitsOfCard__c.field-meta.xml
<CustomField>
    <fullName>BLN_Last4DigitsOfCard__c</fullName>
    <description>FOUK-3977. This field is created to store Last 4 Digits Card Used on Payment record.</description>
    <formula>RIGHT(BLN_PaymentId__c, 4)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last 4 Digits Card Used</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_OriginalPayment__c.field-meta.xml
<CustomField>
    <fullName>BLN_OriginalPayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>FOUK-4665, This Lookup FIeld is created for Payment &amp; Refunds Object</description>
    <label>Linked to Payment Record</label>
    <referenceTo>BLN_Payment__c</referenceTo>
    <relationshipLabel>Payments &amp; Refunds</relationshipLabel>
    <relationshipName>Payments_Refunds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_PaymentId__c.field-meta.xml
<CustomField>
    <fullName>BLN_PaymentId__c</fullName>
    <description>FOUK-4686: This field is created to store Payment Id value.</description>
    <label>Token Number</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>BLN_PaymentMethod__c</fullName>
    <description>FOUK-6982 This field used to store payment method.</description>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automated</fullName>
            </value>
            <value>
                <fullName>Assisted</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Technician</fullName>
            </value>
            <value>
                <fullName>Portal</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_PaymentStatus__c.field-meta.xml
<CustomField>
    <fullName>BLN_PaymentStatus__c</fullName>
    <description>FOUK-4686: This field is created to store Payment status value.</description>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>DECLINE</fullName>
            </value>
            <value>
                <fullName>INITIATED</fullName>
            </value>
            <value>
                <fullName>CANCELLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_PaymentType__c.field-meta.xml
<CustomField>
    <fullName>BLN_PaymentType__c</fullName>
    <description>FOUK-4686: This field is created to store Payment type value.</description>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ECOMMERCE</fullName>
            </value>
            <value>
                <fullName>CHIP &amp; PIN</fullName>
            </value>
            <value>
                <fullName>ONLINE PAYMENT</fullName>
            </value>
            <value>
                <fullName>BRANCH BANKING</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_PmtBatch__c.field-meta.xml
<CustomField>
    <fullName>BLN_PmtBatch__c</fullName>
    <description>FOUK-5663, FOUK-5744 Unique id generated</description>
    <label>Payment Batch Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_PmtGatewayProvider__c.field-meta.xml
<CustomField>
    <fullName>BLN_PmtGatewayProvider__c</fullName>
    <description>FOUK-5663 and FOUK-5744 Capture the payment gateway provider, for automated and assisted payments, it is always Barclays. For any other payment channel, it is Worldpay</description>
    <label>Payment Gateway Provider</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Barclays</fullName>
            </value>
            <value>
                <fullName>WorldPay</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_RctMethod__c.field-meta.xml
<CustomField>
    <fullName>BLN_RctMethod__c</fullName>
    <description>FOUK-5663, FOUK-5744 Determined basis the Payment Type and Card Type mapping data and is needed for syncing with EBS.</description>
    <label>Receipt Method</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_RctMethodId__c.field-meta.xml
<CustomField>
    <fullName>BLN_RctMethodId__c</fullName>
    <description>FOUK-5663, and FOUK-5744 Determined basis the Payment Type and Card Type mapping data and is needed for syncing with EBS.</description>
    <label>Receipt Method Id</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_Status__c.field-meta.xml
<CustomField>
    <fullName>BLN_Status__c</fullName>
    <description>FOUK-4686: This field is created to store Status value.</description>
    <label>Status</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_TxnId__c.field-meta.xml
<CustomField>
    <fullName>BLN_TxnId__c</fullName>
    <description>FOUK-5663, FOUK-5744 Case Number(Name)+&apos;04&apos; - This formula is used by default and is needed to sync data with EBS.</description>
    <label>Transaction ID</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BLN_SCUtilityTest.cls
/** @description : Test class for BLN_APICalloutPublisherTriggerHandler.
*   @Story : FOUK-867
*   @author: Shubhangi Patil (PwC)
*   @CreatedDate: 27/11/2023
*/
@isTest
private class BLN_SCUtilityTest {
    private Static Id accountRecordId=schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
    
    /*  *@description:This method is used to test BLN_SCUtility's generateCorrelationID method.
*return : void
*/
    @TestSetup
    public static void setupTestData () {
        Account testAccount = BLN_TestDataFactory.createAccountforAPI();
        insert testAccount;

        BLN_Payment__c paymentList = BLN_TestDataFactory.createPayments();
        paymentList.BLN_Status__c='valid';
        paymentList.BLN_PmtBatch__c='MV0000100524';
        insert paymentList;

    }
    @isTest
    static void testGenerateCorrelationID() {
        
       /* Id adminProfileId = [SELECT Id FROM Profile WHERE Name = 'Service Agent']?.Id;
        String role = '';
        role= [Select Id FROM UserRole where developerName = 'BLN_UK'].Id;
        User adminUser = new User(
            ProfileId = adminProfileId,
            UserroleId =role,
            FirstName = 'PS',
            LastName = 'Test User',
            UserName = System.now().getTime() + '@test.demo',
            Alias = 'pstes',
            Email = 'test@sample.demo',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'nl_NL',
            TimeZoneSidKey = UserInfo.getTimeZone().getID(),
            UserPermissionsSupportUser = true); 
        insert adminUser;*/
        User adminUser = BLN_TestDataFactory.createAdminUser('lastName');
        
        System.runAs(adminUser){
            Test.startTest();
            String correlationID = BLN_SCUtility.generateCorrelationID();
            System.assert(correlationID.contains('-'), ' ID  contain dashes');
            String secondCorrelationID = BLN_SCUtility.generateCorrelationID();
            BLN_SCUtility.generateRandomAlphabetString();
            System.assertNotEquals(correlationID, secondCorrelationID, ' IDs should be unique');
            Test.stopTest();
        }
        
    }
    
    /*  *@description:This method is used to test BLN_SCUtility's getMotoristDataforMDMSync method.
*return : void
*/
    @isTest
    static void testGetMotoristDataforMDMSync() {
        Account testAccount = [Select Id from Account LIMIT 1];
        Test.startTest();
        Account resultAccount = BLN_SCUtility.getMotoristDataforMDMSync(testAccount.Id);
        Test.stopTest();
        System.assertNotEquals(null, resultAccount,'resultaccount can not be null');
    }
    
    /*  *@description:This method is used to test BLN_SCUtility's getMotoristDataforMDMSync method nagative scenario.
*return : void
*/
    @isTest
    static void testMotoristData() {
        //Account testAccount = [Select Id from Account LIMIT 1];
        Test.startTest();
        Account resultAccount = BLN_SCUtility.getMotoristDataforMDMSync(null);
        Test.stopTest();
        System.assertEquals(null, resultAccount,'resultaccount is null');
        Exception ex;
        System.assertEquals(resultAccount,Null,'resultaccount is null');
        System.assertEquals(ex,Null,'ex is null');
        
    }
    
/*  *@description:This method is used to test BLN_SCUtility's paymentFieldsPopulation method.
*return : void
*/    
    @isTest
     static void testPaymentFieldsPopulation() {
        BLN_Payment__c paymentList = [Select Id FROM BLN_Payment__c LIMIT 1];
        List<BLN_Payment__c> updatedPayments = [SELECT Id,createddate,BLN_Case__c,BLN_First6DigitsofCard__c,BLN_Last4DigitsOfCard__c,LastModifiedDate,BLN_PmtGatewayProvider__c,BLN_PaymentMethod__c,BLN_Status__c, BLN_CR__c, BLN_TxnId__c,BLN_PaymentId__c, BLN_PaymentStatus__c,BLN_PaymentType__c,BLN_RctMethod__c, BLN_OriginalPayment__r.BLN_PmtGatewayProvider__c FROM BLN_Payment__c WHERE Id=: paymentList.id];
        BLN_SCUtility.paymentFieldsPopulation(updatedPayments);
        System.assertNotEquals(null, updatedPayments[0].BLN_CR__c, 'BLN_CR__c should not be null');
        System.assertNotEquals(null, updatedPayments[0].BLN_TxnId__c, 'BLN_TxnId__c should not be null');
        
    }  
    
 /*  *@description:This method is used to test BLN_SCUtility's paymentReceiptMethodPopulation method.
*return : void
*/    
    @isTest
    static void testpaymentReceiptMethodPopulation() {
        BLN_Payment__c paymentList = [Select Id FROM BLN_Payment__c LIMIT 2];
        
        List<BLN_Payment__c> updatedPayments = [SELECT Id,createddate,BLN_Case__c,LastModifiedDate,BLN_Status__c,BLN_PaymentId__c,BLN_RctMethod__c,BLN_CardType__c,BLN_PaymentType__c,BLN_Last4DigitsOfCard__c,BLN_First6DigitsofCard__c, BLN_PaymentStatus__c FROM BLN_Payment__c WHERE Id=: paymentList.id];
        BLN_SCUtility.paymentReceiptMethodPopulation(updatedPayments);
        
        System.assertEquals('valid', updatedPayments[0].BLN_Status__c, 'status is valid');
        System.assertEquals('On-line International Maestro', updatedPayments[0].BLN_CardType__c, 'Card type should be updated to EcommsCard for ecommerce payments');  
        
    }
    
    
/*  *@description:This method is used to test BLN_SCUtility's paymentReceiptMethodPopulation method.
*return : void
*/    
    @isTest
    static void testpaymentReceiptIdMethodPopulation() {
        BLN_Payment__c paymentList = [Select Id FROM BLN_Payment__c LIMIT 1];
        
        List<BLN_Payment__c> updatedPayments = [SELECT Id,createddate,BLN_Case__c,LastModifiedDate,BLN_Status__c,BLN_RctMethod__c,BLN_CardType__c,BLN_Last4DigitsOfCard__c,BLN_First6DigitsofCard__c, BLN_PaymentStatus__c,BLN_PaymentType__c,BLN_RctMethodId__c FROM BLN_Payment__c WHERE Id=: paymentList.id];
        BLN_SCUtility.paymentReceiptIdMethodPopulation(updatedPayments);
        System.assertEquals('ONLINE PAYMENT', updatedPayments[0].BLN_PaymentType__c, 'payment type should not be null');
        
    }
        @isTest
    static void testpaymentBatchDetermination() {
        BLN_Payment__c paymentList = [Select Id FROM BLN_Payment__c LIMIT 1];
        //string pmtbatch = '';
        //pmtbatch = 'SW0000'
        // Get the current date
        Date currentDate = Date.today();
        // Convert to DateTime for formatting
        DateTime currentDateTime = DateTime.newInstance(currentDate.year(), currentDate.month(), currentDate.day());
        // Format the date as a string in ddMMyy format
        String formattedDate = currentDateTime.format('ddMMyy');
        // Concatenate with "SW0000"
        String result = 'SW0000' + formattedDate;


        List<BLN_Payment__c> updatedPayments = [SELECT Id,createddate,BLN_Case__c,LastModifiedDate,BLN_Status__c,BLN_PmtBatch__c, BLN_PaymentId__c,BLN_RctMethod__c,BLN_CardType__c,BLN_PaymentType__c,BLN_Last4DigitsOfCard__c,BLN_First6DigitsofCard__c, BLN_PaymentStatus__c FROM BLN_Payment__c WHERE Id=: paymentList.id];
        BLN_SCUtility.paymentBatchDetermination(updatedPayments);
        BLN_SCUtility.paymentTokenIdConcatinate(updatedPayments);
        
        //System.assertEquals('MV0000100524', updatedPayments[0].BLN_PmtBatch__c, 'Payment batch should be updated with the correct prefix');
         System.assertEquals(result, updatedPayments[0].BLN_PmtBatch__c, 'Payment batch should be updated with the correct prefix');
    }
   
   
}