force-app/main/default/objects/BLN_Corporate__c/BLN_Corporate__c.object-meta.xml
<CustomObject>
    <description>FOUK-6065, 5754, This Custom Object is created for storing information about Corporate</description>
    <label>Corporate</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Corporate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Corporates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_RecCasePriority__mdt/BLN_RecCasePriority__mdt.object-meta.xml
<CustomObject>
    <description>FOUK-6164 For Recovery Case Priority, this metadata will hold information on Priority conditions and these conditions are used for identifying the case priorities.</description>
    <label>Recovery Case Priority</label>
    <pluralLabel>Recovery Case Priorities</pluralLabel>
</CustomObject>

force-app/main/default/objects/BLN_RecCasePriority__mdt/fields/BLN_Active__c.field-meta.xml
<CustomField>
    <fullName>BLN_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>FOUK-6164 This field is use to check custom metadata is active or not</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BLN_RecCasePriority__mdt/fields/BLN_FieldAPIName__c.field-meta.xml
<CustomField>
    <fullName>BLN_FieldAPIName__c</fullName>
    <description>FOUK-6164 For Field API Name</description>
    <label>Field API Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_RecCasePriority__mdt/fields/BLN_FieldValue__c.field-meta.xml
<CustomField>
    <fullName>BLN_FieldValue__c</fullName>
    <description>FOUK-6164 To Store Field Value</description>
    <label>Field Value</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_RecCasePriority__mdt/fields/BLN_Priority__c.field-meta.xml
<CustomField>
    <fullName>BLN_Priority__c</fullName>
    <description>FOUK-6164 To Store Priority on Case</description>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Critical</fullName>
                <default>true</default>
                <label>Critical</label>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BLN_RecoveryCaseHandler.cls
/*****************************************
ClassName : BLN_RecoveryCaseHandler
Description : FOUK-6164 This class is used For Case Priority.
CreatedDate: 12-03-2024
CreatedBy : PwC-India
****************************************/


public with sharing class BLN_RecoveryCaseHandler {
    @InvocableMethod
    /*  *@Description : This method is used to get the records from BLN_RecCasePriority__mdt custom metadata. */
    public static void calculateRecoveryCasePriority(List<Case> caseList) {
        
        Map<String, String> recPriority = new Map<String, String>();
        List<BLN_RecCasePriority__mdt>getMetadata = BLN_RecCasePriority__mdt.getall().values();
        
        For(BLN_RecCasePriority__mdt priorityMetadata :getMetadata){
            
           /*  *@Description : This method is used to get the records from BLN_RecCasePriority__mdt custom metadata Where IsActive = true. */     
            If(priorityMetadata.BLN_Active__c ){                                        
                recPriority.put(priorityMetadata.BLN_FieldAPIName__c + priorityMetadata.BLN_FieldValue__c , priorityMetadata.BLN_Priority__c);
            }   
        }
        
        for (Case caseRec : caseList) {
            String priority = '';
            
            if (caseRec.BLN_ServiceType__c != null  && caseRec.BLN_Corporate__c == null &&  recPriority.containsKey(Label.BLN_RecCasePriorityField1 + caseRec.BLN_ServiceType__c )) {
                priority = recPriority.get(Label.BLN_RecCasePriorityField1 + caseRec.BLN_ServiceType__c);
                
            } else if (caseRec.BLN_ServiceType__c != null && caseRec.BLN_Corporate__c != null && recPriority.containsKey(Label.BLN_RecCasePriorityField1 + caseRec.BLN_ServiceType__c)) {
                
                priority = recPriority.get(Label.BLN_RecCasePriorityField1 + caseRec.BLN_ServiceType__c);
            } else if (recPriority.containsKey(Label.BLN_RecCasePriorityField2 + caseRec.BLN_SecondaryReason__c)) {
                
                priority = recPriority.get(Label.BLN_RecCasePriorityField2 + caseRec.BLN_SecondaryReason__c);
            }
            
            caseRec.Priority = priority;
            
            if(caseRec.BLN_Escalated__c)
            {
                caseRec.Priority = Label.BLN_CriticalPriority;
            }  
        }
        
            if(case.SObjectType.getDescribe(SObjectDescribeOptions.DEFERRED).isUpdateable() && Schema.sObjectType.Case.isUpdateable()){
        
        /*  *@Description : This method is used to Update Case records with calculated priority */
        update caseList;
        
            }
    }
    
}