force-app/main/default/objects/BLN_Corporate__c/BLN_Corporate__c.object-meta.xml
<CustomObject>
    <description>FOUK-6065, 5754, This Custom Object is created for storing information about Corporate</description>
    <label>Corporate</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Corporate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Corporates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_Corporate__c/fields/BLN_OEAuthorizationRequired__c.field-meta.xml
<CustomField>
    <fullName>BLN_OEAuthorizationRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <description>FOUK - 3167</description>
    <label>OE Authorisation Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BLN_Corporate__c/fields/BLN_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>BLN_Vehicle__c</fullName>
    <description>FOUK-6065, 5754, This Custom field is created for storing information about Vehicle Object</description>
    <label>Vehicle</label>
    <referenceTo>BLN_Vehicle__c</referenceTo>
    <relationshipLabel>Corporates</relationshipLabel>
    <relationshipName>Corporates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BLN_Vehicle__c/BLN_Vehicle__c.object-meta.xml
<CustomObject>
    <description>FOUK-495 This object is created for storing the Vehicles.</description>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{00000000}</displayFormat>
        <label>Vehicle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_Vehicle__c/fields/BLN_SpecialVehicle__c.field-meta.xml
<CustomField>
    <fullName>BLN_SpecialVehicle__c</fullName>
    <defaultValue>false</defaultValue>
    <description>FOUK-1543 This field is used to check if vehicle is a special vehicle or not.</description>
    <label>Special Vehicle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BLN_AuthorisationScreenControllerTest.cls
@isTest
public class BLN_AuthorisationScreenControllerTest {

    @isTest
    static void testUpdateCaseRecord() {
        // Test data setup
        BLN_Vehicle__c vehicles = BLN_TestDataFactory.getVehicle();
        vehicles.BLN_SpecialVehicle__c = true;
        insert vehicles;

        BLN_Corporate__c corporate = new BLN_Corporate__c();
        corporate.BLN_OEAuthorizationRequired__c = false;
         corporate.BLN_Vehicle__c = vehicles.Id;
        insert corporate;
       
        Case cse = BLN_TestDataFactory.getCase('Job Request', 'New');
        cse.Type = 'Job Request';
        cse.Status = 'New';
        cse.BLN_SubType__c='Job Request';
        cse.BLN_Corporate__c = corporate.id;
        cse.BLN_ServiceGeolocation__latitude__s=46.22441984873406;
        cse.BLN_ServiceGeolocation__longitude__s=-89.02172505348693;
        
        cse.Priority = 'Medium';
        cse.BLN_MotoristTaxStatus__c = 'Yes';
        cse.BLN_TotalMotoristLiability__c = 6000 ;
        insert cse;
        

        Test.startTest();
        // Call the method under test
        boolean isCaseUpdated = BLN_AuthorisationScreenController.updateCaseRecord(corporate.Id);
        Test.stopTest();

        // Verify the result
        System.assertEquals(true, isCaseUpdated, 'Case record should be updated successfully.');
    }
}