force-app/main/default/objects/BLN_Corporate__c/BLN_Corporate__c.object-meta.xml
<CustomObject>
    <description>FOUK-6065, 5754, This Custom Object is created for storing information about Corporate</description>
    <label>Corporate</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Corporate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Corporates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_Corporate__c/fields/BLN_CorporateLegalEntity__c.field-meta.xml
<CustomField>
    <fullName>BLN_CorporateLegalEntity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>FOUK:5754, 6065 - This Custom field is created for storing information about Insurance Policies.</description>
    <label>Corporate Legal Entity</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Corporates (Corporate Legal Entity)</relationshipLabel>
    <relationshipName>Corporates5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BLN_Corporate__c/fields/BLN_InsuranceLegalEntity__c.field-meta.xml
<CustomField>
    <fullName>BLN_InsuranceLegalEntity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created as part of FOUK-9106 and FOUK-9108</description>
    <label>Insurance Legal Entity</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Corporate(Insurance Legal Entity)</relationshipLabel>
    <relationshipName>Corporates7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BLN_Corporate__c/recordTypes/BLN_CorporateFleet.recordType-meta.xml
<RecordType>
    <fullName>BLN_CorporateFleet</fullName>
    <active>true</active>
    <description>This record type is created for Corporate/Fleet records</description>
    <label>Corporate/Fleet</label>
</RecordType>

force-app/main/default/objects/BLN_Corporate__c/recordTypes/BLN_Insurance.recordType-meta.xml
<RecordType>
    <fullName>BLN_Insurance</fullName>
    <active>true</active>
    <description>This record type is created for Insurance records</description>
    <label>Insurance</label>
</RecordType>

force-app/main/default/objects/BLN_ProductIdentifier__mdt/BLN_ProductIdentifier__mdt.object-meta.xml
<CustomObject>
    <label>Product Identifier</label>
    <pluralLabel>BLN_ProductIdentifiers</pluralLabel>
</CustomObject>

force-app/main/default/objects/BLN_ProductIdentifier__mdt/fields/BLN_CategoryCode__c.field-meta.xml
<CustomField>
    <fullName>BLN_CategoryCode__c</fullName>
    <label>Category Code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ProductIdentifier__mdt/fields/BLN_ProductCode__c.field-meta.xml
<CustomField>
    <fullName>BLN_ProductCode__c</fullName>
    <label>Product Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ProductIdentifier__mdt/fields/BLN_Type__c.field-meta.xml
<CustomField>
    <fullName>BLN_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CHARGES</fullName>
                <default>true</default>
                <label>CHARGES</label>
            </value>
            <value>
                <fullName>WINDSCREEN</fullName>
            </value>
            <value>
                <fullName>BODY GLASS</fullName>
            </value>
            <value>
                <fullName>PRIME</fullName>
            </value>
            <value>
                <fullName>VAPS</fullName>
            </value>
            <value>
                <fullName>REPAIR</fullName>
            </value>
            <value>
                <fullName>HIDE ON UI</fullName>
            </value>
            <value>
                <fullName>EXCLUDE FOR APPOINTMENT</fullName>
            </value>
            <value>
                <fullName>STATIC</fullName>
            </value>
            <value>
                <fullName>DYNAMIC</fullName>
            </value>
            <value>
                <fullName>STATIC &amp; DYNAMIC</fullName>
            </value>
            <value>
                <fullName>SPECIALIST CALIBRATION REQUIRED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/BLN_Description__c.field-meta.xml
<CustomField>
    <fullName>BLN_Description__c</fullName>
    <description>Used for article description.</description>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/BLN_FetchKnowledgeArticles.cls
public with sharing class BLN_FetchKnowledgeArticles {
    
    @AuraEnabled(cacheable=true)
    public static List<Knowledge__kav> getKnowledgeArticles(List<String> articleTitle) {
        return [SELECT Id, Title, BLN_Description__c FROM Knowledge__kav WHERE Title IN :articleTitle WITH SECURITY_ENFORCED];
    }    
    
    @AuraEnabled
    public static String createTaskRecord(String subject, String description, String caseId) {
        String idVal = '';            
        Task newTask = new Task();
        newTask.RecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName().get('BLN_Audit').getRecordTypeId();
        newTask.Subject = subject;
        newTask.Description = description;
        newTask.Status = 'Completed';
        newTask.ActivityDate = Date.today();
        newTask.OwnerId = UserInfo.getUserId();
        newTask.WhatId = Id.valueOf(caseId);
        newTask.BLN_Case__c = Id.valueOf(caseId);
        if(Schema.sObjectType.Task.isCreateable()){
            insert newTask;
            idVal = String.valueOf(newTask.Id);
        }  
        return idVal;
    }    
    
	@AuraEnabled(cacheable = true)
    public static String checkMotabilityAccountName(String caseId) {
        String entityName='';
        Case caseRecord = [SELECT Id,AccountId,BLN_Corporate__c From Case Where Id = :caseId WITH SECURITY_ENFORCED LIMIT 1];
        /*Account acc = new Account();
        if(caseRecord.AccountId != null){
            acc=[Select Id,Name From Account Where Id=:caseRecord.AccountId WITH SECURITY_ENFORCED LIMIT 1];           
        }
        return acc.Name;*/
   
        BLN_Corporate__c corpRecord=[SELECT Id,BLN_InsuranceLegalEntity__c,BLN_CorporateLegalEntity__c,BLN_CorporateLegalEntity__r.Name,RecordTypeId,BLN_InsuranceLegalEntity__r.Name From BLN_Corporate__c where Id=:caseRecord.BLN_Corporate__c WITH SECURITY_ENFORCED LIMIT 1];
        if(corpRecord.recordTypeId == Schema.SObjectType.BLN_Corporate__c.getRecordTypeInfosByDeveloperName().get(System.label.BLN_CorporateFleet).getRecordTypeId()){           
            if(corpRecord.BLN_CorporateLegalEntity__c!=Null){
                entityName=corpRecord.BLN_CorporateLegalEntity__r.Name;                
            }           
        }
        else if(corpRecord.recordTypeId == Schema.SObjectType.BLN_Corporate__c.getRecordTypeInfosByDeveloperName().get(System.label.BLN_Insurance).getRecordTypeId()){
            if(corpRecord.BLN_InsuranceLegalEntity__c!=Null){
                entityName=corpRecord.BLN_InsuranceLegalEntity__r.Name;
            }
                         
        }
        /*else if(corpRecord.recordTypeId == Schema.SObjectType.BLN_Corporate__c.getRecordTypeInfosByDeveloperName().get(System.label.BLN_SplitBill).getRecordTypeId()){
         * if(corpRecord.BLN_InsuranceLegalEntity__c!=Null){
                entityName=corpRecord.BLN_InsuranceLegalEntity__r.Name;
            }
        }*/
        return entityName;
    }    
    
    @AuraEnabled
    public static List<BLN_ProductIdentifier__mdt> checkADASScriptProduct() {
        List<BLN_ProductIdentifier__mdt> productIdentifierListForHideOnUI = new List<BLN_ProductIdentifier__mdt>();
        List<String> typeList = new List<String>();
	    String allTypevalues = System.Label.BLN_ArticleTypes;
        typeList = allTypevalues.split(',');
	    productIdentifierListForHideOnUI = [SELECT Id,BLN_ProductCode__c,BLN_Type__c,BLN_CategoryCode__c FROM BLN_ProductIdentifier__mdt WHERE BLN_Type__c IN : typeList WITH SECURITY_ENFORCED];  
        List<BLN_ProductIdentifier__mdt> prodADASList = new List<BLN_ProductIdentifier__mdt>();
            for(BLN_ProductIdentifier__mdt prodIdentifier : productIdentifierListForHideOnUI){
                prodADASList.add(prodIdentifier);
            }
    
        return prodADASList;
    }
    
}