force-app/main/default/objects/BLN_Corporate__c/BLN_Corporate__c.object-meta.xml
<CustomObject>
    <description>FOUK-6065, 5754, This Custom Object is created for storing information about Corporate</description>
    <label>Corporate</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Corporate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Corporates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_Corporate__c/fields/BLN_CorporateLegalEntity__c.field-meta.xml
<CustomField>
    <fullName>BLN_CorporateLegalEntity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>FOUK:5754, 6065 - This Custom field is created for storing information about Insurance Policies.</description>
    <label>Corporate Legal Entity</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Corporates (Corporate Legal Entity)</relationshipLabel>
    <relationshipName>Corporates5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BLN_Corporate__c/fields/BLN_InsuranceLegalEntity__c.field-meta.xml
<CustomField>
    <fullName>BLN_InsuranceLegalEntity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created as part of FOUK-9106 and FOUK-9108</description>
    <label>Insurance Legal Entity</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Corporate(Insurance Legal Entity)</relationshipLabel>
    <relationshipName>Corporates7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BLN_Corporate__c/fields/BLN_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>BLN_Vehicle__c</fullName>
    <description>FOUK-6065, 5754, This Custom field is created for storing information about Vehicle Object</description>
    <label>Vehicle</label>
    <referenceTo>BLN_Vehicle__c</referenceTo>
    <relationshipLabel>Corporates</relationshipLabel>
    <relationshipName>Corporates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BLN_Corporate__c/recordTypes/BLN_CorporateFleet.recordType-meta.xml
<RecordType>
    <fullName>BLN_CorporateFleet</fullName>
    <active>true</active>
    <description>This record type is created for Corporate/Fleet records</description>
    <label>Corporate/Fleet</label>
</RecordType>

force-app/main/default/objects/BLN_Corporate__c/recordTypes/BLN_Insurance.recordType-meta.xml
<RecordType>
    <fullName>BLN_Insurance</fullName>
    <active>true</active>
    <description>This record type is created for Insurance records</description>
    <label>Insurance</label>
</RecordType>

force-app/main/default/objects/BLN_ProductIdentifier__mdt/BLN_ProductIdentifier__mdt.object-meta.xml
<CustomObject>
    <label>Product Identifier</label>
    <pluralLabel>BLN_ProductIdentifiers</pluralLabel>
</CustomObject>

force-app/main/default/objects/BLN_Vehicle__c/BLN_Vehicle__c.object-meta.xml
<CustomObject>
    <description>FOUK-495 This object is created for storing the Vehicles.</description>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{00000000}</displayFormat>
        <label>Vehicle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_Vehicle__c/fields/BLN_VehicleRegNumber__c.field-meta.xml
<CustomField>
    <fullName>BLN_VehicleRegNumber__c</fullName>
    <description>Fouk-109 To store vehicle registeration number.</description>
    <label>Vehicle Registration Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/BLN_Description__c.field-meta.xml
<CustomField>
    <fullName>BLN_Description__c</fullName>
    <description>Used for article description.</description>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/BLN_FetchKnowledgeArticlesTest.cls
/** @description : This Test class covered BLN_FetchKnowledgeArticles
*   @Story : FOUK-4271 & FOUK-4801
*   @author: Balamurugan (PwC)
*   @CreatedDate: 19/06/2024
*/


/**
 * @description: Test method for getKnowledgeArticles method
 */
@isTest
public with sharing class BLN_FetchKnowledgeArticlesTest {
    
    @isTest
    Public static void testGetKnowledgeArticles() {

        String articleTitle = 'Article 1';
        
        // Insert a single Knowledge__kav record
        Knowledge__kav article = new Knowledge__kav(
            Title = articleTitle,
            BLN_Description__c = 'Description for Article 1',
            UrlName = 'Article-1'
        );
        insert article;

        Test.startTest();
        // Call the method under test
        List<Knowledge__kav> result = BLN_FetchKnowledgeArticles.getKnowledgeArticles(new List<String>{articleTitle});

        List<BLN_ProductIdentifier__mdt> prodList = BLN_FetchKnowledgeArticles.checkADASScriptProduct();

        Test.stopTest();

        // Assert the results
        System.assertEquals(1, result.size(), 'Expected size does not match');
        Knowledge__kav retrievedArticle = result[0];
        System.assertEquals(articleTitle, retrievedArticle.Title, 'Article title does not match');
        System.assertEquals(prodList.size(),prodList.size(), 'Expected size does not match');
        }
    
/**
 * @description: Test method for testCreateTaskRecord method
 */
    @isTest
    Public static void testCreateTaskRecord() {
        // Create a test Case record
        Case testCase = new Case(
            Subject = 'Test Case',
            Description = 'Test Case Description',
            Status = 'New'
        );
        insert testCase;

        Test.startTest();
        // Call the method under test
        String taskId = BLN_FetchKnowledgeArticles.createTaskRecord('Test Task', 'Test Task Description', testCase.Id);
        Test.stopTest();

        // Query the Task to verify insertion
        Task insertedTask = [SELECT Id, Subject, Description, Status, ActivityDate, OwnerId, WhatId, BLN_Case__c 
                             FROM Task WHERE Id = :taskId];

        // Assert the results
        System.assertEquals('Test Task', insertedTask.Subject, 'Subject does not match');
        System.assertEquals('Test Task Description', insertedTask.Description, 'Description does not match');
        System.assertEquals('Completed', insertedTask.Status, 'Status is not Completed');
        System.assertEquals(Date.today(), insertedTask.ActivityDate, 'ActivityDate does not match');
        System.assertEquals(UserInfo.getUserId(), insertedTask.OwnerId, 'Owner does not match');
        System.assertEquals(testCase.Id, insertedTask.WhatId, 'WhatId does not match');
        System.assertEquals(testCase.Id, insertedTask.BLN_Case__c, 'BLN_Case__c does not match');
    }
    
    @isTest
    static void testCheckMotabilityCorporateFleet() {
        // Create a test account
        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;

         Account testAccountcorp = new Account(Name = 'Some Legal Entity Id');
        insert testAccountcorp;
       
        BLN_Vehicle__c veh = BLN_TestDataFactory.getVehicle();
        veh.BLN_VehicleRegNumber__c='BN12OEE';
        insert veh;
        
        RecordType rtCorporateFleet = [SELECT Id FROM RecordType WHERE DeveloperName = :System.label.BLN_CorporateFleet AND SObjectType = 'BLN_Corporate__c' LIMIT 1];
        
        // Create the BLN_Corporate__c record with the 'Corporate Fleet' record type
        BLN_Corporate__c corpRecord = new BLN_Corporate__c(
            RecordTypeId = rtCorporateFleet.Id,
            BLN_CorporateLegalEntity__c =testAccountcorp.Id ,
            BLN_Vehicle__c=veh.Id       
        );
        insert corpRecord;
        
        // Create a test case associated with the test account
        Case testCase = new Case(Subject = 'Test Case', AccountId = testAccount.Id, BLN_Corporate__c = corpRecord.Id);
        insert testCase;
        
        Test.startTest();
        String entityName = BLN_FetchKnowledgeArticles.checkMotabilityAccountName(testCase.Id);
        Test.stopTest();

        // Assertions to check that the entityName is returned correctly
        System.assertEquals('Some Legal Entity Id', entityName, 'The entity name should be correct for Corporate Fleet');        
    }
    @isTest
    static void testCheckMotabilityInsurance() {
        // Create a test account
        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;
        
         Account testAccountcorp = new Account(Name = 'Some Legal Entity Id');
        insert testAccountcorp;
       
        BLN_Vehicle__c veh = BLN_TestDataFactory.getVehicle();
        veh.BLN_VehicleRegNumber__c='BN12OEE';
        insert veh;
        
        RecordType rtInsurance = [SELECT Id FROM RecordType WHERE DeveloperName = :System.label.BLN_Insurance AND SObjectType = 'BLN_Corporate__c' LIMIT 1];
        
        // Create the BLN_Corporate__c record with the 'Corporate Fleet' record type
        BLN_Corporate__c corpRecord = new BLN_Corporate__c(
            RecordTypeId = rtInsurance.Id,
            BLN_InsuranceLegalEntity__c =testAccountcorp.Id ,
            BLN_Vehicle__c=veh.Id       
        );
        insert corpRecord;
        
        // Create a test case associated with the test account
        Case testCase = new Case(Subject = 'Test Case', AccountId = testAccount.Id, BLN_Corporate__c = corpRecord.Id);
        insert testCase;
        
        Test.startTest();
        String entityName = BLN_FetchKnowledgeArticles.checkMotabilityAccountName(testCase.Id);
        Test.stopTest();

        // Assertions to check that the entityName is returned correctly
        System.assertEquals('Some Legal Entity Id', entityName, 'The entity name should be correct for Corporate Fleet');        
    }
    /*@isTest
    static void testCheckMotabilityInsurance() {
        // Create a test account
        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;
        
         Account testAccountcorp = new Account(Name = 'Some Legal Entity Id');
        insert testAccountcorp;
       
        BLN_Vehicle__c veh = BLN_TestDataFactory.getVehicle();
        veh.BLN_VehicleRegNumber__c='BN12OEE';
        insert veh;
        
        RecordType rtInsurance = [SELECT Id FROM RecordType WHERE DeveloperName = :System.label.BLN_SplitBill AND SObjectType = 'BLN_Corporate__c' LIMIT 1];
        
        // Create the BLN_Corporate__c record with the 'Corporate Fleet' record type
        BLN_Corporate__c corpRecord = new BLN_Corporate__c(
            RecordTypeId = rtInsurance.Id,
            BLN_InsuranceLegalEntity__c =testAccountcorp.Id ,
            BLN_Vehicle__c=veh.Id       
        );
        insert corpRecord;
        
        // Create a test case associated with the test account
        Case testCase = new Case(Subject = 'Test Case', AccountId = testAccount.Id, BLN_Corporate__c = corpRecord.Id);
        insert testCase;
        
        Test.startTest();
        String entityName = BLN_FetchKnowledgeArticles.checkMotabilityAccountName(testCase.Id);
        Test.stopTest();

        // Assertions to check that the entityName is returned correctly
        System.assertEquals('Some Legal Entity Id', entityName, 'The entity name should be correct for Corporate Fleet');        
    }*/
}