force-app/main/default/objects/BLN_Corporate__c/BLN_Corporate__c.object-meta.xml
<CustomObject>
    <description>FOUK-6065, 5754, This Custom Object is created for storing information about Corporate</description>
    <label>Corporate</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Corporate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Corporates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_Corporate__c/fields/BLN_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>BLN_Vehicle__c</fullName>
    <description>FOUK-6065, 5754, This Custom field is created for storing information about Vehicle Object</description>
    <label>Vehicle</label>
    <referenceTo>BLN_Vehicle__c</referenceTo>
    <relationshipLabel>Corporates</relationshipLabel>
    <relationshipName>Corporates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BLN_Vehicle__c/BLN_Vehicle__c.object-meta.xml
<CustomObject>
    <description>FOUK-495 This object is created for storing the Vehicles.</description>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{00000000}</displayFormat>
        <label>Vehicle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_Vehicle__c/fields/BLN_VIN__c.field-meta.xml
<CustomField>
    <fullName>BLN_VIN__c</fullName>
    <description>FOUK-495 This field is used to store vehicle identification number</description>
    <label>VIN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_VehicleDamage__c/BLN_VehicleDamage__c.object-meta.xml
<CustomObject>
    <description>FOUK-539 This is Vehicle Damage object</description>
    <label>Vehicle Damage</label>
    <nameField>
        <displayFormat>VD-{00000000}</displayFormat>
        <label>Vehicle Damage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Damages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_VehicleDamage__c/fields/BLN_Case__c.field-meta.xml
<CustomField>
    <fullName>BLN_Case__c</fullName>
    <description>FOUK-436 This field is used to store case details</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Vehicle Damages</relationshipLabel>
    <relationshipName>Vehicle_Damages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BLN_VehicleDamage__c/fields/BLN_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>BLN_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>FOUK-539 This field is used to store the associated vehicle.</description>
    <label>Vehicle</label>
    <referenceTo>BLN_Vehicle__c</referenceTo>
    <relationshipLabel>Vehicle Damages</relationshipLabel>
    <relationshipName>Vehicle_Damages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BLN_RecoveryCaseHandlerTest.cls
/*****************************************
ClassName : BLN_RecoveryCaseHandlerTest
Description : FOUK-6164 This test class is used to cover testcoverage for BLN_RecoveryCaseHandler.
CreatedDate: 12-03-2024
CreatedBy : PwC-India
****************************************/


@isTest
private class BLN_RecoveryCaseHandlerTest {
    /*Description : Creating a records using testDataFactory for case*/
    @isTest
    static void testCalculateRecoveryCasePriority() {
        Case casedata=BLN_TestDataFactory.createCaseForRecovery('Price (Cash Opportunities)','Customer Checking Finances',FALSE);
        casedata.BLN_Corporate__c = null;
        insert casedata;
        
        /*Description : Creating a records using testDataFactory for Vehicle Damage*/
        BLN_VehicleDamage__c vehicledamage=BLN_TestDataFactory.createVehcileDamagerForRecovery();
        vehicledamage.BLN_Case__c =	casedata.Id;
        insert vehicledamage;
        
        // Call the method 
        Test.startTest();
        List<Case> caseList = [SELECT Id, BLN_ServiceType__c, BLN_Corporate__c, BLN_SecondaryReason__c, BLN_Escalated__c FROM Case WHERE Id = :casedata.Id ];
        BLN_RecoveryCaseHandler.calculateRecoveryCasePriority(caseList);
        Test.stopTest();
        
        // Verify the priority calculation
        Case updatedCase = [SELECT Id, Priority FROM Case WHERE Id = :casedata.Id];
        System.assertEquals('High', updatedCase.Priority, 'Priority should be set to High');
        
    }  
    
    @isTest
    static void testCalculateRecoveryCasePriorityMedium() {
        Case casedataformedium=BLN_TestDataFactory.createCaseForRecovery('Price (Cash Opportunities)','Customer Checking Finances',FALSE);
        casedataformedium.BLN_Escalated__c = FALSE;
        insert casedataformedium;

        BLN_Vehicle__c veh = BLN_TestDataFactory.getVehicle();
        veh.BLN_VIN__c='';
        insert veh;
        
        BLN_Corporate__c corporate=BLN_TestDataFactory.createcorporate();
        corporate.BLN_Vehicle__c=veh.Id;
        insert corporate;
        
        Case casedataformedium1=BLN_TestDataFactory.createCaseForRecovery('Price (Cash Opportunities)','Customer Checking Finances',FALSE);
        casedataformedium1.BLN_Corporate__c = corporate.id;
        insert casedataformedium1;
        
        /*Description : Creating a records using testDataFactory for Vehicle Damage*/
        BLN_VehicleDamage__c vehicledamage=BLN_TestDataFactory.createVehcileDamagerForRecovery();
        vehicledamage.BLN_Case__c =	casedataformedium1.Id;
        insert vehicledamage;
        
        // Call the method
        Test.startTest();
        List<Case> caseList = [SELECT Id, BLN_ServiceType__c, BLN_Corporate__c, BLN_SecondaryReason__c, BLN_Escalated__c FROM Case WHERE Id = :casedataformedium.Id OR Id = :casedataformedium1.Id ];
        BLN_RecoveryCaseHandler.calculateRecoveryCasePriority(caseList);
        Test.stopTest();
        
        // Verify the priority calculation
        Case updatedCase = [SELECT Id, Priority FROM Case WHERE Id = :casedataformedium.Id];
        System.assertEquals('Medium', updatedCase.Priority, 'Priority should be set to High');
        
        
    }

    @isTest
    static void testCalculateRecoveryCasePriorityCriticalEscalated() {
        Case casedata=BLN_TestDataFactory.createCaseForRecovery('Price (Cash Opportunities)','Customer Checking Finances',TRUE);
        casedata.BLN_Corporate__c = null;
        insert casedata;
        
        /*Description : Creating a records using testDataFactory for Vehicle Damage*/
        BLN_VehicleDamage__c vehicledamage=BLN_TestDataFactory.createVehcileDamagerForRecovery();
        vehicledamage.BLN_Case__c =	casedata.Id;
        insert vehicledamage;
        
        // Call the method 
        Test.startTest();
        List<Case> caseList = [SELECT Id, BLN_ServiceType__c, BLN_Corporate__c, BLN_SecondaryReason__c, BLN_Escalated__c FROM Case WHERE Id = :casedata.Id ];
        BLN_RecoveryCaseHandler.calculateRecoveryCasePriority(caseList);
        Test.stopTest();
        
        // Verify the priority calculation
        Case updatedCase = [SELECT Id, Priority FROM Case WHERE Id = :casedata.Id];
        System.assertEquals('Critical', updatedCase.Priority, 'Priority should be set to Critical');
    }  
}