force-app/main/default/objects/BLN_APICalloutMapper__mdt/BLN_APICalloutMapper__mdt.object-meta.xml
<CustomObject>
    <description>FOUK-6359, API callout header and URL mapping master</description>
    <label>API Callout Mapper</label>
    <pluralLabel>API Callout Mappers</pluralLabel>
</CustomObject>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_CalloutURL__c.field-meta.xml
<CustomField>
    <fullName>BLN_CalloutURL__c</fullName>
    <description>FOUK-6359, Callout URL for Refund</description>
    <label>Callout URL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_NamedCredential__c.field-meta.xml
<CustomField>
    <fullName>BLN_NamedCredential__c</fullName>
    <description>Named Credential for Callout Api</description>
    <label>Named Credential</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BLN_InitiateAutomPaymentMock.cls
/*****************************************
ClassName : BLN_InitiateAutomPaymentMock 
Description :  FOUK-7125, Mock Class For BLN_InitiateAutomPaymentTest to test BLN_InitiateAutomPayment Apex Class
CreatedDate: 04-04-2024
Author: Ayush Kumar Singh (PwC India)
****************************************/
@isTest
public class BLN_InitiateAutomPaymentMock implements HttpCalloutMock{
 /*****************************************
    MethodName : respond
    @description : This method is used to provide mock response for callout
    @return response
    Input Parameter : HttpRequest
    Output Parameter : JSON response
    CreatedDate: 04-04-2024
    CreatedBy : Ayush Kumar Singh (PwC India)
    Change log :
    ****************************************/
    public HTTPResponse respond(HTTPRequest req) {
        BLN_APICalloutMapper__mdt apiCalloutmapperRec = BLN_APICalloutMapper__mdt.getInstance(System.Label.BLN_AutomPmtAPICallName);
        String endPoint = apiCalloutmapperRec.BLN_NamedCredential__c + apiCalloutmapperRec.BLN_CalloutURL__c;
        // Condition for token response
        if(req.getEndpoint() == System.label.BLN_MelissaAccessTokenEndpoint){
            String contentType = 'application/x-www-form-urlencoded';
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', contentType);
            res.setBody('{"access_token": "MockAccessToken123", "expires_in": 3600, "token_type": "Bearer","scope": "read"}');
            res.setStatusCode(200);
            return res;
        }
        //condition for successful response
        else if (req.getEndpoint()==endPoint)
        {
            String contentType = 'application/x-www-form-urlencoded';
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', contentType);
            res.setBody('{"statusCode": "200","message": "Success"}');
            res.setStatusCode(200);
            return res;  
        }
        return null;        
    }
}