force-app/main/default/objects/BLN_APICalloutMapper__mdt/BLN_APICalloutMapper__mdt.object-meta.xml
<CustomObject>
    <description>FOUK-6359, API callout header and URL mapping master</description>
    <label>API Callout Mapper</label>
    <pluralLabel>API Callout Mappers</pluralLabel>
</CustomObject>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_APITimeout__c.field-meta.xml
<CustomField>
    <fullName>BLN_APITimeout__c</fullName>
    <description>Timeout value Milliseconds</description>
    <inlineHelpText>Milliseconds</inlineHelpText>
    <label>API Timeout</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_CalloutURL__c.field-meta.xml
<CustomField>
    <fullName>BLN_CalloutURL__c</fullName>
    <description>FOUK-6359, Callout URL for Refund</description>
    <label>Callout URL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_DestinationSystem__c.field-meta.xml
<CustomField>
    <fullName>BLN_DestinationSystem__c</fullName>
    <description>FOUK-6359, Destination System for Refund Integration</description>
    <label>Destination System</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_Headers__c.field-meta.xml
<CustomField>
    <fullName>BLN_Headers__c</fullName>
    <description>FOUK-6359, Headers for Refund Integration</description>
    <label>Headers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_Method__c.field-meta.xml
<CustomField>
    <fullName>BLN_Method__c</fullName>
    <description>Method for the Api callout</description>
    <label>Method</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_NamedCredential__c.field-meta.xml
<CustomField>
    <fullName>BLN_NamedCredential__c</fullName>
    <description>Named Credential for Callout Api</description>
    <label>Named Credential</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/BLN_ExternalFileLinks__c.object-meta.xml
<CustomObject>
    <description>FOUK-5770 This custom object will hold records to keep mapping between the ParentId eg WOLIId and AWS DocumentId</description>
    <label>External File Links</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>ExtFileLink</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External File Links</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_Category__c.field-meta.xml
<CustomField>
    <fullName>BLN_Category__c</fullName>
    <description>Categorization of the File Uploaded</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Inspection</fullName>
            </value>
            <value>
                <fullName>Additional Inspection</fullName>
            </value>
            <value>
                <fullName>Post-Inspection</fullName>
            </value>
            <value>
                <fullName>Recalibration</fullName>
            </value>
            <value>
                <fullName>Failed Appointment Photos</fullName>
            </value>
            <value>
                <fullName>Corrective Action Report</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_DocumentId__c.field-meta.xml
<CustomField>
    <fullName>BLN_DocumentId__c</fullName>
    <description>FOUK-7055 This field is to hold the AWS Id returned by Mule-AWS</description>
    <label>Document Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_FileCreationDate__c.field-meta.xml
<CustomField>
    <fullName>BLN_FileCreationDate__c</fullName>
    <description>FOUK-7055 This field is to hold DateTime of when document Id was created</description>
    <label>File Creation Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_FileName__c.field-meta.xml
<CustomField>
    <fullName>BLN_FileName__c</fullName>
    <description>FOUK-7055 This field is to hold original file name</description>
    <label>File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_FileSize__c.field-meta.xml
<CustomField>
    <fullName>BLN_FileSize__c</fullName>
    <description>FOUK-7055 File size of the file in bytes</description>
    <label>File Size</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_FileType__c.field-meta.xml
<CustomField>
    <fullName>BLN_FileType__c</fullName>
    <description>FOUK-7055 This field is to hold File Type</description>
    <label>File Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JPG</fullName>
            </value>
            <value>
                <fullName>PNG</fullName>
            </value>
            <value>
                <fullName>PDF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_ParentId__c.field-meta.xml
<CustomField>
    <fullName>BLN_ParentId__c</fullName>
    <description>FOUK-7055 This field is to hold Parent Id</description>
    <externalId>true</externalId>
    <label>Parent Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_ParentObjectName__c.field-meta.xml
<CustomField>
    <fullName>BLN_ParentObjectName__c</fullName>
    <description>FOUK-7055 This field is to hold name of Parent Object</description>
    <label>Parent Object Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_S3BucketLink__c.field-meta.xml
<CustomField>
    <fullName>BLN_S3BucketLink__c</fullName>
    <description>FOUK-7055 This field is to hold Amazon AWS S3 Bucket Link</description>
    <label>S3 Bucket Link</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BLN_FileCategoryConfig__mdt/BLN_FileCategoryConfig__mdt.object-meta.xml
<CustomObject>
    <description>FOUK-9422, FOUK-7055 
Metadata created for storing configuration of File category</description>
    <label>File Category Config</label>
    <pluralLabel>File Category Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/BLN_FileCategoryConfig__mdt/fields/BLN_CategoryType__c.field-meta.xml
<CustomField>
    <fullName>BLN_CategoryType__c</fullName>
    <description>FOUK-9422, FOUK-7055 - created for storing configuration of File category</description>
    <label>Category Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Inspection</fullName>
                <default>true</default>
                <label>Pre-Inspection</label>
            </value>
            <value>
                <fullName>Additional Inspection</fullName>
            </value>
            <value>
                <fullName>Post-Inspection</fullName>
            </value>
            <value>
                <fullName>Recalibration</fullName>
            </value>
            <value>
                <fullName>Failed Appointment Photos</fullName>
            </value>
            <value>
                <fullName>Corrective Action Report</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_FileCategoryConfig__mdt/fields/BLN_Keywords__c.field-meta.xml
<CustomField>
    <fullName>BLN_Keywords__c</fullName>
    <description>FOUK-9422, FOUK-7055 created for storing File Keywords</description>
    <label>Keywords</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_FileTypesUploadToAWS__mdt/BLN_FileTypesUploadToAWS__mdt.object-meta.xml
<CustomObject>
    <description>FOUK-7053 MetaData to store which types of files should be uploaded to AWS</description>
    <label>File Types upload to AWS</label>
    <pluralLabel>File Types upload to AWS</pluralLabel>
</CustomObject>

force-app/main/default/classes/BLN_UploadFileToAWSQueueable.cls
/*****************************************
ClassName : BLN_UploadFileToAWSQueueable
Description : FOUK-7053
CreatedDate: 25-06-2024
CreatedBy : PwC-India
****************************************/


/*  *@description:This class is used to upload file to AWS*/
public with sharing class BLN_UploadFileToAWSQueueable implements Queueable, Database.AllowsCallouts  {
    public Map<String,String> keywordVsCategoryMap = new Map<String,String>();
    public List<ContentDocumentLink> cdlList{get;set;}
/**
*@description:This is a constructor.
*@return 
*/
    public BLN_UploadFileToAWSQueueable(List<ContentDocumentLink> cdlList){
           this.cdlList = cdlList;
         }

        /**
*@description:This is method used to do callout 
*@return  void
*/
    public void execute(QueueableContext context) {

        try{
            //collect all keywords vs category            
            List<BLN_FileCategoryConfig__mdt> categoryConfigMetaData = BLN_FileCategoryConfig__mdt.getall().values();
            if (categoryConfigMetaData != null && categoryConfigMetaData.size() > 0) {
                for (BLN_FileCategoryConfig__mdt configRec : categoryConfigMetaData) {
                    
                    if (configRec.BLN_Keywords__c != null) {                        
                        generateKeywordVscategoryMap(configRec);                        
                    }
                    
                }
            }


            Set<Id> contentDocumentIds = new Set<Id>();
            for (ContentDocumentLink cdl : cdlList) {

                if(cdl.ContentDocumentId!=null){
                    contentDocumentIds.add(cdl.ContentDocumentId);
                }
            }
        
            List<ContentVersion> newCvList = new List<ContentVersion>();
            if(Schema.sObjectType.ContentVersion.isAccessible()){
                newCvList = [SELECT Id, ContentDocumentId, VersionData, Title, FileType, FileExtension, CreatedBy.Name, CreatedDate, 
                                ContentSize,BLN_IsUploadedToAWS__c 
                            FROM ContentVersion 
                            WHERE ContentDocumentId IN :contentDocumentIds WITH SECURITY_ENFORCED];
        }
        
        List<String> fileTypeList = new List<String>();
        List<BLN_FileTypesUploadToAWS__mdt> fileTypeMetaData = BLN_FileTypesUploadToAWS__mdt.getall().values();
        for(BLN_FileTypesUploadToAWS__mdt fileTypeMeta :fileTypeMetaData){
            if(fileTypeMeta.DeveloperName!=null){
            fileTypeList.add(fileTypeMeta.DeveloperName);
            }
        }
        // Create a map to store ContentVersion records with ContentDocumentId as the key
        Map<Id, ContentVersion> documentVersionMap = new Map<Id, ContentVersion>();
        for (ContentVersion cv : newCvList) {
                if(fileTypeList.contains(cv.FileExtension) && cv.ContentDocumentId!=null){
            documentVersionMap.put(cv.ContentDocumentId, cv);
            }
        }
            // // Query ContentDocumentLink records associated with the ContentDocumentId
            // List<ContentDocumentLink> cdlList = new List<ContentDocumentLink>();
            // if(Schema.sObjectType.ContentDocumentLink.isAccessible()){
            //  cdlList = [SELECT Id, ContentDocumentId, LinkedEntityId, LinkedEntity.Type FROM ContentDocumentLink WHERE ContentDocumentId IN :documentVersionMap.keySet() ];
            // }
            // List to store FileDataWrapper objects
            List<FileDataWrapper> fileDataWrapList = new List<FileDataWrapper>();
        
            for (ContentDocumentLink cdl : cdlList) {
                if (documentVersionMap.containsKey(cdl.ContentDocumentId)) {
                ContentVersion cv = documentVersionMap.get(cdl.ContentDocumentId);
                // Create a new FileDataWrapper object and populate it with data from ContentVersion
                FileDataWrapper fileDataWrap = new FileDataWrapper();
                fileDataWrap.additionalInfo = 'Additional';
                fileDataWrap.documentType = cv.FileType;
                fileDataWrap.fileExtension = cv.FileExtension;
                fileDataWrap.fileName = cv.Title +'.'+cv.FileExtension;
                fileDataWrap.documentSource = System.label.BLN_DocumentSource;
                fileDataWrap.createdBy = cv.CreatedBy.Name; // Uncomment and use CreatedById if needed
                fileDataWrap.fileBytes = EncodingUtil.base64Encode(cv.VersionData);
                fileDataWrap.associations = new List<AssociationWrapper>{
                    new AssociationWrapper(cdl.LinkedEntityId,System.label.BLN_SalesForceWorkOrder)
                };
                fileDataWrapList.add(fileDataWrap);
            }
        }


        String endPoint;
        HttpResponse response = new HttpResponse();
        Map<String,String> headerMap = new Map<String,String>();
        DocStoreWrapper docStoreRes = new DocStoreWrapper(); 
        List<ContentVersion> uplodedCvList =  new List<ContentVersion>();
        // DocStoreErrorWrapper docStoreError = new DocStoreErrorWrapper();
        List<BLN_ExternalFileLinks__c> extFileLinkList = new List<BLN_ExternalFileLinks__c>();
            
        Map<String,DocInfoWrapper> docStoreInfoMap = new Map<String,DocInfoWrapper>();

            if(!fileDataWrapList.isEmpty()){
                BLN_APICalloutMapper__mdt calloutDetails = BLN_APICalloutMapper__mdt.getInstance(System.label.BLN_UploadDocumentLabel);    
                headerMap.put(System.label.BLN_AuthorizationBearer.split(System.label.BLN_Comma)[0],System.label.BLN_AuthorizationBearer.split(System.label.BLN_Comma)[1]+' '+BLN_HTTPCallOutAccessToken.getAccessToken()?.accessToken);
            
        for(String str : calloutDetails.BLN_Headers__c.split(System.label.BLN_Semicolon)){
            headerMap.put(str.split(System.label.BLN_Comma)[0],str.split(System.label.BLN_Comma)[1]);
        }
        endPoint = calloutDetails.BLN_NamedCredential__c + calloutDetails.BLN_CalloutURL__c;
                Integer timeout = Integer.valueOf(calloutDetails.BLN_APITimeout__c);
                response = BLN_HttpCalloutUtility.makeCallout(calloutDetails.BLN_DestinationSystem__c, endPoint, calloutDetails.BLN_Method__c, headerMap,'',JSON.serialize(fileDataWrapList),timeout);
        }

        if ( response.getStatusCode() == 201 || response.getStatusCode() == 200) {
            docStoreRes = (DocStoreWrapper) JSON.deserialize(response.getBody(), DocStoreWrapper.class);  
            for(DocInfoWrapper docStore: docStoreRes.docStore){
                docStoreInfoMap.put(docStore.associationId,docStore);
            }
                
            }
            
           for(ContentDocumentLink cdl: cdlList){
                if(docStoreInfoMap.containsKey(cdl.LinkedEntityId) && documentVersionMap.containsKey(cdl.ContentDocumentId)){
                    DocInfoWrapper docStoreInfo = docStoreInfoMap.get(cdl.LinkedEntityId);
                    ContentVersion cv = documentVersionMap.get(cdl.ContentDocumentId);
                    BLN_ExternalFileLinks__c extFileLink = new BLN_ExternalFileLinks__c();
                    extFileLink.BLN_FileName__c = cv.Title;
                    extFileLink.BLN_FileType__c = cv.FileType;
                    extFileLink.BLN_ParentId__c = docStoreInfo.associationId;
                    extFileLink.BLN_ParentObjectName__c = cdl.LinkedEntityId.getSObjectType().getDescribe().getName();
                    extFileLink.BLN_DocumentId__c = docStoreInfo.documentId;
                    extFileLink.BLN_FileCreationDate__c = cv.CreatedDate;
                    extFileLink.BLN_S3BucketLink__c = docStoreInfo.publicLink;
                    extFileLink.BLN_FileSize__c =  String.valueOf(cv.ContentSize);

                    //for categorization
                    Set<String> keywords =keywordVsCategoryMap.keySet();

                    for(String keyword : keywords){
                        if(cv.Title.contains(keyword)){
                            extFileLink.BLN_Category__c =  keywordVsCategoryMap.get(keyword);
                            break;
                        }
                    }
                    extFileLinkList.add(extFileLink);
                    uplodedCvList.add(new ContentVersion(Id = cv.Id , BLN_IsUploadedToAWS__c = true));
                }
            }
            

            if(!extFileLinkList.isEmpty() && Schema.sObjectType.BLN_ExternalFileLinks__c.isCreateable()){
                insert extFileLinkList;
            }

            if(!uplodedCvList.isEmpty() && Schema.sObjectType.BLN_ExternalFileLinks__c.isCreateable()){
          update uplodedCvList;
      }
    }
        catch(Exception e){
            BLN_ExceptionLogger.captureException(e);
        }
    }


    
    public void generateKeywordVscategoryMap(BLN_FileCategoryConfig__mdt configRec){
        List<String> keywordList = new List<String>();
        keywordList.addAll(configRec.BLN_Keywords__c.split(','));
        if (keywordList != null && keywordList.size() > 0) {
            for (String keyword : keywordList) {
                keywordVsCategoryMap.put(keyword, configRec.BLN_CategoryType__c);
            }                
        }
    }
    
     // Inner class to wrap file data
     public class FileDataWrapper {
        public String additionalInfo;
        public String documentType;
        public String fileExtension;
        public String fileName;
        public String documentSource;
        public String createdBy;
        public String fileBytes;
        public List<AssociationWrapper> associations;
    }
    // Inner class to wrap associations
    public class AssociationWrapper {
        public String associationId;
        public String typeOfAssociation;
        
        // Constructor for AssociationWrapper
        public AssociationWrapper(String associationId,string typeOfAssociation) {
            this.associationId = associationId;
            this.typeOfAssociation = typeOfAssociation; // Initialize with default or actual type if needed
        }
    }
    public class DocStoreWrapper {
        public List<DocInfoWrapper> docStore { get; set; }
    
    }
    public class DocInfoWrapper {
        public String associationId { get; set; }
        public String documentId { get; set; }
        public String publicLink { get; set; }
    }
}