force-app/main/default/objects/BLN_APICalloutMapper__mdt/BLN_APICalloutMapper__mdt.object-meta.xml
<CustomObject>
    <description>FOUK-6359, API callout header and URL mapping master</description>
    <label>API Callout Mapper</label>
    <pluralLabel>API Callout Mappers</pluralLabel>
</CustomObject>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_CalloutURL__c.field-meta.xml
<CustomField>
    <fullName>BLN_CalloutURL__c</fullName>
    <description>FOUK-6359, Callout URL for Refund</description>
    <label>Callout URL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_DestinationSystem__c.field-meta.xml
<CustomField>
    <fullName>BLN_DestinationSystem__c</fullName>
    <description>FOUK-6359, Destination System for Refund Integration</description>
    <label>Destination System</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_Headers__c.field-meta.xml
<CustomField>
    <fullName>BLN_Headers__c</fullName>
    <description>FOUK-6359, Headers for Refund Integration</description>
    <label>Headers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_Method__c.field-meta.xml
<CustomField>
    <fullName>BLN_Method__c</fullName>
    <description>Method for the Api callout</description>
    <label>Method</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_NamedCredential__c.field-meta.xml
<CustomField>
    <fullName>BLN_NamedCredential__c</fullName>
    <description>Named Credential for Callout Api</description>
    <label>Named Credential</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/BLN_ExternalFileLinks__c.object-meta.xml
<CustomObject>
    <description>FOUK-5770 This custom object will hold records to keep mapping between the ParentId eg WOLIId and AWS DocumentId</description>
    <label>External File Links</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>ExtFileLink</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External File Links</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_Category__c.field-meta.xml
<CustomField>
    <fullName>BLN_Category__c</fullName>
    <description>Categorization of the File Uploaded</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Inspection</fullName>
            </value>
            <value>
                <fullName>Additional Inspection</fullName>
            </value>
            <value>
                <fullName>Post-Inspection</fullName>
            </value>
            <value>
                <fullName>Recalibration</fullName>
            </value>
            <value>
                <fullName>Failed Appointment Photos</fullName>
            </value>
            <value>
                <fullName>Corrective Action Report</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_DocumentId__c.field-meta.xml
<CustomField>
    <fullName>BLN_DocumentId__c</fullName>
    <description>FOUK-7055 This field is to hold the AWS Id returned by Mule-AWS</description>
    <label>Document Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_FileCreationDate__c.field-meta.xml
<CustomField>
    <fullName>BLN_FileCreationDate__c</fullName>
    <description>FOUK-7055 This field is to hold DateTime of when document Id was created</description>
    <label>File Creation Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_FileName__c.field-meta.xml
<CustomField>
    <fullName>BLN_FileName__c</fullName>
    <description>FOUK-7055 This field is to hold original file name</description>
    <label>File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_FileSize__c.field-meta.xml
<CustomField>
    <fullName>BLN_FileSize__c</fullName>
    <description>FOUK-7055 File size of the file in bytes</description>
    <label>File Size</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_FileType__c.field-meta.xml
<CustomField>
    <fullName>BLN_FileType__c</fullName>
    <description>FOUK-7055 This field is to hold File Type</description>
    <label>File Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JPG</fullName>
            </value>
            <value>
                <fullName>PNG</fullName>
            </value>
            <value>
                <fullName>PDF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_ParentId__c.field-meta.xml
<CustomField>
    <fullName>BLN_ParentId__c</fullName>
    <description>FOUK-7055 This field is to hold Parent Id</description>
    <externalId>true</externalId>
    <label>Parent Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_ParentObjectName__c.field-meta.xml
<CustomField>
    <fullName>BLN_ParentObjectName__c</fullName>
    <description>FOUK-7055 This field is to hold name of Parent Object</description>
    <label>Parent Object Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_S3BucketLink__c.field-meta.xml
<CustomField>
    <fullName>BLN_S3BucketLink__c</fullName>
    <description>FOUK-7055 This field is to hold Amazon AWS S3 Bucket Link</description>
    <label>S3 Bucket Link</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BLN_FileCategoryConfig__mdt/BLN_FileCategoryConfig__mdt.object-meta.xml
<CustomObject>
    <description>FOUK-9422, FOUK-7055 
Metadata created for storing configuration of File category</description>
    <label>File Category Config</label>
    <pluralLabel>File Category Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/BLN_FileCategoryConfig__mdt/fields/BLN_CategoryType__c.field-meta.xml
<CustomField>
    <fullName>BLN_CategoryType__c</fullName>
    <description>FOUK-9422, FOUK-7055 - created for storing configuration of File category</description>
    <label>Category Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Inspection</fullName>
                <default>true</default>
                <label>Pre-Inspection</label>
            </value>
            <value>
                <fullName>Additional Inspection</fullName>
            </value>
            <value>
                <fullName>Post-Inspection</fullName>
            </value>
            <value>
                <fullName>Recalibration</fullName>
            </value>
            <value>
                <fullName>Failed Appointment Photos</fullName>
            </value>
            <value>
                <fullName>Corrective Action Report</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_FileCategoryConfig__mdt/fields/BLN_Keywords__c.field-meta.xml
<CustomField>
    <fullName>BLN_Keywords__c</fullName>
    <description>FOUK-9422, FOUK-7055 created for storing File Keywords</description>
    <label>Keywords</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_FileTypesUploadToAWS__mdt/BLN_FileTypesUploadToAWS__mdt.object-meta.xml
<CustomObject>
    <description>FOUK-7053 MetaData to store which types of files should be uploaded to AWS</description>
    <label>File Types upload to AWS</label>
    <pluralLabel>File Types upload to AWS</pluralLabel>
</CustomObject>

force-app/main/default/classes/BLN_UploadSRToAWS.cls
public with sharing class BLN_UploadSRToAWS {
    
    public static Map<String,String> keywordVsCategoryMap = new Map<String,String>();

    //invokable method to send data to Docstore
    @InvocableMethod(label='Service Report Ids' category='Service Report')
    public static void sendDatatoDocstore(List<ID> ids){
        processData(ids);
    }
    
    @future(callout=true)
    public static void processData(List<ID> ids){

        try {
        
            Boolean processPDFsForDocstore = false;

            List<BLN_ExternalFileLinks__c> extFileLinkList = new List<BLN_ExternalFileLinks__c>();
            List<ContentVersion> uplodedCvList =  new List<ContentVersion>();
            
            //filter by allowable file type
            List<BLN_FileTypesUploadToAWS__mdt> fileTypeMetaData = BLN_FileTypesUploadToAWS__mdt.getall().values();
            for(BLN_FileTypesUploadToAWS__mdt fileTypeMeta :fileTypeMetaData){
                if(fileTypeMeta.DeveloperName == 'PDF'){
                    processPDFsForDocstore = true;
                }
            }

            //collect all keywords vs category            
            List<BLN_FileCategoryConfig__mdt> categoryConfigMetaData = BLN_FileCategoryConfig__mdt.getall().values();
            if (categoryConfigMetaData != null && categoryConfigMetaData.size() > 0) {
                for (BLN_FileCategoryConfig__mdt configRec : categoryConfigMetaData) {
                    
                    if (configRec.BLN_Keywords__c != null) {                        
                        generateKeywordVscategoryMap(configRec);                        
                    }
                    
                }
            }
            
            if(processPDFsForDocstore){
                
                List<BLN_UploadFileToAWSQueueable.FileDataWrapper> fileDataWrapList = 
                    new List<BLN_UploadFileToAWSQueueable.FileDataWrapper>();
                
                List<ServiceReport> serviceReportList = [SELECT Id, ContentVersionDocumentId, CreatedDate,
                                                            ContentVersionDocument.FileType, 
                                                            ContentVersionDocument.FileExtension,
                                                            ContentVersionDocument.Title,
                                                            createdby.name, ParentId, ServiceReportNumber,
                                                            ContentVersionDocument.VersionData,
                                                            ContentVersionDocument.ContentSize
                                                        FROM ServiceReport 
                                                        WHERE Id IN: ids WITH SECURITY_ENFORCED];
                
                if(serviceReportList != null && serviceReportList.size() > 0){
                    //create payload
                    Map<String,String> headerMap = new Map<String,String>();
                        
                    BLN_APICalloutMapper__mdt calloutDetails = BLN_APICalloutMapper__mdt.getInstance(System.label.BLN_UploadDocumentLabel);    
                    headerMap.put(System.label.BLN_AuthorizationBearer.split(System.label.BLN_Comma)[0],System.label.BLN_AuthorizationBearer.split(System.label.BLN_Comma)[1]+' '+BLN_HTTPCallOutAccessToken.getAccessToken()?.accessToken);
                    
                    for(String str : calloutDetails.BLN_Headers__c.split(System.label.BLN_Semicolon)){
                        headerMap.put(str.split(System.label.BLN_Comma)[0],str.split(System.label.BLN_Comma)[1]);
                    }
                    
                    for(ServiceReport srRec: serviceReportList){
                        
                        BLN_UploadFileToAWSQueueable.FileDataWrapper fileDataWrap 
                            = new BLN_UploadFileToAWSQueueable.FileDataWrapper();
                        fileDataWrap.additionalInfo = 'Additional';
                        fileDataWrap.documentType = srRec.ContentVersionDocument.FileType;
                        fileDataWrap.fileExtension = srRec.ContentVersionDocument.FileExtension;
                        String processedTitle = srRec.ServiceReportNumber.replace(':', '-');
                        fileDataWrap.fileName = processedTitle
                                                +'.'
                                                +srRec.ContentVersionDocument.FileExtension;
                        fileDataWrap.documentSource = System.label.BLN_DocumentSource;
                        fileDataWrap.createdBy = srRec.CreatedBy.Name;
                        fileDataWrap.fileBytes = EncodingUtil.base64Encode(srRec.ContentVersionDocument.VersionData);
                        fileDataWrap.associations = new List<BLN_UploadFileToAWSQueueable.AssociationWrapper>{
                            new BLN_UploadFileToAWSQueueable.AssociationWrapper(srRec.ParentId,
                                                                                System.label.BLN_SalesForceWorkOrder)
                        };
                        
                        //proceed for callout                    
                        String endPoint;
                        HttpResponse response = new HttpResponse();
                        
                        endPoint = calloutDetails.BLN_NamedCredential__c + calloutDetails.BLN_CalloutURL__c;
                        
                        response = BLN_HttpCalloutUtility.makeCallout(calloutDetails.BLN_DestinationSystem__c, 
                                                                    endPoint, 
                                                                    calloutDetails.BLN_Method__c, 
                                                                    headerMap,
                                                                    '',
                                                                    JSON.serialize(new List<BLN_UploadFileToAWSQueueable.FileDataWrapper>{fileDataWrap}));
                            
                        extFileLinkList.add(createExternalFileRec(response, srRec)); 
                        
                        uplodedCvList.add(updateContentVersion(srRec.ContentVersionDocumentId));
                        
                    }
                    
                }    
                
                if(extFileLinkList != null && extFileLinkList.size() > 0 && Schema.sObjectType.BLN_ExternalFileLinks__c.isCreateable()){
                    insert extFileLinkList;
                }
                
                if(uplodedCvList != null && uplodedCvList.size() > 0 && Schema.sObjectType.ContentVersion.isUpdateable()){
                    update uplodedCvList;  
                }
                
            }

        } catch (Exception e) {
            BLN_ExceptionLogger.captureException(e);    
        }
    }


    public static BLN_ExternalFileLinks__c createExternalFileRec(HttpResponse response, ServiceReport srRec){

        if ( response.getStatusCode() == 201 || response.getStatusCode() == 200) {
            BLN_UploadFileToAWSQueueable.DocStoreWrapper docStoreRes 
                            = new BLN_UploadFileToAWSQueueable.DocStoreWrapper();
            docStoreRes = (BLN_UploadFileToAWSQueueable.DocStoreWrapper) JSON.deserialize(response.getBody(), BLN_UploadFileToAWSQueueable.DocStoreWrapper.class);  
            
            BLN_ExternalFileLinks__c extFileLink = new BLN_ExternalFileLinks__c();
            extFileLink.BLN_FileName__c = srRec.ServiceReportNumber;
            extFileLink.BLN_FileType__c = srRec.ContentVersionDocument.FileType;
            extFileLink.BLN_ParentId__c = srRec.ParentId;
            extFileLink.BLN_ParentObjectName__c = srRec.ParentId.getSObjectType().getDescribe().getName();
            extFileLink.BLN_DocumentId__c = docStoreRes.docStore[0].documentId;
            extFileLink.BLN_FileCreationDate__c = srRec.CreatedDate;
            extFileLink.BLN_S3BucketLink__c = docStoreRes.docStore[0].publicLink;
            extFileLink.BLN_FileSize__c =  String.valueOf(srRec.ContentVersionDocument.ContentSize);
            
            //for categorization
            Set<String> keywords = keywordVsCategoryMap.keySet();
            
            for(String keyword : keywords){
                if(srRec.ServiceReportNumber.contains(keyword)){
                    extFileLink.BLN_Category__c = keywordVsCategoryMap.get(keyword);
                    break;
                }
            }
            
            return extFileLink;           
            
        }

        return null;

    }

    public static ContentVersion updateContentVersion(Id cvId){
        ContentVersion cv = new ContentVersion(Id = cvId,
                                                BLN_IsUploadedToAWS__c = true);

        return cv;
    }
    
    public static void generateKeywordVscategoryMap(BLN_FileCategoryConfig__mdt configRec){
        List<String> keywordList = new List<String>();
        keywordList.addAll(configRec.BLN_Keywords__c.split(','));
        if (keywordList != null && keywordList.size() > 0) {
            for (String keyword : keywordList) {
                keywordVsCategoryMap.put(keyword, configRec.BLN_CategoryType__c);
            }                
        }
    }

}