force-app/main/default/objects/BLN_APICalloutMapper__mdt/BLN_APICalloutMapper__mdt.object-meta.xml
<CustomObject>
    <description>FOUK-6359, API callout header and URL mapping master</description>
    <label>API Callout Mapper</label>
    <pluralLabel>API Callout Mappers</pluralLabel>
</CustomObject>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_APITimeout__c.field-meta.xml
<CustomField>
    <fullName>BLN_APITimeout__c</fullName>
    <description>Timeout value Milliseconds</description>
    <inlineHelpText>Milliseconds</inlineHelpText>
    <label>API Timeout</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_CalloutURL__c.field-meta.xml
<CustomField>
    <fullName>BLN_CalloutURL__c</fullName>
    <description>FOUK-6359, Callout URL for Refund</description>
    <label>Callout URL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_DestinationSystem__c.field-meta.xml
<CustomField>
    <fullName>BLN_DestinationSystem__c</fullName>
    <description>FOUK-6359, Destination System for Refund Integration</description>
    <label>Destination System</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_Headers__c.field-meta.xml
<CustomField>
    <fullName>BLN_Headers__c</fullName>
    <description>FOUK-6359, Headers for Refund Integration</description>
    <label>Headers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_Method__c.field-meta.xml
<CustomField>
    <fullName>BLN_Method__c</fullName>
    <description>Method for the Api callout</description>
    <label>Method</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_NamedCredential__c.field-meta.xml
<CustomField>
    <fullName>BLN_NamedCredential__c</fullName>
    <description>Named Credential for Callout Api</description>
    <label>Named Credential</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BLN_QueueMSGSessionCallout.cls
/**@description : This Apex class used to send callout and mapping.
*  @author: PwC India
*  @Story:
*  @CreatedDate: 10/07/2024
*/

public without sharing class BLN_QueueMSGSessionCallout implements Queueable, Database.AllowsCallouts {
    private String payloadJson = '';

/**
*@description:This is a constructor.
*@return 
*/
    public BLN_QueueMSGSessionCallout(String json) {
        payloadJson = json;
    }

     /**
*@description:This is method used to do callout and field mapping.
*@return  void
*/
public void execute(QueueableContext context) {
    String responseBody = '';
    try{
        String requestBody = payloadJson;
        BLN_APICalloutMapper__mdt calloutData = BLN_APICalloutMapper__mdt.getInstance('BLN_MSGSessionApiCallout');

         Map<String,String> headerMap = new Map<String,String>();
         headerMap.put(System.label.BLN_AuthorizationBearer.split(System.label.BLN_Comma)[0],System.label.BLN_AuthorizationBearer.split(System.label.BLN_Comma)[1]+' '+BLN_HTTPCallOutAccessToken.getAccessToken()?.accessToken);
         for(String header : calloutData.BLN_Headers__c.split(System.label.BLN_Semicolon)){
             headerMap.put(header.split(System.label.BLN_Comma)[0],header.split(System.label.BLN_Comma)[1]);
         }
         String hCode = EncodingUtil.convertToHex(Crypto.generateAesKey(128));
         String correlID = hCode.substring(0,4)+'-'+hCode.substring(0,4)+'-'+hCode.substring(5,8)+'-'+hCode.substring(9,12)+'-'+hCode.substring(12,16)+'-'+hCode.substring(16,20);
        headerMap.put(System.label.BLN_XCORRELATIONID,correlID);
        HttpResponse response = BLN_HttpCalloutUtility.makeCallout(calloutData.BLN_DestinationSystem__c,calloutData.BLN_NamedCredential__c+calloutData.BLN_CalloutURL__c,calloutData.BLN_Method__c,headerMap,'',requestBody,Integer.valueOf(calloutData.BLN_APITimeout__c));

        if(response.getStatusCode() == 201){
            responseBody = response.getBody();
        }
        
    }catch(Exception e){
        BLN_ExceptionLogger.captureException(e);

    }
} 
}