force-app/main/default/objects/BLN_APICalloutMapper__mdt/BLN_APICalloutMapper__mdt.object-meta.xml
<CustomObject>
    <description>FOUK-6359, API callout header and URL mapping master</description>
    <label>API Callout Mapper</label>
    <pluralLabel>API Callout Mappers</pluralLabel>
</CustomObject>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_CalloutURL__c.field-meta.xml
<CustomField>
    <fullName>BLN_CalloutURL__c</fullName>
    <description>FOUK-6359, Callout URL for Refund</description>
    <label>Callout URL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_EntityName__c.field-meta.xml
<CustomField>
    <fullName>BLN_EntityName__c</fullName>
    <description>FOUK-6359, Entity Name of the callout</description>
    <label>Entity Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_EventType__c.field-meta.xml
<CustomField>
    <fullName>BLN_EventType__c</fullName>
    <description>FOUK-6359, Event Type for Refund Integration</description>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Create</fullName>
                <default>true</default>
                <label>Create</label>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_Headers__c.field-meta.xml
<CustomField>
    <fullName>BLN_Headers__c</fullName>
    <description>FOUK-6359, Headers for Refund Integration</description>
    <label>Headers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_NamedCredential__c.field-meta.xml
<CustomField>
    <fullName>BLN_NamedCredential__c</fullName>
    <description>Named Credential for Callout Api</description>
    <label>Named Credential</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_SourceSystem__c.field-meta.xml
<CustomField>
    <fullName>BLN_SourceSystem__c</fullName>
    <description>FOUK-6359, Source System for Refund Integration</description>
    <label>Source System</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/BLN_Payment__c.object-meta.xml
<CustomObject>
    <description>FOUK-4686: This object is created to store Payment information.</description>
    <label>Payments &amp; Refunds</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments &amp; Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_CR__c.field-meta.xml
<CustomField>
    <fullName>BLN_CR__c</fullName>
    <description>FOUK-3977 This is used in BLN_SCUtility class.</description>
    <externalId>true</externalId>
    <label>CR</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_Currency__c.field-meta.xml
<CustomField>
    <fullName>BLN_Currency__c</fullName>
    <defaultValue>&apos;GBP&apos;</defaultValue>
    <description>FOUK-5663, FOUK-5744 Fixed value for UK</description>
    <label>Currency</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_LinkData__c.field-meta.xml
<CustomField>
    <fullName>BLN_LinkData__c</fullName>
    <description>FOUK-9249, stores the link data id from Worldpay</description>
    <label>Link Data</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_OriginalPayment__c.field-meta.xml
<CustomField>
    <fullName>BLN_OriginalPayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>FOUK-4665, This Lookup FIeld is created for Payment &amp; Refunds Object</description>
    <label>Linked to Payment Record</label>
    <referenceTo>BLN_Payment__c</referenceTo>
    <relationshipLabel>Payments &amp; Refunds</relationshipLabel>
    <relationshipName>Payments_Refunds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_PaymentAmountTaken__c.field-meta.xml
<CustomField>
    <fullName>BLN_PaymentAmountTaken__c</fullName>
    <description>FOUK-4686: This field is created to store Payment amount taken value.</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_PmtGatewayProvider__c.field-meta.xml
<CustomField>
    <fullName>BLN_PmtGatewayProvider__c</fullName>
    <description>FOUK-5663 and FOUK-5744 Capture the payment gateway provider, for automated and assisted payments, it is always Barclays. For any other payment channel, it is Worldpay</description>
    <label>Payment Gateway Provider</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Barclays</fullName>
            </value>
            <value>
                <fullName>WorldPay</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_PmtReferenceId__c.field-meta.xml
<CustomField>
    <fullName>BLN_PmtReferenceId__c</fullName>
    <description>FOUK-9426 To Store Value of Payment Reference</description>
    <label>Payment Reference</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Payment__c/fields/BLN_RefundType__c.field-meta.xml
<CustomField>
    <fullName>BLN_RefundType__c</fullName>
    <description>FOUK-5663, FOUK-5744 Determines whether it was a full refund made or a partial refund based on the comparison of payment amount and the total amount refunded.</description>
    <label>Refund Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full</fullName>
            </value>
            <value>
                <fullName>Partial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BLN_PushRefundtoGateway.cls
/*****************************************
ClassName : BLN_PushRefundtoGateway
Description :  FOUK-6359, do the callout after creating Refund Record
CreatedDate: 28-03-2024
Author: Ayush Kumar Singh (PwC India)
****************************************/
public class BLN_PushRefundtoGateway implements Queueable{
    public String paymentRecordId ; 
    public BLN_PushRefundtoGateway(String  paymentRecordId){
        this.paymentRecordId = paymentRecordId ;
    }
    public void execute(QueueableContext context) {
        pushRefundToGateway(paymentRecordId);
    }
    
    /*****************************************
MethodName : pushRefundToGateway
Description : This method will be callout will the LWC bln_RefundScreen
Output Parameter : String
CreatedDate: 28-03-2024
CreatedBy : Ayush Kumar Singh (PwC India)
Change log :
****************************************/
    @AuraEnabled
    @Future(callout=true)
    public static void pushRefundToGateway(String  paymentRecordId){
        String returnString = '';
        HttpResponse response = new HttpResponse();
        Map<String,String> headerMap = new Map<String,String>();
        String endPoint='';
        String payload = '';
        BLN_APICalloutMapper__mdt apiCalloutmapperRec = BLN_APICalloutMapper__mdt.getInstance(System.Label.BLN_RefundAPICallName);
        try{
            endPoint =  apiCalloutmapperRec.BLN_NamedCredential__c + apiCalloutmapperRec.BLN_CalloutURL__c;
            List<BLN_Payment__c> paymentRecCreated  = [SELECT Id, Name, BLN_PaymentAmountTaken__c, BLN_RefundType__c, BLN_Currency__c, BLN_OriginalPayment__c,BLN_OriginalPayment__r.BLN_PmtGatewayProvider__c, BLN_CR__c, BLN_PmtGatewayProvider__c,BLN_OriginalPayment__r.BLN_PmtReferenceId__c,BLN_OriginalPayment__r.BLN_LinkData__c FROM BLN_Payment__c WHERE Id=:paymentRecordId];
            if(!paymentRecCreated.isEmpty()){
                payload = makePayload(paymentRecCreated[0], apiCalloutmapperRec);
            }
            headerMap.put(System.label.BLN_AuthorizationBearer.split(System.label.BLN_Comma)[0],System.label.BLN_AuthorizationBearer.split(System.label.BLN_Comma)[1]+' '+BLN_HTTPCallOutAccessToken.getAccessToken().accessToken);
            for(String str : apiCalloutmapperRec.BLN_Headers__c.split(System.label.BLN_Semicolon)){
                headerMap.put(str.split(System.label.BLN_Comma)[0],str.split(System.label.BLN_Comma)[1]);
            }
            response = BLN_HttpCalloutUtility.makeCallout(System.label.BLN_TargetSystemMulesoft, endPoint, System.label.BLN_HttpMethodPost, headerMap, '', payload);
            if(response.getStatusCode() == 200){
                BLN_IntegrationLoggerFuture.processIntegrationLogger(JSON.serializePretty(response));
            }
        }
        catch(exception e){
            // Handling the exceptions and log an error message
            BLN_ExceptionLogger.captureException(e);
        }
    }
    
    /*****************************************
MethodName : makePayload
Description : This method is used to make the payload
Output Parameter : BLN_Payment__c, BLN_APICalloutMapper__mdt
CreatedDate: 28-03-2024
CreatedBy : Ayush Kumar Singh (PwC India)
Change log :
****************************************/
    private static String makePayload(BLN_Payment__c paymentRecord, BLN_APICalloutMapper__mdt apiCalloutmapperRec){
        
        Datetime dt = System.now();
        String isoString = dt.format('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'');
        String timezoneOffset = UserInfo.getTimezone().getDisplayName();
        String offsetHours = timezoneOffset.substring(timezoneOffset.indexOf('GMT') + 3, timezoneOffset.indexOf('GMT') + 6);
        String offsetMinutes = timezoneOffset.substring(timezoneOffset.indexOf('GMT') + 7, timezoneOffset.indexOf('GMT') + 9);
        String formattedString = dt.format('yyyy-MM-dd\'T\'HH:mm:ss.SSS') + offsetHours + ':' + offsetMinutes;

        PayloadWrapper payload = new PayloadWrapper();
        payload.entityName = apiCalloutmapperRec.BLN_EntityName__c;
        payload.entityID = paymentRecord.Id;
        payload.eventType = apiCalloutmapperRec.BLN_EventType__c;
        payload.sourceSystem = apiCalloutmapperRec.BLN_SourceSystem__c;
        payload.timestamp = formattedString;//'2024-07-10T13:08:12.000353+00:00';
        payload.initialisedSystem = apiCalloutmapperRec.BLN_SourceSystem__c;
        
        Cls_data data = new Cls_data();
        Cls_current current = new Cls_current();
        Cls_refunds refunds = new Cls_refunds();
        if(paymentRecord.BLN_OriginalPayment__c!=null){
          //  refunds.paymentId = paymentRecord.BLN_OriginalPayment__r.BLN_CR__c!=null ? paymentRecord.BLN_OriginalPayment__r.BLN_CR__c : '';
            refunds.provider = paymentRecord.BLN_OriginalPayment__r.BLN_PmtGatewayProvider__c!=null ?paymentRecord.BLN_OriginalPayment__r.BLN_PmtGatewayProvider__c : '';
            if(paymentRecord.BLN_OriginalPayment__r.BLN_PmtGatewayProvider__c ==System.Label.BLN_Worldpay){
                refunds.paymentId=paymentRecord.BLN_OriginalPayment__r.BLN_LinkData__c;
            }
            
            
            else if(paymentRecord.BLN_OriginalPayment__r.BLN_PmtGatewayProvider__c == System.Label.BLN_BarclaysGatewayProvider){
                refunds.paymentId=paymentRecord.BLN_OriginalPayment__r.BLN_PmtReferenceId__c;
            }
        }
        else{
            refunds.paymentId = '';
            refunds.provider = '';
        }
        refunds.amount = paymentRecord.BLN_PaymentAmountTaken__c!=null ? String.valueOf(paymentRecord.BLN_PaymentAmountTaken__c.intValue()): '';
        refunds.refundType = paymentRecord.BLN_RefundType__c!=null ? paymentRecord.BLN_RefundType__c : '';
        refunds.currency2 = paymentRecord.BLN_Currency__c!=null ?paymentRecord.BLN_Currency__c : '';
        refunds.internalId = paymentRecord.Id;
        current.refunds = refunds;
        
        
        
        data.current = current;
        
        payload.data = data;
        return JSON.serializePretty(payload).replaceAll('currency2', 'currency');
    }
    public class PayloadWrapper{
        @AuraEnabled
        public String entityName{get;set;}
        @AuraEnabled
        public String entityID{get;set;}
        @AuraEnabled
        public String eventType{get;set;}
        @AuraEnabled
        public String sourceSystem{get;set;}
        @AuraEnabled
        public String timestamp{get;set;}
        @AuraEnabled
        public String initialisedSystem{get;set;}
        @AuraEnabled
        public Cls_data data{get;set;}
    }
    
    public class Cls_data {
        @AuraEnabled
        public Cls_current current{get;set;}
    }
    public class Cls_current {
        @AuraEnabled
        public Cls_refunds refunds{get;set;}
    }
    public class Cls_refunds {
        @AuraEnabled
        public String paymentId{get;set;}
        //@AuraEnabled
        //public String environment{get;set;}
        //@AuraEnabled
        //public String saleIdentification{get;set;}
        //@AuraEnabled
        //public String merchantId{get;set;}
        @AuraEnabled
        public String amount{get;set;}
        @AuraEnabled
        public String refundType{get;set;}
        @AuraEnabled
        public String currency2{get;set;}	// it needs to be replaced by "currency" when passed as payload
        @AuraEnabled
        public String internalId{get;set;}
        @AuraEnabled
        public String provider{get;set;}
    }
}