force-app/main/default/objects/BLN_APICalloutMapper__mdt/BLN_APICalloutMapper__mdt.object-meta.xml
<CustomObject>
    <description>FOUK-6359, API callout header and URL mapping master</description>
    <label>API Callout Mapper</label>
    <pluralLabel>API Callout Mappers</pluralLabel>
</CustomObject>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_APITimeout__c.field-meta.xml
<CustomField>
    <fullName>BLN_APITimeout__c</fullName>
    <description>Timeout value Milliseconds</description>
    <inlineHelpText>Milliseconds</inlineHelpText>
    <label>API Timeout</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_CalloutURL__c.field-meta.xml
<CustomField>
    <fullName>BLN_CalloutURL__c</fullName>
    <description>FOUK-6359, Callout URL for Refund</description>
    <label>Callout URL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_DestinationSystem__c.field-meta.xml
<CustomField>
    <fullName>BLN_DestinationSystem__c</fullName>
    <description>FOUK-6359, Destination System for Refund Integration</description>
    <label>Destination System</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_Headers__c.field-meta.xml
<CustomField>
    <fullName>BLN_Headers__c</fullName>
    <description>FOUK-6359, Headers for Refund Integration</description>
    <label>Headers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_Method__c.field-meta.xml
<CustomField>
    <fullName>BLN_Method__c</fullName>
    <description>Method for the Api callout</description>
    <label>Method</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_NamedCredential__c.field-meta.xml
<CustomField>
    <fullName>BLN_NamedCredential__c</fullName>
    <description>Named Credential for Callout Api</description>
    <label>Named Credential</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_CalloutSettings__c/BLN_CalloutSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Callout Settings</label>
</CustomObject>

force-app/main/default/classes/BLN_HTTPCallOutAccessToken.cls
/** @description : This Apex is called from Service Appointment and call OKTA to get Access Token of MuleSoft
*   @Story : FOUK-1175
*   @author: Shailendra Tiwari (PwC)
*   @CreatedDate: 01/12/2023
*/
public with sharing class BLN_HTTPCallOutAccessToken {
    /*  *@description: This method is used to get access token.
        *@return : Wrapper class data
    */
    public static WrapperAccessToken getAccessToken() {
        Integer sec;
        DateTime now;        
        Map<String,String> headerMap = new Map<String,String>();
        BLN_CalloutSettings__c calloutOptions = BLN_CalloutSettings__c.getInstance();

        Cache.OrgPartition orgPart = Cache.Org.getPartition('local.OKTAIdP');
        DateTime expiresIn = (DateTime) orgPart.get('OKTATokenExpirationDateTime');
        String oktaToken = (String) orgPart.get('OKTAAccessToken');

        WrapperAccessToken token;
        if (expiresIn != null && oktaToken != null && expiresIn > Datetime.now().addSeconds(60)) {
            token = new WrapperAccessToken();
            token.accessToken = oktaToken;
        } else {
        
        BLN_APICalloutMapper__mdt calloutData = BLN_APICalloutMapper__mdt.getInstance('BLN_OktaTokenApi');
        
        if(String.isNotBlank(calloutData.BLN_Headers__c)){
            for(String header : calloutData.BLN_Headers__c.split(System.label.BLN_Semicolon)){
                if(header.contains(System.label.BLN_Comma)){
                    headerMap.put(header.split(System.label.BLN_Comma)[0],header.split(System.label.BLN_Comma)[1]);
                }
            }
        }
        String endPoint = calloutData.BLN_NamedCredential__c + (String.isNotBlank(calloutData.BLN_CalloutURL__c) ? calloutData.BLN_CalloutURL__c : ''); 
        Boolean createIntgrLogger = false;
        
        // Send the request and get the response
        HttpResponse tokenResponse = BLN_HttpCalloutUtility.makeCallout(createIntgrLogger,calloutData.BLN_DestinationSystem__c,endPoint,calloutData.BLN_Method__c,headerMap,'','',Integer.valueOf(calloutData.BLN_APITimeout__c));
        Map<String, Object> results = (Map<String, Object>)JSON.deserializeUntyped(tokenResponse.getBody());
        
        if((tokenResponse.getstatusCode() == 200 || tokenResponse.getstatusCode() == 201) && results.containsKey('body') != null){
                token = new WrapperAccessToken();
            token.accessToken = results.containsKey('access_token') ? (String)results.get('access_token') : '';
            token.expiresIn = results.containsKey('expires_in') ? (Integer)results.get('expires_in') : 0;
            sec = token.expiresIn == 0 ? 0 : token.expiresIn - 60;            
            now = DateTime.now();
            token.expireTime = now.addSeconds(sec);
        
                if(String.isNotBlank(token.accessToken)){
                    orgPart.put('OKTAAccessToken', token.accessToken);
                    orgPart.put('OKTATokenExpirationDateTime', token.expireTime);
                }
            }
        }
        
        return token;
    }
    
    public class WrapperAccessToken{
        public String accessToken;
        public Integer expiresIn;
        public Datetime expireTime;
    }
}