force-app/main/default/objects/BLN_APICalloutMapper__mdt/BLN_APICalloutMapper__mdt.object-meta.xml
<CustomObject>
    <description>FOUK-6359, API callout header and URL mapping master</description>
    <label>API Callout Mapper</label>
    <pluralLabel>API Callout Mappers</pluralLabel>
</CustomObject>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_CalloutURL__c.field-meta.xml
<CustomField>
    <fullName>BLN_CalloutURL__c</fullName>
    <description>FOUK-6359, Callout URL for Refund</description>
    <label>Callout URL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_DestinationSystem__c.field-meta.xml
<CustomField>
    <fullName>BLN_DestinationSystem__c</fullName>
    <description>FOUK-6359, Destination System for Refund Integration</description>
    <label>Destination System</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_Method__c.field-meta.xml
<CustomField>
    <fullName>BLN_Method__c</fullName>
    <description>Method for the Api callout</description>
    <label>Method</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_NamedCredential__c.field-meta.xml
<CustomField>
    <fullName>BLN_NamedCredential__c</fullName>
    <description>Named Credential for Callout Api</description>
    <label>Named Credential</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/BLN_ExternalFileLinks__c.object-meta.xml
<CustomObject>
    <description>FOUK-5770 This custom object will hold records to keep mapping between the ParentId eg WOLIId and AWS DocumentId</description>
    <label>External File Links</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>ExtFileLink</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External File Links</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_Category__c.field-meta.xml
<CustomField>
    <fullName>BLN_Category__c</fullName>
    <description>Categorization of the File Uploaded</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Inspection</fullName>
            </value>
            <value>
                <fullName>Additional Inspection</fullName>
            </value>
            <value>
                <fullName>Post-Inspection</fullName>
            </value>
            <value>
                <fullName>Recalibration</fullName>
            </value>
            <value>
                <fullName>Failed Appointment Photos</fullName>
            </value>
            <value>
                <fullName>Corrective Action Report</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_DocumentId__c.field-meta.xml
<CustomField>
    <fullName>BLN_DocumentId__c</fullName>
    <description>FOUK-7055 This field is to hold the AWS Id returned by Mule-AWS</description>
    <label>Document Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_FileCreationDate__c.field-meta.xml
<CustomField>
    <fullName>BLN_FileCreationDate__c</fullName>
    <description>FOUK-7055 This field is to hold DateTime of when document Id was created</description>
    <label>File Creation Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_FileName__c.field-meta.xml
<CustomField>
    <fullName>BLN_FileName__c</fullName>
    <description>FOUK-7055 This field is to hold original file name</description>
    <label>File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_FileSize__c.field-meta.xml
<CustomField>
    <fullName>BLN_FileSize__c</fullName>
    <description>FOUK-7055 File size of the file in bytes</description>
    <label>File Size</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_FileType__c.field-meta.xml
<CustomField>
    <fullName>BLN_FileType__c</fullName>
    <description>FOUK-7055 This field is to hold File Type</description>
    <label>File Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JPG</fullName>
            </value>
            <value>
                <fullName>PNG</fullName>
            </value>
            <value>
                <fullName>PDF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_ParentId__c.field-meta.xml
<CustomField>
    <fullName>BLN_ParentId__c</fullName>
    <description>FOUK-7055 This field is to hold Parent Id</description>
    <externalId>true</externalId>
    <label>Parent Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_ParentObjectName__c.field-meta.xml
<CustomField>
    <fullName>BLN_ParentObjectName__c</fullName>
    <description>FOUK-7055 This field is to hold name of Parent Object</description>
    <label>Parent Object Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_S3BucketLink__c.field-meta.xml
<CustomField>
    <fullName>BLN_S3BucketLink__c</fullName>
    <description>FOUK-7055 This field is to hold Amazon AWS S3 Bucket Link</description>
    <label>S3 Bucket Link</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_ShowToCustomer__c.field-meta.xml
<CustomField>
    <fullName>BLN_ShowToCustomer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>FOUK-7055 This field is to confirm if corresponding file entry needs to be displayed to customer on portal or not</description>
    <label>Show To Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BLN_FileCategoryConfig__mdt/BLN_FileCategoryConfig__mdt.object-meta.xml
<CustomObject>
    <description>FOUK-9422, FOUK-7055 
Metadata created for storing configuration of File category</description>
    <label>File Category Config</label>
    <pluralLabel>File Category Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/BLN_FileCategoryConfig__mdt/fields/BLN_CategoryType__c.field-meta.xml
<CustomField>
    <fullName>BLN_CategoryType__c</fullName>
    <description>FOUK-9422, FOUK-7055 - created for storing configuration of File category</description>
    <label>Category Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Inspection</fullName>
                <default>true</default>
                <label>Pre-Inspection</label>
            </value>
            <value>
                <fullName>Additional Inspection</fullName>
            </value>
            <value>
                <fullName>Post-Inspection</fullName>
            </value>
            <value>
                <fullName>Recalibration</fullName>
            </value>
            <value>
                <fullName>Failed Appointment Photos</fullName>
            </value>
            <value>
                <fullName>Corrective Action Report</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_FileCategoryConfig__mdt/fields/BLN_ShowToCustomer__c.field-meta.xml
<CustomField>
    <fullName>BLN_ShowToCustomer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>FOUK-9422, FOUK-7055  created for storing the value to show to customer</description>
    <label>Show to customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BLN_DisplayDocStoreRecordsController.cls
/*****************************************
ClassName : BLN_DisplayDocStoreRecordsController
Description : FOUK-7055
CreatedDate: 25-06-2024
CreatedBy : PwC-India
****************************************/
/*  *@description:This class is used to open and download files uploaded on the AWS storage */

public without sharing class BLN_DisplayDocStoreRecordsController {
    @AuraEnabled (cacheable=true)
    public static WrapperList getFileDetails(Id parentId, boolean isCommunity){
        WrapperList wrap = new WrapperList();
        try {

            Id recordId  = parentId;
            String sObjName = recordId.getSObjectType().getDescribe().getName();
            wrap.objName = sObjName;
            List<BLN_ExternalFileLinks__c> extFileLinkList = [SELECT Id, BLN_FileName__c, BLN_FileType__c, BLN_FileSize__c,BLN_FileCreationDate__c,BLN_ParentId__c,BLN_ParentObjectName__c,BLN_S3BucketLink__c,BLN_DocumentId__c,BLN_Category__c FROM BLN_ExternalFileLinks__c WHERE BLN_ParentId__c =: parentId AND BLN_ParentObjectName__c =: sObjName WITH SECURITY_ENFORCED ];
             
            SObjectAccessDecision decisionExtFileLinkList = Security.stripInaccessible(
            AccessType.READABLE, 
            extFileLinkList
            );

            Map<String,boolean> showToCustomerMap = new Map<String,boolean> ();
            List<BLN_FileCategoryConfig__mdt> categoryConfigMetaData = BLN_FileCategoryConfig__mdt.getall().values();
            for(BLN_FileCategoryConfig__mdt fileCategory: categoryConfigMetaData){
                if(fileCategory.BLN_CategoryType__c!=null){
                showToCustomerMap.put(fileCategory.BLN_CategoryType__c,fileCategory.BLN_ShowToCustomer__c);
               }
            }
            
            List<BLN_ExternalFileLinks__c> extFileLinkForPortal = new List<BLN_ExternalFileLinks__c>();
            for(BLN_ExternalFileLinks__c extFile: extFileLinkList){
              
               if(showToCustomerMap.containsKey(extFile.BLN_Category__c) && showToCustomerMap.get(extFile.BLN_Category__c)){
                extFileLinkForPortal.add(extFile);
               }
            }
            if(isCommunity){
                wrap.fileList = extFileLinkForPortal ;
            }
            else{
                wrap.fileList = extFileLinkList;
            }
            wrap.fileList = [SELECT Id, BLN_FileName__c, BLN_FileType__c, BLN_FileSize__c,BLN_FileCreationDate__c,BLN_ParentId__c,BLN_ParentObjectName__c,BLN_S3BucketLink__c,BLN_DocumentId__c,BLN_Category__c FROM BLN_ExternalFileLinks__c WHERE BLN_ParentId__c =: parentId AND BLN_ParentObjectName__c =: sObjName ];
            SObjectAccessDecision decision = Security.stripInaccessible(
                                            AccessType.READABLE,
                                            wrap.fileList);
            return wrap;

            
        } catch (Exception e) {
          //  throw new AuraHandledException(e.getMessage());
            BLN_ExceptionLogger.captureException(e);
            String errorMsg = string.valueof(e);
            wrap.errorMessage = errorMsg;
            return  wrap;
        }
    }

    @AuraEnabled
    public static String fetchDocumentDetails(string docId){
        Integer timeout = 30000;
        String endPoint;
        HttpResponse response = new HttpResponse();
        String getResponseStr ;
        Map<String,String> headerMap = new Map<String,String>();
       try{
        BLN_APICalloutMapper__mdt calloutDetails = BLN_APICalloutMapper__mdt.getInstance(System.label.BLN_FetchDocumentLabel);    
        headerMap.put(System.label.BLN_AuthorizationBearer.split(System.label.BLN_Comma)[0],System.label.BLN_AuthorizationBearer.split(System.label.BLN_Comma)[1]+' '+BLN_HTTPCallOutAccessToken.getAccessToken()?.accessToken);
 
        endPoint = calloutDetails.BLN_NamedCredential__c + calloutDetails.BLN_CalloutURL__c + '/'+ docId;
        
        response = BLN_HttpCalloutUtility.makeCallout(calloutDetails.BLN_DestinationSystem__c, endPoint, calloutDetails.BLN_Method__c, headerMap,'','',timeout);
        
        getResponseStr = response.getBody();
        return getResponseStr;
       }catch (Exception e) {
        BLN_ExceptionLogger.captureException(e);
       
        return string.valueof(e);
       }     

    }

    public class WrapperList{
        @AuraEnabled public List<BLN_ExternalFileLinks__c> fileList = new List<BLN_ExternalFileLinks__c>();
        @AuraEnabled public String objName;
        @AuraEnabled public String errorMessage; 
    }
}