force-app/main/default/objects/BLN_APICalloutMapper__mdt/BLN_APICalloutMapper__mdt.object-meta.xml
<CustomObject>
    <description>FOUK-6359, API callout header and URL mapping master</description>
    <label>API Callout Mapper</label>
    <pluralLabel>API Callout Mappers</pluralLabel>
</CustomObject>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_CalloutURL__c.field-meta.xml
<CustomField>
    <fullName>BLN_CalloutURL__c</fullName>
    <description>FOUK-6359, Callout URL for Refund</description>
    <label>Callout URL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_DestinationSystem__c.field-meta.xml
<CustomField>
    <fullName>BLN_DestinationSystem__c</fullName>
    <description>FOUK-6359, Destination System for Refund Integration</description>
    <label>Destination System</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_Headers__c.field-meta.xml
<CustomField>
    <fullName>BLN_Headers__c</fullName>
    <description>FOUK-6359, Headers for Refund Integration</description>
    <label>Headers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_Method__c.field-meta.xml
<CustomField>
    <fullName>BLN_Method__c</fullName>
    <description>Method for the Api callout</description>
    <label>Method</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_NamedCredential__c.field-meta.xml
<CustomField>
    <fullName>BLN_NamedCredential__c</fullName>
    <description>Named Credential for Callout Api</description>
    <label>Named Credential</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_SourceSystem__c.field-meta.xml
<CustomField>
    <fullName>BLN_SourceSystem__c</fullName>
    <description>FOUK-6359, Source System for Refund Integration</description>
    <label>Source System</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BLN_InvoiceCalloutController.cls
public with sharing class BLN_InvoiceCalloutController {

    @InvocableMethod(label='syncCloseCompletedCase' description='Completed/Close data sync' category='Case')
    public static void syncCloseCompletedCase(List<String> caseId) {

        if(caseId.size() > 0 && caseId[0] != null && caseId[0] != 'undefined') {
            String caseIdP = caseId[0].split('~')[0];
            String eventTypeP = caseId[0].split('~')[1];
            BLN_APICalloutMapper__mdt calloutDetails = BLN_APICalloutMapper__mdt.getInstance(System.label.BLN_InvoiceCalloutName);
            Map<String,String> headerMap = new Map<String,String>();
            Integer timeout = 60000;
            headerMap.put(System.label.BLN_AuthorizationBearer.split(System.label.BLN_Comma)[0],System.label.BLN_AuthorizationBearer.split(System.label.BLN_Comma)[1]+' '+BLN_HTTPCallOutAccessToken.getAccessToken()?.accessToken);
            String hCode = EncodingUtil.convertToHex(Crypto.generateAesKey(128));
            String correlID = hCode.substring(0,4)+'-'+hCode.substring(0,4)+'-'+hCode.substring(5,8)+'-'+hCode.substring(9,12)+'-'+hCode.substring(12,16)+'-'+hCode.substring(16,20);
            headerMap.put(System.label.BLN_XCORRELATIONID, correlID);

            for(String str : calloutDetails.BLN_Headers__c.split(System.label.BLN_Semicolon)){
                headerMap.put(str.split(System.label.BLN_Comma)[0],str.split(System.label.BLN_Comma)[1]);
            }
            
            String requestBody = BLN_InvoiceCalloutController.makeRequestBody('BULK_JOB', caseIdP, eventTypeP, calloutDetails.BLN_SourceSystem__c, System.Now());
            HttpResponse response = BLN_HttpCalloutUtility.makeCallout(calloutDetails.BLN_DestinationSystem__c,
                                    calloutDetails.BLN_NamedCredential__c + calloutDetails.BLN_CalloutURL__c, 
                                    calloutDetails.BLN_Method__c, headerMap, caseIdP, requestBody, timeout);
            
            String returnPayloadAsString = response.getStatusCode() == 201 ? response.getBody() : System.label.BLN_CalloutFailed;
        }
    }

    private static String makeRequestBody(String entityName, String caseId, String eventType, String sourceSystem, DateTime timestamp) {

        RequestBODYWrapper requestBody = new RequestBODYWrapper();
        requestBody.entityName = entityName;
        requestBody.entityID = caseId;
        requestBody.eventType = eventType;
        requestBody.sourceSystem = sourceSystem;
        requestBody.timestamp = timestamp;
        requestBody.initialisedSystem = SourceSystem;

        CurrentWrapper currentWrp = new CurrentWrapper();
        currentWrp.caseId = caseId;
        DataWrapper dataWrapper = new DataWrapper();
        dataWrapper.current = currentWrp;
        requestBody.data = dataWrapper;
        return JSON.serialize(requestBody, true);
    }

    public class RequestBODYWrapper {
        public String entityName;
        public String entityID;
        public String eventType;
        public String sourceSystem;
        public dateTime timestamp;
        public String initialisedSystem;
        public DataWrapper data;
    }

    public class DataWrapper {
        public CurrentWrapper current;
    }

    public class CurrentWrapper {
        public String caseId;
    }
}