force-app/main/default/objects/BLN_APICalloutMapper__mdt/BLN_APICalloutMapper__mdt.object-meta.xml
<CustomObject>
    <description>FOUK-6359, API callout header and URL mapping master</description>
    <label>API Callout Mapper</label>
    <pluralLabel>API Callout Mappers</pluralLabel>
</CustomObject>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_APITimeout__c.field-meta.xml
<CustomField>
    <fullName>BLN_APITimeout__c</fullName>
    <description>Timeout value Milliseconds</description>
    <inlineHelpText>Milliseconds</inlineHelpText>
    <label>API Timeout</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_CalloutURL__c.field-meta.xml
<CustomField>
    <fullName>BLN_CalloutURL__c</fullName>
    <description>FOUK-6359, Callout URL for Refund</description>
    <label>Callout URL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_DestinationSystem__c.field-meta.xml
<CustomField>
    <fullName>BLN_DestinationSystem__c</fullName>
    <description>FOUK-6359, Destination System for Refund Integration</description>
    <label>Destination System</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_Headers__c.field-meta.xml
<CustomField>
    <fullName>BLN_Headers__c</fullName>
    <description>FOUK-6359, Headers for Refund Integration</description>
    <label>Headers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_Method__c.field-meta.xml
<CustomField>
    <fullName>BLN_Method__c</fullName>
    <description>Method for the Api callout</description>
    <label>Method</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_NamedCredential__c.field-meta.xml
<CustomField>
    <fullName>BLN_NamedCredential__c</fullName>
    <description>Named Credential for Callout Api</description>
    <label>Named Credential</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Vehicle__c/BLN_Vehicle__c.object-meta.xml
<CustomObject>
    <description>FOUK-495 This object is created for storing the Vehicles.</description>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{00000000}</displayFormat>
        <label>Vehicle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_Vehicle__c/fields/BLN_BodyType__c.field-meta.xml
<CustomField>
    <fullName>BLN_BodyType__c</fullName>
    <description>FOUK-3425 This field is used to store body type of vehicle.</description>
    <label>Body Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Vehicle__c/fields/BLN_MakeOfVehicle__c.field-meta.xml
<CustomField>
    <fullName>BLN_MakeOfVehicle__c</fullName>
    <description>FOUK-116--&gt; This field is created for make of vehicle details.</description>
    <label>Make Of Vehicle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Vehicle__c/fields/BLN_MDMID__c.field-meta.xml
<CustomField>
    <fullName>BLN_MDMID__c</fullName>
    <description>FOUK-1819 This field is used to store MDM Id for vehicle object.</description>
    <externalId>true</externalId>
    <label>MDM ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Vehicle__c/fields/BLN_ModelOfVehicle__c.field-meta.xml
<CustomField>
    <fullName>BLN_ModelOfVehicle__c</fullName>
    <description>FOUK-116--&gt; This field is created for model of vehicle .</description>
    <label>Model Of Vehicle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Vehicle__c/fields/BLN_MVRIS__c.field-meta.xml
<CustomField>
    <fullName>BLN_MVRIS__c</fullName>
    <description>FOUK-495 This field is used to store MVRIS of the vehicle</description>
    <label>MVRIS</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Vehicle__c/fields/BLN_VIN__c.field-meta.xml
<CustomField>
    <fullName>BLN_VIN__c</fullName>
    <description>FOUK-495 This field is used to store vehicle identification number</description>
    <label>VIN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Vehicle__c/fields/BLN_Year__c.field-meta.xml
<CustomField>
    <fullName>BLN_Year__c</fullName>
    <description>FOUK-495 This field is used to store year the vehicle was registered</description>
    <label>Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BLN_VehicleDamage__c/BLN_VehicleDamage__c.object-meta.xml
<CustomObject>
    <description>FOUK-539 This is Vehicle Damage object</description>
    <label>Vehicle Damage</label>
    <nameField>
        <displayFormat>VD-{00000000}</displayFormat>
        <label>Vehicle Damage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Damages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_VehicleDamage__c/fields/BLN_AssessmentStatus__c.field-meta.xml
<CustomField>
    <fullName>BLN_AssessmentStatus__c</fullName>
    <description>FOUK-3956: Ths field is created to store Assessment status value in Vehicle damage record.</description>
    <label>Assessment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Pending Image upload</fullName>
            </value>
            <value>
                <fullName>Sent for Tech review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_VehicleDamage__c/fields/BLN_BOMID__c.field-meta.xml
<CustomField>
    <fullName>BLN_BOMID__c</fullName>
    <description>FOUK-3956: This field is created to store BOM ID value in vehicle damage record.</description>
    <label>BOM ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_VehicleDamage__c/fields/BLN_Case__c.field-meta.xml
<CustomField>
    <fullName>BLN_Case__c</fullName>
    <description>FOUK-436 This field is used to store case details</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Vehicle Damages</relationshipLabel>
    <relationshipName>Vehicle_Damages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BLN_VehicleDamage__c/fields/BLN_GlassHoleType__c.field-meta.xml
<CustomField>
    <fullName>BLN_GlassHoleType__c</fullName>
    <description>FOUK-3956: This field is created to store Glass/Hole Type value in Vehicle Damage record.</description>
    <label>Glass/Hole Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BK</fullName>
                <label>Back Window</label>
            </value>
            <value>
                <fullName>DR</fullName>
                <label>Door</label>
            </value>
            <value>
                <fullName>PT</fullName>
                <label>Partition</label>
            </value>
            <value>
                <fullName>RF</fullName>
                <label>Roof</label>
            </value>
            <value>
                <fullName>QT</fullName>
                <label>Quarter</label>
            </value>
            <value>
                <fullName>SI</fullName>
                <label>Side</label>
            </value>
            <value>
                <fullName>VN</fullName>
                <label>Vent</label>
            </value>
            <value>
                <fullName>WS</fullName>
                <label>Windshield</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_VehicleDamage__c/fields/BLN_OutcomeType__c.field-meta.xml
<CustomField>
    <fullName>BLN_OutcomeType__c</fullName>
    <description>FOUK-3956: This field is created to store outcome type in Vehicla damage record.</description>
    <label>Outcome Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Repair</fullName>
            </value>
            <value>
                <fullName>Replacement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_VehicleDamage__c/fields/BLN_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>BLN_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>FOUK-539 This field is used to store the associated vehicle.</description>
    <label>Vehicle</label>
    <referenceTo>BLN_Vehicle__c</referenceTo>
    <relationshipLabel>Vehicle Damages</relationshipLabel>
    <relationshipName>Vehicle_Damages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BLN_VehicleDamage__c/fields/BLN_WorkType__c.field-meta.xml
<CustomField>
    <fullName>BLN_WorkType__c</fullName>
    <description>FOUK-527 This field is used to store the results of damage assessment.</description>
    <label>Work Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Replacement &amp; Recalibration</fullName>
            </value>
            <value>
                <fullName>Replacement</fullName>
            </value>
            <value>
                <fullName>Recalibration</fullName>
            </value>
            <value>
                <fullName>Side &amp; Rear</fullName>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
            <value>
                <fullName>No Work Required</fullName>
            </value>
            <value>
                <fullName>Sunroof</fullName>
                <isActive>false</isActive>
                <label>Sunroof</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BLN_ConnectWithGPS.cls
/*****************************************
ClassName : BLN_ConnectWithGPS
Description : FOUK-2164 This controller class is used to call 'vehicle-schematics' & 'vehicle-bill-of-materials' request GPS API &
Passed the data back to 'BLN_DamageAssessmentFlow'.
CreatedDate: 15-12-2023
CreatedBy : PWC-India
****************************************/
public with sharing class BLN_ConnectWithGPS {
    

    /*@description : getBomId method used to get bomId.
@return : method returns the String .
@param : parameter send Parser */
  public static String getBomId(BLN_ProductParser parser){
    String bomId = '';
    List<String> listBomId = new List<String>(); 
    if(parser.Results.size() > 1){
        for (Integer i = 0; i < parser.Results.size(); i++) {  
            listBomId.add(string.valueof(parser.Results[i].bomId));  
        }
         bomId =  String.join(listBomId, ',');
} else{
    bomId =  string.valueof(parser.Results[0].bomId);
}
   // system.debug('bomId12345678 '+bomId);
   return bomId;
   }
    
    /*@description : receiveBomIdFromGPS method used to get bomId.
@return : method returns the String list.
@param : parameter send transactionId, vehicleHoleId And recordId */
    @invocablemethod
    public static list<List<String>> receiveBomIdFromGPS(list<list<string>> listOfBom) {
        string endPoint = '';
        string bomId = '';
        list<string> tranAndHole = new list<string>();
        if(listOfBom !=null &&  listOfBom.size() > 0 && listOfBom[0]!=null){
            tranAndHole = listOfBom[0];
        }
        
        BLN_ProductParser parser = new BLN_ProductParser();
       // Map<String, Object> requestBody= new Map<String, Object>();
        List<String> returnList = new List<String>();
        Map<String,String> headerMap = new Map<String,String>();
        list<list<string>> newReturn = new list<list<string>>();
        HttpResponse response = new HttpResponse();
        try{
            BLN_APICalloutMapper__mdt calloutDetails = BLN_APICalloutMapper__mdt.getInstance(System.label.BLN_GetPidQuestionsLabel); 

            endPoint=calloutDetails.BLN_NamedCredential__c+calloutDetails.BLN_CalloutURL__c+system.label.BLN_TransactionPath+tranAndHole[0]+system.label.BLN_HoleIdPath+tranAndHole[1];
           // system.debug('receiveBomIdFromGPS EndPoint'+ endPoint);
          // BLN_HTTPCallOutAccessToken.wrapperAccessToken wrapperToken = BLN_HTTPCallOutAccessToken.getAccessToken();
            headerMap.put(System.label.BLN_AuthorizationBearer.split(System.label.BLN_Comma)[0],System.label.BLN_AuthorizationBearer.split(System.label.BLN_Comma)[1]+' '+BLN_HTTPCallOutAccessToken.getAccessToken()?.accessToken);
            for(String str : calloutDetails.BLN_Headers__c.split(System.label.BLN_Semicolon)){
                headerMap.put(str.split(System.label.BLN_Comma)[0],str.split(System.label.BLN_Comma)[1]);
            }
            response = BLN_HttpCalloutUtility.makeCallout(calloutDetails.BLN_DestinationSystem__c,endPoint,calloutDetails.BLN_Method__c, headerMap,Integer.valueOf(calloutDetails.BLN_APITimeout__c));

            //if(response.getStatuscode() == 200){
                parser = BLN_ProductParser.parseGPS(response.getBody());
           // }
            if(parser !=null && parser.vehicleDamage !=null && parser.vehicleDamage.status !=null && parser.vehicleDamage.status == System.label.BLN_ResultLabel){
               /* if(parser.Results[0].bomId != null ){
                    bomId = string.valueof(parser.Results[0].bomId);
                }*/

                //Added Under 11509
                bomId =  getBomId(parser);

            /* List<String> listBomId = new List<String>(); 
                if(parser.Results.size() > 1){
                    for (Integer i = 0; i < parser.Results.size(); i++) {  
                        listBomId.add(string.valueof(parser.Results[i].bomId));  
                    }
                     bomId =  String.join(listBomId, ',');
            } else{
                bomId =  string.valueof(parser.Results[0].bomId);
            }*/

                returnList.add(parser.vehicleDamage.status);
                returnList.add(bomId); 
                newReturn.add(returnList);  

            }else if(parser !=null && parser.vehicleDamage !=null && parser.vehicleDamage.status !=null && parser.vehicleDamage.status == System.label.BLN_QuestionLabel){
                
                returnList.add(parser.vehicleDamage.transactionId);
                returnList.add(parser.vehicleDamage.status);
                returnList.add(parser.Question.question);
                newReturn.add(returnList); 

            } else if(response.getStatuscode() != 200){if (response.getStatuscode() == 0){returnList.add(system.label.BLN_APITimeOutErrorMsg);}else{returnList.add(parser.errors[0].detail);}newReturn.add(returnList); }
           
        }catch(exception e){
            BLN_ExceptionLogger.captureException(e);

        }
        return newReturn;
    }
    /*@description : getAnswerFromGPS method used to get Question or bomId.
@return : method returns the String list.
@param : parameter send ans, transId And recordId */
    @AuraEnabled 
    public static List<String> getAnswerFromGPS(string ans, string transId, string recordId, string glassHoleType){
        BLN_ProductParser parser = new BLN_ProductParser(); 
        HttpResponse response = new HttpResponse();
        List<String> returnList = new List<String>();
        Map<String,String> headerMap = new Map<String,String>();
        string endPoint='';
        string bomId = '';
       // BLN_HTTPCallOutAccessToken.wrapperAccessToken wrapperToken = BLN_HTTPCallOutAccessToken.getAccessToken();
        try{      
            BLN_APICalloutMapper__mdt calloutDetails = BLN_APICalloutMapper__mdt.getInstance(System.label.BLN_GetPidQuestionsLabel); 
              
            endPoint=calloutDetails.BLN_NamedCredential__c+calloutDetails.BLN_CalloutURL__c+system.label.BLN_TransactionPath+transId+system.label.BLN_AnswerPath+ans;
           // system.debug('getAnswerFromGPS EndPoint'+ endPoint);
            headerMap.put(System.label.BLN_AuthorizationBearer.split(System.label.BLN_Comma)[0],System.label.BLN_AuthorizationBearer.split(System.label.BLN_Comma)[1]+' '+BLN_HTTPCallOutAccessToken.getAccessToken()?.accessToken);
            for(String str : calloutDetails.BLN_Headers__c.split(System.label.BLN_Semicolon)){
                headerMap.put(str.split(System.label.BLN_Comma)[0],str.split(System.label.BLN_Comma)[1]);
            }
            response = BLN_HttpCalloutUtility.makeCallout(calloutDetails.BLN_DestinationSystem__c,endPoint,calloutDetails.BLN_Method__c, headerMap,Integer.valueOf(calloutDetails.BLN_APITimeout__c));
            parser = BLN_ProductParser.parseGPS(response.getBody());
            if(response.getStatusCode()== 200){
               
                if(parser !=null && parser.vehicleDamage !=null && parser.vehicleDamage.status !=null) {       
                returnList.add(parser.VehicleDamage.status);
            }
            }else if(response.getStatuscode() != 200){if (response.getStatuscode() == 0){ returnList.add(system.label.BLN_APITimeOutErrorMsg);}else{returnList.add(parser.errors[0].detail);}}
            if(parser !=null && parser.vehicleDamage !=null && parser.Results !=null && parser.Results.size() > 0 && parser.Results[0].bomId != null &&parser.vehicleDamage.status !=null && parser.vehicleDamage.status == System.label.BLN_ResultLabel){
                
                bomId = getBomId(parser);

             /*List<String> listBomId = new List<String>(); 
                if(parser.Results.size() > 1){
                    for (Integer i = 0; i < parser.Results.size(); i++) {  
                        listBomId.add(string.valueof(parser.Results[i].bomId));  
                    }
                     bomId =  String.join(listBomId, ',');
            } else{
                bomId =  string.valueof(parser.Results[0].bomId);
            }*/

               // bomId = string.valueof(parser.Results[0].bomId);


                insertVehicleDamage(recordId, bomId, glassHoleType);

            }else if(parser !=null && parser.vehicleDamage !=null && parser.VehicleDamage.transactionId !=null && parser.vehicleDamage.status !=null && parser.vehicleDamage.status == System.label.BLN_QuestionLabel){
                returnList.add(parser.VehicleDamage.transactionId);
                returnList.add(parser.Question.question);

            }

        }catch(exception e){
            BLN_ExceptionLogger.captureException(e);

        }
        return returnList;
    }
    /*@description : getSchematicApi method used to get bomId.
@return : method returns the Map.
@param : recordId */
    @AuraEnabled
    public static String getSchematicApi(String recordId){
        integer count = 0;
        integer row = 0;
        string bodyTypeEncoded = '';
        string modelEncoded = '';
        string makeEncoded = '';
        integer resSize;
        string responseBody = '';
        string endPoint='';
        String displayVal = '';
        String vehicleImage = '';
        String errorDetail = '';
        String wrap = '';
        String vin = '';
        String mvris = '';
        String vehicleId = '';

        BLN_ProductParser parser = new BLN_ProductParser();
        HttpResponse response = new HttpResponse();
        Map<Integer,HoverContent[]> hcMap = new Map<Integer,HoverContent[]>();
        list<BLN_ProductParser.Schematics> shemL = new list<BLN_ProductParser.Schematics>();
        map<integer,list<BLN_ProductParser.Schematics>> scheMap = new map<integer,list<BLN_ProductParser.Schematics>>();
        list<HoverContent> hcList = new list<HoverContent>();
        Map<String,String> headerMap = new Map<String,String>();
        Case objCase=new Case();
        BLN_Vehicle__c objVeh= new  BLN_Vehicle__c();
        try{
            if(!string.isBlank(recordId)){ 
                objCase = [SELECT Id, BLN_Vehicle__c FROM Case WHERE Id =: recordId WITH SECURITY_ENFORCED];
            }
            if(objCase.BLN_Vehicle__c != null){
                objVeh = [SELECT Id, BLN_BodyType__c, BLN_MakeOfVehicle__c, BLN_ModelOfVehicle__c, BLN_Year__c, BLN_VIN__c,BLN_MDMID__c,BLN_MVRIS__c FROM BLN_Vehicle__c WHERE Id =: objCase.BLN_Vehicle__c WITH SECURITY_ENFORCED];
            }
            bodyTypeEncoded = EncodingUtil.urlEncode(objVeh.BLN_BodyType__c, System.label.BLN_UTF);
            makeEncoded = EncodingUtil.urlEncode(objVeh.BLN_MakeOfVehicle__c, System.label.BLN_UTF);
            modelEncoded = EncodingUtil.urlEncode(objVeh.BLN_ModelOfVehicle__c, System.label.BLN_UTF);
           
            if(!String.isBlank(objVeh.BLN_VIN__c)){
            vin = system.label.BLN_Vin+objVeh.BLN_VIN__c;
            }else{
            vin = '';   
            }

            if(!String.isBlank(objVeh.BLN_MVRIS__c)){
            mvris = system.label.BLN_MvrisEnd+objVeh.BLN_MVRIS__c;
            }else{
            mvris = '';
            }

            if(!String.isBlank(objVeh.BLN_MDMID__c)){
            vehicleId = system.label.BLN_VehicleIdEnd+objVeh.BLN_MDMID__c;
            }else{
            vehicleId = '';
            }
        

          //  BLN_HTTPCallOutAccessToken.WrapperAccessToken wrapperToken = BLN_HTTPCallOutAccessToken.getAccessToken();

            BLN_APICalloutMapper__mdt calloutDetails = BLN_APICalloutMapper__mdt.getInstance(System.label.BLN_GetSchematicLable); 


            endPoint=calloutDetails.BLN_NamedCredential__c + calloutDetails.BLN_CalloutURL__c+system.label.BLN_MakePath+ makeEncoded +system.label.BLN_ModelPath+ modelEncoded+system.label.BLN_YearPath+string.valueOf(objVeh.BLN_Year__c)+system.label.BLN_ExternalRef+objCase.Id+vin+mvris+vehicleId+system.label.BLN_BodyTypePath+bodyTypeEncoded; //+system.label.BLN_Vin+objVeh.BLN_VIN__c
           /* if(String.isBlank(objVeh.BLN_VIN__c)){
             endPoint=calloutDetails.BLN_NamedCredential__c + calloutDetails.BLN_CalloutURL__c+system.label.BLN_MakePath+ makeEncoded +system.label.BLN_ModelPath+ modelEncoded+system.label.BLN_YearPath+string.valueOf(objVeh.BLN_Year__c)+system.label.BLN_ExternalRef+objCase.Id+system.label.BLN_BodyTypePath+bodyTypeEncoded; //+system.label.BLN_Vin+objVeh.BLN_VIN__c
             }else{
             endPoint=calloutDetails.BLN_NamedCredential__c + calloutDetails.BLN_CalloutURL__c+system.label.BLN_MakePath+ makeEncoded +system.label.BLN_ModelPath+ modelEncoded+system.label.BLN_YearPath+string.valueOf(objVeh.BLN_Year__c)+system.label.BLN_ExternalRef+objCase.Id+system.label.BLN_Vin+objVeh.BLN_VIN__c+system.label.BLN_BodyTypePath+bodyTypeEncoded;    
             }*/
            headerMap.put(System.label.BLN_AuthorizationBearer.split(System.label.BLN_Comma)[0],System.label.BLN_AuthorizationBearer.split(System.label.BLN_Comma)[1]+' '+BLN_HTTPCallOutAccessToken.getAccessToken()?.accessToken);
            for(String str : calloutDetails.BLN_Headers__c.split(System.label.BLN_Semicolon)){
                headerMap.put(str.split(System.label.BLN_Comma)[0],str.split(System.label.BLN_Comma)[1]);
            }
            
            response = BLN_HttpCalloutUtility.makeCallout(calloutDetails.BLN_DestinationSystem__c,endPoint,calloutDetails.BLN_Method__c, headerMap,Integer.valueOf(calloutDetails.BLN_APITimeout__c));
            If(response !=null) {
                responseBody = response.getBody();
                resSize = responseBody.length();
            }

          

            if(response.getStatuscode() == 200){
                parser = BLN_ProductParser.parseGPS(response.getBody());

                list<list<BLN_ProductParser.Schematics>> sLi = parser.schematics;
                vehicleImage = parser.digitalReferenceName;
             
                hcMap = new Map<Integer,HoverContent[]>();
                If(sLi !=null && sLi.size() > 0){
                for(list<BLN_ProductParser.Schematics> sdl : sLi){
                    scheMap.put(row++,sdl);
                }
               
                for(integer i=0; i<sLi.size();i++){
                    shemL = scheMap.get(i);
                    hcList = new HoverContent[0];
                    for(BLN_ProductParser.Schematics dis : shemL){
                        HoverContent hc = new HoverContent();
                        hc.vhid = dis.vehicleHoleId!=null ? dis.vehicleHoleId : 0000;
                        hc.vType=dis.vehicleHoleTypeCode!=null ? dis.vehicleHoleTypeCode : 	system.label.BLN_TestLabel;
                        hc.displayType=dis.display!=null ? dis.display : system.label.BLN_TestLabel;
                        hc.transactionId=parser.vehicleDamage.transactionId;
                       
                        displayVal=dis.display!=null ? dis.display : system.label.BLN_NullLabel;
                        hcList.add(hc);
                    }
                    hcMap.put(count++,hcList);
                }
            }
                WrapperList wrapListObj = New WrapperList();
                wrapListObj.hoverMap = hcMap;
                wrapListObj.vehicleImage = vehicleImage;

                wrap = JSON.serializePretty(wrapListObj);
            } else

            if(response.getStatuscode() != 200){
                WrapperList wrapListObj = New WrapperList();if(response.getStatuscode() != 0){parser = BLN_ProductParser.parseGPS(response.getBody());}errorDetail = response.getStatuscode() != 0 ? parser.errors[0].detail : '';wrapListObj.errorDetail = response.getStatuscode() == 0 ? system.label.BLN_APITimeOutErrorMsg : errorDetail;wrap = JSON.serializePretty(wrapListObj);
            }
        }catch(exception e){
            BLN_ExceptionLogger.captureException(e);
           
        }

        return wrap;
    }
    /*@description : getPidQuestionGPS method used to get Question or bomId.
@return : method returns the Map.
@param : transactionId, productId, recordId */
    @AuraEnabled
    public static List<String> getPidQuestionGPS(string transactionId, string productId, string recordId, string glassHoleType){        
        string bomId = '';
        HttpResponse response = new HttpResponse();
        BLN_ProductParser parser = new BLN_ProductParser();
        List<String> returnList = new List<String>();
        Map<String,String> headerMap = new Map<String,String>();
        string endPoint='';
      //  BLN_HTTPCallOutAccessToken.wrapperAccessToken wrapperToken = BLN_HTTPCallOutAccessToken.getAccessToken();
        try{
            BLN_APICalloutMapper__mdt calloutDetails = BLN_APICalloutMapper__mdt.getInstance(System.label.BLN_GetPidQuestionsLabel);

            endPoint=calloutDetails.BLN_NamedCredential__c+calloutDetails.BLN_CalloutURL__c+system.label.BLN_TransactionPath+transactionId+system.label.BLN_AtrNameValuePath+productId;
           // system.debug('getPidQuestionGPS EndPoint'+ endPoint);
            headerMap.put(System.label.BLN_AuthorizationBearer.split(System.label.BLN_Comma)[0],System.label.BLN_AuthorizationBearer.split(System.label.BLN_Comma)[1]+' '+BLN_HTTPCallOutAccessToken.getAccessToken()?.accessToken);
            for(String str :  calloutDetails.BLN_Headers__c.split(System.label.BLN_Semicolon)){
                headerMap.put(str.split(System.label.BLN_Comma)[0],str.split(System.label.BLN_Comma)[1]);
            }
            response = BLN_HttpCalloutUtility.makeCallout(calloutDetails.BLN_DestinationSystem__c,endPoint,calloutDetails.BLN_Method__c, headerMap,Integer.valueOf(calloutDetails.BLN_APITimeout__c));
            parser = BLN_ProductParser.parseGPS(response.getBody());
             

              // bomId = string.valueof(parser.Results[0].bomId);
                if(response.getStatusCode() == 200 && parser !=null && parser.vehicleDamage !=null && parser.vehicleDamage.status !=null){
                   returnList.add(parser.vehicleDamage.status);
                 }  

                if(response.getStatusCode() == 200 && parser !=null && parser.vehicleDamage !=null && parser.vehicleDamage.status !=null && parser.vehicleDamage.status == System.label.BLN_ResultLabel){
                   // List<String> listBomId = new List<String>();  
                  
                    bomId = getBomId(parser);
                    /* if(parser.Results.size() > 1){
                     for (Integer i = 0; i < parser.Results.size(); i++) {  
                         listBomId.add(string.valueof(parser.Results[i].bomId));  
                     } 
                     bomId =  String.join(listBomId, ',');
                 } else{
                     bomId =  string.valueof(parser.Results[0].bomId);
                 }*/
                   
                    insertVehicleDamage(recordId, bomId, glassHoleType);
                    
                }

                else if(response.getStatusCode() == 200 && parser !=null && parser.Question !=null && parser.Question.question !=null && parser.vehicleDamage !=null && parser.VehicleDamage.transactionId !=null && parser.vehicleDamage.status !=null && parser.vehicleDamage.status == System.label.BLN_QuestionLabel){
                    returnList.add(parser.VehicleDamage.transactionId);
                    returnList.add(parser.Question.question);
                    
                }                
            

            else if(response.getStatuscode() != 200){if (response.getStatuscode() == 0){ returnList.add(system.label.BLN_APITimeOutErrorMsg);}else{returnList.add(parser.errors[0].detail);}
            }
        }
        catch(exception e){
                       
            BLN_ExceptionLogger.captureException(e);
        }
        return returnList;
        } 
    

    
    /*@description : insertVehicleDamage method used to log.
@return : method returns nothing.
@param : recordId, bomId */ 
    public static void insertVehicleDamage(string recordId, string bomId, string glassHoleType){
        
        try{
            Case caseRecord = new Case();
            BLN_VehicleDamage__c vedhicleDamageRecord = new BLN_VehicleDamage__c();
            if(!string.isBlank(recordId) && Case.SObjectType.getDescribe(SObjectDescribeOptions.DEFERRED).isAccessible() && Schema.SObjectType.Case.fields.BLN_Vehicle__c.isAccessible()) {
                caseRecord = [select id,BLN_Vehicle__r.id from Case where id=:recordId WITH SECURITY_ENFORCED limit 1];
            }
                if(caseRecord != null && caseRecord.id!=null && BLN_VehicleDamage__c.SObjectType.getDescribe(SObjectDescribeOptions.DEFERRED).isCreateable()){
                    vedhicleDamageRecord.BLN_Case__c = caseRecord.id;
                    vedhicleDamageRecord.BLN_Vehicle__c=caseRecord.BLN_Vehicle__r.id;
                    vedhicleDamageRecord.BLN_BOMID__c=bomId;
                    vedhicleDamageRecord.BLN_AssessmentStatus__c = System.label.BLN_CompletedLabel;
                    vedhicleDamageRecord.BLN_GlassHoleType__c = glassHoleType;
                    if(glassHoleType!= null && glassHoleType!= system.label.BLN_WindScreenInitials){
                    vedhicleDamageRecord.BLN_WorkType__c = system.label.BLN_SideAndRear;  
                    }else{
                    vedhicleDamageRecord.BLN_WorkType__c = system.label.BLN_replacement;
                    }
                    vedhicleDamageRecord.BLN_OutcomeType__c = system.label.BLN_replacement;
                    insert vedhicleDamageRecord;
                }
            }
        
        catch(Exception e){          
            BLN_ExceptionLogger.captureException(e);
        }
    }
    
    
    public class HoverContent{
        @AuraEnabled
        public Integer vhid{get;set;}
        @AuraEnabled
        public String vtype{get;set;}
        @AuraEnabled
        public String displayType{get;set;}
        @AuraEnabled
        public String transactionId{get;set;}
       
    }

    public class WrapperList{
       
        @AuraEnabled
        public  map<Integer,HoverContent[]> hoverMap{get;set;}

        @AuraEnabled
        public String vehicleImage{get;set;}

        @AuraEnabled
        public String errorDetail{get;set;}
    }
    
}