force-app/main/default/objects/BLN_APICalloutMapper__mdt/BLN_APICalloutMapper__mdt.object-meta.xml
<CustomObject>
    <description>FOUK-6359, API callout header and URL mapping master</description>
    <label>API Callout Mapper</label>
    <pluralLabel>API Callout Mappers</pluralLabel>
</CustomObject>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_APITimeout__c.field-meta.xml
<CustomField>
    <fullName>BLN_APITimeout__c</fullName>
    <description>Timeout value Milliseconds</description>
    <inlineHelpText>Milliseconds</inlineHelpText>
    <label>API Timeout</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_CalloutURL__c.field-meta.xml
<CustomField>
    <fullName>BLN_CalloutURL__c</fullName>
    <description>FOUK-6359, Callout URL for Refund</description>
    <label>Callout URL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_DestinationSystem__c.field-meta.xml
<CustomField>
    <fullName>BLN_DestinationSystem__c</fullName>
    <description>FOUK-6359, Destination System for Refund Integration</description>
    <label>Destination System</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_Headers__c.field-meta.xml
<CustomField>
    <fullName>BLN_Headers__c</fullName>
    <description>FOUK-6359, Headers for Refund Integration</description>
    <label>Headers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_Method__c.field-meta.xml
<CustomField>
    <fullName>BLN_Method__c</fullName>
    <description>Method for the Api callout</description>
    <label>Method</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_APICalloutMapper__mdt/fields/BLN_NamedCredential__c.field-meta.xml
<CustomField>
    <fullName>BLN_NamedCredential__c</fullName>
    <description>Named Credential for Callout Api</description>
    <label>Named Credential</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/BLN_ExternalFileLinks__c.object-meta.xml
<CustomObject>
    <description>FOUK-5770 This custom object will hold records to keep mapping between the ParentId eg WOLIId and AWS DocumentId</description>
    <label>External File Links</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>ExtFileLink</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External File Links</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_Category__c.field-meta.xml
<CustomField>
    <fullName>BLN_Category__c</fullName>
    <description>Categorization of the File Uploaded</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Inspection</fullName>
            </value>
            <value>
                <fullName>Additional Inspection</fullName>
            </value>
            <value>
                <fullName>Post-Inspection</fullName>
            </value>
            <value>
                <fullName>Recalibration</fullName>
            </value>
            <value>
                <fullName>Failed Appointment Photos</fullName>
            </value>
            <value>
                <fullName>Corrective Action Report</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_DocumentId__c.field-meta.xml
<CustomField>
    <fullName>BLN_DocumentId__c</fullName>
    <description>FOUK-7055 This field is to hold the AWS Id returned by Mule-AWS</description>
    <label>Document Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_FileType__c.field-meta.xml
<CustomField>
    <fullName>BLN_FileType__c</fullName>
    <description>FOUK-7055 This field is to hold File Type</description>
    <label>File Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>JPG</fullName>
            </value>
            <value>
                <fullName>PNG</fullName>
            </value>
            <value>
                <fullName>PDF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_ExternalFileLinks__c/fields/BLN_ParentId__c.field-meta.xml
<CustomField>
    <fullName>BLN_ParentId__c</fullName>
    <description>FOUK-7055 This field is to hold Parent Id</description>
    <externalId>true</externalId>
    <label>Parent Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BLN_SendDocsForPrintBatch.cls
/**@description : This batch class will send Documents for Printing
*  @author: PwC India
*  @Story: FOUK-5770 (Create Bulk Customer Service ReportFOUK-5770 File for Printing and Posting)
*  @CreatedDate: 26/04/2024
*/
@SuppressWarnings('PMD.AvoidGlobalModifier, PMD.ApexSuggestUsingNamedCred')
global class BLN_SendDocsForPrintBatch implements  Database.Batchable<sObject>,  Database.AllowsCallouts, Schedulable {
    public static Integer expiresIn;

    global Database.QueryLocator start(Database.BatchableContext bc){
        String status = System.Label.BLN_ReadyForPrintStatus;
        Datetime last24Hours = System.now().addHours(-24);
        String query = 'SELECT Id, LastModifiedDate, Status, BLN_PrintStatus__c, WorkOrderId, WorkOrder.CaseId, WorkOrder.Case.CaseNumber  FROM WorkOrderLineItem WHERE BLN_PrintStatus__c=:status AND LastModifiedDate>=:last24Hours';
        return Database.getQueryLocator(query);        
    }
    
    global void execute(Database.BatchableContext bc, List<WorkOrderLineItem> scope){
        String oktaToken = BLN_HTTPCallOutAccessToken.getAccessToken()?.accessToken;
        if(!String.isBlank(oktaToken)){
            sendDocsToMuleSoftForPrinting(oktaToken, scope);
        }
    }
    
    global void finish(Database.BatchableContext bc){
        AsyncApexJob job = [SELECT Id, JobType, ApexClassId, Status, NumberOfErrors, MethodName, CompletedDate FROM AsyncApexJob WHERE Id =: bc.getJobId()];
    }
    
    global void execute(SchedulableContext ctx) {
        Integer batchSize = 200;
        BLN_SendDocsForPrintBatch batch = new BLN_SendDocsForPrintBatch();
        Database.executeBatch(batch, batchSize);
    }

    public static void sendDocsToMuleSoftForPrinting(String accessToken, List<WorkOrderLineItem> scope){
        try{
            Map<String, String> mapOfParentIdAndAWSDocId = getMapOfParentIdAndAWSDocId(scope);
                
            // Start Preparing JSON for Request Body
            Current current = new Current();
            current.bucketName = System.Label.BLN_PrintCalloutBucketName;
            List<Document> documents = new List<Document>();

            for(WorkOrderLineItem woli:scope){
                Document doc = new Document();
                doc.woliID = woli.Id;
                if(woli.WorkOrder!=null){
                    if(woli.WorkOrder.CaseId!=null){
                        doc.caseId = woli.WorkOrder.Case.CaseNumber!=null ? woli.WorkOrder.Case.CaseNumber : '';
                    }
                }
                if(!mapOfParentIdAndAWSDocId.isEmpty() && mapOfParentIdAndAWSDocId.containsKey(woli.Id)){
                    doc.serviceReportDocumentId = mapOfParentIdAndAWSDocId.get(woli.Id);// get the serviceReportDocumentId from AWS
                }
                else{
                    doc.serviceReportDocumentId = '';
                }
                documents.add(doc);
            }

            current.documents = documents;

            Data data = new Data();
            data.current = current;

            PayloadWrapper payLoad = new PayloadWrapper();
            payLoad.entityName = '';
            payLoad.entityID = '';
            payLoad.eventType = System.Label.BLN_PrintEventType;
            payLoad.sourceSystem = '';
            payLoad.timestamp = makeTimeStamp();
            payLoad.initialisedSystem = '';
            payLoad.data = data;

            BLN_APICalloutMapper__mdt calloutDetails = BLN_APICalloutMapper__mdt.getInstance(System.label.BLN_DocsForPrintApi);
            Map<String,String> headerMap = new Map<String,String>();
            headerMap.put(System.label.BLN_AuthorizationBearer.split(System.label.BLN_Comma)[0],System.label.BLN_AuthorizationBearer.split(System.label.BLN_Comma)[1]+' '+accessToken);
            
            if(String.isNotBlank(calloutDetails.BLN_Headers__c)){
                for(String header : calloutDetails.BLN_Headers__c.split(System.label.BLN_Semicolon)){
                    if(header.contains(System.label.BLN_Comma)){
                        headerMap.put(header.split(System.label.BLN_Comma)[0],header.split(System.label.BLN_Comma)[1]);
                    }
                }
            }
            Integer timeout = Integer.valueOf(calloutDetails.BLN_APITimeout__c);
            HttpResponse res = BLN_HttpCalloutUtility.makeCallout(calloutDetails.BLN_DestinationSystem__c,calloutDetails.BLN_NamedCredential__c + calloutDetails.BLN_CalloutURL__c, calloutDetails.BLN_Method__c,headerMap,'Send Docs For Printing',JSON.serialize(payLoad),timeout);
           
        } catch (Exception ex) {
            // Store Exception Logger Record
            BLN_ExceptionLogger.captureException(ex);
        }
    }
    
    public static string resHeaders(HttpResponse res){
        string[] headerkeys = res.getHeaderKeys();
        String headers;
        for(String header : headerkeys){
            headers = res.getHeader(header) + ',';
        }
        return headers;
    }
    
    public static String randomCodeGenerator() {
        Blob blobKey = Crypto.GenerateAESKey(128);
        String hexKey = EncodingUtil.ConvertTohex(blobKey);
        String uid = hexKey.SubString(0,8)+ '-' + hexKey.SubString(8,12) + '-' + hexKey.SubString(12,16) + '-' + hexKey.SubString(16,20) + '-' + hexKey.substring(20);
        return uid;
    }
    
    public static String makeTimeStamp(){
        String currentDateTime = '';
        currentDateTime = System.now().formatGMT('yyyy-MM-dd\'T\'HH:mm:ss.SSSSSSZ');
        String last2Chars = currentDateTime.right(2);
        currentDateTime = currentDateTime.removeEnd(last2Chars);
        currentDateTime = currentDateTime + ':' + last2Chars;
        return currentDateTime;
    }

    public static Map<String, String> getMapOfParentIdAndAWSDocId(List<WorkOrderLineItem> scope){
        Map<String, String> mapOfParentIdAndAWSDocId = new Map<String, String>();
        Set<Id> setOfWoliIds = new Set<Id>();
        for(WorkOrderLineItem woli:scope){
            setOfWoliIds.add(woli.Id);
        }

        if(!setOfWoliIds.isEmpty()){
            List<BLN_ExternalFileLinks__c> externalLinks = [SELECT Id, BLN_ParentId__c, BLN_DocumentId__c 
                                                            FROM BLN_ExternalFileLinks__c 
                                                            WHERE BLN_ParentId__c IN:setOfWoliIds
                                                           		AND BLN_FileType__c = 'PDF'
                                                           	AND BLN_Category__c = 'Post-Inspection'];
            for(BLN_ExternalFileLinks__c link:externalLinks){
                if(link.BLN_ParentId__c!=null && link.BLN_DocumentId__c!=null){
                    mapOfParentIdAndAWSDocId.put(link.BLN_ParentId__c, link.BLN_DocumentId__c);
                }
            }
        }
        return mapOfParentIdAndAWSDocId;
    }

    public class PayloadWrapper {
        public String entityName{get;set;}
        public String entityID{get;set;}
        public String eventType{get;set;}
        public String sourceSystem{get;set;}
        public String timestamp{get;set;}
        public String initialisedSystem{get;set;}
        public Data data{get;set;}
    }  

    public class Data {
        public Current current{get;set;}
    }

    public class Current {
        public String bucketName{get;set;}
        public List<Document> documents{get;set;}
    }
    
	public class Document {
		public String caseId{get;set;}
		public String woliID{get;set;}
		public String serviceReportDocumentId{get;set;}
	}    
}