force-app/main/default/objects/BLN_Vehicle__c/BLN_Vehicle__c.object-meta.xml
<CustomObject>
    <description>FOUK-495 This object is created for storing the Vehicles.</description>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{00000000}</displayFormat>
        <label>Vehicle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_Vehicle__c/fields/BLN_MakeOfVehicle__c.field-meta.xml
<CustomField>
    <fullName>BLN_MakeOfVehicle__c</fullName>
    <description>FOUK-116--&gt; This field is created for make of vehicle details.</description>
    <label>Make Of Vehicle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Vehicle__c/fields/BLN_ModelOfVehicle__c.field-meta.xml
<CustomField>
    <fullName>BLN_ModelOfVehicle__c</fullName>
    <description>FOUK-116--&gt; This field is created for model of vehicle .</description>
    <label>Model Of Vehicle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Vehicle__c/fields/BLN_VehicleRegNumber__c.field-meta.xml
<CustomField>
    <fullName>BLN_VehicleRegNumber__c</fullName>
    <description>Fouk-109 To store vehicle registeration number.</description>
    <label>Vehicle Registration Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Vehicle__c/fields/BLN_Year__c.field-meta.xml
<CustomField>
    <fullName>BLN_Year__c</fullName>
    <description>FOUK-495 This field is used to store year the vehicle was registered</description>
    <label>Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BLN_ShowOutstandingBalanceTest.cls
/*
ClassName : BLN_ShowOutstandingBalanceTest
Description :	BLN_ShowOutstandingBalance test class.
@Story : FOUK-5777
percentage : 87%
CreatedBy : Sourabh Bhattacharjee
*/
@isTest
public class BLN_ShowOutstandingBalanceTest {
 @isTest
    static void getBal1(){
        Account acc = new Account(Name = 'Test Account',BLN_RegisteredAddressTerritory__c = 'Test');
        insert acc;
        Contact con = new Contact(LastName = 'Test Contact', AccountId = acc.Id);
        insert con;
        BLN_Vehicle__c vehicleRec = new BLN_Vehicle__c(
            BLN_Year__c = 2020,
            BLN_VehicleRegNumber__c = 'ABC123',
            BLN_MakeOfVehicle__c = 'Test Make',
            BLN_ModelOfVehicle__c = 'Test Model'
        );
        insert vehicleRec;

        OperatingHours oh = new OperatingHours(
            Name = 'Test Operating Hours'
        );
        insert oh;

         // Create Service Territory and Operating Hours
        ServiceTerritory st = new ServiceTerritory
            (Name = 'Test Territory',
             OperatingHoursId = oh.Id ,
             IsActive = true
            );
	        insert st;

        Case testCase = new Case(
            Subject = 'Test Case',
            AccountID = acc.Id,
            ContactId = con.Id,
            Status = 'New',
            Origin = 'Web',
            BLN_Vehicle__c = vehicleRec.Id,
            BLN_BookingStatus__c = 'Confirmed',
            BLN_SubType__c='Job Request',
            Type = 'Job Request',
            Priority = 'Medium',
            BLN_TotalMotoristLiability__c = 6000
        );
        insert testCase;
        Test.startTest();
        BLN_ShowOutstandingBalance.getBal(testCase.id);
        Test.stopTest();
        System.assert(testCase.Id != null, 'Case ID Should not be null');
    }
@isTest
    static void getBal2(){
        Account acc = new Account(Name = 'Test Account',BLN_RegisteredAddressTerritory__c = 'Test');
        insert acc;
        Contact con = new Contact(LastName = 'Test Contact', AccountId = acc.Id);
        insert con;
        BLN_Vehicle__c vehicleRec = new BLN_Vehicle__c(
            BLN_Year__c = 2020,
            BLN_VehicleRegNumber__c = 'ABC123',
            BLN_MakeOfVehicle__c = 'Test Make',
            BLN_ModelOfVehicle__c = 'Test Model'
        );
        insert vehicleRec;

        OperatingHours oh = new OperatingHours(
            Name = 'Test Operating Hours'
        );
        insert oh;

         // Create Service Territory and Operating Hours
        ServiceTerritory st = new ServiceTerritory
            (Name = 'Test Territory',
             OperatingHoursId = oh.Id ,
             IsActive = true
            );
	        insert st;

        Case testCase = new Case(
            Subject = 'Test Case',
            AccountID = acc.Id,
            ContactId = con.Id,
            Status = 'New',
            Origin = 'Web',
            BLN_Vehicle__c = vehicleRec.Id,
            BLN_BookingStatus__c = 'Confirmed',
            BLN_SubType__c='Job Request',
            Type = 'Job Request',
            Priority = 'Medium',
            BLN_TotalMotoristLiability__c = 2
        );
        insert testCase;
        Test.startTest();
        BLN_ShowOutstandingBalance.getBal(testCase.id);
        Test.stopTest();
        System.assert(testCase.Id != null, 'Case ID Should not be null');
    }
    @isTest
    static void getBal3(){
        Account acc = new Account(Name = 'Test Account',BLN_RegisteredAddressTerritory__c = 'Test');
        insert acc;
        Contact con = new Contact(LastName = 'Test Contact', AccountId = acc.Id);
        insert con;
        BLN_Vehicle__c vehicleRec = new BLN_Vehicle__c(
            BLN_Year__c = 2020,
            BLN_VehicleRegNumber__c = 'ABC123',
            BLN_MakeOfVehicle__c = 'Test Make',
            BLN_ModelOfVehicle__c = 'Test Model'
        );
        insert vehicleRec;

        OperatingHours oh = new OperatingHours(
            Name = 'Test Operating Hours'
        );
        insert oh;

         // Create Service Territory and Operating Hours
        ServiceTerritory st = new ServiceTerritory
            (Name = 'Test Territory',
             OperatingHoursId = oh.Id ,
             IsActive = true
            );
	        insert st;

        Case testCase = new Case(
            Subject = 'Test Case',
            AccountID = acc.Id,
            ContactId = con.Id,
            Status = 'New',
            Origin = 'Web',
            BLN_Vehicle__c = vehicleRec.Id,
            BLN_BookingStatus__c = 'Provisional',
            BLN_SubType__c='Job Request',
            Type = 'Job Request',
            Priority = 'Medium',
            BLN_TotalMotoristLiability__c = 2
        );
        insert testCase;
        Test.startTest();
        BLN_ShowOutstandingBalance.getBal(testCase.id);
        Test.stopTest();
        System.assert(testCase.Id != null, 'Case ID Should not be null');
    }
}