force-app/main/default/objects/BLN_Vehicle__c/BLN_Vehicle__c.object-meta.xml
<CustomObject>
    <description>FOUK-495 This object is created for storing the Vehicles.</description>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{00000000}</displayFormat>
        <label>Vehicle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_Vehicle__c/fields/BLN_BodyType__c.field-meta.xml
<CustomField>
    <fullName>BLN_BodyType__c</fullName>
    <description>FOUK-3425 This field is used to store body type of vehicle.</description>
    <label>Body Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Vehicle__c/fields/BLN_MakeOfVehicle__c.field-meta.xml
<CustomField>
    <fullName>BLN_MakeOfVehicle__c</fullName>
    <description>FOUK-116--&gt; This field is created for make of vehicle details.</description>
    <label>Make Of Vehicle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Vehicle__c/fields/BLN_ModelOfVehicle__c.field-meta.xml
<CustomField>
    <fullName>BLN_ModelOfVehicle__c</fullName>
    <description>FOUK-116--&gt; This field is created for model of vehicle .</description>
    <label>Model Of Vehicle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Vehicle__c/fields/BLN_Year__c.field-meta.xml
<CustomField>
    <fullName>BLN_Year__c</fullName>
    <description>FOUK-495 This field is used to store year the vehicle was registered</description>
    <label>Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BLN_SelectServiceTypeControllerTest.cls
/** @description : Test class for BLN_SelectServiceTypeController apex class
*   @Story : FOUK-8373
*   @author: Siddhant Pandya (PwC)
*   @CreatedDate: 21/05/2024
*/
@isTest
public class BLN_SelectServiceTypeControllerTest {
/**
*@description : This method is used for testing BLN_SelectServiceTypeController.checkVehicleValues method
*@return void
*/
@isTest
    static void testCheckVehicleValues(){
        BLN_Vehicle__c vehicle1 = BLN_TestDataFactory.getVehicle();
        vehicle1.BLN_MakeOfVehicle__c = 'BMW';
        vehicle1.BLN_ModelOfVehicle__c = 'X2';
        vehicle1.BLN_Year__c = 2020;
        vehicle1.BLN_BodyType__c = 'Carbon';
        insert vehicle1;

        BLN_Vehicle__c vehicle2 = BLN_TestDataFactory.getVehicle();
        insert vehicle2;

        Test.startTest();
        Boolean value1 = BLN_SelectServiceTypeController.checkVehicleValues(vehicle1.Id);
        Boolean value2 = BLN_SelectServiceTypeController.checkVehicleValues(vehicle2.Id);
        Test.stopTest();
        
        System.assertEquals(true,value1 && !value2, 'Value1 should be true, Value2 should be false');
    }
}