force-app/main/default/objects/BLN_Vehicle__c/BLN_Vehicle__c.object-meta.xml
<CustomObject>
    <description>FOUK-495 This object is created for storing the Vehicles.</description>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{00000000}</displayFormat>
        <label>Vehicle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_Vehicle__c/fields/BLN_BodyType__c.field-meta.xml
<CustomField>
    <fullName>BLN_BodyType__c</fullName>
    <description>FOUK-3425 This field is used to store body type of vehicle.</description>
    <label>Body Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Vehicle__c/fields/BLN_MakeOfVehicle__c.field-meta.xml
<CustomField>
    <fullName>BLN_MakeOfVehicle__c</fullName>
    <description>FOUK-116--&gt; This field is created for make of vehicle details.</description>
    <label>Make Of Vehicle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Vehicle__c/fields/BLN_ModelOfVehicle__c.field-meta.xml
<CustomField>
    <fullName>BLN_ModelOfVehicle__c</fullName>
    <description>FOUK-116--&gt; This field is created for model of vehicle .</description>
    <label>Model Of Vehicle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_Vehicle__c/fields/BLN_Year__c.field-meta.xml
<CustomField>
    <fullName>BLN_Year__c</fullName>
    <description>FOUK-495 This field is used to store year the vehicle was registered</description>
    <label>Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BLN_SelectServiceTypeController.cls
/** @description : This class is used as controller of BLN_SelectServiceType LWC
*   @Story : FOUK-8373
*   @author: Siddhant Pandya (PwC)
*   @CreatedDate: 21/05/2024
*/
public with sharing class BLN_SelectServiceTypeController {
/**
*@description : This method is called from 'BLN_SelectServiceType' LWC, for checking vehicle values if filled or not.
*@return void
*/
    @AuraEnabled
    public static boolean checkVehicleValues(Id vehicleId) {
        String query = 'Select id, BLN_MakeOfVehicle__c, BLN_ModelOfVehicle__c, BLN_Year__c, BLN_BodyType__c from BLN_Vehicle__c where id = \''+vehicleId+'\'';
        BLN_Vehicle__c vehicle = Database.query(query);

        if(vehicle !=null && (vehicle.BLN_MakeOfVehicle__c == null || vehicle.BLN_ModelOfVehicle__c == null || vehicle.BLN_Year__c == null || vehicle.BLN_BodyType__c == null || vehicle.BLN_MakeOfVehicle__c == '' || vehicle.BLN_ModelOfVehicle__c == '' || vehicle.BLN_BodyType__c == ''))
        {
            return false;
        }

        return true;
    }
}