force-app/main/default/objects/BLN_AccountAlternativeName__c/BLN_AccountAlternativeName__c.object-meta.xml
<CustomObject>
    <description>FOUK-8128. This is a new object name as Account Alternative Name.</description>
    <label>Account Alternative Name</label>
    <nameField>
        <displayFormat>AAN-{0000}</displayFormat>
        <label>Alternative Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Alternative Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_AccountAlternativeName__c/fields/BLN_Account__c.field-meta.xml
<CustomField>
    <fullName>BLN_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>FOUK-8128. This field is the relationship between Account and Account Alternative Name.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Alternative Names</relationshipLabel>
    <relationshipName>Account_Alternative_Names</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BLN_AccountAlternativeName__c/fields/BLN_AlternativeAccountName__c.field-meta.xml
<CustomField>
    <fullName>BLN_AlternativeAccountName__c</fullName>
    <description>FOUK-8128. This field is the reference of Alternative Account Name.</description>
    <label>Alternative Account Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_AccountGroupRule__c/BLN_AccountGroupRule__c.object-meta.xml
<CustomObject>
    <label>Account Group Rule</label>
    <nameField>
        <label>Account Group Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Group Rules</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_AccountGroupRule__c/fields/BLN_ActiveFrom__c.field-meta.xml
<CustomField>
    <fullName>BLN_ActiveFrom__c</fullName>
    <description>FOUK-5765</description>
    <label>Active From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BLN_AccountGroupRule__c/fields/BLN_ActiveTo__c.field-meta.xml
<CustomField>
    <fullName>BLN_ActiveTo__c</fullName>
    <description>FOUK-5765</description>
    <label>Active To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BLN_AccountGroupRule__c/fields/BLN_ClientType__c.field-meta.xml
<CustomField>
    <fullName>BLN_ClientType__c</fullName>
    <label>Client Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ClientTypes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_AccountGroupRule__c/fields/BLN_CorporateType__c.field-meta.xml
<CustomField>
    <fullName>BLN_CorporateType__c</fullName>
    <description>FOUK-5765</description>
    <label>Corporate Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ClientTypes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_AccountGroupRule__c/fields/BLN_OwningBusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>BLN_OwningBusinessUnit__c</fullName>
    <description>FOUK-5765</description>
    <label>Owning Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BLN_OwningBusinessUnitGlobal</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/BLN_AccountRuleParameter__c.object-meta.xml
<CustomObject>
    <description>FOUK-1904</description>
    <label>Account Rule Parameter</label>
    <nameField>
        <displayFormat>ARP-{000000}</displayFormat>
        <label>Account Rule Parameter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Rule Parameters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_Account__c.field-meta.xml
<CustomField>
    <fullName>BLN_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Mandatory relationship to the Account to which Account rule parameter applies to.(FOUK-1904)</description>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Rule Parameters</relationshipLabel>
    <relationshipName>BLN_AccountRuleParameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_AccountRuleGroup__c.field-meta.xml
<CustomField>
    <fullName>BLN_AccountRuleGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Rule Group</label>
    <referenceTo>BLN_AccountGroupRule__c</referenceTo>
    <relationshipLabel>Account Rule Parameters</relationshipLabel>
    <relationshipName>Account_Rule_Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_ActiveFrom__c.field-meta.xml
<CustomField>
    <fullName>BLN_ActiveFrom__c</fullName>
    <description>Specifies validity date for Account Rule Parameter. This date will be set when Account Rule Parameter will be agreed. If data is not set - ARP is considered not activated. (FOUK-1904)</description>
    <label>Active From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_ActiveTo__c.field-meta.xml
<CustomField>
    <fullName>BLN_ActiveTo__c</fullName>
    <description>Specifies validity date for Account Rule Parameter. This date will be set when Account Rule Parameter will be agreed. If data is not set - ARP is considered not activated. (FOUK-1904)</description>
    <label>Active To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_ProductCategory__c.field-meta.xml
<CustomField>
    <fullName>BLN_ProductCategory__c</fullName>
    <label>Product Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_SLAType__c.field-meta.xml
<CustomField>
    <fullName>BLN_SLAType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>FOUK-6522 Lookup field for SLA record types to SLA Definition custom object</description>
    <label>SLA Type</label>
    <referenceTo>BLN_SLADefinition__c</referenceTo>
    <relationshipLabel>Account Rule Parameters</relationshipLabel>
    <relationshipName>Account_Rule_Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BLN_SLADefinition__c/BLN_SLADefinition__c.object-meta.xml
<CustomObject>
    <description>FOUK-6522 New custom object to log all the Service Level Agreement (SLAs) agreed with clients at contract with associated Account   Legal Entity or Grouping level</description>
    <label>SLA Definition</label>
    <nameField>
        <label>SLA Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SLAs Definition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_SLADefinition__c/fields/BLN_Category__c.field-meta.xml
<CustomField>
    <fullName>BLN_Category__c</fullName>
    <description>FOUK-6522 Category picklist field for SLA Definition</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Telephony</fullName>
            </value>
            <value>
                <fullName>Time To Serve</fullName>
            </value>
            <value>
                <fullName>Quality</fullName>
            </value>
            <value>
                <fullName>ADAS</fullName>
            </value>
            <value>
                <fullName>Job Retention</fullName>
            </value>
            <value>
                <fullName>NPS &amp; Other Survey Questions</fullName>
            </value>
            <value>
                <fullName>Complaints</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Financial</fullName>
            </value>
            <value>
                <fullName>Job processing</fullName>
            </value>
            <value>
                <fullName>Repair Ratio</fullName>
            </value>
            <value>
                <fullName>Mobile Appointments</fullName>
            </value>
            <value>
                <fullName>MI Reporting</fullName>
            </value>
            <value>
                <fullName>Subcontractors</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/BLN_OwningBusinessUnitGlobal.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Autoglass-UK</fullName>
        <default>true</default>
        <label>Autoglass-UK</label>
    </customValue>
    <description>FOUK-5765</description>
    <masterLabel>Owning Business Unit Global</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/ClientTypes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Insurance</fullName>
        <label>Insurer</label>
    </customValue>
    <customValue>
        <fullName>Fleet National</fullName>
    </customValue>
    <customValue>
        <fullName>Fleet Local</fullName>
    </customValue>
    <customValue>
        <fullName>Lease</fullName>
    </customValue>
    <customValue>
        <fullName>Rental</fullName>
    </customValue>
    <customValue>
        <fullName>Trade/Commercial</fullName>
    </customValue>
    <customValue>
        <fullName>Wholesale</fullName>
    </customValue>
    <customValue>
        <fullName>Agent/Broker</fullName>
    </customValue>
    <customValue>
        <fullName>Intercompany</fullName>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <customValue>
        <fullName>Intermediary</fullName>
    </customValue>
    <customValue>
        <fullName>Fleet</fullName>
        <isActive>false</isActive>
        <label>Fleet</label>
    </customValue>
    <customValue>
        <fullName>Trade Client</fullName>
        <isActive>false</isActive>
        <label>Trade Client</label>
    </customValue>
    <masterLabel>Client Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BLN_MDMTriggerHandlerTest.cls
/*****************************************
ClassName : BLN_AccountTrigger, BLN_ContactMDMTrigger,BLN_ARPMDMTrigger, BLN_SLADefinitionMMDMTrigger,BLN_PDSMDMTrigger, BLN_AGRMDMTrigger
@description : FOUK-4467 This test  class is used to cover BLN_RecalculateTerritoryManagementRules.
CreatedDate: 28-12-2023
CreatedBy : PwC-India
****************************************/
@isTest
public with sharing class BLN_MDMTriggerHandlerTest {
    private class MockResponseGenerator implements HttpCalloutMock {
               public HTTPResponse respond(HTTPRequest req) {
            if(req.getEndpoint() == 'callout:BLN_OktaAuthToken'){
                HttpResponse response = new HttpResponse();
                response.setBody('{"token_type":"Bearer","expires_in":3600,"access_token":"MockAccessToken123","scope":"read"}');
                response.setStatusCode(200);
                return response;      
            } else {
                HttpResponse res = new HttpResponse();
                res.setHeader('Content-Type', 'application/json');
                res.setBody('{"message": "Success"}');
                res.setStatusCode(200);
                return res;
            }

        }
    }
    @isTest
    static void personAccMdmHandlerTest() {
        Account acc =  BLN_TestDataFactory.createAccount('Sample','PersonAccount','8698023890');
        test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockResponseGenerator());
        
        insert acc;
        acc.PersonHomePhone = '8698023891';
        update acc;
        test.stopTest();
        List<Account> accList = [select Id from account where Id =: acc.Id];
        System.assertEquals(accList.size()>0,true,'account inserted');
      
    }

    @isTest
    static void salesAccMdmHandlerTest() {
        Account testAccount = BLN_TestDataFactory.createSalesAccount('TestMockB2BAccount1','Agriculture','Underwriter',1,'Insurance','GB123456779', 'AA161811','San Francisco', 'testStreet','12345' ,'GB','Blue Anchor' ,'Minehead',
        '7890' , 'United Kingdom','BLN_CustomerB2BAccount');
        Map<String,Map<String,string>> fieldsMap = new Map<String,Map<String,string>>();
        BLN_MDMConfiguration.MDMParameters param = new BLN_MDMConfiguration.MDMParameters();
        param.streamName =  'Sales';
        param.sourceObject = 'Account';
        param.eventType = 'Create';
        
        test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockResponseGenerator());
        insert testAccount;
        fieldsMap.put(testAccount.Id,new Map<String,string>{'Id'=>testAccount.Id,'Name' => 'TestMockB2BAccount1','Status'=>'Prospect'});
        param.fieldsToSync = fieldsMap;
        Database.executeBatch(new BLN_QueueMDMGateWay(param));
        testAccount.Industry = 'Apparel';
        testAccount.BLN_MDMAccountID__c = '563522';
        update testAccount;
        test.stopTest();
        List<Account> accList = [select Id from account where Id =: testAccount.Id];
        System.assertEquals(accList.size()>0,true,'account inserted');
      
    }



    @isTest
    static void contactdMdmHandlerTest() {
        Account testAccount = BLN_TestDataFactory.createSalesAccount('TestMockB2BAccount1','Agriculture','Underwriter',1,'Insurance','GB123456779', 'AA161811','San Francisco', 'testStreet','12345' ,'GB','Blue Anchor' ,'Minehead',
        '7890' , 'United Kingdom','BLN_CustomerB2BAccount');
        testAccount.BLN_MDMAccountID__c = '463522';

        insert testAccount;
        Contact testContact = BLN_TestDataFactory.getContact('Test');
        testContact.FirstName = 'Test';
        testContact.LastName = 'Contact';
        testContact.Email = 'test123@gmail.com';
        testContact.AccountId = testAccount.Id;
        
        test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockResponseGenerator());
        insert testContact;
        testContact.LastName = 'testContact';
        update testContact;
        test.stopTest();
        List<Account> accList = [select Id from account where Id =: testAccount.Id];
        System.assertEquals(accList.size()>0,true,'account inserted');

      
    }

    @isTest
    static void arpMdmHandlerTest() {
        Account accRec = new Account(Name = 'Test Account', BLn_ClientType__c = 'Insurance');
         accRec.BLN_MDMAccountID__c = '568522';

        insert accRec;

        BLN_AccountGroupRule__c agr = new BLN_AccountGroupRule__c(
            Name = 'test Agr',
            BLN_ActiveFrom__c = System.now().addDays(-1).date(),
            BLN_ActiveTo__c = System.Date.today(),
            BLN_CorporateType__c = 'Insurance',
            BLN_OwningBusinessUnit__c = 'Autoglass-UK'

        );
        insert agr;
        BLN_SLADefinition__c sla = new BLN_SLADefinition__c(
            Name = 'test sla',
            BLN_Category__c = 'Quality'
        );
        insert sla;
        // Create account rule parameter
            String getDivertToAuthorizationTeam = Schema.SObjectType.BLN_AccountRuleParameter__c.getRecordTypeInfosByName().get('Automatic Divert to Authorisation Team').getRecordTypeId();
           BLN_AccountRuleParameter__c getDivertAuth = new BLN_AccountRuleParameter__c(
               BLN_Account__c = accRec.Id,
               RecordTypeId = getDivertToAuthorizationTeam,
               BLN_ProductCategory__c = 'Test Product',
               BLN_ActiveFrom__c = System.now().addDays(-1).date(),
               BLN_ActiveTo__c = System.Date.today(),

               BLN_AccountRuleGroup__c = agr.Id,
               BLN_SLAType__c =  sla.Id

           );
          
        test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockResponseGenerator());
        insert getDivertAuth;
        getDivertAuth.BLN_ActiveFrom__c  =  System.now().addDays(-2).date();
        update getDivertAuth;
        sla.BLN_Category__c = 'Telephony';
        update sla;
        agr.BLN_ActiveFrom__c = System.now().addDays(-2).date();
        update agr;

        test.stopTest();
        List<Account> accList = [select Id from account where Id =: accRec.Id];
        System.assertEquals(accList.size()>0,true,'account inserted');
      
    }

    @isTest
    static void alterNativeMdmTest() {
        Account accRec = new Account(Name = 'Test Account', BLn_ClientType__c = 'Insurance');
          accRec.BLN_MDMAccountID__c = '568512';
        insert accRec;
        // Create account rule parameter
        
        BLN_AccountAlternativeName__c alter = new BLN_AccountAlternativeName__c(
            BLN_Account__c = accRec.Id,
            BLN_AlternativeAccountName__c = 'test alter'

        );
        test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockResponseGenerator());
        insert alter;
        alter.BLN_AlternativeAccountName__c  =  'test alter1';

        update alter;
        test.stopTest();
        List<Account> accList = [select Id from account where Id =: accRec.Id];
        System.assertEquals(accList.size()>0,true,'account inserted');
        

    }
    
  
    
   
}