force-app/main/default/objects/BLN_AccountRuleParameter__c/BLN_AccountRuleParameter__c.object-meta.xml
<CustomObject>
    <description>FOUK-1904</description>
    <label>Account Rule Parameter</label>
    <nameField>
        <displayFormat>ARP-{000000}</displayFormat>
        <label>Account Rule Parameter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Rule Parameters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_Account__c.field-meta.xml
<CustomField>
    <fullName>BLN_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Mandatory relationship to the Account to which Account rule parameter applies to.(FOUK-1904)</description>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Rule Parameters</relationshipLabel>
    <relationshipName>BLN_AccountRuleParameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_ActiveFrom__c.field-meta.xml
<CustomField>
    <fullName>BLN_ActiveFrom__c</fullName>
    <description>Specifies validity date for Account Rule Parameter. This date will be set when Account Rule Parameter will be agreed. If data is not set - ARP is considered not activated. (FOUK-1904)</description>
    <label>Active From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_ActiveTo__c.field-meta.xml
<CustomField>
    <fullName>BLN_ActiveTo__c</fullName>
    <description>Specifies validity date for Account Rule Parameter. This date will be set when Account Rule Parameter will be agreed. If data is not set - ARP is considered not activated. (FOUK-1904)</description>
    <label>Active To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_Procedure__c.field-meta.xml
<CustomField>
    <fullName>BLN_Procedure__c</fullName>
    <label>Procedure Text</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/recordTypes/Procedure.recordType-meta.xml
<RecordType>
    <fullName>Procedure</fullName>
    <active>true</active>
    <description>Record Type to store Procedure records</description>
    <label>Procedure</label>
</RecordType>

force-app/main/default/classes/BLN_ShowProceduresTest.cls
/*****************************************
ClassName : BLN_ShowProceduresTest
@description : FOUK 5079 This class is used to test BLN_ShowProcedures.
@author: PwC
CreatedDate:  01-08-2024
CreatedBy : PwC-India
***************************************/
@isTest
public with sharing class BLN_ShowProceduresTest {

    @isTest
    public static void getProceduresArpTest() {
        String customerB2BAccountRecordtypeId = [SELECT Id, Name FROM RecordType where Name = 'Customer(B2B Account)'].Id;
        Account accRec1 = new Account(Name = 'Test Account', BLn_ClientType__c = 'Insurance',recordtypeId = customerB2BAccountRecordtypeId);
        insert accRec1;
        Account accRec2 = new Account(Name = 'Test Account1', BLn_ClientType__c = 'Insurance',recordtypeId = customerB2BAccountRecordtypeId); 
        insert accRec2;
            
            String procedureRecType = Schema.SObjectType.BLN_AccountRuleParameter__c.getRecordTypeInfosByName().get('Procedure').getRecordTypeId();
            
            BLN_AccountRuleParameter__c procedureRec1 = new BLN_AccountRuleParameter__c(
                BLN_Account__c = accRec1.Id,
                RecordTypeId = procedureRecType	,
                BLN_Procedure__c = 'Test text',
                BLN_ActiveFrom__c = System.now().addDays(-1).date(),
                BLN_ActiveTo__c = System.Date.today()
            );
            insert procedureRec1;

            BLN_AccountRuleParameter__c procedureRec2 = new BLN_AccountRuleParameter__c(
                BLN_Account__c = accRec2.Id,
                RecordTypeId = procedureRecType	,
                BLN_Procedure__c = 'Test text',
                BLN_ActiveFrom__c = System.now().addDays(-1).date(),
                BLN_ActiveTo__c = System.Date.today()
            );
            insert procedureRec2;
            
            Test.startTest();
                List<List<BLN_AccountRuleParameterWrapper>> arpList1 =  BLN_ShowProcedures.getProceduresArp(new List<List<String>>{new List<String>{accRec1.Id}});
                List<List<BLN_AccountRuleParameterWrapper>> arpList2 =  BLN_ShowProcedures.getProceduresArp(new List<List<String>>{new List<String>{accRec1.Id,accRec2.Id}});
            Test.stopTest();
            System.assertEquals(false, arpList1.isEmpty(), 'procedures not null');
            System.assertEquals(false, arpList2.isEmpty(), 'procedures not null');
    }
}