force-app/main/default/objects/BLN_AccountRuleParameter__c/BLN_AccountRuleParameter__c.object-meta.xml
<CustomObject>
    <description>FOUK-1904</description>
    <label>Account Rule Parameter</label>
    <nameField>
        <displayFormat>ARP-{000000}</displayFormat>
        <label>Account Rule Parameter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Rule Parameters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_Account__c.field-meta.xml
<CustomField>
    <fullName>BLN_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Mandatory relationship to the Account to which Account rule parameter applies to.(FOUK-1904)</description>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Person Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Rule Parameters</relationshipLabel>
    <relationshipName>BLN_AccountRuleParameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_ActiveFrom__c.field-meta.xml
<CustomField>
    <fullName>BLN_ActiveFrom__c</fullName>
    <description>Specifies validity date for Account Rule Parameter. This date will be set when Account Rule Parameter will be agreed. If data is not set - ARP is considered not activated. (FOUK-1904)</description>
    <label>Active From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_ActiveTo__c.field-meta.xml
<CustomField>
    <fullName>BLN_ActiveTo__c</fullName>
    <description>Specifies validity date for Account Rule Parameter. This date will be set when Account Rule Parameter will be agreed. If data is not set - ARP is considered not activated. (FOUK-1904)</description>
    <label>Active To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_AuthorizationLimit__c.field-meta.xml
<CustomField>
    <fullName>BLN_AuthorizationLimit__c</fullName>
    <description>Amount of authorization limit. Auth limit is only based on the cost to the corporate (e.g not including the excess)
Parameter defines amount only - currency is determined based on related Account currency.</description>
    <label>Authorization Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_Excess__c.field-meta.xml
<CustomField>
    <fullName>BLN_Excess__c</fullName>
    <label>Excess</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Motorist</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Secondary Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_InsurerAccount__c.field-meta.xml
<CustomField>
    <fullName>BLN_InsurerAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secondary Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Rule Parameters (Insurer Account)</relationshipLabel>
    <relationshipName>Account_Rule_Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_OEAuthorization__c.field-meta.xml
<CustomField>
    <fullName>BLN_OEAuthorization__c</fullName>
    <description>Parameter controls if OE glass requirement for an account. OE glass might be enforced, not allowed, within motorists liability, allowed or extra authorisation might be needed.</description>
    <label>OE Authorization Option</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OE Glass Only</fullName>
            </value>
            <value>
                <fullName>Non-OE Glass Only</fullName>
            </value>
            <value>
                <fullName>OE Motorist Liability</fullName>
            </value>
            <value>
                <fullName>OE Authorisation Required</fullName>
            </value>
            <value>
                <fullName>OE Glass Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_PolicyLimit__c.field-meta.xml
<CustomField>
    <fullName>BLN_PolicyLimit__c</fullName>
    <label>Policy Limit Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_PolicyNumbers__c.field-meta.xml
<CustomField>
    <fullName>BLN_PolicyNumbers__c</fullName>
    <description>FOUK - 6460</description>
    <label>Policy Number/s</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_Product__c.field-meta.xml
<CustomField>
    <fullName>BLN_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Account Rule Parameters</relationshipLabel>
    <relationshipName>Account_Rule_Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_Remainder__c.field-meta.xml
<CustomField>
    <fullName>BLN_Remainder__c</fullName>
    <label>Remainder</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Motorist</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Secondary Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_RepairExcess__c.field-meta.xml
<CustomField>
    <fullName>BLN_RepairExcess__c</fullName>
    <label>Repair Excess Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_ReplacementExcess__c.field-meta.xml
<CustomField>
    <fullName>BLN_ReplacementExcess__c</fullName>
    <label>Replacement Excess Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/fields/BLN_VAT__c.field-meta.xml
<CustomField>
    <fullName>BLN_VAT__c</fullName>
    <label>VAT</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Motorist</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Secondary Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_AccountRuleParameter__c/recordTypes/BLN_AuthorizationLimit.recordType-meta.xml
<RecordType>
    <fullName>BLN_AuthorizationLimit</fullName>
    <active>true</active>
    <description>Authorization Limit</description>
    <label>Authorization Limit</label>
</RecordType>

force-app/main/default/objects/BLN_AccountRuleParameter__c/recordTypes/BLN_OEAuthorization.recordType-meta.xml
<RecordType>
    <fullName>BLN_OEAuthorization</fullName>
    <active>true</active>
    <label>OE Authorization</label>
</RecordType>

force-app/main/default/objects/BLN_AccountRuleParameter__c/recordTypes/BLN_ProductAllowance.recordType-meta.xml
<RecordType>
    <fullName>BLN_ProductAllowance</fullName>
    <active>true</active>
    <description>FOUK-6068. This is the reference Record type of Product Allowance.</description>
    <label>Product Allowance</label>
</RecordType>

force-app/main/default/objects/BLN_Corporate__c/BLN_Corporate__c.object-meta.xml
<CustomObject>
    <description>FOUK-6065, 5754, This Custom Object is created for storing information about Corporate</description>
    <label>Corporate</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Corporate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Corporates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_Corporate__c/fields/BLN_CHFVATStatus__c.field-meta.xml
<CustomField>
    <fullName>BLN_CHFVATStatus__c</fullName>
    <description>FOUK-5023 :  storing CHF VaT status</description>
    <label>DA/Non DA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rated</fullName>
                <label>Non DA</label>
            </value>
            <value>
                <fullName>Exempt</fullName>
                <label>DA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BLN_Corporate__c/fields/BLN_CorporateSite__c.field-meta.xml
<CustomField>
    <fullName>BLN_CorporateSite__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>FOUK-6065, 5754, This Custom field is created for storing information about Insurance Policies.</description>
    <label>Corporate Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Corporates (Corporate Site Name)</relationshipLabel>
    <relationshipName>Corporates3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BLN_Corporate__c/fields/BLN_InsuranceSite__c.field-meta.xml
<CustomField>
    <fullName>BLN_InsuranceSite__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>FOUK-6065, 5754, This Custom field is created for storing information about Insurance Policies.</description>
    <label>Insurance Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Corporates (Insurance Site Name)</relationshipLabel>
    <relationshipName>Corporates2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BLN_Corporate__c/fields/BLN_PolicyLimit__c.field-meta.xml
<CustomField>
    <fullName>BLN_PolicyLimit__c</fullName>
    <defaultValue>0</defaultValue>
    <description>FOUK-10644, created as part of FOUK-10644.</description>
    <label>Policy Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BLN_Corporate__c/fields/BLN_RepairExcess__c.field-meta.xml
<CustomField>
    <fullName>BLN_RepairExcess__c</fullName>
    <defaultValue>0</defaultValue>
    <description>FOUK-6065, 5754, This Custom field is created for storing information about  Glass Repair Excess Amount</description>
    <label>Glass Repair Excess Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BLN_Corporate__c/fields/BLN_ReplacementExcess__c.field-meta.xml
<CustomField>
    <fullName>BLN_ReplacementExcess__c</fullName>
    <defaultValue>0</defaultValue>
    <description>FOUK-6065, 5754, This Custom field is created for storing information about Replacement Excess.</description>
    <label>Glass Replacement Excess Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BLN_Corporate__c/fields/BLN_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>BLN_Vehicle__c</fullName>
    <description>FOUK-6065, 5754, This Custom field is created for storing information about Vehicle Object</description>
    <label>Vehicle</label>
    <referenceTo>BLN_Vehicle__c</referenceTo>
    <relationshipLabel>Corporates</relationshipLabel>
    <relationshipName>Corporates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BLN_Vehicle__c/BLN_Vehicle__c.object-meta.xml
<CustomObject>
    <description>FOUK-495 This object is created for storing the Vehicles.</description>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{00000000}</displayFormat>
        <label>Vehicle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BLN_Vehicle__c/fields/BLN_MDMID__c.field-meta.xml
<CustomField>
    <fullName>BLN_MDMID__c</fullName>
    <description>FOUK-1819 This field is used to store MDM Id for vehicle object.</description>
    <externalId>true</externalId>
    <label>MDM ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BLN_CheckBvtTaskCreationUtilityTest.cls
/*****************************************
ClassName : BLN_CheckBvtTaskCreationUtilityTest
@description : Test class for BLN_CheckBvtTaskCreationUtility class.
@author: PwC
CreatedDate: 26-11-2024
CreatedBy : PwC-India
****************************************/
@isTest
public class BLN_CheckBvtTaskCreationUtilityTest {
    @isTest
    public static void testcheckBvtTaskCreation(){
        //Make JSON for methods.
        String jsonRes =		'{'+
        '    "status": "success",'+
        '    "quotes": ['+
        '        {'+
        '            "quoteId": "39239816",'+
        '            "locationId": "9y8hfh9",'+
        '            "quoteTotals": {'+
        '                "totalPrice": 0,'+
        '                "totalTax": 176.8,'+
        '                "totalRepair": 0,'+
        '                "totalReplacement": 629.51,'+
        '                "totalCalibration": 0,'+
        '                "totalSundries": 0,'+
        '                "totalIncludingTax": 1060.78'+
        '            },'+
        '            "insuranceTotals": {'+
        '                "payableByInsuranceRepair": 0,'+
        '                "payableByInsuranceReplacement": 0,'+
        '                "payableByInsuranceCalibration": 0,'+
        '                "payableByInsuranceSundry": 0,'+
        '                "totalPayableByInsurance": 0,'+
        '                "totalTaxPayableByInsurance": 0,'+
        '                "totalIncludingTaxPayableByInsurance": 0'+
        '            },'+
        '            "motoristTotals": {'+
        '                "payableByMotoristRepair": 0,'+
        '                "payableByMotoristReplacement": 629.51,'+
        '                "payableByMotoristCalibration": 0,'+
        '                "payableByMotoristSundry": 0,'+
        '                "totalTaxPayableByMotorist": 1060.78,'+
        '                "totalPayableByMotorist": 883.98,'+
        '                "totalInludingTaxPayableByMotorist": 1060.78'+
        '            },'+
        '            "taxTotals": {'+
        '                "totalTaxRepair": 0,'+
        '                "totalTaxReplacement": 0,'+
        '                "totalTaxCalibration": 0,'+
        '                "totalTaxSundries": 0'+
        '            },'+
        '            "tradeCompanyTotals": {'+
        '                "payableByTradeRepair": 0,'+
        '                "totalPayableByTrade": 0,'+
        '                "totalPayableByTradeIncludingTax": 0,'+
        '                "payableByTradeSundry": 0,'+
        '                "payableByTradeReplacement": 0,'+
        '                "payableByTradeCalibration": 0,'+
        '                "payableByTradeTotalTax": 0'+
        '            },'+
        '            "discountThresholdA": 848.62,'+
        '            "discountThresholdB": 689.51,'+
        '            "discountThresholdC": 618.79,'+
        '            "priceExpirationDate": "2024-05-27T00:00:00Z",'+
        '            "lineItems": ['+
        '                {'+
        '                    "lineItemId": 2,'+
        '                    "parentLineItemId": 2,'+
        '                    "bundleName": null,'+
        '                    "partNumber": "2474AGNMVZ6C",'+
        '                    "belronPartNumber": "2474AGNMVZ6C",'+
        '                    "partDescription": "MINI MINI 2CA 2016 ^WINDSCREEN  DROP DOWN BAND / ENCAPSULATION BOTTOM / FITTING SENSOR / GLASS COLOR - GREEN / SILKPRINT 4/4 / VERTICAL VIN",'+
        '                    "quantity": 1,'+
        '                    "baseListPrice": 629.51,'+
        '                    "netPrice": 629.51,'+
        '                    "taxRate": 20,'+
        '                    "totalTax": 125.9,'+
        '                    "netPriceIncludingTax": 755.41,'+
        '                    "selectProduct": true,'+
        '                    "optional": "mandatory",'+
        '                    "partOfBundle": true,'+
        '                    "bundleHierarchy": null,'+
        '                    "nonBundlePrice": null,'+
        '                    "availabilityDetails": ['+
        '                        {'+
        '                            "stockLocationId": "9y8hfh9",'+
        '                            "availableFromDate": "2024-03-27T00:00:00Z"'+
        '                        }'+
        '                    ]'+
        '                }'+
        '            ]'+
        '        }'+
        '    ]'+
        '}';

        String insuranceRTId = Schema.getGlobalDescribe().get('BLN_Corporate__c').getDescribe().getRecordTypeInfosByName().get('Insurance').getRecordTypeId();
        String corporateRTId = Schema.getGlobalDescribe().get('BLN_Corporate__c').getDescribe().getRecordTypeInfosByName().get('Corporate/Fleet').getRecordTypeId();
        String splitBillRTId = Schema.getGlobalDescribe().get('BLN_Corporate__c').getDescribe().getRecordTypeInfosByName().get('Split Bill').getRecordTypeId();

        // BLN_Corporate__c corporate1 = new BLN_Corporate__c(RecordTypeId = insuranceRTId, BLN_Vehicle__c=testVehicle.id,BLN_CHFVATStatus__c = 'Rated');
        // corporate1.BLN_InsuranceSite__c = 
        // BLN_Corporate__c corporate2 = new BLN_Corporate__c(RecordTypeId = corporateRTId, BLN_Vehicle__c=testVehicle.id,BLN_CHFVATStatus__c = 'Rated');
        // BLN_Corporate__c corporate3 = new BLN_Corporate__c(RecordTypeId = splitBillRTId, BLN_Vehicle__c=testVehicle.id,BLN_CHFVATStatus__c = 'Rated');
        // List<BLN_Corporate__c> corpList = new List<BLN_Corporate__c>();
        // corpList.add(corporate1);
        // corpList.add(corporate2);
        // corpList.add(corporate3);
        // insert corpList;

        Account accRec= new Account();
        accRec.name = 'test';
        accRec.recordtypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('BLN_CustomerB2BAccount').getRecordTypeId();        
        insert accRec;

        Account accRec2= new Account();
        accRec2.name = 'test 2';
        accRec2.recordtypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('BLN_CustomerB2BAccount').getRecordTypeId();        
        insert accRec2;

        // BLN_Vehicle__c vehicles = BLN_TestDataFactory.getVehicle();
        BLN_Vehicle__c vehicles = BLN_TestDataFactory.getVehicle();
        insert vehicles;

        BLN_Corporate__c corporate1=BLN_TestDataFactory.createcorporate();
        corporate1.BLN_CorporateSite__c = accRec.Id;
        corporate1.BLN_InsuranceSite__c = accRec2.id;
        corporate1.BLN_Vehicle__c = vehicles.id;
        corporate1.RecordTypeId = splitBillRTId;
        // insert corporate1;

        BLN_Corporate__c corporate2 = BLN_TestDataFactory.createcorporate();
        corporate2.BLN_CorporateSite__c = accRec.Id;
        corporate2.BLN_InsuranceSite__c = accRec2.id;
        corporate2.BLN_Vehicle__c = vehicles.id;
        corporate2.RecordTypeId = corporateRTId;
        // insert corporate2;

        BLN_Corporate__c corporate3 = BLN_TestDataFactory.createcorporate();
        corporate3.BLN_CorporateSite__c = accRec.Id;
        corporate3.BLN_InsuranceSite__c = accRec2.id;
        corporate3.BLN_Vehicle__c = vehicles.id;
        corporate3.RecordTypeId = insuranceRTId;
        // insert corporate3;

        List<BLN_Corporate__c> corpList = new List<BLN_Corporate__c>();
        corpList.add(corporate1);
        corpList.add(corporate2);
        corpList.add(corporate3);
        insert corpList;

        Account testAcc = BLN_TestDataFactory.createTestAccount();
        testAcc.FirstName = 'Test';
        testAcc.LastName = 'Cont act';
        testAcc.PersonEmail = 'test123@gmail.com';
        insert testAcc;

        Case cse = BLN_TestDataFactory.getCase('Job Request', 'New');
        cse.Type = 'Job Request';
        cse.Status = 'New';
        // cse.ContactId = testContact.Id;
        cse.BLN_ServiceGeolocation__latitude__s=46.22441984873406;
        cse.BLN_ServiceGeolocation__longitude__s=-89.02172505348693;
        cse.AccountId = testAcc.Id ;
        cse.Priority = 'Medium';
        cse.BLN_MotoristTaxStatus__c = 'Yes';
        cse.BLN_TotalMotoristLiability__c = 6000 ;
        cse.BLN_Vehicle__c = vehicles.id;
        cse.BLN_Corporate__c = corporate3.Id;
        insert cse;

        product2 prod1 = new product2();
        prod1.Name = 'Test1';
        prod1.BLN_MDMID__c = '2474AGNMVZ6C';
        prod1.ProductCode = '12345'; 
        prod1.IsActive = true;
        prod1.BLN_BondedNonBonded__c = true;
        insert prod1;

        //ARP creation
        List<BLN_AccountRuleParameter__c> arpList = new List<BLN_AccountRuleParameter__c>();
        BLN_AccountRuleParameter__c acpTest1 = new BLN_AccountRuleParameter__c(
            BLN_Account__c = accRec.Id,
            BLN_InsurerAccount__c = accRec.Id,
            BLN_ReplacementExcess__c = 123,
            BLN_VAT__c = 'Motorist',
            BLN_Excess__c = 'Motorist',
            BLN_PolicyNumbers__c = '123',
            BLN_PolicyLimit__c = 123,
            BLN_RepairExcess__c = 123,
            BLN_Remainder__c = 'Motorist',
            BLN_ActiveFrom__c = Date.today(),
            BLN_ActiveTo__c = Date.today().addDays(10),
            BLN_OEAuthorization__c = System.label.BLN_OEAuthorizationReq,
            RecordTypeId = Schema.SObjectType.BLN_AccountRuleParameter__c.getRecordTypeInfosByDeveloperName().get('BLN_OEAuthorization').getRecordTypeId()
        );
        // insert acpTest;

        BLN_AccountRuleParameter__c acpTest2 = new BLN_AccountRuleParameter__c(
            BLN_Account__c = accRec.Id,
            BLN_InsurerAccount__c = accRec.Id,
            BLN_ReplacementExcess__c = 123,
            BLN_VAT__c = 'Motorist',
            BLN_Excess__c = 'Motorist',
            BLN_PolicyNumbers__c = '123',
            BLN_PolicyLimit__c = 123,
            BLN_RepairExcess__c = 123,
            BLN_Remainder__c = 'Motorist',
            BLN_ActiveFrom__c = Date.today(),
            BLN_ActiveTo__c = Date.today().addDays(10),
            BLN_AuthorizationLimit__c = 0,
            RecordTypeId = Schema.SObjectType.BLN_AccountRuleParameter__c.getRecordTypeInfosByDeveloperName().get('BLN_AuthorizationLimit').getRecordTypeId()
        );

        BLN_AccountRuleParameter__c acpTest3 = new BLN_AccountRuleParameter__c(
            BLN_Account__c = accRec.Id,
            BLN_InsurerAccount__c = accRec.Id,
            BLN_ReplacementExcess__c = 123,
            BLN_VAT__c = 'Motorist',
            BLN_Excess__c = 'Motorist',
            BLN_PolicyNumbers__c = '123',
            BLN_PolicyLimit__c = 123,
            BLN_RepairExcess__c = 123,
            BLN_Remainder__c = 'Motorist',
            BLN_ActiveFrom__c = Date.today(),
            BLN_ActiveTo__c = Date.today().addDays(10),
            BLN_Product__c = prod1.Id,
            RecordTypeId = Schema.SObjectType.BLN_AccountRuleParameter__c.getRecordTypeInfosByDeveloperName().get('BLN_ProductAllowance').getRecordTypeId()
        );

        // insert acpTest;
        arpList.add(acpTest1);
        arpList.add(acpTest2);
        arpList.add(acpTest3);
        insert arpList;

        Test.startTest();
        Boolean result1 = BLN_CheckBvtTaskCreationUtility.checkBvtTaskCreation(jsonRes, cse.Id);

        cse.BLN_Corporate__c = corporate2.Id;
        update cse;
        Boolean result2 = BLN_CheckBvtTaskCreationUtility.checkBvtTaskCreation(jsonRes, cse.Id);

        cse.BLN_Corporate__c = corporate1.Id;
        update cse;
        Boolean result3 = BLN_CheckBvtTaskCreationUtility.checkBvtTaskCreation(jsonRes, cse.Id);

        BLN_CheckBvtTaskCreationUtility.setAccountId(corporate1);

        BLN_CheckBvtTaskCreationUtility.setAccountId(corporate2);

        BLN_CheckBvtTaskCreationUtility.setAccountId(corporate3);

        Test.stopTest();

        system.assertEquals(true, result1, 'Value should be true');
        system.assertEquals(true, result2, 'Value should be true');
        system.assertEquals(true, result3, 'Value should be true');
    }

    @isTest
    public static void testcheckBvtTaskCreationSplitBill(){
        //Make JSON for methods.
        String jsonRes =		'{'+
        '    "status": "success",'+
        '    "quotes": ['+
        '        {'+
        '            "quoteId": "39239816",'+
        '            "locationId": "9y8hfh9",'+
        '            "quoteTotals": {'+
        '                "totalPrice": 0,'+
        '                "totalTax": 176.8,'+
        '                "totalRepair": 0,'+
        '                "totalReplacement": 629.51,'+
        '                "totalCalibration": 0,'+
        '                "totalSundries": 0,'+
        '                "totalIncludingTax": 1060.78'+
        '            },'+
        '            "insuranceTotals": {'+
        '                "payableByInsuranceRepair": 0,'+
        '                "payableByInsuranceReplacement": 0,'+
        '                "payableByInsuranceCalibration": 0,'+
        '                "payableByInsuranceSundry": 0,'+
        '                "totalPayableByInsurance": 0,'+
        '                "totalTaxPayableByInsurance": 0,'+
        '                "totalIncludingTaxPayableByInsurance": 10'+
        '            },'+
        '            "motoristTotals": {'+
        '                "payableByMotoristRepair": 0,'+
        '                "payableByMotoristReplacement": 629.51,'+
        '                "payableByMotoristCalibration": 0,'+
        '                "payableByMotoristSundry": 0,'+
        '                "totalTaxPayableByMotorist": 1060.78,'+
        '                "totalPayableByMotorist": 883.98,'+
        '                "totalInludingTaxPayableByMotorist": 1060.78'+
        '            },'+
        '            "taxTotals": {'+
        '                "totalTaxRepair": 0,'+
        '                "totalTaxReplacement": 0,'+
        '                "totalTaxCalibration": 0,'+
        '                "totalTaxSundries": 0'+
        '            },'+
        '            "tradeCompanyTotals": {'+
        '                "payableByTradeRepair": 0,'+
        '                "totalPayableByTrade": 0,'+
        '                "totalPayableByTradeIncludingTax": 10,'+
        '                "payableByTradeSundry": 0,'+
        '                "payableByTradeReplacement": 0,'+
        '                "payableByTradeCalibration": 0,'+
        '                "payableByTradeTotalTax": 0'+
        '            },'+
        '            "discountThresholdA": 848.62,'+
        '            "discountThresholdB": 689.51,'+
        '            "discountThresholdC": 618.79,'+
        '            "priceExpirationDate": "2024-05-27T00:00:00Z",'+
        '            "lineItems": ['+
        '                {'+
        '                    "lineItemId": 2,'+
        '                    "parentLineItemId": 2,'+
        '                    "bundleName": null,'+
        '                    "partNumber": "2474AGNMVZ6C",'+
        '                    "belronPartNumber": "2474AGNMVZ6C",'+
        '                    "partDescription": "MINI MINI 2CA 2016 ^WINDSCREEN  DROP DOWN BAND / ENCAPSULATION BOTTOM / FITTING SENSOR / GLASS COLOR - GREEN / SILKPRINT 4/4 / VERTICAL VIN",'+
        '                    "quantity": 1,'+
        '                    "baseListPrice": 629.51,'+
        '                    "netPrice": 629.51,'+
        '                    "taxRate": 20,'+
        '                    "totalTax": 125.9,'+
        '                    "netPriceIncludingTax": 755.41,'+
        '                    "selectProduct": true,'+
        '                    "optional": "mandatory",'+
        '                    "partOfBundle": true,'+
        '                    "bundleHierarchy": null,'+
        '                    "nonBundlePrice": null,'+
        '                    "totalIncludingTaxPayableByInsurance": 10,'+
        '                    "totalPayableByTradeIncludingTax": 10,'+
        '                    "availabilityDetails": ['+
        '                        {'+
        '                            "stockLocationId": "9y8hfh9",'+
        '                            "availableFromDate": "2024-03-27T00:00:00Z"'+
        '                        }'+
        '                    ]'+
        '                }'+
        '            ]'+
        '        }'+
        '    ]'+
        '}';

        String splitBillRTId = Schema.getGlobalDescribe().get('BLN_Corporate__c').getDescribe().getRecordTypeInfosByName().get('Split Bill').getRecordTypeId();

        Account accRec= new Account();
        accRec.name = 'test';
        accRec.recordtypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('BLN_CustomerB2BAccount').getRecordTypeId();        
        insert accRec;

        Account accRec2= new Account();
        accRec2.name = 'test 2';
        accRec2.recordtypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('BLN_CustomerB2BAccount').getRecordTypeId();        
        insert accRec2;

        // BLN_Vehicle__c vehicles = BLN_TestDataFactory.getVehicle();
        BLN_Vehicle__c vehicles = BLN_TestDataFactory.getVehicle();
        insert vehicles;

        BLN_Corporate__c corporate1=BLN_TestDataFactory.createcorporate();
        corporate1.BLN_CorporateSite__c = accRec2.Id;
        corporate1.BLN_InsuranceSite__c = accRec.id;
        corporate1.BLN_Vehicle__c = vehicles.id;
        corporate1.RecordTypeId = splitBillRTId;
        insert corporate1;

        //ARP creation
        List<BLN_AccountRuleParameter__c> arpList = new List<BLN_AccountRuleParameter__c>();
        BLN_AccountRuleParameter__c acpTest1 = new BLN_AccountRuleParameter__c(
            BLN_Account__c = accRec.Id,
            BLN_InsurerAccount__c = accRec.Id,
            BLN_ReplacementExcess__c = 123,
            BLN_VAT__c = 'Motorist',
            BLN_Excess__c = 'Motorist',
            BLN_PolicyNumbers__c = '123',
            BLN_PolicyLimit__c = 123,
            BLN_RepairExcess__c = 123,
            BLN_Remainder__c = 'Motorist',
            BLN_ActiveFrom__c = Date.today(),
            BLN_ActiveTo__c = Date.today().addDays(10),
            BLN_OEAuthorization__c = System.label.BLN_OEAuthorizationReq,
            RecordTypeId = Schema.SObjectType.BLN_AccountRuleParameter__c.getRecordTypeInfosByDeveloperName().get('BLN_OEAuthorization').getRecordTypeId()
        );
        // insert acpTest;

        BLN_AccountRuleParameter__c acpTest2 = new BLN_AccountRuleParameter__c(
            BLN_Account__c = accRec2.Id,
            BLN_InsurerAccount__c = accRec2.Id,
            BLN_ReplacementExcess__c = 123,
            BLN_VAT__c = 'Motorist',
            BLN_Excess__c = 'Motorist',
            BLN_PolicyNumbers__c = '123',
            BLN_PolicyLimit__c = 123,
            BLN_RepairExcess__c = 123,
            BLN_Remainder__c = 'Motorist',
            BLN_ActiveFrom__c = Date.today(),
            BLN_ActiveTo__c = Date.today().addDays(10),
            BLN_OEAuthorization__c = System.label.BLN_OEAuthorizationReq,
            RecordTypeId = Schema.SObjectType.BLN_AccountRuleParameter__c.getRecordTypeInfosByDeveloperName().get('BLN_OEAuthorization').getRecordTypeId()
        );

        BLN_AccountRuleParameter__c acpTest3 = new BLN_AccountRuleParameter__c(
            BLN_Account__c = accRec.Id,
            BLN_InsurerAccount__c = accRec.Id,
            BLN_ReplacementExcess__c = 123,
            BLN_VAT__c = 'Motorist',
            BLN_Excess__c = 'Motorist',
            BLN_PolicyNumbers__c = '123',
            BLN_PolicyLimit__c = 123,
            BLN_RepairExcess__c = 123,
            BLN_Remainder__c = 'Motorist',
            BLN_ActiveFrom__c = Date.today(),
            BLN_ActiveTo__c = Date.today().addDays(10),
            BLN_AuthorizationLimit__c = 0,
            RecordTypeId = Schema.SObjectType.BLN_AccountRuleParameter__c.getRecordTypeInfosByDeveloperName().get('BLN_AuthorizationLimit').getRecordTypeId()
        );

        BLN_AccountRuleParameter__c acpTest4 = new BLN_AccountRuleParameter__c(
            BLN_Account__c = accRec2.Id,
            BLN_InsurerAccount__c = accRec2.Id,
            BLN_ReplacementExcess__c = 123,
            BLN_VAT__c = 'Motorist',
            BLN_Excess__c = 'Motorist',
            BLN_PolicyNumbers__c = '123',
            BLN_PolicyLimit__c = 123,
            BLN_RepairExcess__c = 123,
            BLN_Remainder__c = 'Motorist',
            BLN_ActiveFrom__c = Date.today(),
            BLN_ActiveTo__c = Date.today().addDays(10),
            BLN_AuthorizationLimit__c = 0,
            RecordTypeId = Schema.SObjectType.BLN_AccountRuleParameter__c.getRecordTypeInfosByDeveloperName().get('BLN_AuthorizationLimit').getRecordTypeId()
        );

        //Add products for Product allowance ARP
        product2 prod1 = new product2();
        prod1.Name = 'Test1';
        prod1.BLN_MDMID__c = '2474AGNMVZ6C';
        prod1.ProductCode = '12345'; 
        prod1.IsActive = true;
        prod1.BLN_BondedNonBonded__c = true;
        insert prod1;

        BLN_AccountRuleParameter__c acpTest5 = new BLN_AccountRuleParameter__c(
            BLN_Account__c = accRec.Id,
            BLN_InsurerAccount__c = accRec.Id,
            BLN_ReplacementExcess__c = 123,
            BLN_VAT__c = 'Motorist',
            BLN_Excess__c = 'Motorist',
            BLN_PolicyNumbers__c = '123',
            BLN_PolicyLimit__c = 123,
            BLN_RepairExcess__c = 123,
            BLN_Remainder__c = 'Motorist',
            BLN_ActiveFrom__c = Date.today(),
            BLN_ActiveTo__c = Date.today().addDays(10),
            BLN_Product__c = prod1.Id,
            RecordTypeId = Schema.SObjectType.BLN_AccountRuleParameter__c.getRecordTypeInfosByDeveloperName().get('BLN_ProductAllowance').getRecordTypeId()
        );

        BLN_AccountRuleParameter__c acpTest6 = new BLN_AccountRuleParameter__c(
            BLN_Account__c = accRec2.Id,
            BLN_InsurerAccount__c = accRec2.Id,
            BLN_ReplacementExcess__c = 123,
            BLN_VAT__c = 'Motorist',
            BLN_Excess__c = 'Motorist',
            BLN_PolicyNumbers__c = '123',
            BLN_PolicyLimit__c = 123,
            BLN_RepairExcess__c = 123,
            BLN_Remainder__c = 'Motorist',
            BLN_ActiveFrom__c = Date.today(),
            BLN_ActiveTo__c = Date.today().addDays(10),
            BLN_Product__c = prod1.Id,
            RecordTypeId = Schema.SObjectType.BLN_AccountRuleParameter__c.getRecordTypeInfosByDeveloperName().get('BLN_ProductAllowance').getRecordTypeId()
        );

        arpList.add(acpTest1);
        arpList.add(acpTest2);
        arpList.add(acpTest3);
        arpList.add(acpTest4);
        arpList.add(acpTest5);
        arpList.add(acpTest6);
        insert arpList;

        Account testAcc = BLN_TestDataFactory.createTestAccount();
        testAcc.FirstName = 'Test';
        testAcc.LastName = 'Cont act';
        testAcc.PersonEmail = 'test123@gmail.com';
        insert testAcc;

        Case cse = BLN_TestDataFactory.getCase('Job Request', 'New');
        cse.Type = 'Job Request';
        cse.Status = 'New';
        // cse.ContactId = testContact.Id;
        cse.BLN_ServiceGeolocation__latitude__s=46.22441984873406;
        cse.BLN_ServiceGeolocation__longitude__s=-89.02172505348693;
        cse.AccountId = testAcc.Id ;
        cse.Priority = 'Medium';
        cse.BLN_MotoristTaxStatus__c = 'Yes';
        cse.BLN_TotalMotoristLiability__c = 6000 ;
        cse.BLN_Vehicle__c = vehicles.id;
        cse.BLN_Corporate__c = corporate1.Id;
        insert cse;

        Test.startTest();
        Boolean result1 = BLN_CheckBvtTaskCreationUtility.checkBvtTaskCreation(jsonRes, cse.Id);
        
        acpTest1.BLN_OEAuthorization__c = System.label.BLN_OEMotoristLiability;
        update acpTest1;
        Boolean result2 = BLN_CheckBvtTaskCreationUtility.checkBvtTaskCreation(jsonRes, cse.Id);
        Test.stopTest();

        system.assertEquals(true, result1, 'Value should be true');
        system.assertEquals(true, result2, 'Value should be true');
    }
}